= Шифрование системных настроек

Конфиденциальные настрйоки системы могут быть зашифрованы при помощи встроенного механизма шифрования системы. Механизм использует сертификат шифрования с публичной и приватной частями. В данный момент шифрование поддерживается только для настроек модуля {em}, начиная с версии {edi-cu-mc}.

CAUTION: Если вы планируете включить шифрование для уже настроенного {of-em}, потребуется заново задать пароли в настройках операторов ЭДО.

.Шифрование настраивается следующим образом:
// tag::letsencrypt[]
. Создайте сертификат по инструкции "xref:create-cert.adoc#cr-cert[Создание сертификата шифрования в Linux]".
+
WARNING: Пароль для сертификата указывать не требуется!
+
. Добавьте сертификаты с публичным и приватным ключом на клиентскую и серверную машины модуля {wf} по пути `/root/.dotnet/corefx/cryptography/x509stores/my`. Приватный ключ требуется и на клиенте, потому что xref:edi:admin:configure-directory.adoc[при загрузке операторов] нужны пароли к УЗ. +
Приватная часть требуется только на машине, где планируется настраивать/редактировать справочник ЮЗДО и под пользователем, который будет это делать. Устанавливать сертификат на все рабочие места с {wincl}ом не требуется.
. Убедитесь, что в настройках оператора Диадок появился xref:new-admin-console@edi:diadoc:connection-settings.adoc#thumbprint[параметр для ввода отпечатка] _Thumbprint_.
. В свойствах menu:Контекстное меню[Свойства > Состав > Отпечаток] созданного сертификата скопируйте отпечаток (например: 3f65b0bc7ca3f7291c5473e1cfb411f62bc0dfbe) и укажите его в настройках оператора. Теперь вы можете указывать параметры `Password` и `ProxyPassword`; если указать параметры до того, как был задан отмечаток, возникнет ошибка. Если сертификат не будет найден на машине клиента, при вводе пароля возникнет ошибка.
. Перезапустите службу {wfs-new}.
. Повторно введите пароли (_Password_, _ApiKey_, _ProxyPassword_) в настройках оператора Диадок, чтобы они сохранились с учетом новой логики шифрования. Если этот шаг пропустить, то документооборот с оператором будет невозможен.
. Перезагрузите xref:new-admin-console@edi:admin:configure-directory.adoc[список операторов] и xref:new-admin-console@edi:admin:configure-partners.adoc[котрагентов].
. Проверьте работу модуля ЭДО (достаточно убедиться, что работает получение и отправка документов, если всё работает стандартно, дешифровка работает).
// end::letsencrypt[]