= Сервис обслуживания ЭП

Сервис обслуживания ЭП -- компонент модуля {bo}. Сервис указывает в журнале подписей {wc}а актуальный статус подписи, тип и дату окончания срока действия сертификата. Сервис обслуживания ЭП может работать в сочетании с Криптосервисом -- Docker-контейнером, выполняющим функции обслуживания ЭП.

Для использования криптосервиса ЭП требуется https://www.docker.com/[Docker] актуальной версии и опция лицензии {dv} _Сервис обслуживания электронной подписи_ (только для добавления архивного штампа времени). Криптосервис может быть получен из общего реестра образов Docker Hub -- `docsvision/cryptoservice` или реестра образов {dv} -- `packages.docsvision.com/cryptoservice`.
// Для формирования подписи лицензия не требуется, см. требования GBL-3116, GBL-3074, GBL-3326 и GBL-2865

[#functions]
== Функциональные возможности сервиса обслуживания ЭП

WARNING: Сервис обслуживания ЭП -- расширение, входящее в стандартную поставку модуля {bo}, не следует путать его с Криптосервисом. Криптосервис поставляется в виде Docker-контейнера.

.Сервис обслуживания подписи:
* Если срок действия сертификата не истёк, Сервис указывает в карточке актуальный статус подписи, тип и дату окончания срока действия сертификата, даёт возможность просматривать дополнительную информацию о подписи в xref:webclient:user:docs-sign.adoc#advanced-info[журнале подписей {wc}а].

.Криптосервис дополняет функции сервиса по обслуживанию следующими возможностями:
* Если срок действия сертификата не истёк, Криптосервис доступен и функционирует, в карточку добавляется новый архивный штамп времени и улучшает подпись до CAdES-A.
* В {dv} версии 6.1 и выше Криптосервис является обязательным для проверки подписей CAdES-BES и CAdES-X Long Type 1 с нестандартными для .NET 6 алгоритмами в сертификатах. Требуется, например, при использовании сертификатов КриптоПро.
* В {dv} версии 6.1 и выше Криптосервис также необходим для функционирования Простой подписи.

Из-за использования библиотеки tspcom.dll Криптосервис требует быть развернут минимум в 32-битном процессе Службы рабочих процессов.

[#cryptoservice]
== Установка и запуск Криптосервиса

.Криптосервис работает с {dv} следующих версий:
* Модуль "{pl}" версии 6.1 и выше + "{wc}" 18 и выше. +
Криптосервис является обязательным для проверки подписей с нестандартными для .NET 6 алгоритмами в сертификатах. Требуется, например, при использовании сертификатов КриптоПро.
* Модуль "{pl}" версии 5.5.5 + "{wc}" 17. +
Криптосервис указывает в xref:webclient:user:docs-sign.adoc#advanced-info[журнале подписей {wc}а] актуальный статус подписи, тип и дату окончания срока действия сертификата, делает доступной расширенную информацию о подписи.
// * Модуль "{pl}" версии 5.5.4 + "{wc}" 16 + "Служба рабочих процессов" версии 5.5.1. +
// Функциональность аналогична предыдущему пункту.

Криптосервис можно установить и запустить командой:

[source]
----
docker run -d -p 8100:8094 packages.docsvision.com/cryptoservice <.>
----
<.> Если используется Docker Hub, замените `packages.docsvision.com/cryptoservice` на `docsvision/cryptoservice`.

Настройки криптосервиса задаются в командной строке.

При запуске контейнера необходимо связать порт хоста с портом контейнера, например, `-p 8100:8094`. В примере `8100` -- порт хоста, `8094` -- порт контейнера. Для работы функций проверки и формирования подписи сервер {dv} должен подключаться к контейнеру через порт хоста. Адрес Криптосервиса указывается в конфигурационном файле, <<config,см. подробности ниже>>.

По умолчанию Криптосервис использует TSP-службу с адресом `http://cryptopro.ru/tsp/tsp.srf`. При необходимости адрес используемой TSP-службы можно переопределить с помощью переменной окружения `TSP_SERVICE_ADDRESS`. Ниже приведён пример переопределения адреса TSP-сервиса:

 $ docker run -d -p 8100:8094 -e TSP_SERVICE_ADDRESS=http://testca2012.cryptopro.ru/tsp/tsp.srf packages.docsvision.com/cryptoservice

Контейнер поставляется в комплекте со следующими сертификатами:

* https://www.gosuslugi.ru/crt[Защищённые сертификаты Минцифры].
* https://ca.kontur.ru/about/certificates[Сертификаты УЦ "Контур"].
* https://tlsca.cryptopro.ru/UI/CaCerts.aspx[Сертификаты "Крипто-Про УЦ 2.0" (TLS CA)].
* http://cpca20.cryptopro.ru/[Сертификаты УЦ ООО "Крипто-Про"].

При необходимости использования дополнительных сертификатов выполните одну из следующих настроек:

* Укажите путь к папке сертификатов:
. Необходимые сертификаты сохраните в отдельную папку на диске Docker-хоста.
. Смонтируйте в каталог `/var/cryptoservice/cacerts` Docker-контейнера и запустите контейнер. +
При запуске контейнера всё содержимое папки будет импортировано в хранилище.
+
[source,bash]
----
docker run -d -p 8100:8094 -v ./Cert:/var/cryptoservice/cacerts packages.docsvision.com/cryptoservice <.>
----
<.> Если используется Docker Hub, замените `packages.docsvision.com/cryptoservice` на `docsvision/cryptoservice`.
+
* Заново соберите образ:
+
. Создайте Dockerfile:
+
[source,dockerfile]
----
FROM packages.docsvision.com/cryptoservice
COPY ./your/cacerts/ /var/cryptoservice/cacerts/ <.>
----
<.> Если используется Docker Hub, замените `packages.docsvision.com/cryptoservice` на `docsvision/cryptoservice`
+
. Соберите собственный образ:
+
 $ docker build . -t cryptoservice
+
. Запустите контейнер:
+
 $ docker run -d -p 8100:8094 cryptoservice

[#config]
== Настройка Криптосервиса в {dv} 6.1

. После установки Криптосервиса создайте файл с расширением `.json` и любым именем, скопируйте созданный конфигурационный файл по пути `/usr/lib/docsvision/platform/config` и перезапустите службу *{sss-new}*. Пример содержимого файла `.json` приведён ниже:
+
[source,json]
----
{
  "DocsVision": {
    "BackOffice": {
      "Server": {
        "Extension": {
          "ComplexSignatureServiceAddress": "ConnectAddress=http://server.domain.com:8100/cryptoservice/api/v1" <.>
        }
      }
    }
  }
}
----
<.> Адрес Криптосервиса.
+
. Зайдите в Консоль управления и xref:mgmtconsole:user:worker-service.adoc[создайте процесс] Службы {ws} с типом конфигурации _Обслуживание ЭП_.
+
[WARNING]
====
* {blank}
+
include::workerservice:admin:launch.adoc[tags=cpus]
+
* {blank}
+
include:::partial$excerpts.adoc[tags=one-ws]
====
+
. В соединении {dv} выберите сервер, на котором указан адрес Криптосервиса в конфигурационном файле из примера выше.

// [#registry]
// == Настройки Криптосервиса для модулей {pl} 5.5.5 и Служба {ws} 5.5.2
//
// .Чтобы изменить настройки, перейдите на сервере {dv} в ветку реестра:
// . [[one]]`{hklm-dv}\BackOffice\5.5\Server\Extension`.
// . В указанной ветке создайте параметр `ComplexSignatureServiceAddress` со строковым значением -- адресом Криптосервиса.
// +
// Например, так: параметр `ComplexSignatureServiceAddress` со значением `ConnectAddress=http://server.domain.com:8094/cryptoservice/api/v1`.
// +
// . Зайдите в Консоль управления и xref:mgmtconsole:user:worker-service.adoc[создайте процесс] Службы {ws} с типом конфигурации _Обслуживание ЭП_.
// +
// [WARNING]
// ====
// include:::partial$excerpts.adoc[tags=one-ws]
// ====
// +
// . В соединении {dv} выберите сервер, на котором выполнен <<one,пункт 1>>.

События работы сервиса записываются в журнал Криптосервиса. Ознакомиться с журналом можно, имея идентификатор контейнера:

 sudo docker ps <.>
 sudo docker logs идентификатор-контейнера <.>

<.> Узнать идентификатор контейнера.
<.> Посмотреть журнал Криптосервиса.

[#ocsp]
== Улучшение подписи с сертификатом без адреса OCSP сервиса

При улучшении подписи, созданной с помощью сертификата без адреса OCSP сервиса, могут возникать ошибки вида: `The signer certificate <...> must have OCSP evidence but it doesn't contain any OCSP reference. OCSP evidence is not created`.

Исправить ситуацию можно, если известен адрес OCSP сервиса, выдавшего сертификат.

.Требования к сертификату:
****
* Сертификат, которым выполнялась подпись, должен быть доверенным. Доверенный сертификат -- это сертификат, у которого корневой и промежуточные сертификаты добавлены в доверенные в образе Крипто-сервиса.
* Сертификат OCSP сервиса (для подписания ответов сервиса) должен быть доверенным. Сертификат с большой вероятность будут недоверенным в случае если используется неквалифицированная электронная подпись (НЭП).
* Сертификат OCSP сервиса должен быть выпущен тем же УЦ, что и сертификат, которым выполнялась подпись (поле `Issuer` в сертификатах должно совпадать). Иными словами, нужно использовать OCSP сервис того же УЦ, который выпустил сертификат, которым выполнялась подпись. Только данный УЦ может контролировать статус отзыва сертификата.
* Получить сертификат OCSP сервиса можно запросить в УЦ, либо развернуть сервис самостоятельно.
* Сертификат TSP сервиса также должен быть доверенным.
* Получить сертификат TSP сервиса можно также через техподдержку компании, которая предоставляет сервис, либо через утилиту CryptExpert.
****

Когда адрес сервиса известен, необходимо в файле настроек криптосервиса `/etc/cryptoservice/settings.json` указать актуальные адреса OCSP серверов следующим образом:

[source,json]
----
{
    "ocspSettings": [
        {
            "ocspUrl": "http://ocsp-service.ru/ocspn/ocsp.srf", <.>
        },
        {
            "ocspUrl": "http://ocsp-service.example.ru/ocspn1000000/ocsp.srf",
        }
    ]
}
----
<.> `"ocspUrl"` -- адрес OCSP сервиса.

Конфигурационный файл `settings.json` должен располагаться в контейнере криптосервиса по пути `/etc/cryptoservice/`. Если в файле задана хотя бы одна группа настроек `ocspSettings`, то при улучшении подписи криптосервис будет проверять цепочку родительских сертификатов сертификата улучшаемой подписи.

Серийные номера сертификатов сопоставляются с номером, указанным в конфигурационном файле, при совпадении заданный адрес OCSP будет использоваться для самого близкого родительского сертификата. Чтобы серийный номер сертификата считывался успешно, поместите его в каталог конревных сертификатов `/var/cryptoservice/cacerts`.

Контейнер криптосервиса можно сразу смонтировать вместе с файлом настроек OCSP сервиса следующим образом:

 $ docker run -d -p 8100:8094 -v /path/to/settings.json:/etc/cryptoservice/settings.json packages.docsvision.com/cryptoservice
