= Работа в {dv} по протоколу LDAPS без Active Directory

Расширение позволяет серверу приложений и другим компонентам {dv} работать по протоколам LDAP\LDAPS без привязки к конкретной службе каталогов Active Directory. Администратор амостоятельно может выбрать хранилище, из которого будут получены данные по доменным учётным записям, включая системные УЗ.

[NOTE]
====
* Для работы расширения авторизации LDAPS не требуется дополнительных опций лицензии.
* Автоизация с помощью LDAPS поддерживается в {dv} при установке модуля {pl} {ald-pl-req} и других модулей, входящих в обновление.
====

[source,json]
----
{
  "Docsvision": {
    "Platform": {
      "Server": {
        "Authentication": {
          "Extensions": {
            "LDAP": {
            "Name": "LDAP", <.>
            "TypeName": "DocsVision.Platform.Authentication.LDAP.GenericLDAPBasicRootAuthExtension, DocsVision.Platform.Authentication, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7148AFE997F90519", <.>
            "Settings": "<?xml version=\"1.0\" encoding=\"utf-16\"?><LdapConnectorOptions><LdapServerAddresses><string>dv.io</string></LdapServerAddresses><Port>389</Port><EnableLDAPS>true</EnableLDAPS><FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName><Credential><UserName>kmg02@dv.io</UserName><Password>kmg002</Password></Credential></LdapConnectorOptions>", <.>
            "Id": "{36351525-8FCE-48AB-8AD3-4C1FA575FF78}" <.>
            }
          }
	    },
        "Tenants": { <.>
		}
      }
	}
  }
}
----
<.> `Name` -- задаёт отображаемое имя сервиса аутентификации в справочнике сотрудников, на вкладке "Безопасность".
<.> `TypeName` -- строка с именем типа, реализующего расширение, указывается так же, как в примере.
<.> `Settings` -- строка настроек расширения, для LDAPS. Подробнее см. <<ldaps-settings,ниже>>.
<.> `ID` -- строка с идентификатором расширения в виде Guid.
<.> `Tenants` -- расширение регистрируется сразу для всех БД, подключенных к {dv}, указывать параметр не требуется. Если указать идентификатор для конкретной БД, система будет работать, но такие настройки не будут применены.

[#ldaps-settings]
== Строка настроек LDAPS

[source,xml]
----
<?xml version="1.0" encoding="utf-16"?>
<LdapConnectorOptions>
	<LdapServerAddresses>
		<string>example.com</string> <.>
	</LdapServerAddresses>
	<Port>389</Port> <.>
    <EnableLDAPS>true</EnableLDAPS> <.>
	<FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName> <.>
	<Credential>
		<UserName>user@example.com</UserName> <.>
		<Password>user</Password> <.>
	</Credential>
</LdapConnectorOptions>
----
<.> `LdapServerAddresses` -- адреса серверов LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `EnableLDAPS` -- флаг активации использования протокола LDAPS.
<.> `FullyQualifiedDnsHostName` -- указывать ли полное имя домена в формате `user@example.com` учётной записи после `@`.
<.> `UserName` -- `UserName` -- имя пользователя (при использовании аутентификации LDAPS).
<.> `Password` -- `Password` -- пароль (при использовании аутентификации LDAPS).

[#ald]
== Расширение аутентификации ALD Pro

ALD Pro является альтернативной службой каталогов с групповыми политиками, предназначеннолй для управления устройствами в сети. ALD Pro работает по протоколу LDAPS.

[source,json]
----
{
  "Authentication": {
	"Extensions": {
      "ALDPro": {
		"Name": "ALDPro", <.>
		"TypeName": "DocsVision.Platform.Authentication.LDAP.ALDProBasicRootAuthExtension, DocsVision.Platform.Authentication, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7148AFE997F90519", <.>
		"Settings": "<?xml version=\"1.0\" encoding=\"utf-16\"?><LdapConnectorOptions><LdapServerAddresses><string>172.16.18.236</string></LdapServerAddresses><Port>389</Port><EnableLDAPS>true</EnableLDAPS><FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName><Credential><UserName>kmg01@astrald.ru</UserName><Password>P@ssw0rd</Password></Credential></LdapConnectorOptions>", <.>
		"Id": "{36351525-8FCE-48AB-8AD3-4C1FA575FF77}" <.>
		}
	},
	"Tenants": { <.>
		}
	}
  }
}
----
<.> `Name` -- задаёт отображаемое имя сервиса аутентификации в справочнике сотрудников, на вкладке "Безопасность".
<.> `TypeName` -- строка с именем типа, реализующего расширение.
<.> `Settings` -- строка настроек расширения, для LDAPS. Подробнее см. <<ldaps-settings,ниже>>.
<.> `ID` -- строка с идентификатором расширения в виде Guid.
<.> `Tenants` -- расширение регистрируется сразу для всех БД, подключенных к {dv}, указывать параметр не требуется. Если указать идентификатор для конкретной БД, система будет работать, но такие настройки не будут применены.

[#ald-settings]
=== Строка настроек ALD Pro

include::partial$excerpts.adoc[tags=pretty]

[source,xml]
----
<?xml version="1.0" encoding="utf-16"?>
<LdapConnectorOptions>
	<LdapServerAddresses> <.>
		<string>173.15.17.145</string>
	</LdapServerAddresses>
	<Port>389</Port> <.>
    <EnableLDAPS>true</EnableLDAPS> <.>
	<FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName> <.>
	<BaseDN>dc=astrald,dc=ru</BaseDN> <.>
	<Credential>
		<UserName>admin@astrald.ru</UserName> <.>
		<Password>Password</Password> <.>
	</Credential>
</LdapConnectorOptions>
----
<.> `LdapServerAddresses` -- адреса серверов LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `EnableLDAPS` -- флаг активации использования протокола LDAPS.
<.> `FullyQualifiedDnsHostName` -- указывать ли полное имя домена в формате `user@example.com` учётной записи после `@`.
<.> `BaseDN` -- обязательная настройка, что-то делает?
<.> `UserName` -- `UserName` -- имя пользователя (при использовании аутентификации LDAPS).
<.> `Password` -- `Password` -- пароль (при использовании аутентификации LDAPS).

.Особенности и рекомендации при работе с ALD Pro:
****
* Расширение ALD Pro имеет особенности именования. Расширение не поддерживает пробелы и заглавные буквы в именах пользователей и групп, а также имеет прочие ограничения наименования.
+
В связи с этим была добавлена настройка сопоставления доменных групп и ролей {dv}. Также для упрощения настройки, *только для данного провайдера* были сделаны новые стандартные имена групп пользователей в нижнем регистре. Т.е. группы пользователей с такими именами будут сопоставятся со штатными ролями {dv} без дополнительных настроек *только в рамках данного коннектора*:
+
** *docsvision_users*
** *docsvision_power_users*
** *docsvision_administrators*
** *docsvision_security_administrators*
** *docsvision_archive_operators*
** *docsvision_search_query_creators*
** *docsvision_workflow_process_creators*
** *docsvision_aggregation_users*
** *docsvision_management_console_administrators*
+
* Особенности доступа. Всегда обязательно нужно указывать верные `DistinguishedName`. Это часть `dc=astrald,dc=ru`. В данном случае вид части обусловлен тем, что домен `astrald.ru`. Если он будет, например `astrald.example.domain.ru`, то вид изменится: `dc=astrald,dc=example,dc=domain,dc=ru`. +
Эта настройка указывается в опциях в поле `BaseDN`.
* Имя пользователя. Расширение работает с так называемым `uid` пользователя. Как уже говорилось ранее, параметр должен быть строчным, допускется использовать *только* следующие варианты:
+
 user01
 user01@astrald.ru
 astrald.ru\user01
+
Вариант `astrald\user01` недопустим, т.к. просто с `dc=astrald` контроллер не ответит.
+
* Если мы каким-то образом пытаемся оперировать с пользователем, то обязательно указывать часть `cn=users,cn=accounts` и `BaseDN`. В противном случае контроллер не находит его.
****

[#additional-settings]
== Дополнительные настройки

Выполненные настройки будут автоматически приведены в действие только если машины с сервером {dv} и клиентскими приложениями будут введены в домен ALDPro, указанный в настройках. Иначе потребуются дополнительные настройки, описанные ниже.

. Выполните команду:
+
 $ sudo nano /usr/share/ca-certificates/astrald.crt
+
. Скопируйте сертификат удостоверяющего центра домена в полученный файл и сохраните его.
. Выполните команду:
+
 $ sudo dpkg-reconfigure ca-certificates
+
. В диалоговом окне конфигурации сертификатов выберите "Да", чтобы доверять новым сертификатам.
. В следующем окне найдите строчку "astrald", выберите её и примените выбор.
+
На экран будет выведено сообщение об успешном добавлении нового сертификата.
+
. Выполните команду
+
 $ sudo nano /etc/hosts
+
Добавьте в файл строку `172.16.18.236 dc1.astrald.ru astrald.ru`.
+
. В настройках расширения адрес сервера укажите в виде: `dc1.astrald.ru`. При указании IP работать не будет. Порт `636` указывать необязательно.
. На машине с клиентскими компонентами нужно создать аналогичный сертификат и добавить его в доверенные.
. После выполнения описанных настроек авторизация должна выполняться успешно без введения в домен машин с сервером {dv} и клиентскими приложениями.
