= Настроить метрики web-сервисов

{dv} позволяет настраивать и просматривать метрики для web-сервисов. Метрики предоставляются в формате Prometheus.

.Метрики доступны для следующих сервисов:
* Сервер приложений
* Сервер {wc}а
* Основной процесс {wf}
* Основной процесс Службы {ws}

.Чтобы настроить метрики:
. Задайте настройку для метрик одним из поддерживаемых способов:
+
* {blank}
+
[subs="specialchars,attributes,quotes"]
Откройте конфигурационный файл `appsettings.json`, например {config-ws}, и укажите следующие настройки:
+
[source,json]
----
{
 "Metrics": {
    "Key": "secret-key-my"
  },
}
----
+
NOTE: Если параметр отсутствуtт в конфигурационном файле, создайте его самостоятельно.
+
* _Только для xref:mgmtconsole:servers:appserver-etc.adoc[Сервера приложений], xref:mgmtconsole:servers:webclient-etc.adoc[{wc}а] и xref:mgmtconsole:servers:workflow-etc.adoc[{wf}]._ На странице дополнительных настроек модуля в {of-mc} укажите настройку `Metrics__ApiKey`.
+
. Выполните запрос метрик с помощью curl (или иного rest-клиента):
+
 curl -v -H "X-Metrics-Key: secret-key-my" http://адрес-сервиса:ПОРТ/metrics
+
. В ответе будут данные в формате Prometheus:
+
----
# TYPE process_memory_usage_bytes gauge
# UNIT process_memory_usage_bytes bytes
# HELP process_memory_usage_bytes The amount of physical memory in use.
process_memory_usage_bytes{otel_scope_name="OpenTelemetry.Instrumentation.Process",otel_scope_version="0.5.0-beta.7"} 106971136 1776691371291
----
