:link: https://github.com/Docsvision/WebClient-Samples/tree/master/Others/SettingsExtension
:name: SettingsExtension

= Работа с хранилищем секретов

Конфиденциальные настройки и параметры конфигурации {dv} могут быть прочитаны из специализированных хранилищ секретов. К секретам относятся, например API-ключи, пароли системных пользователей и т.д., полный список см. <<fields,ниже>>.

ifdef::engineer[]
Ознакомиться с примером разработки коннектора к хранилищу настроек можно на GitHub: {link}[{name}].
endif::[]

Работа с внешними хранилищами секретов выполняется через подключаемые коннекторы, начиная с версий, входящих в {mc-cu1}. В качестве примера используется хранилище секретов OpenBao. Аналогичным образом могут быть подключены и другие.

[#connection]
== Подключение хранилища секретов

Чтобы подключить внешнее хранилище секретов к {dv}, в конфигурационные файлы `appsettings.json` основных компонентов (Сервер приложений, {wc}, {wf}, {fs}, {mc}) в секцию `SettingsService` необходимо добавить подчинённую секцию `SecretStorage`. Фрагмент json-схемы для настройки доступа:

[source,json]
----
{
  "DocsVision": {
    "SettingsService": {
      "SecretStorage": { <.>
        "ConnectorType": "Example.Connector, Example.Assembly", <.>
        "Settings": {
          ... <.>
        }
      }
    }
  }
}
----
<.> `SecretStorage` -- секция должна быть одинакова для всех компонентов, подключенных к одной {of-mc}.
<.> `ConnectorType` -- полное имя класса коннектора, реализующего подключение внешнего источника.
<.> `Settings` -- индивидуальные настройки коннектора. Набор параметров в секции и их значения должны быть идентичными для всех компонентов, подключенных к одной {of-mc}.

Чувствительные данные для подключения к хранилищу, такие как токены, пароли, API-ключи и другие, не рекомендуется задавать в открытом виде в конфигурационном файле. В целях безопасности они могут быть определены в переменных окружения.

Набор настроек в секции `Settings` отличается в зависимости от типа хранилища. Может включать адрес, токен, путь, идентификатор приложения, таймаут подключения и множество других параметров. Список параметров зависит от реализации коннектора и определяется его разработчиком. Администратор заполняет их в соответствии с документацией к коннектору. Например, для OpenBao могут быть добавлены следующие настройки:

[source,json]
----
{
  "DocsVision": {
    "SettingsService": {
      "ApiKey": "anything",
      "SecretStorage": {
       "ConnectorType": "DocsVision.Settings.Extensions.OpenBao.OpenBaoSecretStorageConnector, DocsVision.Settings.Extensions.OpenBao", <.>
       "Settings": {
        "Url": "http://docsvision.example.com:8200", <.>
        "Token": "this-is-token" <.>
       }
      }
    }
  }
}
----
<.> `ConnectorType` -- тип коннектора к хранилищу секретов, в данном случае -- OpenBao.
<.> `Url` -- адрес подключения к хранилищу.
<.> `Token` -- токен для доступа к хранилищу.

Когда внешний провайдер настроен в конфигурации, при запуске компонента выполняется тестовое обращение к хранилищу. Если хранилище недоступно, служба компонента не запускается, а в журнал записывается ошибка с причиной отказа.

NOTE: Одновременно допускается подключать только одно внешнее хранилище.

[#read]
== Чтение настроек компонентов системы

Компоненты системы (например, {wc}, {sett-serv}, и др.) получают настройки в следующем порядке:

. Переменные окружения
. Конфигурационный файл
. Сервис настроек (значение возвращается напрямую или из внешнего хранилища секретов)

Чтение значения выполняется последовательно в соответствии с указанным порядком. Если значение найдено в одном из источников, дальнейший поиск не выполняется.

Наивысшим приоритетом обладают значения, указанные в переменных окружения. Если настройка не найдена в переменных окружения, выполняется его поиск в  конфигурационном файле. В последнюю очередь значение будет получено из {of-sett-serv}. Если для параметра настроено внешнее хранилище настроек, значение будет получено из него через {sett-serv}.

Для доступа к внешнему хранилищу секретов требуется доступность {of-sett-serv}. Если {sett-serv} недоступен, настройка не может быть получена, даже при доступности внешнего хранилища секретов.

[#fields]
== Полный список настроек, записываемых в хранилище секретов

Если внешнее хранилище секретов настроено, значения следующих настроек сохраняется в него. В {sett-serv} сохраняется только указатель на секрет.

[cols=",", options="header"]
|===

|Страница настроек в {mc} |Настройка

.3+|**Сервер приложений** |Пароль системной учетной записи

|API-ключ для подключения к Workflow

|Строка подключения к БД в Мастере БД

|**Веб-клиент** |Пароль системной учетной записи

.2+|**Управление процессами** |Пароль системной учетной записи

| API-ключ

|**Файловый сервис** |Строка подключения к БД

|**Домен** |Пароль пользователя для подключения к LDAP-каталогам текущего домена

|**Расширение** |Настройки расширения

|===
