= Работа с хранилищем секретов

Конфиденциальные настройки и параметры конфигурации {dv} могут быть прочитаны из специализированных хранилищ секретов. К секретам относятся, например API-ключи для подключения к Сервису настроек, пароли системных пользователей и т.д., полный список см. <<fields,ниже>>. Поддерживаются хранилища секретов Vault, OpenBao, Infisical или др.

Работа с хранилищами секретов поддерживается в {dv}, начиная с версий, входящих в {mc-cu1}.

Для подключения к внешнему хранилищу в конфигурационные файлы `appsettings.json` основных компонентов (Сервер приложений, {wc}, {wf}, {fs}, {mc}) в секцию `SettingsService` добавляется вложенная секция `SecretStorage`. Фрагмент json-схемы для настройки доступа:

[source,json]
----
{
  "Docsvision": {
    "SettingsService": {
      "SecretStorage": { <.>
        "ConnectorType": "Example.Connector, Example.Assembly", <.>
        "Settings": {
          ... <.>
        }
      }
    }
  }
}
----
<.> `SecretStorage` -- cекция должна быть одинакова для всех компонентов, подключенных к одной {of-mc}.
<.> `ConnectorType` -- полное имя класса коннектора, реализующего подключение внешнего источника.
<.> `Settings` -- индивидуальные настройки коннектора. Набор параметров в секции и их значения должны быть идентичными для всех компонентов, подключенных к одной {of-mc}.

Набор настроек в секции `Settings` отличается в зависимости от типа хранилища. Может включать адрес, токен, путь, идентификатор приложения, таймаут подключения и множество других параметров. Список параметров зависит от реализации коннектора и определяется его разработчиком. Администратор заполняет их в соответствии с документацией к коннектору. Например, для OpenBao могут быть добавлены следующие настройки:

[source,json]
----
{
  "DocsVision": {
    "ServiceId": "0000-0000-0000-0000-0000",
    "SettingsService": {
      "ConnectionString": "http://docsvision.example.com:5200/api",
      "ApiKey": "anything", <.>
      "SecretStorage": {
       "ConnectorType": "DocsVision.Settings.Extensions.OpenBao.OpenBaoSecretStorageConnector, DocsVision.Settings.Extensions.OpenBao",
       "Settings": {
        "Url": "http://docsvision.example.com:8200",
        "Token": "this-is-token"
       }
      }
    }
  }
}
----
<.> Чувствительные данные для подключения к хранилищу, такие как токены, пароли, API-ключи и другие, не рекомендуется задавать в открытом виде в конфигурационном файле. В целях безопасности они могут быть определены в переменных окружения.

Когда внешний провайдер настроен в конфигурации, при запуске компонента выполняется тестовое обращение к хранилищу. Если хранилище недоступно, служба компонента не запускается, а в журнал записывается ошибка с причиной отказа.

NOTE: Одновременно допускается подключать только одно внешнее хранилище.

[#fields]
== Полный список настроек

Если внешнее хранилище секретов настроено, значения следующих настроек сохраняется в него. В {sett-serv} сохраняется только указатель на секрет.

[cols=",", options="header"]
|===

|Страница |Настройка

.2+|**Сервер приложений** |Пароль системной учетной записи

|API-ключ для подключения к Workflow

|**Мастер БД** |Строка подключения к БД

|**Веб-клиент** |Пароль системной учетной записи

.2+|**Управление процессами** |Пароль системной учетной записи

| API-ключ

|**Файловый сервис** |Строка подключения к БД

|**Домен** |Пароль пользователя для подключения к LDAP-каталогам текущего домена

|**Расширение** |Настройки расширения

|===
