= Требования учётной записи сервера {dv}

Перечисленные права должны быть предоставлены системной учётной записи {dv} -- учётной записи для службы сервера {dv}.

== Требования на уровне СУБД

.Для СУБД {mssql} Server:
* CREATE VIEW, CREATE TABLE, CREATE PROCEDURE, CREATE FUNCTION и ALTER SERVER STATE на уровне базы данных, ALTER DATABASE, а также ALTER для схемы dbo.
* Учётная запись для входа в СУБД должна обладать правами `sysadmin`. В противном случае не получится создать или обновить БД, также не получится использовать полнотекстовый поиск {mssql}.
* На системную базу данных _master_:
+
** Разрешение EXECUTE для процедуры sp_configure.
** Разрешение EXECUTE на расширенной хранимой процедуре *xp_cmdshell*.
** Разрешение EXECUTE для всех пользовательских хранимых процедур и функций.
** Роли: *db_ddladmin*, *db_datareader*.
** Разрешение VIEW SERVER STATE.
+
.Выдать права вручную можно, например, так:
[source,sql]
----
USE MASTER

GO

GRANT VIEW SERVER STATE TO [DOMAIN\userAccount]
----
+
* На системную базу данных _msdb_: роли db_datareader и SQLAgentOperatorRole (минимально допускается: SQLAgentUserRole).
* На системную базу данных _tempdb_: роль db_owner (минимально допускается комбинация: datareader, datawriter, ddladmin).
* На все базы данных {dv}:
+
--
** Роль db_owner.
** EXECUTE для хранимых процедур, которые начинаются с префиксов *dvsys_*, *dvsp_* и *dvreport_* (используются для обработки данных).
** SELECT, INSERT, UPDATE, DELETE для таблиц *dvsys_sessions*, *dvsys_card_group*, *dvsys_file_group* (используются для создания сессии, групповой обработки карточек и файлов).
** SELECT на всех таблицах базы данных, которые начинаются с префиксов *dvsys_* и *dvtable_* (необходимо для подсистемы поиска и представлений).
--
+
* Необходимые привилегии на работу с другими БД, если доступ к ним осуществляется из разработанных серверных расширений или иными способами.
* Полный доступ к папке FileStream, если подключено хранилище "FileStream хранилище во внешней базе данных {mssql} Server" или "Filestream хранилище в базе данных {dv}".

.Для СУБД {pgsql}:
* Права пользователя "postgres".
+
[WARNING]
====
Данные требования предъявляются к учётной записи, с которой сервер {dv} обращается к БД {dv}:

* Если БД подключена с использованием SQL-аутентификации, то данные требования предъявляются к учётной записи, которая указана при подключении БД к {dv}.
* Если БД подключена с использованием аутентификации Windows, то данные требования предъявляются к учётной записи, от имени которой запущен пул приложений _DefaultAppPool_ и служба Сервера {dv}.
====
