= Общие сведения о коннекторе

== Назначение и функции Коннектора

_Коннектор к Saby (СБИС)_ является дополнительным компонентом _{of-em}_, который добавляет поддержку работы с оператором Saby (СБИС).

Коннектор предоставляет следующие возможности:

* Отправка и получение электронных документов через оператора Saby (СБИС).
* Получение списка организаций и контрагентов, зарегистрированных у оператора ЭДО Saby (СБИС).

== Необходимые ресурсы

[cols=",",options="header"]
|===
|Требование
|Описание требования

|Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Необходимое программное обеспечение
|Серверная и клиентская части _{of-em}_ версии {edi-req} и выше.

|Требования к каналам связи
|Администратор локальной сети должен обеспечить возможность подключения с сервера {dv} и серверов СУБП к сервису оператора Saby (СБИС). Стандартная точка подключения: "https://online.sbis.ru/".

|Лицензия
|Для работы с Коннектором лицензия на систему {dv} должна содержать дополнительную опцию _{dv} Коннектор к Saby (СБИС)_.

|Учётная запись в системе Saby (СБИС)
a|Для передачи электронных документов через оператора ЭДО "Saby (СБИС)" необходимо быть зарегистрированным пользователем данной системы. Регистрация организации в системе "Saby (СБИС)" выполняется самостоятельно.

Для загрузки контрагентов требуется подключение к ЭДО "Saby (СБИС)" с тарифом, включающим оплату доступа к API. В противном случае при загрузке контрагентов в журнале сервера будет появляться ошибка "Необходима оплата тарифа АПИ". Если учётная запись используется в нескольких независимых организациях с разными тарифами, конкретно для коннектора можно сделать отдельную учётную запись и добавить её только в организации с доступом к API.

[NOTE]
====
Информация о подключении к оператору Saby (СБИС) приведена на сайте https://www.sbis.ru/.
====
|===
