include::dv6@installguide:ROOT:pre-config-server.adoc[]

[#runtime]
== Обновление среды выполнения

. Обновите до {asp-bundle}:
+
* Клиентские рабочие места, использующие DvWebTool и DVSupService
* Переведите собственные решения {wc}а на .NET 8.
+
. Обновите до {net-r}:
+
** Рабочие места с {wincl}ом.

include::dv6@programmer:WebClient:net6.adoc[leveloffset=+1]

[#solutions]
== Обновление компонентов собственных решений

. В {dv} 6.1 были обновлены собственные компоненты {dv}. Перекомпилируйте свои проекты, в которых есть зависимости от сборок {dv}.
+
. В новой версии {dv} изменился способ хранения расширенных метаданных в БД: теперь данные хранятся в основных таблицах секций, а не в отдельных "extended"-таблицах. При обновлении системы стандартным образом все существующие данные из *extended*-таблиц будут перенесены в основные таблицы секций, а сами *extended*-таблицы переименованы в `dvtable_\{ID-секции}_extended_old_data`.
+
После обновления системы необходимо изменить код скриптов, напрямую обращающихся к *extended*-таблицам в БД, если такие функции были реализованы в Решении, например, для расчёта ролевой модели безопасности. К примеру, если существующий скрипт содержал обращение к таблице `dvtable\_\{3997861d-4ff5-496a-b8a2-d16617de91d7}\_extended`, теперь нужно обращаться к таблице `dvtable_\{3997861d-4ff5-496a-b8a2-d16617de91d7}`.
+
NOTE: Данное изменение не затрагивает динамические метаданные. Скрипты, работающие с таблицами динамических секций и полей, изменять *не нужно*.
+
. Изменился цикл жизни серверного расширения: теперь на каждое обращение к расширению создаётся новый экземпляр, а затем уничтожается. Это может потребовать изменить код серверного расширения, если расширение сохраняет своё состояние между вызовами.
+
. Изменилось описание расширенных отчётов в схеме библиотеки карточек, теперь указывается тип файла отчёта, задаётся описание колонок результирующей выборки и другие. Это может потребовать повторного формирования и загрузки собственных отчётов.

[#libs]
== Обновление компонентов собственных библиотек карточек

В новой версии модуля {pl} изменился механизм проверки соответствия клиентских компонентов библиотек карточек.

.Если в решении на базе {dv} реализованы собственные библиотеки карточек:
. Подключите новые сборки {dv} к проекту компонента.
. Добавьте в ресурсы XML-файл с описанием библиотеки карточек.
. В реализацию класса `CardLibrary` -- если .NET-сборка -- добавить переопределение метода `GetLibraryDefinition`. Метод должен возвращать описание библиотеки карточек.
+
[source,csharp]
----
protected override string GetLibraryDefinition()
{
  return Resources.CardLibDefinition;
}
----
+
. Повторно соберите, протестируйте работоспособность и распространите клиентский компонент библиотеки карточек.
+
.Для С++ реализации клиентского компонента библиотеки карточек нужно:
* Поддержать интерфейс `ICardLibraryInfo2`;
* Изменить поведение свойства `ICardLibraryInfo.Version`.
+
См. подробнее в руководстве разработчика, раздел "xref:programmer:samples:solution/snap-in/new-snap-in.adoc[]").
