:os1: Astra Linux

= Удаление старой версии {dv} 6.1

. Перед удалением сохраните настройки сервера (названия подключенных баз данных, учётные записи сервисов, имена почтовых профилей, настройки производительности сервиса Workflow, и другие), которые можно найти в конфигурационных файлах модулей.
+
Удалите все установленные серверные компоненты с сервера Linux, следуя инструкции в руководстве по установке на Linux, раздел "xref:new-admin-console@install-linux:ROOT:uninstall.adoc[]", или используя команды ниже:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get purge docsvision-*

{os2}::
+
 $ sudo dnf remove package docsvision-*

{os3}::
+
 $ sudo apt-get remove --purge docsvision-*
====
+
. Удалите все установленные серверные компоненты с машины Windows стандартным образом (используя меню "Установка и удаление программ"), также удалите комплект утилит {rk}, если он был установлен. Модуль {pl} удаляется в последнюю очередь. +
Серверные компоненты были необходимы для работы {cns} и {pu}. Начиная с НО 26.1, настройка системы выполняется с помощью {of-mc}.
+
. Если клиентские и серверные компоненты старой версии устанавливались на одной машине, после удаления серверных компонентов запустите восстановление клиентских компонентов модуля {pl}. Найдите в списке установленных программ `Docsvision PlatformСlient`, нажмите кнопку *Восстановить* и проследуйте инструкциям мастера установки.
