= Удаление старой версии {dv} 6.1

. Перед удалением сохраните настройки сервера (названия подключенных баз данных, учётные записи сервисов, имена почтовых профилей, настройки производительности сервиса Workflow, и другие), которые можно найти в конфигурационных файлах модулей.
+
Удалите все установленные серверные компоненты с сервера Linux, следуя инструкции в руководстве по установке на Linux, раздел "xref:new-admin-console@install-linux:ROOT:uninstall.adoc[]", или используя команды ниже:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get purge docsvision-*

{os2}::
+
 $ sudo dnf remove package docsvision-*
====
+
. Если клиентские и серверные компоненты старой версии устанавливались на одной машине, после удаления серверных компонентов запустите восстановление клиентских компонентов модуля {pl}. Найдите в списке установленных программ `Docsvision PlatformСlient`, нажмите кнопку *Восстановить* и проследуйте инструкциям мастера установки.
. Перезагрузите компьютер.
. Удалите серверные компоненты с машины Windows стандартным образом (используя меню "Установка и удаление программ"). Модуль {pl} удаляется в последнюю очередь.
+
Перед удалением сохраните настройки, которые можно найти в Консоли настройки {dv}.
+
. Удалите стандартным образом компоненты {dv} на кластерах и отдельных серверах, например, для модулей "{wf}", "Служба {ws}" и "{mc}". Если был отдельно установлен сервис полнотекстового поиска, удалите его стандартным образом.
. Перезагрузите компьютеры.
