= Контейнер строка

Элемент разметки `_Контейнер строка_` является контейнером для других элементов управления. Дочерние элементы управления в ЭР `_Контейнер строка_` размещаются последовательно слева направо.

== Особенности элемента управления "Контейнер строка"

* Содержимое элемента управления при необходимости переносится на следующую строку (без ограничений по высоте).
* Вложенные элементы размещаются последовательно без пропусков с настраиваемым разделителем.
* Вложенные элементы управления должны быть в режиме редактирования *_Без редактирования_*.
* Поддерживаются следующие типы дочерних элементов управления: `_Строка_`, `_Метка_`, `_Дата/время_`, `_Флаг_`, `_Раскрывающийся список_`, `_Число_`, `_Партнер_`, `_Подразделение_`, `_Подразделение контрагента_`, `_Строка конструктора справочников_`.

== Свойства

include::partial$properties.adoc[tags=general]

=== Внешний вид

include::partial$properties.adoc[tags=divider]

include::partial$properties.adoc[tags=labelText]

=== Поведение

include::partial$properties.adoc[tags=visibility]

include::partial$properties.adoc[tags=addCss]

include::partial$properties.adoc[tags=editOperationForVisibility]

include::partial$properties.adoc[tags=stdCss]

=== События

include::partial$properties.adoc[tags=mouseOver]

include::partial$properties.adoc[tags=mouseAway]

include::partial$properties.adoc[tags=onClick]
