= Функции администратора

При установке модуля _{am}_ в систему {dv} будут загружены стандартные настройки (роли, состояния).

WARNING: Изменение стандартных настроек не допускается.

.Администратору системы разрешается:
* Настраивать дискреционные права доступа к узлам Справочника номенклатуры делfootnote:[Пользовательский интерфейс настройки дискреционных прав доступа реализован в _{wc}е_.]. Удалять настроенные дискреционные права к узлам Справочника номенклатуры дел не рекомендуется.
* Создавать новые роли для работы с карточками:
** Объекты номенклатуры:
*** Раздел
*** Архивное дело
*** Том
*** Фонд
*** Опись
** Архивный документ
* Изменять созданные роли. Удалять созданные роли не рекомендуется.

.Работа с функциями модуля осуществляется в {wc}е:
. При установке {wc}а должны быть установлены компоненты _{am}_. См. xref:webclient:admin:install-server.adoc#archive[документацию по администрированию модуля "{wc}"].
. В основное меню должна быть добавлена ссылка для открытия Справочника номенклатуры дел. См. пользовательскую документацию xref:webclient:user:docs-to-case.adoc[модуля "{wc}"].

[#view-docs]
== Просмотр документов, списанных в дело

Чтобы просматривать документы, списанные в дело, в карточке:

* _Архивное дело_
* _Том_

Должен находиться элемент управления `_Контрол табличных данных_`.
ЭУ выводит все документы из первого найденного тома данного дела. Том создаётся автоматически при добавлении в дело первого документа. Подробнее элемент управления описан в документации модуля {wc}, см. подробнее раздел "xref:webclient:layouts:ctrl/table/dataGridControl.adoc[]".
