= Настройка отображения поля «Индекс подразделения»

Поля _Индекс организации_ и _Индекс подразделения_ используются для расчета
индекса раздела и индекса подраздела в справочнике номенклатуры дел в типе строки _Организация_ и в типе строки _Подразделение_.

Оба поля привязаны в схеме данных к General Data\UnitIndex.

== Справочник «Места хранения»

Справочник «Места хранения» необходим для заполнения поля «Место
хранения» в карточке дела. Для строки справочника настроена собственная
разметка, которая включает поля:

* Название (стандартное поле)
* Адрес (строка)

Справочник располагается по пути: Конструктор
справочников\Управление архивом\Места хранения.

== Справочник «Сроки хранения»

Справочник _Сроки хранения_ необходим для заполнения поля _Срок
хранения_ в карточке дела. Для строки справочника настроена собственная
разметка, которая включает поля:

[cols="34%,33%,33%",options="header"]
|===
|Название поля |Назначение |Тип поля

|Название |Название статьи по перечню утверждённых сроков хранения
|Строка (стандартное поле)

|Описание |Описание статьи по перечню утверждённых сроков хранения
|Текст (стандартное поле)

|Срок (лет) |Исчисляемый в годах срок хранения |Целое число

|Срок (список) |Неисчисляемый срок хранения a|
Выпадающий список значений:

* Пост
* ДМН
* ДЗН
* До ликвидации организации
* До ликвидации справочно-информационного фонда, библиотеки организации
* До востребования
* До списания транспортных средств

|Номер статьи |Номер статьи по перечню утверждённых сроков хранения
|Строка

|Пункт статьи |Пункт статьи по перечню утверждённых сроков хранения
|Строка

|ЭПК |Необходимость проведения ЭПК для принятия решения об уничтожении
документов |Да/Нет

|Примечания |Дополнительные примечания по статье хранения |Текст
|===

Справочник располагается по пути: menu:Конструктор
справочников[Управление архивом > Сроки хранения].