:link: https://github.com/Docsvision/WebClient-Samples/tree/master/Others/NetStatSolution
:name: NetStatSolution

= Пример разработки решения

В данном практическом примере содержится типовой сценарий разработки решения.

include::WebClient:client/authorization.adoc[tags=link]

include::6.1@webclient:ROOT:partial$excerpts.adoc[tags=wc-node]
* Visual Studio {vscode-v} и выше.
* WiX Toolset -- для сборки пакетов установки. Последняя версия доступна на http://wixtoolset.org/[странице] проекта.
* Установленные клиентские компоненты базовых модулей {dv} (обязательно Платформа, {wincl}), совместимые с платформой {dv} версии 6.1 и выше.

== Основные сведения

Пример, приведенный в данном разделе, содержит полный сценарий создания собственного решения (на платформе {dv}) для учёта сетевого оборудования организации и сбора статистики его отказов, а также исходные коды всего проекта.

В процессе его создания будут рассмотрены вопросы, связанные с разработкой библиотеки карточек, пакетов установки, а также необходимых модулей {dv}. Вопросы, связанные с локализацией решений, а также созданием пакетов установки для различных платформ, здесь не рассматриваются.

.Для данного решения будут созданы:
* Библиотека карточек и её компонент.
* Карточка *учёта сетевого оборудования* и её компонент.
* Два пакета установки: клиентская и серверная части.
* Объектная модель карточки учёта сетевого оборудования.
* Расширение {wc}а для добавления кнопки создания карточки учёта сетевого оборудования в диалог создания карточек.
* Web-расширение для оформления кнопки создания карточки.
* Решение с разметками создания, просмотра и редактирования карточки учёта сетевого оборудования.

Также введём дополнительное требование на совместимость карточки с конструкторами {dv}, чтобы иметь возможность настраивать разметку карточки при помощи _конструктора разметок_.

.Чтобы решение было законченным, также потребуются:
* Бизнес-процесс _Проверка доступности сетевых узлов_, который должен фиксировать факт изменения доступности сетевого устройства. +
Непосредственная реализация логики проверки не предусмотрена.
+
* Выгруженные настройки _справочника видов карточек_, _конструктора разметок_, _конструктора состояний_ и другие.
* В качестве примера, экземпляр карточки _учёта сетевого оборудования_, который предполагается загружаться в {dv} при установке решения. В собственном решении подобным образом может быть загружен шаблон карточки.

Данное руководство сопровождается исходными кодами всего решения, в том числе пакетов установки, а также схемами библиотеки карточек и карточки.

== Описание файлов проекта

* `Binaries` -- каталог для размещения готовых сборок.
* `CardDefs` -- каталог со схемами карточки учёта сетевого оборудования и библиотеки модуля учёта сетевых устройств, а также их ресурсами.
* `CardLib` -- каталог с проектом (C#) компонента библиотеки карточек.
* `CardPackage` -- каталог с данными справочников и конструкторов, выгруженных из базы данных {dv}. Используются на этапе формирования `CardPackage` и `SqlPackage`.
* `Database` -- каталог с файлом, определяющим путь к файлу с метаданными библиотеки карточек. Используются на этапе формирования `CardPackage` и `SqlPackage`.
* `Installers` -- каталог сборки пакетов установки.
* `NetstatSolution.Cards` -- каталог с проектом компонента карточки.
* `NetStatSolution.ObjectModel` -- каталог с объектной моделью карточки.
* `NetstatSolutionClientInstaller` -- каталог с проектом пакета установки клиентской части решения.
* `NetstatSolutionInstaller` -- каталог с проектом пакета установки серверной части решения.
* `NetStatSolutionServerExtension` -- расширение {wc}а для добавления кнопки создания карточки учёта сетевого оборудования в диалог создания карточек.
* `NetStatSolutionWebExtension` -- web-расширение для оформления кнопки создания карточки.
* `Solution` -- каталог решения с разметками создания, просмотра и редактирования карточки учёта сетевого оборудования.
