= Настройки модуля "{td}"

.Перед использованием модуля "{td}" требуется выполнить настройки:
. {blank}
+
[subs="specialchars,attributes,quotes"]
Укажите настройки модуля в конфигурационном файле модуля по адресу {config}:
+
.Заполните настройки соединения {dv}:
[source,json]
----
{
  "DocsVisionConnection": {
      "Url": "http://localhost:5000/api/v1", <.>
      "Database": "DocsvisionDB", <.>
      "Username": "User", <.>
      "Password": "P@ssword" <.>
  },
  "DateFormat": "yyyy-MM-dd HH:mm:ss", <.>
  "DecimalFormat": "#,##0.00", <.>
  "Kestrel": { <.>
    "Endpoints": {
      "Http": {
        "Url": "http://*:7047" <.>
      }
    }
  }
}
----
<.> Адрес сервера приложений.
<.> Псевдоним БД {dv}.
<.> Имя пользователя для подключения к серверу {dv}. Предоставьте этой учётной записи права, необходимые для выполнения операций сервиса.
<.> Пароль пользователя для подключения к серверу {dv}.
<.> Опциональный параметр, задающий предпочитаемый формат даты, например, согласно https://ru.wikipedia.org/wiki/ISO_8601[ISO 8601].
<.> Опциональный параметр, задающий предпочитаемый https://learn.microsoft.com/en-us/dotnet/api/system.decimal.tostring[формат] чисел.
<.> Адрес и порт запуска сервиса {of-td}.
+
. Перезапустите службу {of-td}.
. Выполните необходимые настройки в справочнике {of-td} документов согласно инструкции в разделе "xref:template-designer.adoc#setup[Первичная настройка Конструктора шаблонов]".
