:update:
:os1: Astra Linux

= Установка обновлений

WARNING: Накопительное обновление 25.3 переводит все модули {dv} на .NET 8. Обновление отдельных модулей невозможно, обновлять необходимо всю систему целиком. На серверах системы потребуется обновление дополнительного ПО {asp-bundle}.

include::new-admin-console@install-linux:ROOT:pre-config-server.adoc[tags=astranet]

[#modules]
== Обновление модулей

. После ознакомления с условиями, описанными в разделе "xref:index.adoc[]" и установки {asp-bundle} на сервера {dv} обновление выполняется стандартным образом:
+
include::ROOT:partial$main-update-process.adoc[]
+
. Запустите программу _{cns}_ и обновите существующую БД стандартным образом. При необходимости воспользуйтесь инструкцией, приведённой в документации модуля _{pl}_, раздел "xref:6.1@platform:console:db-update.adoc[]".
+
NOTE: Установка флагов в диалогах выбора обновляемых библиотек карточек и настроек модулей может оказаться недоступной, если изменений в библиотеке карточек между обновлениями не было.

[#client]
== Обновление клиентских компонентов

. Обновите до {asp-bundle}:
+
* Клиентские рабочие места, использующие DvWebTool и DVSupService
* Переведите собственные решения {wc}а на .NET 8.
+
. Обновите до {net-r}:
+
** Рабочие места с {wincl}ом.
+
. Клиентские компоненты модулей на компьютерах пользователей обновятся автоматически после запуска {wincl}а. Также новые версии можно установить вручную из предоставляемых пакетов установки. Новые версии модулей устанавливаются с областью установки модуля {pl}.
