:config-ws: `/usr/lib/docsvision/workerservice/Configuration.json` для Linux и `C:\Program Files\Docsvision\WorkerService\Configuration.json` для Windows

= Настройка кластера Службы {ws}

Служба {ws} поддерживает работу в кластере. При необходимости работы в кластере, администратор должен выполнить шаги, описанные в данной инструкции.

. Установите и настройте Службу {ws} на первом узле кластера согласно xref:install.adoc[инструкции].
. По аналогии установите Службу {ws} на втором узле кластера.
. {blank}
+
[subs="specialchars,attributes,quotes"]
У второго экземпляра Службы {ws} заполните настройки в конфигурационном файле {config-ws}.
+
[source,json]
----
{
  "SettingsServiceConnectionString": "ConnectAddress=http://settings.domain.com:5200/api", <.>
  "ApiKey": "anything", <.>
  "RestApiAddress": "http://worker.domain.com:5900/api", <.>
  "LogTraceLevel": "1" <.>
}
----
<.> `SettingsServiceConnectionString` -- Адрес подключения к Сервису настроек, который должен совпадать с тем, что указан в конфигурационном файле первого экземпляра Службы {ws}.
<.> `ApiKey` -- Ключ доступа к Сервису настроек -- "пароль",  который  должен совпадать с тем, что указан в конфигурационном файле первого экземпляра Службы {ws}.
<.> `RestApiAddress` -- Адрес подключения к Службе {ws}. По умолчанию указан `\http://localhost:5900/api`. Укажите сетевой адрес, по которому {sett-serv} сможет обращаться к данному экземпляру.
<.> `LogTraceLevel` -- Уровень журналирования Службы {ws}, см. подробнее "Журнал работы".
+
. Откройте {mc} и убедитесь, что на странице xref:mgmtconsole:user:worker-service.adoc["Настройка Службы {ws}"] отобразился второй узел Службы {ws}.
. Для второго узла Службы {ws} подключите необходимые процессы и укажите в них соединения {dv} и почтового сервера, которые указаны в процессах первого узла Службы {ws}.
