= Шифрование настроек Службы {ws}

Чувствительные настройки Службы {ws}, например, пароли и ключи рекомендуется шифровать. Так как хранилищем настроек является {sett-serv}, шаги, необходимые для шифрования настроек, описаны в документации {of-sett-serv}, см. раздел "xref:CU-MC@settings-service:admin:encryption.adoc[]".

include::CU-MC@settings-service:admin:encryption.adoc[tags=sett-serv-version]
Поддерживаемая версия Службы {ws} и расширения для {of-mc}: {worker-serv-encr-req}.

Если в Сервисе настроек задано шифрование, настройки будут зашифрованы перед сохранением в базу данных Сервиса настроек. В противном случае настройки хранятся в открытом виде.

.Список шифруемых настроек Службы {ws}:
[cols=",",options="header"]
|===

|Настройка |Комментарий

|Пароль в соединении к {dv} |
|Пароль в почтовом соединении к MS Exchange Web Service |
|Пароль в почтовом соединении к POP3 серверу |
|Пароль в почтовом соединении к SMTP серверу |
|Клиентский секрет в почтовом соединении к MS Exchange Web Services |
|API-ключ для {of-mir} |Для типа конфигурации "Коннектор к реестру МЧД" в {of-mc}.

|===
