= Запуск Службы {ws}

[subs="specialchars,attributes,quotes"]
Работу _Службы {ws}_ обеспечивает служба {wss-new}. Данная служба должна быть запущена от имени учётной записи с правами администратора, т.е. для УЗ требуется членство в группе *{dv-sys-wf-dir}* в справочнике сотрудников на сервере {dv}.
// учётная запись должна быть добавлена в группу локальных администраторов на сервере {dv}.

_Cлужба {ws}_ может использовать сервис перештамповки подписей.
// tag::cpus[]
Для корректной работы службы {ws} с использованием сервиса перештамповки подписей необходимо использовать машину, имеющую как минимум два процессора.
// end::cpus[]

При первом запуске _Служба {ws}_ читает список типов установленных расширений и прописывает себя вместе с расширениями в _{sett-serv}_. Таким образом Служба {ws} идентифицирует себя и открывает доступ к своим функциям для системы {dv}.

В дальнейшем, когда _Служба {ws}_ прочитает конфигурацию и создаст расширения, для работы отдельных расширений могут потребоваться права пользователей из группы _{dv-sys-wf-dir}_ в справочнике сотрудников {dv}.

Все настройки службы считываются из _{of-sett-serv}_.

[NOTE]
====
// tag::console[]
[subs="specialchars,attributes,quotes"]
При использовании модуля _{mc}_ убедитесь, что сервер {dv} на Linux активен и на нём запущены службы {of-mc}, {of-sett-serv} и Службы {ws}.

// , что учётная запись, под которой запускается _Служба {ws}_ включена в группу *{dv-sett-serv-admins-serv}* на сервере с модулем _{mc}_.
// end::console[]
В противном случае будет недоступен xref:6.1@mgmtconsole:user:worker-service.adoc[узел Службы {ws}] в {of-mc}.
====
