= Журнал работы

Журнал работы модуля в локальной файловой системе располагается в каталоге `/var/log/docsvision` для Linux и `C:\ProgramData\Docsvision\Logs` для Windows.

// include::install-linux:ROOT:appendix/commands.adoc[tags=log]

:module-service: {ws}
include::6.1@webclient:admin:partial$excerpts.adoc[tags=no-rights]

Пути к журналам и уровень журналирования настраиваются в конфигурационном файле по адресу `/usr/lib/docsvision/workerservice/Configuration.json` в Linux и `C:\Program Files\Docsvision\WorkerService\Configuration.json` в Windows:

* `LogFile` -- путь к журналу работы.
* `LogTraceLevel` -- уровень журналирования.
+
.Администратор может настроить следующие уровни журналирования:
** Журналирование отключено (Off) = `0`.
** Только ошибки (Error) = `1`.
** Ошибки и предупреждения (Warning) = `2`.
** Сообщения, ошибки и предупреждения (Info) = `3`. При установке данного уровня 1 раз в минуту в журнал будет записываться информация по текущей загрузке Службы {ws}: количество обработанных сообщений и задач, количество сообщений и задач в обработке, длину очередей задач и сообщений.
** Подробное журналирование (Verbose) = `4`. При установке данного уровня в сообщениях о начале и завершении обработки сообщения указывается точный идентификатор сообщения (`RowID`) и идентификатор карточки сообщений (`InstanceID`). Также указывается точное время выполнения задач.
