:wt: edi-diadoc-server

= Установка и удаление Коннектора

[#requirements]
== Требования

Ознакомьтесь с требованиями в разделе "xref:ROOT:requirements.adoc[]".

Пользователь, выполняющий установку {of-em}, должен обладать правами локального администратора.

[NOTE]
====
Администратор {dv} -- пользователь, включенный в группу безопасности *{dv-admins-serv}* в конфигурационном файле модуля {pl}.
====

[#linux-connector]
== Установка компонентов Коннектора к Диадок на сервер под управлением Linux

Серверные компоненты _Коннектора к Диадок_ устанавливаются на сервер под управлением Linux с установленными серверными компонентами _{of-em}_.

. При xref:admin:install.adoc[установке {of-em}] будет предложено установить также:
+
* `docsvision-edi-diadoc-server` -- дополнительный компонент модуля, добавляющий поддержку работы с оператором Диадок.
+
. _Коннектор к Диадок_ может быть установлен следующей командой с предварительным обновлением индекса пакетов:
include::6.1@platform:admin:partial$install.adoc[tags=commands]
+
include::ROOT:partial$excerpts.adoc[tags=last-connector]

[#windows-connector]
== Установка компонентов Коннектора к Диадок на сервер под управлением Windows

Серверные компоненты _Коннектора к Диадок_ устанавливаются на сервер под управлением Windows с установленными серверными компонентами _{of-em}_.

. При xref:admin:install.adoc#windows-server[установке {of-em}] компоненты Коннектора к Диадок устанавливаются вместе с Серверными компонентами {of-em}, дополнительных действий не требуется.

[#client]
== Установка клиентской части Коннектора

Клиентская часть _Коннектора к Диадок_ устанавливается на компьютеры с установленной клиентская частью _{of-em}_. Если _{wincl}_ и клиентская часть _{of-em}_ установлены для всех пользователей, клиентский компонент _Коннектора_ также должен быть установлен для всех пользователей.

. Запустите мастер установки:
+
* `{dv} EDI Integration client.msi` и выберите компоненты _Коннектора к Диадок_ с областью установки _Для текущего пользователя_.
* `msiexec /i "{dv} EDI Integration client.msi" ALLUSERS=1`, чтобы установить Коннектор с областью установки _Для всех пользователей_. Для данного варианта установки требуются права администратора.
+
. Выполните шаги инструкции по xref:admin:install.adoc[установке {of-em}] Нажмите на кнопку *Готово*.

[#uninstall]
== Удаление Коннектора

. Удалите настройки оператора Диадок из _Справочника настроек операторов ЮЗДО_.
.. Откройте карточку _Справочник настроек операторов ЮЗДО_ в утилите _{dv} Explorer_ (входит в _{rk}_). Инструкция по работе с утилитой _{dv} Explorer_ приведена в документации _{rk}_, разделе "xref:6.1@resource-kit:dvexplorer:util.adoc[]".
.. Удалите из секции _Операторы_ строку оператора "Диадок".
. Удалите компоненты коннектора:
+
.. В ОС Windows Удалите компоненты коннектора через изменение инсталлятора:
+
* Клиентский компонент модуля: "Коннектор к Диадок. Клиент".
* Серверный компонент модуля: "Коннектор к Диадок. Сервер".
+
.. В ОС Linux удалить компоненты можно командой:
+
include::6.1@platform:admin:partial$delete.adoc[]
