= Настройка функций модуля {ai}

== Исправить текст

Для работы функции _Исправление текста_ администратору необходимо добавить в разметку элемент управления `_Контейнер_` из группы _AI_ и поместить в него элемент управления `_Текст_`.

NOTE: Функция доступна для использования в любых карточках.

== Краткий пересказ и Вопрос по файлу

Функции _Краткий пересказ_ и _Вопрос по файлу_ добавляются в систему как пункты контекстного меню элемента управления `_Список файлов_`. Для работы функций необходимо добавить в разметку элемент управления `_Контейнер_` из группы _AI_ и поместить в него элемент управления `_Список файлов_`.

NOTE: Функции доступны для использования только в карточках типа _Документ_ и _Задание_. В заданиях функция доступна только для основных файлов.

== Сгенерировать текст

Для работы функции _Генерация текста_, нужно добавить в разметку элемент управления `_Кнопка генерации текста_`.

NOTE: Функция доступна для использования в карточках типа _Документ_ и _Задание_.

== Информация о тарифах

Для возможности просмотра информации о текущем тарифе необходимо в конструкторе разметок (menu:WebFrame[Диалог профиля пользователя]) добавить еще одну вкладку и поместить в неё ЭУ `_Подписка_`.
