= Установка модуля "{фш}"

. Дополнительные библиотеки:
+
** NLog.dll v. 5.4.0.3182
** Newtonsoft.Json.dll v.13
+
Зарегистрируйте в GAC:
+
** Откройте консоль от имени администратора.
** Перейдите в каталог `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools` (версии могут отличаться).
** Выполните команду `gacutil.exe -i путь_до_библиотеки`.
+
. Распакуйте архив `AiExtension.zip` модуля в папку `%Каталог установки {wc}а%\5.5\`.
+
NOTE: Информация о загруженных клиентских расширениях отображается в {wc}е в окне "О программе".
+
. Содержимое архива будет распаковано в следующие каталоги:
+
* `AiServerExtension` -- `каталог-установки-{wc}а\5.5\Content\Extensions`
* `AiWebExtension` -- `каталог-установки-{wc}а\5.5\Content\Modules`
* `AiDesignerExtension` -- `каталог-установки-{wc}а\5.5\Plugins`
* `ai.config` -- `каталог-установки-{wc}а\5.5\Site`
+
. После распаковки элементов модуля по вышеуказанным путям необходимо нвыполнить настройки в конфигурационном файле `ai.config`. Все узлы, кроме `AiApiKeyECM`, заполнены по умолчанию. В конфигурационном файле содержится следующая информация:
+
* `AiProvider` -- наименование провайдера, содержащего логику взаимодействия с ИИ-сервисом. В данный момент доступно только одно значение: `EcmAiService`.
* `AiApiKeyECM` -- API-ключ для ИИ-сервиса ECM. Выдается по запросу в `sales@docsvision.com`
* `AiAddressECM` -- адрес подключения к ИИ-сервису ECM.
* `AiServiceECM` -- настройка ИИ-модели. В текущей редакции модуля для обработки запросов могут использоваться только последние модели ChatGPT (используется по умолчанию) и DeepSeek.
+
. Перезапустите IIS. Расширение программы {kvr} будет зарегистрировано, включая серверное и клиентское расширения.
. Новые элементы управления будут отображаться в библиотеке программы {kvr}, в группе AI.