= Обновление модуля {ai}

include::webclient:ROOT:partial$excerpts.adoc[tags=what-changed]

[#conditions]
== Условия обновления

* Установка новой версии должна выполняться в нерабочее время.
* Если была установлена новая версия модуля _{pl}_ и после её установки была пропущена обязательная операция обновления БД {dv}, обновите БД {dv} перед установкой модуля {ai}. Cм. инструкцию по обновлению в документации к соответствующей версии модуля _{pl}_.
* Перед установкой обновления xref:ROOT:requirements.adoc[ознакомьтесь] с требованиями к установке модуля.

Режим обновления предназначен для установки новой версии модуля {ai} без удаления существующей версии.

[#update]
== Порядок обновления

.Чтобы обновить версию модуля {ai}:
. Создайте резервную копию конфигурационного файла `ai.config`.
. Остановите службу модуля {ai}.
. xref:install.adoc[Установите] новую версию модуля без удаления существующей.
. Если файл `ai.config` предыдущей версии был модифицирован при настройке модуля {ai} и данные изменения требуется перенести в новую версию, выполните перенос вручную из резервной копии файла, созданной ранее.
. Запустите остановленную службу модуля {ai}.
