antora:
  extensions:
  - require: ./antora-navigator-extension/
    config_file: ./antora-navigator.yml
site:
  title: Документация Docsvision
  url: https://help.docsvision.com/
  robots: allow
urls:
  latest_prerelease_version_segment: dev
content:
  edit_url: ~
  sources:
    - url: https://gitlab.com/antora/demo/demo-component-a.git
      branches: HEAD
    - url: https://gitlab.com/antora/demo/demo-component-b.git
      branches: [v1.0, v2.0, main]
      start_path: docs
    - url: https://github.com/asciidoctor/asciidoctorj
      branches: main, v2.4.x
      start_path: docs
    - url: https://github.com/asciidoctor/asciidoctor-pdf
      branches: v2.3.x
      start_path: docs
    #  - url: https://github.com/Docsvision/WebC-Antora.git
    - url: https://github.com/Docsvision/Worker-Antora.git
    #  - url: https://github.com/Docsvision/Platform-Antora.git
    - url: https://github.com/Docsvision/WebAC-Antora.git
    - url: https://github.com/Docsvision/Install-Guide-Antora.git
    #  - url: https://github.com/Docsvision/Designers-And-Directories-Antora.git
    - url: https://github.com/Docsvision/System-Antora.git
    - url: https://github.com/Docsvision/Approval-Designer-Antora.git
    - url: https://github.com/Docsvision/Base-Objects-Antora.git
    - url: https://github.com/Docsvision/Platform-Upgrade-Antora.git
    - url: https://github.com/Docsvision/Engineer-Antora.git
    #  - url: https://github.com/Docsvision/Programmer-Antora.git
    #  - url: https://github.com/Docsvision/Windows-Client-Antora.git
    #  - url: https://github.com/Docsvision/Document-Management-Antora.git
    #  - url: https://github.com/Docsvision/Schemas-Antora.git
    - url: https://github.com/Docsvision/Solution-Manager-Antora.git
ui:
  bundle:
    url: ./build/ui-bundle.zip
  supplemental_files: ./supplemental-ui
output:
  dir: wwwroot
runtime:
  fetch: true
