antora:
  extensions:
  - '@antora/atlas-extension'
  - require: antora-navigator-extension
    config_file: ./antora-navigator.yml
  - id: unlisted-pages
    enabled: true
    require: ./lib/unlisted.js
#  - id: detect-unused-media
#    enabled: true
#    require: ./lib/detect-unused-media/detect-unused-media.js
site:
  title: Документация Docsvision
  url: /
#  start_page: current@system::index.adoc
  robots: allow
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:from
#  latest_prerelease_version_segment: dev
  html_extension_style: indexify
content:
  branches: ['5.5.*', '6.1*', '6.2*', 'GBL-*', 'SUP-*', 'CU*', 'dv5*', 'dv6*', 'NP-*', 'TSK-*', 'ERR-*']
  edit_url: ~
  sources:
#    - url: https://github.com/Docsvision/antora-product-changes.git
#      branches: [dev]
    - url: https://github.com/Docsvision/antora-start-page.git
      branches: [dv6]
    - url: https://github.com/Docsvision/antora-web-client.git
    - url: https://github.com/Docsvision/antora-worker-service.git
    - url: https://github.com/Docsvision/antora-platform.git
    - url: https://github.com/Docsvision/antora-management-console.git
    - url: https://github.com/Docsvision/antora-install-guide.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-designers-and-directories.git
    - url: https://github.com/Docsvision/antora-system-description.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-approval-designer.git
    - url: https://github.com/Docsvision/antora-back-office.git
    - url: https://github.com/Docsvision/antora-upgrade-guide.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-engineer-guide.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-programmer-guide.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-windows-client.git
    - url: https://github.com/Docsvision/antora-document-management.git
    - url: https://github.com/Docsvision/antora-schemas-description.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-solution-manager.git
    - url: https://github.com/Docsvision/antora-workflow.git
    - url: https://github.com/Docsvision/antora-archive-management.git
    - url: https://github.com/Docsvision/antora-edi.git
    - url: https://github.com/Docsvision/antora-resource-kit.git
    - url: https://github.com/Docsvision/antora-install-linux.git
      branches: ['dv5*', 'dv6*', 'GBL-*']
    - url: https://github.com/Docsvision/antora-take-office.git
    - url: https://github.com/Docsvision/antora-m4d-registry-integration.git
    - url: https://github.com/Docsvision/antora-kontur-integration.git
    - url: https://github.com/Docsvision/antora-directory-replication.git
    - url: https://github.com/Docsvision/antora-branch-exchange.git
    - url: https://github.com/Docsvision/antora-conversion-service.git
    - url: https://github.com/Docsvision/antora-template-designer.git
    - url: https://github.com/Docsvision/antora-notification-service.git
    - url: https://github.com/Docsvision/antora-s3-storage.git
    - url: https://github.com/Docsvision/antora-application-designer.git
    - url: https://github.com/Docsvision/antora-settings-service.git
    - url: https://github.com/Docsvision/antora-teamwork.git
    - url: https://github.com/Docsvision/antora-report-designer.git
    - url: https://github.com/Docsvision/antora-module-ai.git
#    - url: https://github.com/Docsvision/antora-type-admin.git
#      branches: [ dev ]
#    - url: https://github.com/Docsvision/antora-type-user.git
#      branches: [ dev ]
#    - url: https://github.com/Docsvision/antora-type-engineer.git
#      branches: [ dev ]
#    - url: https://github.com/Docsvision/antora-type-programmer.git
#      branches: [ dev ]
ui:
#  supplemental_files:
#    - path: js/nav.js
#      contents: ./node_modules/antora-navigator-extension/data/js/nav.js
  supplemental_files: ./node_modules/antora-navigator-extension/data/
  bundle:
    url: ./build/ui-bundle.zip
asciidoc:
  attributes:
    sectids: ''
    sectanchors: ''
    icons: font
    page-pagination: ''
    toclevels: 10
    experimental: ''
    idprefix: ''
    idseparator: '-'
    toc-title: 'Содержание'
    figure-caption: 'Рисунок'
    table-caption: 'Таблица'
    appendix-caption: 'Приложение'
    example-caption: 'Пример'
#    kroki-default-format: 'svg'
#    kroki-fetch-diagram: 'true'
    warning-caption: 'ОСТОРОЖНО'
    caution-caption: 'ВНИМАНИЕ'
    tip-caption: 'СОВЕТ'
    note-caption: 'ПРИМЕЧАНИЕ'
    important-caption: 'ВАЖНО'
    cns: 'Консоль настройки Docsvision'
    dispatch: 'Диспетчер служб IIS'
    dv: 'Docsvision'
    root-cert: 'Корневой сертификат удостоверяющего центра, выпустившего сертификат пользователя.footnote:[Например, корневой сертификат КриптоПро]@'
    sss: 'Docsvision 5.5 Storage Server'
    fts: 'Docsvision 5.5 Full-Text indexing Service'
    wfs: 'Docsvision 5.5 Workflow Server'
    fss: 'Docsvision 5.5 File Service'
    wss: 'Docsvision 5.5 Worker Service'
    wacs: 'Docsvision Management Console Service'
    wacss: 'Docsvision Settings Service'
    extapi: 'Docsvision Management Console External API Service'
    sss-win: 'Docsvision Platform'
    fts-win: 'Docsvision Full-Text indexing Service'
    wfs-win: 'Docsvision Workflow Server'
    fss-win: 'Docsvision File Service'
    wss-win: 'Docsvision Worker Service'
    wacs-win: 'Docsvision Management Console Service'
    wacss-win: 'Docsvision Settings Service'
    wcs-win: 'Docsvision Web-client'
    extapi-win: 'Docsvision Management Console External API Service'
    sss-new: '*dvappserver* для Linux и *{sss-win}* для Windows@'
    fts-new: '*dvfulltextservice* для Linux и *{fts-win}* для Windows@'
    wfs-new: '*dvworkflow* для Linux и *{wfs-win}* для Windows@'
    fss-new: '*dvfileservice* для Linux и *{fss-win}* для Windows@'
    wss-new: '*dvworkerservice* для Linux и *{wss-win}* для Windows@'
    wacs-new: '*dvconsole* для Linux и *{wacs-win}* для Windows@'
    wacss-new: '*dvsettings* для Linux и *{wacss-win}* для Windows@'
    wcs-new: '*dvwebclient* для Linux и *{wcs-win}* для Windows@'
    extapi-new: 'dvexternalapi@'
    pl: 'Платформа'
    wincl: 'Windows-клиент'
    wc: 'Web-клиент'
    ws: 'фоновых операций'
    of-ws: 'фоновой операции'
    is-ws: 'фоновая операция'
    kvr: 'Конструктор Web-разметок'
    ad: 'Конструктор согласований'
    dm: 'Управление документами'
    bo: 'Базовые объекты'
    wf: 'Управление процессами@'
    to: 'Делопроизводство 4.5'
    es: 'Elasticsearch'
    es-v: '7.14.0@'
    es-link: '7-14-0@'
    em: 'Модуль интеграции с операторами ЭДО'
    rk: 'Resource Kit'
    dvcm: '{dv} CardManager'
    am: 'Управление архивом'
    sm: 'Менеджер решений'
    of-sm: 'Менеджера решений'
    hklm-dv: 'HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision'
    hklm: 'HKEY_LOCAL_MACHINE'
    service: 'специальный сервис логики этапа'
    of-service: 'специального сервиса логики этапа'
    c-service: 'Специальный сервис логики этапа'
    sett-serv: 'Сервис настроек'
    of-sett-serv: 'Сервиса настроек'
    to-sett-serv: 'Сервису настроек'
    mc: 'Консоль управления Docsvision'
    of-mc: 'Консоли управления Docsvision'
    dv-admins-serv: 'DocsVision Administrators'
    dv-sec-admins-serv: 'DocsVision Security Administrators'
    dv-arch-ops-serv: 'DocsVision Archive Operators'
    dv-solution-admins-serv: 'Docsvision SolutionManager Administrators'
    dv-web-admin-cns-admins-serv: 'Docsvision Management Console Administrators'
    dv-sett-serv-admins-serv: 'Docsvision SettingsService Administrators'
    dv-wf-creators-serv: 'Docsvision Workflow Process Creators'
    dv-wf-creators-dir: 'Создатели бизнес-процессов'
    dv-search-creators-serv: 'Docsvision Search Query Creators'
    dv-search-creators-dir: 'Создатели поисковых запросов'
    dv-users-serv: 'DocsVision Users'
    dv-sec-admins-dir: 'Администраторы безопасности'
    dv-arch-ops-dir: 'Операторы архива'
    dv-admins-dir: 'Администраторы'
    dv-ad-admins-dir: 'Администраторы КС'
    dv-sys-wf-dir: 'Системная для WF'
    dv-power-users-serv: 'DocsVision Power Users'
    dv-dm-admins-dir: 'Администраторы УД'
    mssql: 'Microsoft SQL@'
    pgsql: 'PostgreSQL@'
    ttsql: 'Tantor BE'
    tspcom-v: '2.0 и выше'
    ocspcom-v: '2.0 и выше'
    cadescom-v: '2.0.13292 и выше'
    csp-v: '5.0 и выше'
    jcsp-v: '5.0.45559'
    serv-1: '2012'
    serv-2: '2012 R2'
    serv-3: '2016'
    serv-4: '2019'
    serv-5: '2025'
    serv-demo: 'Windows 8/8.1 (64-разрядная) или Windows 10 (64-разрядная)'
    win-req-1: '10 (Pro, Enterprise)'
    win-req-2: '8/8.1 (Pro, Enterprise)'
    asp-bundle: 'ASP.NET Core Runtime версии 8.0@'
    net-r: '.NET Desktop Runtime (x86/x64) версии 8.0@'
    net-v1: '4.7.2'
    net-v2: '3.5 SP1'
    net-v3: '4.6.1'
    config: 'appsettings@'
    ms: 'Microsoft'
    pg: 'Postgres'
    long: 'CADES-X Long Type 1'
    bes: 'CADES-BES'
    chrome-v: 'Google Chrome 109 и выше'
    edge-c: 'Microsoft Edge 109 и выше'
    chromium-v: '114.0.5735 и выше'
    edge-v: '44.17763.1.0 и выше'
    yandex: 'Яндекс.Браузер 23 и выше'
    safari: 'Safari 16 и выше'
    ms-sql-v-1: '2019, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-2: '2017, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-3: '2016, редакции: Enterprise, Standard, Developer Edition'
    ms-sql-v-4: '2016 должно быть установлено обновление https://support.microsoft.com/en-us/help/3205052/cumulative-update-4-for-sql-server-2016[Cumulative Update 4 for SQL Server] или более новое'
    ms-sql-v-5: '2016 SP1 должно быть установлено обновление https://support.microsoft.com/en-us/help/4013106/cumulative-update-2-for-sql-server-2016-sp1[Cumulative Update 2 for SQL Server 2016 SP1] или более новое'
    ms-sql-v-6: '2025, редакции: Enterprise, Standard, Developer Edition'
    pg-sql-v-1: 'PostgreSQL версии 12'
    pg-sql-v-1-1: 'PostgreSQL версии 18'
    pg-sql-v-2: 'Postgres Pro версии 12'
    pg-sql-v-3: 'Postgres Pro версии 18.1'
    tt-sql-v: 'Tantor BE версии 15.4.3'
    pgl-sql-v: 'Pangolin версии 6'
    tt: 'Tantor'
    pgl: 'Pangolin'
    zbd: 'ЗСУБД'
    os1: 'Astra Linux / Альт Сервер / Ubuntu@'
    os2: 'РЕД ОС / SberLinux'
    os3: 'Альт Сервер'
    l-1: '1.7'
    l-1-1: '1.8.1'
    l-2: 'РЕД ОС 8'
    l-3: 'SberLinux 9'
    l-4: 'Альт Сервер 10'
    l-5: 'Альт Сервер 11'
    l-6: 'Ubuntu 24.04'
    ldap-pl-v: '6.1. сборка 380 и выше'
    ldap-wc-v: '6.1. сборка 735 и выше'
    ##### НАКОПИТЕЛЬНЫЕ ВЕРСИИ #####
    55-ws-cu-269: '5.5.2, сборка ???'
    55-bo-cu-269: '5.5.5, сборка ???'
    prl-msg-ws-cu: '6.1, сборка ???'
    prl-msg-bo-cu: '6.1, сборка ???'
    #   НО для новой консоли
    pl-cu-mc: '6.1 сборки 296 и выше'
    wc-cu-mc: '6.1 сборки 1265 и выше'
    wf-cu-mc: '6.1 сборки 279 и выше'
    mc-cu-mc: '6.2 и выше@'
    worker-cu-mc: '6.1 сборки 136 и выше'
    bo-cu-mc: '6.1 сборки 296 и выше'
    ud-cu-mc: '6.1 сборки 87 и выше'
    ad-cu-mc: '6.1 сборки 150 и выше'
    win-cu-mc: '6.1 сборки 132 и выше'
    edi-cu-mc: '6.1 сборки 235 и выше'
    am-cu-mc: '6.1 сборки 47 и выше'
    #   НО для новой консоли
    am-wc-req: 'версии 6.1, сборка 522 и ниже'
    fs: 'Файловый сервис'
    of-fs: 'Файлового сервиса'
    cu252-wc-req: '6.1 сборки 1003 и выше'
    cu252-pl-req: '6.1 сборки 512 и выше'
    #    НО 25.2
    cu245-pl-req: '6.1 сборки 468 и выше'
    cu253-wincl-req: '6.1 сборки 110 и выше'
    cu253-pl-req: '6.1 сборки 546 и выше'
    cu253-wc-req: '6.1 сборки 1110 и выше'
    cu253-wf-req: '6.1, сборка 181'
    cu253-mc-req: '6.1 сборки 170 и выше'
    #    НО 25.3
    ##### НАКОПИТЕЛЬНЫЕ ВЕРСИИ #####
    vscode-v: '2022'
    wcd-lin: '/lib/docsvision/webclient'
    wcd-win: 'Каталог-установки-Web-клиента'
    solutions: '`/lib/docsvision/solutions/LayoutSolutions/WebClient` для Linux и `C:\Program Files\Docsvision\Solutions\LayoutSolutions\WebClient` для Windows'
    webconfig-lin: '/usr/lib/docsvision/webclient/appsettings.json'
    webconfig-cp: 'C:\Program Files\Docsvision\WebClient\appsettings.json'
    webconfig-win: 'Каталог-установки-Web-клиента\5.5\Site\web.config'
    config-ws: '`/usr/lib/docsvision/workerservice/appsettings.json` для Linux и `C:\Program Files\Docsvision\WorkerService\appsettings.json` для Windows@'
    config-mc: '`/usr/lib/docsvision/managementconsole/appsettings.json` для Linux и `C:\Program Files\Docsvision\ManagementConsole\appsettings.json` для Windows@'
    config-pl: '`/usr/lib/docsvision/platform/appsettings.json` для Linux и `C:\Program Files\Docsvision\Platform\appsettings.json` для Windows@'
    config-ss: '`/usr/lib/docsvision/settingsservice/appsettings.json` для Linux и `C:\Program Files\Docsvision\SettingsService\appsettings.json` для Windows@'
    config-wf: '`/usr/lib/docsvision/workflow/appsettings.json` для Linux и `C:\Program Files\Docsvision\Workflow\appsettings.json` для Windows@'
    config-sm: '`/usr/lib/docsvision/solutionmanager/appsettings.json` для Linux и `C:\Program Files\Docsvision\SolutionManager\appsettings.json` для Windows@'
    webconfig: '{webconfig-lin} в Linux и {webconfig-cp} в Windows@'
    config-ft: '`/usr/lib/docsvision/fulltextservice/appsettings.json` для Linux и `C:\Program Files\Docsvision\FullTextService\appsettings.json` для Windows@'
    config-fs: '`/usr/lib/docsvision/fileservice/appsettings.json` для Linux и `C:\Program Files\Docsvision\FileService\appsettings.json` для Windows@'
    log-dbm: '`var/log/docsvison/databasemanager` для Linux и `C:\ProgramData\docsvision\databasemanager` для Windows@'
    pu: 'Панель управления Web-клиентом'
    sm-req: 'версии 6.1 и выше'
    ws-req: 'версии 6.1@'
    bo-req-m4d: '5.5.5, сборка 8670'
    bo-m4d-req: 'версии 6.1, сборка 176 и выше.'
    bo-m4d-503-req: '5.5.5 , сборка 8776 и выше.'
    wc-m4d-req: 'версии 6.1, сборка 651 и выше.'
    mir: 'Модуль интеграции с реестром МЧД'
    of-mir: 'Модуля интеграции с реестром МЧД'
    kd: 'Контур.Доверенность'
    tw: 'Управление задачами'
    of-em: 'Модуля интеграции с операторами ЭДО'
    word: '2013 или 2016'
    wc-61-r7: 'версии 6.1, сборка 735 и выше'
    w-client-1: '7 SP 1 (Enterprise, Professional, Ultimate)'
    w-client-2: '8/8.1 (Pro, Enterprise)footnote:[Работа в ОС Windows 8 поддерживается только в режиме "Рабочего стола". Работа в режиме Metro, в том числе в Metro-Internet Explorer, не поддерживается.]'
    w-client-3: '10 (Pro, Enterprise)'
    w-client-4: '11 (Pro, Enterprise)'
    wc-no-root-since: '{cu253-wc-req}'
    wf-no-root-since: 'версии 6.1, сборка 284 и выше'
    ws-no-root-since: 'версии 6.1, сборка 147 и выше'
    pl-no-root-since: 'версии 6.1, сборка 853 и выше'
    sm-no-root-since: 'версии 6.1, сборка 138 и выше'
    ss-no-root-since: 'версии 6.1, сборка 187 и выше'
    mc-no-root-since: 'версии 6.2, сборка ??? и выше'
    all-no-root-since: 'Точные версии следующие: *{wc}* {wc-no-root-since}, *{wf}* {wf-no-root-since}, *Службы {ws}* {ws-no-root-since}, *{sett-serv}* {ss-no-root-since}, {mc} {mc-no-root-since}, *{fs}* устанавливается вместе с модулем *{pl}* {pl-no-root-since}, Сервис полнотекстового индексирования устанавливается вместе с модулем *{pl}* {pl-no-root-since}'
  extensions:
#  - asciidoctor-kroki
  - '@asciidoctor/tabs'
output:
  dir: wwwroot
runtime:
  fetch: true
