= Инструкция по разворачиванию новой документации Docsvision

Новая документация Docsvision разворачивается с помощью генератора статических сайтов Antora.

Для первой сборки сайта потребуется подключение к интернету, в будущем интернет-соединение потребуется только для получения последних изменений в документации.

[#assembly]
== Сборка сайта

.Выполните указанные ниже действия последовательно:
. Перейдите https://git-scm.com/download/win[по ссылке], скачайте и установите git.
. Установите Node.js предпочтительным способом или скачайте инсталлятор https://nodejs.org/en/download/[с официального сайта].
. Скопируйте на компьютер данный (https://github.com/Grolribasi/antora-playbook[Docsvision/antora-playbook]) репозиторий.
+
* Выполните в Powershell:
+
 git clone https://github.com/Grolribasi/antora-playbook.git
+
. Перейдите в каталог репозитория:
+
 cd antora-playbook
+
. Установите Antora командой:
+
 npm i
+
. Откройте файл `/antora-playbook/antora-playbook.yml` и при необходимости отредактируйте URL сайта:
+
[source,yaml]
----
site:
  title: Документация Docsvision
  url: https://help.docsvision.com/ <.>
  robots: allow
----
<.> Укажите адрес сервера, на котором будет развёрнута документация.
+
. Запустите сборку сайта при помощи Antora, выполнив следующую команду в окне Powershell:
+
[source]
----
npx antora antora-playbook.yml
----
+
****
Если планируется просматривать html-файлы локально, без запуска сервера, удалите следующую строку в `antora-playbook.yml`:

  html_extension_style: indexify

Тогда после сборки путь к HTML-файлам будет короче.
****
+
. Файлы сайта будут расположены в папке `wwwroot`.

[#view]
== Просмотр сайта

.Сайт можно просматривать:
** Локально -- нажмите на сгенерированные html-файлы.
** С простого http-сервера -- выполните шаги ниже.

.Чтобы развернуть сайт на локальном сервере:
. Перейдите в папку репозитория `antora-playbook`.
. Установите локальный http-сервер следующей командой:
+
 antora-playbook $ npm i -g http-server
+
. Выполните команду `http-server`, например, так:
+
 antora-playbook\wwwroot $ http-server build/site -c-1 -p 5000
+
. После запуска команды, локальный адрес веб-сервера будет отображён в окне консоли следующим образом:
+
[source]
----
Starting up http-server, serving antora-playbook\wwwroot
Available on:
  http://127.0.0.1:5000
  http://192.168.1.8:5000
Hit CTRL-C to stop the server
----
+
. Вставьте любой адрес из списка в строку браузера, что просмотреть сайт через локальный веб-сервер.

[#limit]
== Ограничения

В собранном сайте не будет работать поиск.

// Чтобы воспользоваться функциями локального (офлайн) поиска, рекомендуется использовать расширение Antora Lunr Search. Подробная инструкция по разворачиванию приведена https://www.npmjs.com/package/antora-lunr[по ссылке].
//
// Перед использованием расширения Antora Lunr Search рекомендуется удалить папку `antora-playbook/supplemental-ui`.

[#dev]
== Инструкция для разработчиков документации

При запуске Antora исходные документы будут автоматически получены из репозиториев Docsvision на GitHub (все репозитории с приставкой -Antora).

Если вы хотите изменить исходный код документации, необходимо скопировать содержимое каждого репозитория, указанного в файле `antora-playbook.yml`:

[source,yml]
----
content:
  branches: 'dev'
  edit_url: ~
  sources:
    - url: https://github.com/Docsvision/System-Antora.git
----

Замените значение ключа `url` на собственную ссылку или локальное хранилище. См. подробнее в документации Antora: https://docs.antora.org/antora/latest/content-source-repositories/[Repositories and Content Source Roots] и https://docs.antora.org/antora/latest/playbook/content-source-url[URLs for Content Sources], в частности подпункт https://docs.antora.org/antora/latest/playbook/content-source-url/#local-urls[URLs for Content Sources | Use local content repositories].

****
Чтобы подробнее разобраться в синтаксисе AsciiDoc, прочитайте материалы на сайте https://docs.asciidoctor.org/asciidoc/latest/[docs.asciidoctor.org].

Также подробнее ознакомьтесь с https://docs.antora.org/[документацией Antora], чтобы лучше понимать, как создаётся сайт с документацией Docsvision.
****

Для работы с файлами AsciiDoc рекомендуется использовать ПО Jetbrains https://www.jetbrains.com/idea/download/#section=windows[IntelliJ Idea] с https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/index.html[плагином AsciiDoc].
