:dv: Docsvision

= Как развернуть документацию из исходного кода

Новая документация {dv} разворачивается с помощью https://docs.antora.org/[генератора статических сайтов Antora]. Для первой сборки сайта потребуется доступ к репозиториям документации {dv}, https://github.com/Docsvision?q=antora-&type=all&language=&sort=[расположенным на GitHub]. Репозитории документации обозначены префиксом `antora-`. Полный список источников указан в файле `https://github.com/Docsvision/antora-playbook/blob/083db793049a159db9b4c526ce5b1f3a58870c39/antora-playbook.yml#L24[antora-playbook.yml]` репозитория antora-playbook.

Документация может быть развёрнута локально, в таком случае адрес документации может быть изменён.

[#build-site]
== Сборка сайта

.Требования для сборки сайта:
* Установлен git.
* Установлен Node.js версии, указанной в разделе "https://docs.antora.org/antora/latest/install/windows-requirements/[Требования]" на сайте документации Antora.
* Доступ к сайту Github или иной доступ к репозиториям исходного кода документации.
* Доступ к локальной копии репозитория https://github.com/Docsvision/antora-playbook/[Docsvision/antora-playbook/].

. Откройте командную строку с расположением в корне репозитория "Docsvision/antora-playbook/"
. Установите Antora командой:
+
 npm i
+
. Запустите сборку сайта при помощи Antora, выполнив следующую команду:
+
 npx antora antora-playbook.yml
+
. Файлы сайта будут расположены в папке `wwwroot`.

[#view]
== Просмотр сайта

.Сайт можно просматривать:
** Локально -- нажмите на сгенерированные html-файлы, расположенные в папке `wwwroot`.
** С простого http-сервера -- выполните шаги, https://docs.antora.org/antora/latest/preview-site/#run-a-local-server-optional[указанные в инструкции Antora].

[#limitations]
== Ограничения

.После сборки сайта некоторые функции окажутся недоступны:
* Поиск по сайту.
* Просмотр страниц накопительных обновлений.

Чтобы воспользоваться функциями локального (офлайн) поиска, рекомендуется использовать расширение Antora Lunr Search. Подробная инструкция по разворачиванию приведена https://www.npmjs.com/package/antora-lunr[по ссылке].

[#dev]
== Инструкция для разработчиков документации

При запуске Antora исходные документы будут автоматически получены из репозиториев Docsvision на GitHub (все репозитории с приставкой -Antora).

Если вы хотите изменить исходный код документации, необходимо скопировать содержимое каждого репозитория, указанного в файле `antora-playbook.yml`:

[source,yml]
----
content:
  branches: 'dev'
  edit_url: ~
  sources:
    - url: https://github.com/Docsvision/System-Antora.git
----

Замените значение ключа `url` на собственную ссылку или локальное хранилище. См. подробнее в документации Antora: https://docs.antora.org/antora/latest/content-source-repositories/[Repositories and Content Source Roots] и https://docs.antora.org/antora/latest/playbook/content-source-url[URLs for Content Sources], в частности подпункт https://docs.antora.org/antora/latest/playbook/content-source-url/#local-urls[URLs for Content Sources | Use local content repositories].

****
Чтобы подробнее разобраться в синтаксисе AsciiDoc, прочитайте материалы на сайте https://docs.asciidoctor.org/asciidoc/latest/[docs.asciidoctor.org].

Также подробнее ознакомьтесь с https://docs.antora.org/[документацией Antora], чтобы лучше понимать, как создаётся сайт с документацией Docsvision.
****

Для работы с файлами AsciiDoc рекомендуется использовать ПО Jetbrains https://www.jetbrains.com/idea/download/#section=windows[IntelliJ Idea] с https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/index.html[плагином AsciiDoc].
