= Сервис настроек

.В "Сервисе настроек" хранятся:
* Собственные настройки "{of-mc}".
* Настройки сервисов и функций {dv}, управляемых с помощью "{of-mc}".

Содержимое _{of-sett-serv}_ размещается в подключенной к системе БД.

== Структура и функции модуля

Хранилище данных Сервиса настроек	Хранилище, в котором хранятся данные данные Сервиса настроек. По умолчанию - это база данных

Содержимое Сервиса настроек размещается в подключенной к системе БД.

Пользователи работают с Консолью настройки с помощью веб-браузера. Запросы обрабатываются веб-приложением с исполняемым процессом ManagementConsole.WebService.exe. Используется протокол подключения HTTP.

Сформированная пользователем конфигурация для Службы фоновых операций сохраняется в Сервис настроек с исполняемым процессом XXX.Sevice.exe. Для записи настроек используется REST API.

Возможность настройки Службы фоновых операций предоставляет Расширение для работы со службой фоновых операций.

Служба фоновых операций при первом запуске запрашивает новые настройки из Сервиса настроек. Для чтения настроек используется REST API.

Виджеты и Информационные страницы получают статистические данные об обработке сообщений Службой фоновых операций из системы Docsvision. Для получения данных используются карточки Сообщений Службы фоновых операций. Полученная информация отображается в пользовательском интерфейсе.