// tag::no-rights[]
WARNING: Не удаляйте папку с журналом модуля, т.к. у службы {module-service} отсутствуют права на создание новой папки.
// end::no-rights[]

// tag::no-root[]
В ОС Linux служба запускается от имени УЗ {dv} и не требует ROOT-привилегий.
// end::no-root[]

// tag::slash[]
WARNING: Обратите внимание, двойной обратный слэш необходим для экранирования, если указывается значение в конфигурационном файле {wc}а. При указании значения в {of-mc} используется одиночный обратный слэш.
// end::slash[]

// tag::dvweb-win[]
NOTE: Программа _DVWebTool_ устанавливается на клиентскую машину только в ОС {ms} Windows. Для ОС Linux используется _DVSupService_, см. подробнее xref:webclient:user:prepare-add-components.adoc#dvSupService[Установка и запуск службы DVSupService].
// end::dvweb-win[]

//tag::transport[]
Возможность изменить адрес подключения к серверу {dv} и, соответственно, транспорт в {wc}е упразднена, начиная с версии {wc} 17. Даже если в конфигурационном файле транспорт был изменён на COM, будет использоваться REST.
//end::transport[]

// tag::nonoyet[]
Если обновление затронуло модули _{wc}_ и _{pl}_ (если обновлялись оба модуля), перед обновлением _{wc}а_ из установщика, обновите БД через _{cns}_ xref:6.1@platform:console:db-update.adoc[по инструкции].

Если в диалоге `Укажите базы данных из числа подключенных к серверу, в которые следует установить {wc}` не нажать *Отмена*, возникнет ошибка, так как версия модуля _{pl}_ в базе данных еще не обновлена до актуальной.
// end::nonoyet[]

// tag::ifabsent[]
[NOTE]
====
В конфигурации по умолчанию параметры отсутствуют. Предпочтительным способом настройки является {mc}, добавляйте параметры в конфигурационный файл только при крайней необходимости.

Если настройки указаны в конфигурационном файле, они считываются в первую очередь и имеют приоритет над настройками в {of-mc}.
====
// end::ifabsent[]

// tag::preview[]
По умолчанию предпросмотр документов в карточках отключен. Чтобы включить предпросмотр, необходимо настроить компоненты Р7-Офис Сервер документов/OnlyOffice.
// end::preview[]
