= MessagesIncomingMessage -- класс

Входящие сообщения для владельца карточки.

* *Пространство имён:* `Docsvision.WorkerService.ObjectModel`
* *Сборка:* `DocsVision.WorkerService.ObjectModel.dll`

== Синтаксис

[source,csharp]
----
public sealed class MessagesIncomingMessage : ObjectBase
----

== Свойства

[cols=",",options="header"]
|===
|Имя |Описание

|`CreateDate`
|Дата создания сообщения

Тип: `http://msdn.microsoft.com/ru-ru/library/system.datetime.aspx[System.DateTime]`

|`TypeId`
|Идентификатор типа сервиса сообщения

Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`

|`SubTypeId`
|Дополнительный идентификатор, уточняющий тип сообщения

Тип: `http://msdn.microsoft.com/ru-ru/library/system.guid.aspx[System.Guid]`

|`Data`
|Данные сообщения

Тип: `http://msdn.microsoft.com/ru-ru/library/system.string.aspx[System.String]`

|`State`
|Состояние обработки сообщения

Тип: `xref:Interfaces/MessageState_EN.adoc[MessageState]`

|`Concurrent`
|Определяет, может ли сообщение обрабатываться одновременно с другими сообщениями для целевого объекта\службы

Тип: `http://msdn.microsoft.com/ru-ru/library/system.boolean.aspx[System.Boolean]`

|`ErrorCount`
|Количество ошибок во время обработки сообщения

Тип: `http://msdn.microsoft.com/ru-ru/library/system.int32.aspx[System.Int32]`

|`WaitingLocks`
|Блокировки ожидания

Тип: `xref:ObjectModel/MessagesIncomingMessageWaitingLock_CL.adoc[MessagesIncomingMessageWaitingLock]`

|===
