= Общие сведения о модуле {tw}

"{tw}" является расширением для модуля {wc}, он предоставляет два новых многофункциональных элемента управления: Канбан и Календарь.

[#module-functions]
== Функции модуля

Модуль {tw} приносит в систему два элемента управления для модуля {wc}: `_Календарь_` и `_Канбан_`.

* Элемент управления `_Календарь_` предназначен для отображения и редактирования списка событий в различных представлениях.
* Элемент управления `_Канбан_` представляет собой виртуальный аналог доски со стикерами, предназначенный для управления карточками.

[#module-structure]
== Структура модуля

. Расширения программы {kvr}. Содержат общие формы\редакторы свойств для ЭУ из модуля _Управление задачами_, описание свойств ЭУ, собственные редакторы свойств.
. Расширения серверной части {wc}а. Содержат общую серверную логику для ЭУ из модуля _Управления задачами_, контроллеры, сервисы ЭУ, биндинг конвертер, также интерфейсы плагина, реализацию основного плагина и интерфейсы для создания собственного источника данных календаря.
. Клиентские расширения {wc}а. Содержат клиентскую логику ЭУ и клиентские классы.
