. В БД {pgsql} остановите pgAgent.
. Обновите компоненты системы на сервере Linux командами вида:
+
[tabs]
====
{os1}::
+
[source,subs=attributes]
----
sudo apt-get update
sudo apt-get install --only-upgrade docsvision-{update}*
----
ifndef::mancons[]
{os2}::
+
[source,subs=attributes]
----
sudo dnf update docsvision-{update}*
----
endif::[]
ifdef::mancons[]
{os2}::
+
[source,subs=attributes]
----
sudo dnf update docsvision-managementconsole* && sudo dnf update docsvision-settingsservice* && sudo dnf update docsvision-externalapi*
----
endif::[]
====
+
Для сервисов {dv} на сервере Linux при обновлении будет предложено перезаписать текущий конфигурационный файл `appsettings.json`.
+
.Доступные варианты:
[%collapsible]
====
* Перезаписать текущий конфигурационный файл `appsettings.json`.
** Текущий файл будет перезаписан стандартным, все выполненные настройки будут сохранены в файле `appsettings.json.dpkg-old`. Существующие настройки, включая псевдонимы и строки подключения к БД, потребуется перенести в новый файл `appsettings.json`.
* Сохранить текущий `appsettings.json`.
** Все выполненные настройки останутся без изменений, стандартный файл конфигурации будет сохранён как `appsettings.json.dpkg-dist`.
* Показать различия между версиями.
** В окне командной строки будут отображены отличия между старой и новой версией. Знаком `+` обозначаются добавленные строки, знаком `-` обозначаются удалённые строки.
* Запустить оболочку командной строки для проверки ситуации.
** Возвращает в окно командной строки, дальнейшие действия зависят от администратора.
====
+
. Затем установите серверные компоненты на машину с Windows, запустив инсталлятор `.msi` серверной части модуля.
. Перезапустите *{sss-new}* и все сервисы {dv} на Linux.