= Настройка безопасности

[#create-admin]
== Назначение администраторов УД

_{dv-dm-admins-dir}_ -- группа пользователей, которым предоставлены дополнительные права (относительно других пользователей) на модификацию структуры папок Приложения, а также права на просмотр истории карточек УД.

Сравнение прав Администратора УД и рядового пользователя приведено в таблице ниже.

.Сравнение прав администратора УД и пользователя
[cols="50%,50%",options="header"]
|===
|Группа пользователей |Права
|*Права на общие папки*
a|.{dv-dm-admins-dir}:
* Полный доступ.
* Может создавать и менять настройки папок, включая настройки безопасности.

.Все пользователи:
* Создание карточек, просмотр атрибутов и настроек.
+
* Запрещены операции:
** Удаление общих папок.
** Изменение атрибутов и настроек безопасности.
* К папкам отчётов и поиска по категориям всем пользователям назначается доступ на чтение.

|*Шаблонная структура папок маршрутизации*
a|.{dv-dm-admins-dir}:
* Полный доступ.
* Может настраивать и менять атрибуты.

.Все пользователи:
* Только просмотр папок-делегатов.
|===

Администратор {dv} должен назначить _Администраторов УД_.

.Чтобы назначить "Администратора УД":
. Откройте {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте требуемого сотрудника в группу "{dv-dm-admins-dir}".
+
Если при включении пользователя в группу система выдала сообщение о нехватке прав, выдайте себе права на редактирование группы сотрудников _{dv-dm-admins-dir}_ по дискреционной модели.
include::partial$excerpts.adoc[tags=wincl]

[#rights]
== Права на чтение отчётов по заданиям

В модуле {bo}, начиная с {bo-view-report-req}, и {dm}, начиная с {dm-view-report-req}, права доступа к файлам отчётов, добавленным в задания (на исполнение/ознакомление) или группы заданий, определяются хранимыми процедурам:

* Участник задания с файлом: _dvbo_Operand_FileDocument_TasktreeEmployees_
* Участник задания с отчётом: _dvbo_Operand_FileReport_TaskEmployees_

В новых БД хранимые процедуры определяют следующие права доступа к файлам для указанных пользовательских ролей:

[cols=",,,",options="header"]
|===
|Роль |Тип |Условие вычисления |Права

|Участник задания с файлом |Вычисляемая |Текущий пользователь (`Я`) входит в результат *первой хранимой процедуры* (включая постоянных и временных заместителей) |Аналогично роли _Все_

|Участник задания с отчётом |Вычисляемая |Текущий пользователь (`Я`) входит в результат *второй хранимой процедуры* (включая постоянных и временных заместителей) |Аналогично роли _Все_

|Регистратор |Вычисляемая |Текущий пользователь (`Я`) равен полю `Основная информация.Автор` (включая постоянных и временных заместителей) |Аналогично роли _Все_

|===

Если настройка ролевой модели для вида документа _Файл_ в существующей БД выполняется индивидуально:

* Существующие карточки файлов (созданные до {bo} {bo-view-report-req} и {dm} {dm-view-report-req}) автоматически подчиняются новой логике.
* Доступ к уже созданным отдельным файлам пересчитывается при первом обращении к карточке.

[#designer-access]
== Настройка прав доступа на конструкторы и справочники

По умолчанию все пользователи {dv} имеют полные права на справочники и конструкторы: _Конструктор справочников_, _Справочник сотрудников_, _Справочник контрагентов_, _Справочник ссылок_, _Справочник категорий_, _Конструктор правил нумерации_.

Администратор {dv} должен самостоятельно настроить права доступа к справочникам и конструкторам: предоставить или ограничить доступ пользователей.

Права доступа настраиваются с помощью дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]

[#wf-admin]
== Предоставление прав СУБП

Администратор {dv} должен добавить в _Справочник сотрудников_ технологического сотрудника, от имени которого сервис Workflow будет работать с карточками Приложения.

. Запустите {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте нового сотрудника, указав в поле `Пользователь` учётную запись сервиса Workflow (см. документацию по администрированию модуля {wf}, раздел xref:6.1@workflow:admin:install.adoc#account[Создание учётной записи {wf}]), и любое допустимое значение в поле `Фамилия` -- прочие данные можно не указывать.
. Предоставьте администратору {dv} права на редактирование группы сотрудников _Системная для WF_ по дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]
. Добавьте созданного на шаге 3 сотрудника в группу _Системная для WF_.
+
Если для обработки БП используется кластер Workflow с разными учётными записями сервисов Workflow, создайте технологического сотрудника для каждой учётной записи СУБП.
