= Настройка безопасности

[#create-admin]
== Назначение администраторов УД

_{dv-dm-admins-dir}_ -- группа пользователей, которым предоставлены дополнительные права (относительно других пользователей) на модификацию структуры папок Приложения, а также права на просмотр истории карточек УД.

Сравнение прав Администратора УД и рядового пользователя приведено в таблице ниже.

.Сравнение прав администратора УД и пользователя
[cols="50%,50%",options="header"]
|===
|Группа пользователей |Права
|*Права на общие папки*
a|.{dv-dm-admins-dir}:
* Полный доступ.
* Может создавать и менять настройки папок, включая настройки безопасности.

.Все пользователи:
* Создание карточек, просмотр атрибутов и настроек.
+
* Запрещены операции:
** Удаление общих папок.
** Изменение атрибутов и настроек безопасности.
* К папкам отчётов и поиска по категориям всем пользователям назначается доступ на чтение.

|*Шаблонная структура папок маршрутизации*
a|.{dv-dm-admins-dir}:
* Полный доступ.
* Может настраивать и менять атрибуты.

.Все пользователи:
* Только просмотр папок-делегатов.
|===

Администратор {dv} должен назначить _Администраторов УД_.

.Чтобы назначить "Администратора УД":
. Откройте {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте требуемого сотрудника в группу "{dv-dm-admins-dir}".
+
Если при включении пользователя в группу система выдала сообщение о нехватке прав, выдайте себе права на редактирование группы сотрудников _{dv-dm-admins-dir}_ по дискреционной модели.
include::partial$excerpts.adoc[tags=wincl]

// tag::rights[]
ifndef::docmanagement[]
= Настройка приложения "{dm}"

Следующие настройки обязательно должны быть выполнены для доступа к файлам в заданиях и группах заданий.
endif::[]

[#rights]
== Настройка прав доступа к файлам

В модуле {bo}, начиная с {bo-view-report-req}, и {dm}, начиная с {dm-view-report-req}, права доступа к файлам, добавленным в задания (на исполнение/ознакомление) или группы заданий, определяются хранимыми процедурам:

* _dvbo_Operand_FileDocument_TasktreeEmployees_ для роли "Участник задания с файлом"
* _dvbo_Operand_FileReport_TaskEmployees_ для роли "Участник задания с отчётом"

При добавлении файлов или отчета в "Задания УД" и "ГЗ" создаются карточки вида "Файл". Чтобы доступ к таким карточкам работал корректно и только участники заданий могли работать с файлами, необходимо настроить ролевую модель для вида документа "Файл" следующим образом:

NOTE: Для новых БД, созданных после обновления до {bo} {bo-view-report-req} и {dm} {dm-view-report-req}, права доступа будут применены автоматически, дополнительных действий не требуется. Также действия не потребуются, если версии модулей ниже тех, что указаны.

. Откройте Конструктор ролей.
. Выберите вид карточек _Документ -- Файл_.
. Создайте роль с названием _Участник задания с отчётом_.
. Измените корневой оператор в значение *ИЛИ*.
. Добавьте условия для роли _Участник задания с отчётом_:
+
* _Я -- временный заместитель в период неактивности замещаемого_, _Равно_, хранимая процедура _dvbo_Operand_FileReport_TaskEmployees_.
* _Я_, _Равно_, хранимая процедура _dvbo_Operand_FileReport_TaskEmployees_.
* _Я -- постоянный заместитель_, _Равно_, хранимая процедура _dvbo_Operand_FileReport_TaskEmployees_.
+
. Создайте роль с названием _Участник задания с файлом_.
. Измените корневой оператор в значение *ИЛИ*.
. Добавьте условия для роли _Участник задания с файлом_:
+
* _Я -- временный заместитель в период неактивности замещаемого_, _Равно_, хранимая процедура _dvbo_Operand_FileDocument_TasktreeEmployees_.
* _Я_, _Равно_, хранимая процедура _dvbo_Operand_FileDocument_TasktreeEmployees_.
* _Я -- постоянный заместитель_, _Равно_, хранимая процедура _dvbo_Operand_FileDocument_TasktreeEmployees_.
+
. Создайте роль с названием _Регистратор_.
. Измените корневой оператор в значение *ИЛИ*.
. Добавьте условия для роли _Регистратор_:
+
* _Я -- временный заместитель в период неактивности замещаемого_, _Равно_ _Основная информация.Автор_.
* _Я_, _Равно_ _Основная информация.Автор_.
* _Я -- постоянный заместитель_, _Равно_ _Основная информация.Автор_.
+
. Для созданных ролей в матрице доступа выдайте все права, которые настроены для роли _Все_.
. Для роли _Все_ в матрице доступа удалите все назначенные права.
. Сохраните настройки ролей.
+
После сохранения настроек доступ к новым и существующим карточкам файлов автоматически будет определяться в соответствии с новой логикой.
// end::rights[]

[#designer-access]
== Настройка прав доступа на конструкторы и справочники

По умолчанию все пользователи {dv} имеют полные права на справочники и конструкторы: _Конструктор справочников_, _Справочник сотрудников_, _Справочник контрагентов_, _Справочник ссылок_, _Справочник категорий_, _Конструктор правил нумерации_.

Администратор {dv} должен самостоятельно настроить права доступа к справочникам и конструкторам: предоставить или ограничить доступ пользователей.

Права доступа настраиваются с помощью дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]

[#wf-admin]
== Предоставление прав СУБП

Администратор {dv} должен добавить в _Справочник сотрудников_ технологического сотрудника, от имени которого сервис Workflow будет работать с карточками Приложения.

. Запустите {wincl} от имени администратора {dv}.
. Откройте _Справочник сотрудников_.
. Добавьте нового сотрудника, указав в поле `Пользователь` учётную запись сервиса Workflow (см. документацию по администрированию модуля {wf}, раздел xref:6.1@workflow:admin:install.adoc#account[Создание учётной записи {wf}]), и любое допустимое значение в поле `Фамилия` -- прочие данные можно не указывать.
. Предоставьте администратору {dv} права на редактирование группы сотрудников _Системная для WF_ по дискреционной модели безопасности.
include::partial$excerpts.adoc[tags=wincl]
. Добавьте созданного на шаге 3 сотрудника в группу _Системная для WF_.
+
Если для обработки БП используется кластер Workflow с разными учётными записями сервисов Workflow, создайте технологического сотрудника для каждой учётной записи СУБП.
