= Общие сведения о сервисе

{cs} является дополнительным модулем {dv}. Сервис позволяет конвертировать документы между поддерживаемыми форматами с использованием внешнего сервиса конвертации Р7/OnlyOffice.

Сервис поставляется отдельной библиотекой по запросу или может быть установлен с помощью инсталлятора. В стандартной поставке {dv} сервис используется для конвертации файлов из формата Microsoft Word (`.doc`, `.docx`) в PDF-A в примере решения Кадрового Электронного Документооборота (КЭДО), однако открытый API позволяет использовать модуль для выполнения дополнительных задач конвертации.

[NOTE]
====
include::ROOT:partial$exceprts.adoc[tags=license-check]
====

Пример использования сервиса приведён в https://github.com/Docsvision/WebClient-Samples/tree/master/ServerExtensions/ConversionSample[репозитории примеров {wc}а].

[#purpose-function]
== Назначение и функции модуля

.Сервис позволяет конвертировать файлы между следующими поддерживаемыми форматами: `PDF/A`, `pdf`, `bmp`, `gif`, `jpg`, `odp`, `otp`, `png`, `potm`, `potx`, `ppsm`, `ppsx`, `pptm`, `pptx`, `csv`, `ods`, `ots`, `xlsm`, `xlsx`, `xltm`, `xltx`, `docm`, `docx`, `docxf`, `dotm`, `dotx`, `epub`, `fb2`, `html`, `odt`, `ott`, `rtf`, `txt`.

{cs} принимает в качестве исходного файл одного из поддерживаемых форматов и на выходе формирует результирующий файл в другом формате. Например, исходным файлом может быть документ в формате Microsoft Word (`.doc`, `.docx`), а результирующим -- PDF-A (`.pdf`), обратная конвертация (PDF-A -> MS Word) также возможна. Подробнее о поддерживаемых преобразованиях см. в разделе "xref:programmer:index.adoc[]".

[#doc-list]
== Разделы документации

.Документация модуля содержит следующие разделы:
. Общие сведения о модуле.
. Администрирование модуля.
. Руководство разработчика {of-cs}.

