:config-mc: `/usr/lib/docsvision/managementconsole/appsettings.json`

= Первичная настройка {of-mc}

[CAUTION]
====
В {mc} версии {mc-cu-mc} изменился состав параметров конфигурационного файла. Конфигурационный файл необходимо привести к актуальной структуре, удалив устаревшие параметры и добавив новые.
====

. {blank}
+
[subs="specialchars,attributes,quotes"]
На сервере {of-mc} создайте резервную копию конфигурационного файла Консоли по адресу {config-mc}.
+
. В том же каталоге найдите файл под названием `appsettings.json.dpkg-dist`, откройте его в любом текстовом редакторе и сравните с текущей версией конфигурационного файла `appsettings.json` при помощи любой утилиты сравнения текстовых файлов.
. Настройки в `appsettings.json.dpkg-dist` являются эталонными, это значит, что необходимо вручную удалить параметры, которых больше нет в эталонном файле (они считаются устаревшими), перенести в `appsettings.json` новые параметры из эталонного файла и, при необходимости, заполнить параметры рабочими настройками.
+
.В новой версии конфигурационного файла:
* Удалён параметр для Сервиса внешнего API, т.к. сервис был упразднён и его установка не требуется.
* Добавлен параметр `Kestrel`, указывающий URL для доступа к {of-mc}. В том числе параметр может использоваться при настройке защищённого соединения. Поскольку Консоль версии {page-version} является основным инструментом администрирования системы и содержит конфиденциальные данные, для работы рекомендуется использовать защищённое содинение см. подробнее "xref:new-admin-console@engineer:ROOT:https-connection.adoc[]".
+
.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:5100" <.>
      }
    }
  }
}
----
<.> URL для доступа к {of-mc}.
+
. Сохраните выполненные изменения и перезапустите службы {of-sett-serv} и {of-mc}.
+
Состояние службы должно измениться на "запущена", если конфигурационный файл соответствует эталонному и не содежит ошибок.
