= Установка расширений для {of-mc} на Linux

{mc} версии 6.2 является основным инструментом настройки системы. Возможность настройки обеспечивается специальными расширениями для модулей системы. Расширения включают связанные с соответствующими модулями ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки системы.

Данный раздел описывает установку расширений для {of-mc} в ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:./install-server.adoc[обновления] остальных модулей системы.

include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc-ext]
== Установка расширения {wc}а для {of-mc}

.Чтобы установить "Расширение {wc}а для {of-mc}":
:of: Расширения {wc}а для {of-mc}
:wt: ext-webc-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]
+
. Запустите расширение:
+
 $ sudo systemctl start docsvision-ext-webc-mc

[#wf-ext]
== Установка расширения модуля {wf} для {of-mc}

.Чтобы установить "Расширение модуля {wf} для {of-mc}":
:of: Расширения модуля {wf} для {of-mc}
:wt: ext-workflow-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]
+
. Запустите расширение:
+
  $ sudo systemctl start docsvision-ext-workflow-mc

[#pl-ext]
== Установка расширения сервера приложений для {of-mc}

.Чтобы установить "Расширение сервера приложений для {of-mc}":
:of: Расширения сервера приложений для {of-mc}
:wt: ext-platform-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]
. Запустите расширение:
+
[source,bash,subs=attributes]
  $ sudo systemctl start docsvision-ext-{wt}

[#fs-ext]
== Установка расширения {of-fs} для {of-mc}

.Чтобы установить "Расширение {of-fs} для {of-mc}":
:of: Расширения {of-fs} для {of-mc}
:wt: ext-fileservice-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]
+
[source,bash,subs=attributes]
  $ sudo systemctl start docsvision-ext-{wt}
