:update:
:os1: Astra Linux
:mc-cu-mc: версии 6.2
:sss-new: dvappserver
:wacs-new: dvconsole
:wacss-new: dvsettings

= Установка обновлений

WARNING: Начиная с накопительного обновления 25.3 все модули {dv} были переведены на .NET 8. Если ранее не выполнялось обновление до НО 25.3, необходимо обновить всю систему целиком. На серверах системы потребуется дополнительное ПО {asp-bundle}.

[#modules]
== Обновление модулей

. После ознакомления с условиями, описанными в разделе "xref:index.adoc[]" и установки {asp-bundle} на сервера {dv} выполните обновление системными средствами, следуя инструкции ниже. Модуль {mc} будет обновлён до {mc-cu-mc}.
+
. Сервис внешнего API необходимо удалить в {os1} и {os3}, в {os2} Сервис будет удалён автоматически.
+
[tabs]
====
{os1}::
+
[source,subs=attributes]
----
sudo apt-get purge docsvision-externalapi
----

{os3}::
+
[source,subs=attributes]
----
sudo apt-get remove docsvision-externalapi
----
====
+
include::new-admin-console@platform:admin:partial$update.adoc[tag=main-update-process]
+
При первом обновлении настройки из конфигурационных файлов автоматически появятся в интерфейсе {of-mc}. При первом обновлении конфигурационные файлы рекомендуется сохранить, иначе придётся xref:./pre-config-server.adoc[выполнять настройку системы с нуля в Консоли управления]. Обратите внимание, если настройка в файле `appsettings.json` и в Консоли упрравления имеет разные значения, приоритет отдаётся значению из конфигурационного файла. При последующих обновлениях рекомендуется оставить в конфигурационых файлах минимальные настройки.
+
. Перезапустите службу Сервера {dv} и все сервисы {dv} на Linux. Рекомендуемый порядок перезапуска: *{wacss-new}*, *{sss-new}*, *{wacs-new}*, оставшиеся сервисы.
. Если при установке модулей вы выбрали вариант &quot;Сохранить текущий `appsettings.json`&quot;, перейдите сразу к пункту "xref:./db-connect.adoc[]" или "xref:./db-create.adoc[]" в зависимости от наличия настроенной БД.
