= Действия после {chego} системы

В НО 26.1, включающем {mc} {mc-cu-mc} и другие модули, часть параметров из конфигурационных файлов была перенесена в интерфейс Консоли управления. Консоль управления стала приоритетным способом настройки системы, однако настройки из конфигурационных файлов всё ещё имеют приоритет. Это сделано с целью оставить возможность постепенного перехода к конфигурации исключительно через Консоль управления.

*Изменять конфигурационные файлы допустимо только после полного завершения всех действий по обновлению системы*, чтобы существующие настройки автоматически перенеслись в интерфейс Консоли управления. После обновления системы рекомендуется привести конфигурационные файлы модулей системы к эталонному виду. Эталонные конфигурационные файлы располагаются по адресу `/usr/lib/docsvision/имя-модуля/appsettings.json.dpkg-dist`.

.После обновления системы выполните следующие действия:
. На сервере {dv} перейдите к каталогу `/usr/lib/docsvision/` и откройте каталог любого модуля, например, `/usr/lib/docsvision/platform/`.
. Откройте в любом текстовом редакторе и сравните текущий конфигурационный файл `appsettings.json` с эталонным `appsettings.json.dpkg-dist` при помощи любой утилиты сравнения текстовых файлов.
. Удалите параметры, которых больше нет в эталонном файле. Если в `appsettings.json` отсутствуют параметры из эталонного файла, добавьте их и при необходимости заполните рабочими настройками.
. Повторите аналогичные действия для каждого модуля и службы: {wc}, {wf}, {fs}.
. Сохраните выполненные изменения и перезапустите службы модулей, конфигурационные файлы которых были изменены.
+
 $ sudo systemctl restart dvappserver dvwebclient dvsettings dvconsole dvworkerservice dvworkflow dvfileservice
+
Состояние служб должно измениться на "запущена", если конфигурационный файл соответствует эталонному и не содежит ошибок.
