= Удаление серверных компонентов с машины Windows

. Сохраните настройки сервера (названия подключенных баз данных, учётные записи сервисов, имена почтовых профилей, настройки производительности сервиса Workflow, и другие), которые можно найти в Консоли настройки {dv} и конфигурационных файлах модулей (сохранить конфигурационные файлы будет предложено в процессе установки).
. Удалите все установленные серверные компоненты с машины Windows стандартным образом (используя меню "Установка и удаление программ"), также удалите комплект утилит {rk}, если он был установлен. Модуль {pl} удаляется в последнюю очередь. Серверные компоненты были необходимы для работы {cns} и {pu}. Начиная с НО 26.1, настройка системы выполняется с помощью {of-mc}.
. Если клиентские и серверные компоненты старой версии устанавливались на одной машине, после удаления серверных компонентов запустите восстановление клиентских компонентов модуля {pl}. Найдите в списке установленных программ `Docsvision PlatformСlient`, нажмите кнопку *Восстановить* и проследуйте инструкциям мастера установки.
. Перезагрузите компьютер.
