= Общие сведения о модуле {ai}

Настоящий раздел документации описывает работу с модулем {ai}.

[#module-functions]
== Функции модуля

Модуль {ai} является дополнительным модулем системы {dv}, предназначенным для интеллектуальной обработки текстовой информации и файлов в электронных документах. Все функции модуля интегрируются в интерфейс {dv} и доступны для работы с документами, вне зависимости от используемой базы данных, поддерживаемой модулем {pl}.

WARNING: На текущий момент работа с модулем {ai} поддерживается только в модуле {wc} 17.

.Модуль {ai} предоставляет следующие возможности:
* Улучшение текста -- исправление орфографических и пунктуационных ошибок в тексте, улучшение стилистики текста.
*	Озвучка текста -- голосовая озвучка текста из поля (например, в кратком пересказе).
* Краткий пересказ -- анализ документа и предоставление краткого пересказа его содержания.
* Вопрос по файлу -- ответы на вопросы по выбранному документу.
*	Анализ файла -- анализ документа по выбранному профилю проверки.
*	Сравнение документов -- сравнение выбранного документа с другими документами карточки.
* Генерация текста -- помощь в формализации текстовой информации. Генерация нового текста на основе введенных параметров, данных из карточки документа и/или приложенных файлов документов к карточке.
*	Создание протокола -- формирование протокола из медиафайлов по выбранному шаблону.
*	Извлечение атрибутов во входящих -- извлечение атрибутов из файла и автозаполнение карточки Входящего документа (входит в Документы УД {dv}).
*	Создание задания голосовым вводом -- создание задания на исполнение (входит в Задания УД {dv}) с главной страницы голосовым вводом.

[#module-structure]
== Структура модуля

.Архив модуля содержит следующие компоненты:
* `AiServerExtension` -- серверное расширение.
* `AiWebExtension` -- клиентское расширение.
* `AiDesignerExtension` -- расширение программы {kvr}.
* `ai.config` -- конфигурационный файл модуля.

[#docs]
== Как организована документация

* Общие сведения -- общая информация о модуле.
* Необходимые ресурсы -- требования к программному и аппаратному обеспечению компьютера, к системе {dv} для установки модуля.
* Структура модуля -- перечислены компоненты, составляющие модуль.
* Администрирование модуля -- инструкция по установке, первоначальной настройке и удалению модуля.
* Настройка модуля -- перечисление основных функций администратора модуля.
* Руководство пользователя -- работа с функциями модуля со стороны пользователя.
