= Настройки {wincl}а и РМА

include::new-admin-console@install-linux:ROOT:partial$excerpts.adoc[tags=winconfig]

Данные параметры позволяют настраивать установку клиентских компонентов модулей, а также поведение {wincl}а/РМА.

[#client]
== Настройки установки клиентской части решений

.Фрагмент файла "windows-client-part.json":
[source,json]
----
{
  "Site": {
    "InstallLogPath": null, <.>
    "InstallAction": 0, <.>
    "InstallUILevel":  0, <.>
    "InstallScope": 0 <.>
  }
}
----
<.> Путь к папке, в которой будет создаваться журнал для всех инсталлируемых компонентов.
<.> Операция, которую выполняет {wincl} при инсталляции решений:
+
* `0` -- инсталлировать необходимые библиотеки в режиме по умолчанию.
* `1` -- не инсталлировать ничего.
* `2` -- инсталлировать необходимые библиотеки полностью.
* `3` -- инсталлировать необходимые библиотеки в режиме advertise, при этом в реестр записывается регистрация компонентов, а сами компоненты устанавливаются при первом использовании.
+
<.> Уровень отображения пользовательского интерфейса инсталляций:
+
* `0` -- используется настройки интерфейса по умолчанию.
* `1` -- полностью автоматическая инсталляция.
* `2` -- минимальный интерфейс.
* `3` -- сокращенный интерфейс.
* `4` -- полный интерфейс.
+
<.> Область установки компонентов:
+
* `0` -- для текущего пользователя.
* `1` -- для всех пользователей.
* `2` -- авто-распознавание, при наличии полномочий устанавливается для всех пользователей, иначе только для текущего пользователя.
+
[WARNING]
====
Если на компьютере установлена клиентская часть модуля {pl}, другие базовые модули будут устанавливаться с той же областью установки и настройка _Область установки_ игнорируется.

При обновлении базовых модулей {dv} также используется область установки обновляемой версий.

Данное исключение относится только к базовым модулям {dv}, дополнительные модули устанавливаются и обновляются с областью установки, выбранной в параметре _Область установки_.
====

[#interface]
== Настройки интерфейса {wincl}а по умолчанию

Показывать панели::
Настройки указываются в параметре `"ShowPanels"`. Выбранное значение определяет список панелей, которые будут отображаться в окнах {wincl}а и РМА. Значение может быть от `0` до `4`, то есть, если нужен вариант *_Все панели_*, следует указать `4`.
+
* `0` -- Дерево папок и панель представления.
* `1` -- Дерево папок.
* `2` -- Панель представления.
* `3` -- Панель представления и область просмотра.
* `4` -- Все панели.

Периодичность обновления данных представления::
Настройка регулирует интервал автоматического обновления представления {wincl} и РМА. Если указанный интервал равен нулю, автоматическое обновление представлений на экранах пользователей не происходит. Автоматическое обновление выполняется только в текущей активной папке пользователя.
+
За настройку отвечает параметр `"RefreshTimeout"`, значение указывается в секундах, например, `300`.

Не скрывать панель инструментов Internet Explorer:::
Параметр `"KeepBrowserUI"` может быть задан, значение `1` или не задан, значение `0`. Если параметр задан, у пользователя РМА будет отображаться стандартная панель инструментов браузера Internet Explorer помимо стандартной панели инструментов РМА.

Язык интерфейса::
Выбранное значение определяет язык интерфейса {wincl} и РМА, который будет использоваться по умолчанию у всех пользователей.
+
Язык интерфейса настраивается в параметре `"LangName"`. Допустимые значения: `RUS` или `ENU`. Оставьте значение пустым, если интерфейс должен определяться автоматически.

Производительность::
Значение настраивается в параметре `"PerformanceState"` и определяет параметры запуска {wincl} и РМА:
+
* `0` -- `Высокая` -- {wincl} будет автоматически запускаться при загрузке ОС и будет свернут в область уведомлений при закрытии окна.
+
В этом режиме необходимые данные считываются в фоновом процессе, что обеспечивает максимально возможную скорость открытия карточек.
+
* `1` -- `Средняя` -- {wincl} не будет автоматически запускаться при загрузке ОС и будет свернут в область уведомлений при закрытии окна.
+
В этом режиме необходимые данные считываются в фоновом процессе, что обеспечивает максимально возможную скорость открытия карточек после первого открытия приложения вручную.
+
* `2` -- `Низкая` -- {wincl} не будет автоматически запускаться при загрузке ОС и будет закрыт при закрытии окна.
+
В этом режиме данные будут считываться при каждом первом открытии карточки после запуска {wincl}а, поэтому карточки будут открываться медленнее, чем в других режимах. Режим рекомендуется использовать, если имеется много клиентских компьютеров, не удовлетворяющих рекомендованным аппаратным требованиям.
+
[NOTE]
====
Отдельные настройки могут быть переопределены в {wincl}е/РМА. Например, язык пользовательского интерфейса.
====
