= Настроить размер пула соединений с сервером БД

Сервер приложений {dv} при работе с сервером БД использует пул соединений фиксированного размера. Изменить размер пула по умолчанию можно с помощью специальной настройки в конфигурационном файле. По умолчанию данная настройка отсутствует, а размер задан как `100 соединений`.

****
Начиная с модуля {pl} версии {pl-cu5}, поддерживается два варианта настройки размера пула соединений с сервером БД:

* При помощи изменения параметра в конфигурационном файле `appsettings.json`
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:db-config.adoc#pool-volume[Размер пула соединений с сервером БД]"
****

Чтобы изменить количество соединений, необходимо в конфигурационном файле `/usr/lib/docsvision/platform/appsettings.json` создать параметр `DbConnectionPoolSize`, в котором определить требуемый размер пула.

[WARNING]
====
Увеличение размера пула может привести к увеличению потребляемой памяти на серверах приложений и баз данных.
====

[source,json]
----
  "DocsVision": {
    "Platform": {
      "Server": {
        "Databases": {
          "max_connections": 40,
          "DbConnectionPoolSize": 100
        }
      }
    }
  }
----

Конфигурировать СУБД нужно учитывая перечисленные ниже факты:

Используя настройки *max_connections* в БД {pgsql} можно ограничить количество подключений к серверу БД. Настройка влияет на подключения к серверу БД, а не к БД. Если на сервере {pgsql} несколько БД, ограничение влияет на общее количество подключений к серверу: может быть открыто 60 соединений с одной БД, а с другой удастся открыть лишь 40, дальнейшие попытки открыть подключение выдадут ошибку.

Настройка *DbConnectionPoolSize* определяет максимальный размер пула соединений с базой на клиентской стороне, а не с сервером. Если на одном сервере приложений подключили две БД {pgsql} c одного инстанса, то *{sss-new}* при определённых нагрузках может пытаться открыть по 100 соединений к каждой БД, то есть 200 подключений к одному инстансу {pgsql}.

Если два сервера приложений обрабатывают одну БД {pgsql}, то каждый *{sss-new}* может пытаться открыть по 100 соединений к этой базе, то есть 200 подключений к одному инстансу {pgsql}.

Также нужно помнить о подключениях от _pgagent_, каких-то дополнительных соединениях от _pgadmin_ (или другой среды администрирования), ServerConsole, сервиса полнотекстового индексирования, файлового сервиса.
