:do-what: варианта установки локализованных значений для полей
:link: "xref:dev@mgmtconsole:servers:appserver-general.adoc[Общие настройки сервера приложений]"

= Настроить режим локализации полей

В системе {dv} поддерживается возможность установки локализованных значений для полей. Фактическое возвращаемое сервером значение поля определяется локалью клиентского приложения.

include::admin:partial$mancons.adoc[]

.Системная функция локализации полей используется для локализации следующих элементов:
* Названий папок.
* Названий представлений и групп представлений.
* Названий столбцов и текста в строках агрегации значений в представлениях.
* Названий поисковых запросов и групп запросов.

== Функция локализации полей

.Функция локализации полей работает следующим образом:
* Запустите {wincl} с текущей локалью и задайте имя объекта из списка в описании функции.
* Затем запустите {wincl} с другой локалью и задайте имя на этот же объект на другом языке.
* Каждой локали, заданной в {wincl}е, будет соответствовать имя объекта на своём языке.
+
Если локализованное значение отсутствует, будет возвращено значение для локали по умолчанию.

.По умолчанию используются следующие настройки локализации полей:
* Функция локализации полей отключена.
* Язык локализации по умолчанию -- `1049` (русский).

[WARNING]
====
Локализованные значения поля хранятся в отдельной секции. На чтение секции требуется дополнительное время. Это влияет на скорость работы с данными.

Значение поля для основной локали хранится в основной секции. Доступ к основной секции осуществляется в обычном режиме и не влияет на скорость работы с данными.
====

== Изменить настройки режима локализации полей по умолчанию

.Чтобы изменить настройки режима локализации полей по умолчанию:
. Откройте конфигурационный файл модуля по адресу `/usr/lib/docsvision/fulltextservice/appsettings.json` на машине с серверными компонентами {dv}.
. Перейдите к разделу menu:{dv}[Platform > Server].
. Чтобы изменить язык локализации по умолчанию, измените значение параметра `MainLocaleID` на:
* `1049` -- русский,
* `1033` -- английский.
+
Если параметр отсутствует -- добавьте самостоятельно.
+
. Чтобы изменить режим локализации, измените значение параметра `LocalizationMode` на одно из следующих:
+
* `0` -- режим локализуемых полей выключен.
* `1` -- только чтение локализуемых полей.
* `2` -- только запись локализуемых полей.
* `3` -- режим локализуемых полей включён.
* `4` -- режим локализуемых полей включён с особым режимом. Новое значение поля будет сохраняться и для основной локали и для локали клиентского приложения.
+
Если параметр отсутствует -- добавьте самостоятельно.
+
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "MainLocaleID": 1049,
        "LocalizationMode": 4
        }
      }
    }
  }
}
----
+
. Перезапустите {sss}.
+
WARNING: Если система {dv} работает в кластере, выполните аналогичные настройки на всех серверах кластера {dv}.
