= Блок "Модули расширения"

В разделе "Модули расширения" отображаются подразделы с настройками базовых и дополнительных модулей {dv}, для которых предусмотрена возможность настройки.

Модуль {pl} добавляет раздел настроек "Сервис полнотекстового поиска". В _{cns}_ будет добавлен раздел настроек модуля _{wf}_, если модуль установлен. Подробное описание приведено в документации по администрированию модуля _{wf}_, в разделе "xref:6.1@workflow:admin:console.adoc[]".

* Модуль {pl} добавляет настройки "Сервиса полнотекстового поиска". Подробное описание приведено в разделах:
** "xref:search-full-text.adoc[]" для программы {cns}
// ** "xref:dev@mgmtconsole:servers:fulltext.adoc[]" для {of-mc}
* Если модуль _{wf}_ установлен, его настройки также будут добавлены. Подробное описание приведено в разделах:
** "xref:6.1@workflow:admin:console.adoc[]" для программы {cns}
** "xref:dev@mgmtconsole:user:connections-mail-server.adoc[]" и "xref:dev@mgmtconsole:servers:workflow-connection.adoc[]" для {of-mc}
