= Настроить протоколирование работы файлового сервиса

Работа файлового сервиса {dv} (служба *{fss-new}*) протоколируется со следующими параметрами по умолчанию:

.Если для сервера {dv} включено протоколирование работы:
* Файл журнала: `/var/log/docsvision/fileservice/`.
* Уровень логирования: `уровень-логирования-сервера`.

.Чтобы изменить настройки:
. Отредактируйте параметр `"NLog":` в конфигурационном файле файлового сервиса `/usr/lib/docsvision/fileservice/appsettings.json`.
+
Журнал формируется, если в конфигурационном файле службы *{fss-new}* указана строка подключения к БД {dv} в параметре `"Databases":`. Уровни журналирования настраиваются внутри секции `nlog`. Ниже приведён пример, где уровень журналирования указывается словом, а не цифрой, `minlevel="Warn"`:
+
--
.Фрагмент конфигурационного файла службы {fss-new}:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "Databases": {
          "alias": "Initial Catalog=DBname; Data Source=database.server.com; User ID=user; Password=qwerty" <.>
        }
      }
    }
  },
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/fileservice/${shortdate}.log",
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn", <.>
        "writeTo": "logFile"
      }
    ]
  }
}
----
<.> Строка подключения к базе данных {dv}.
<.> Уровень журналирования по умолчанию -- "Warn".
--
+
Дополнительная информация по настройке журналирования приведена https://nlog-project.org[на сайте] компонента NLog.
+
. Перезапустите файловый сервис {dv}.
+
[WARNING]
====
Учётная запись файлового сервиса {dv} должна обладать правами на создание, изменение и чтение файла журнала.
====
