= Доступ к Storage Server по HTTPS

При необходимости можно настроить доступ к *{sss-new}* по протоколу HTTPS, для этого потребуется выполнить настройки, описанные далее.

// tag::certificate[]
. Установите пакет `openssl` командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install openssl

{os2}::
+
 $ sudo dnf install openssl
====
+
. [[before]]Создайте самоподписанный сертификат SSL.
+
--
 $ openssl req -x509 -newkey rsa:2048 -keyout docsvision.key -nodes -out certificate.crt -subj "/CN=example.company.com" <.>

<.> Замените `docsvision.key` и `certificate.crt` на собственные названия для ключа и сертификата, вместо `/CN=example.company.com` укажите адрес сервера {dv} на Linux, например, `/CN=help.docsvision.com`.
--
+
NOTE: Подробный пример создания сертификата приведён в руководстве по настройке системы, раздел "xref:new-admin-console@engineer:ROOT:create-cert.adoc[]".
+
. Добавьте сертификат в доверенные, скопировав его в директорию `/usr/local/share/ca-certificates/`.
. Обновите список доверенных сертификатов:
+
[tabs]
====
{os1}::
+
 $ sudo update-ca-certificates

{os2}::
+
 $ sudo update-ca-trust
====
+
. Отредактируйте конфигурационный файл `appsettings.json`:
// end::certificate[]
+
 $ sudo nano /usr/lib/docsvision/platform/appsettings.json
+
.Фрагмент конфигурационного файла:
[source,json]
----
{
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://*:5020", <.>
        "Certificate": {
          "Path": "/folder/certificate.crt", <.>
          "KeyPath": "/folder/docsvision.key" <.>
        }
      }
    }
  }
}
----
<.> `Url` -- адрес и порт для доступа по HTTPS. При такой конфигурации сервис будет прослшуивать одновременно два порта: стандартный `5000` для HTTP и `5020` для HTTPS. Чтобы использовать стандартный порт `5000` для подключения по HTTPS, измените параметры следующим образом: menu:Http[Url > "https://*:5000"]. Обратите внимание, вместо `Https` в данной конфигурации указывается `Http`.
<.> `Path` -- локальное расположение сертификата, созданного <<before,ранее>>.
<.> `KeyPath` -- локальное расположение ключа шифрования для сертификата, созданного <<before,ранее>>.
+
. Измените также конфигурационный файл {wc} по адресу `/usr/lib/docsvision/webclient/appsettings.json`. Измените параметр `"ConnectionAddress"`, в котором необходимо указать адрес с `https`.
. Перезапустите службы *{sss-new}* и *{wcs-new}*.
+
. На машине с Windows, где планируется работа в {wincl}е, необходимо добавить созданный <<before,ранее>> сертификат в доверенные корневые сертификаты и указать адрес Storage Server с `https` в конфигурационном файле `windows-client-part.json` в параметрах `"ConnectAddress"` и `"ServerUrl"`. Подробнее см. "xref:new-admin-console@platform:console:manage-access.adoc[]" в документации модуля {pl}.
. Выполните аналогичные настройки для конфигурационных файлов модулей {mc} и {wf}.
. Проверьте подключение. Если настройки выполнены корректно, {wc}, {wincl} и программа DVExplorer должны работать без ошибок, обновление БД также должно проходить без ошибок.
