= Ограничить результаты поискового запроса

****
Начиная с модуля {pl} версии {pl-cu5}, поддерживается два варианта ограничения результатов поискового запроса:

* При помощи изменения параметра в конфигурационном файле на сервере `appsettings.json`
* Из {of-mc}, через дополнительные настройки, по пути `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;ResultLimit` без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:appserver-etc.adoc[]"
****

Максимальное количество карточек, возвращаемых поисковым запросом, ограничение -- по умолчанию не больше `2000 карточек`.

Чтобы изменить данное ограничение, измените значение параметра `ResultLimit` в конфигурационном файле по пути `/usr/lib/docsvision/platform/appsettings.json`:

[source,json]
----
  "DocsVision": {
      "Platform": {
        "Server": {
          "ResultLimit": 50; <.>
        }
      }
  }
----
<.> Отображение не более 50 карточек в результатах.

[WARNING]
====
* Увеличение значения `ResultLimit` может привести к замедлению работы сервера {dv} и клиентских приложений.
* Параметр не применяется при постраничной проверке прав доступа в представлениях.
====
