:with-console: no
:with-config: yes
:do-what: варианты настройки журналирования сервера
:link: "xref:6.2@mgmtconsole:servers:appserver-general.adoc[]"

= Журналы системы

В системе {dv} имеется ряд журналов, которые используются для сбора информации о процессе установки и работы системы:

* <<server,Журнал работы сервера>>.
* <<client,Журналы установки клиентских компонентов>>.
* <<console,Журнал сообщений "Консоли настройки {dv}">>.
* <<search,Журнал сообщений сервиса полнотекстового поиска>>.
* <<file,Журнал работы файлового сервиса>>.

// Если любой из файлов журнала не получается сохранить по указанному в настройках пути, он будет сохранён в папке `%localappdata%\Docsvision\Logs`. Путь к папке может отличаться в зависимости от пользователя, под которым запущены службы или серверная консоль.

[#server]
== Журнал работы сервера

Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.

include::admin:partial$mancons.adoc[]

По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/appserver/dvappserver.log` в Linux и `C:\ProgramData\docsvision\appserver\dvappserver.log` в Windows. Путь к журналу и уровень журналирования можно настроить в конфигурационном файле модуля {pl}, подробнее работа с конфигурационным файлом описана в разделе "xref:admin:config-platform.adoc[]"

Пример настройки уровня журналирования приведён ниже.

.Фрагмент конфигурационного файла Службы сервера {dv}:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "TraceLevel": 1, <.>
        "LogFile": "/var/log/docsvision/appserver/dvappserver.log" <.>
      }
    }
  }
}
----
<.> Уровень журналирования: `0` -- журналирование не ведётся, `1` -- Error, `2` -- Warning, `3` -- Info, `4` -- Verbose. Если значение не задано, по умолчанию используется "Error".
<.> Путь до файла журнала. По умолчанию `/var/log/docsvision/appserver/dvappserver.log` в Linux и `C:\ProgramData\docsvision\appserver\dvappserver.log` в Windows.

[NOTE]
====
В системном журнале и журнале приложений может встречаться ошибка `Unexpected error: The file '/docsvision/StorageServer/Fetch.aspx' does not exist.`

Ошибка возникает из-за наличия модуля _Конструктор отчетов_, несовместимого с {dv} текущей версии. Обработка запросов от данного модуля будет отключена.
====

[#client]
== Журналы установки клиентских компонентов

В журналах установки клиентских компонентов фиксируются события, возникающие в процессе установки клиентской части модулей {dv}.

Журнал формируется отдельно для каждого из устанавливаемых клиентских компонентов и сохраняется в текстовый файл.

Путь к папке для хранения журналов всех установленных клиентских компонентов указывается в программе _{cns}_ в параметре *Папка журналов установки* раздела "xref:config-client.adoc[Настройка клиентской части]".

Просмотреть журнал можно, открыв файл в текстовом редакторе.

[#search]
== Журнал сообщений сервиса полнотекстового поиска

Данный журнал содержит информацию о работе сервиса полнотекстового индексирования {dv}.

По умолчанию журналы сообщений сервиса полнотекстового поиска сохраняется в директории `/var/log/docsvision/fulltextservice.log` в Linux и `C:\ProgramData\docsvision\fulltextservice.log` в Windows.

Подробнее настройка журналирования полнотекстового поиска описана в разделе "xref:search-logging.adoc[]".

[#console]
== Журнал сообщений "Консоли настройки {dv}"

{cns} устанавливается на машину Windows. По умолчанию журнал располагается по адресу `Каталог-установки-серверной-части-модуля-{pl}\Logs\ServerConsole.log`

.Ведение журнала можно отключить в настройках:
. Откройте _{cns}_.
. В меню выберите menu:Инструменты[Настройки...].
. В окне _Общие настройки_ поставьте флаг `*Журналировать операции консоли настройки*` и укажите путь к файлу журнала в поле _Файл журнала_.

В журнале ведётся протоколирование событий программы _{cns}_ и всех операций, выполняемых через программу.

[#file]
== Журнал работы файлового сервиса

В данный журнал сохраняется информация об ошибках работы файлового сервиса {dv}, а также информационные сообщения (если включено).

Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}. По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/fileservice` в Linux и `C:\ProgramData\docsvision\fileService\fileservice.log` в Windows. Путь к журналу и уровень журналирования можно настроить в конфигурационном файле модуля {pl}.

.Фрагмент конфигурационного файла {of-fs}:
[source,json]
----
{
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/fileservice/${shortdate}.log", <.>
        "layout": "${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}"
      }
    },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Warn", <.>
        "writeTo": "logFile"
      }
    ]
  }
}
----
<.> Путь к файлу журнала настраивается в параметре `\{gdc:baseLogFolder}`. По умолчанию используется каталог `/var/log/docsvision/fileservice` в Linux и `C:\ProgramData\docsvision\fileService\fileservice.log` в Windows.
<.> Уровень журналирования, по умолчанию используется `Warn`.

Подробнее настройка журналирования {of-fs} описана в разделе "xref:file-service-logging.adoc[Настройка протоколирования работы файлового сервиса {dv}]".

[#appserv-requests]
== Протоколирование запросов сервера приложений

Протоколирование запросов полезно для анализа входящих запросов на сервере приложений и ответов на них, заголовков и т.д.

.Журнал запросов содержит следующую информацию:
* HTTP запросы и ответы.
* Дата и время запросов и ответов.
* Заголовки

Протоколирование запросов сервера приложений настраивается в конфигурационном файле модуля по адресу `/usr/lib/docsvision/platform/appsettings.json` в Linux и `C:\ProgramFiles\docsvision\platform\appsettings.json` в Windows, за настройку отвечает параметр `W3CLogging`:

[source,json]
----
{
"W3CLogging": {
	"IsEnabled": true, <.>
	"LogDirectory": "/var/log/docsvision/appserver", <.>
	"LoggingFields": "Date,Time,ServerName,Method,UriStem,UriQuery,ProtocolStatus,TimeTaken,ProtocolVersion,Host,UserAgent,Referer,ConnectionInfoFields", <.>
	"FileSizeLimit": 10485760, <.>
	"RetainedFileCountLimit": 4, <.>
	"FileName": "appserver-w3c-" <.>
}
}
----
<.> Включение/отключение протоколирования событий. Значение по умолчанию: `false`, в стандартной конфигурации остальные настройки отсутствуют.
<.> Путь к журналу.
<.> Журналируемые поля. По умолчанию указываются запросы, ответы, заголовки, дата/время (записывается в формате UTC) и имя сервера. Со всеми допустимыми значениями можно ознакомиться в https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Middleware/HttpLogging/src/W3CLoggingFields.cs[документации Microsoft].
<.> Максимальный размер файла журнала, после которого будет создаваться новый. Значение в байтах, по умолчанию 10485760 байт (10 Мб). Цифра `0` означает отсутствие ограничения по размеру.
<.> Количество сохраняемых файлов журнала. Допустимые значения от `1` до `10000`, по умолчанию используется `4`.
<.> Префикс имени файла журнала.

Запросы будут записаны в файл `/var/log/docsvision/appserver/appserver-w3c-&#x7b;YYYYMMDD.X&#x7d;.txt` в Linux и `C:\ProgramData\docsvision\appserver\appserver-w3c-&#x7b;YYYYMMDD.X&#x7d;.txt` в Windows. Настройка альтернативного расширения поддерживается только при протоколировании с NLog, см. подробнее <<nlog,ниже>>.

[#nlog]
=== Протоколирование запросов с помощью NLog

Если требуется отображать в журналах локальное время или расширить список журналируемой информации, есть возможность подключения Nlog. При этом стандартное журналирование "W3CLogging" будет отключено (вне независимости от значения параметра menu:W3CLogging[IsEnabled].

Протоколирование запросов с использованием NLog имеет ряд преимуществ перед журналированием W3CLogging. NLog предлагает больше параметров логирования (38 против 17),указывает в журнале местное время с точностью до миллисекунды, позволяет задать свои форматы для отображаемых данных и даёт гибкость в управлении файлами журнала.

// tag::nlo[]
.Чтобы активировать протоколирование запросов с помощью NLog, измените параметры журналирования в параметре menu:NLog[targets]:
[source,json]
----
{
"NLog": {
   "extensions": [
    { "assembly": "DocsVision.AppServer" } <.>
   ],
   "targets": {
    "w3cFile": {
      "type": "File",
      "fileName": "${gdc:baseLogFolder}/docsvision/appserver/appserver-w3c-${date:format=yyyyMMdd}.${processId}.log",
      "layout": {
         "type": "W3CLoggingLayout",
        "columns": [ <.>
		{ "column": "date" },
		{ "column": "time", "layout": "${longdate}" }, <.>
		{ "column": "c-ip" },
	    ]
      }
    }
   },
   "rules": [
    {
      "logger": "*",
      "minLevel": "Debug",
      "writeTo": "w3cFile"
    }
   ]
}
}
----
<.> Обязательный параметр, если он не указан, NLog не будет записывать обычные сообщения в журнал.
<.> Секция задаёт собственный набор колонок. Если список колонок не указан, в журнал будут включены только колонки по умолчанию `date`, `time`, `c-ip`, `s-ip`, `cs-username`, `s-computername`, `cs-method`, `cs-uri-stem`, `cs-uri-query`, `sc-statuscode`, `sc-bytes`, `cs-bytes`, `time-taken`, `cs-host`, `cs(User-Agent)`.
<.> Формат представления данных колонки может быть изменён. Если формат не указан, будут использоваться значения по умолчанию. В `layout` можно использовать любые переменные NLog, подробнее см. в https://nlog-project.org/config/?tab=layout-renderers[документации NLog].
// end::nlo[]

.Полный список колонок и допустимых значений для журналирования:
[%collapsible]
====
* `date` -- Дата начала обработки запроса. Значение по умолчанию: `$&#x7b;date:format=yyyy-MM-dd&#x7d;`.
* `time` -- Время начала обработки запроса. Значение по умолчанию: `$&#x7b;date:format=HH:mm:ss.fff&#x7d;`.
* `appserver-version` -- Версия {wc}а. Например `6.1.725+a4c9b271d7`. Значение по умолчанию: `$&#x7b;appserver-version&#x7d;`. Для протоколирования запросов сервера приложений аналогичная колонка называется `appserver-version`.
* `c-ip` -- IP-адрес клиента. Значение по умолчанию: `$&#x7b;aspnet-request-ip&#x7d;`.
* `cs(Auth-Type)` -- Тип используемой аутентификации (например, Cookie). Значение по умолчанию: `$&#x7b;aspnet-user-authtype&#x7d;`.
* `cs(Certificate)` -- Сертификат клиента текущего запроса. Значение по умолчанию: `$&#x7b;aspnet-request-client-certificate&#x7d;`.
* `cs(Content-Type)` -- Тип контента: `text/html`, `multipart/form-data` и т.д.. Значение по умолчанию: `$&#x7b;aspnet-request-contenttype&#x7d;`.
* `cs(Cookie)` -- Cookie, подробнее о допустимых параметрах https://github.com/NLog/NLog/wiki/AspNet-Response-Cookie-Layout-Renderer[в документации NLog]. Значение по умолчанию: `$&#x7b;aspnet-request-cookie&#x7d;`.
* `cs(Referer)` -- Значение поля `Referer` из заголовка запроса. Значение по умолчанию: `$&#x7b;aspnet-request-referrer&#x7d;`.
* `cs(User-Agent)` -- User agent. Значение по умолчанию: `$&#x7b;aspnet-request-useragent&#x7d;`.
* `cs-bytes` -- Получено байтов. Значение по умолчанию: `$&#x7b;aspnet-request-contentlength&#x7d;`.
* `cs-connectionid` -- Идентификатор соединения, см. https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connectioninfo.id?view=aspnetcore-8.0[в документации Microsoft]. Значение по умолчанию: `$&#x7b;aspnet-request-connection-id&#x7d;`.
* `cs-form` -- Данные формы из запроса. Подробнее о параметрах https://github.com/NLog/NLog/wiki/AspNetRequest-Form-Layout-Renderer[в документации NLog]. Значение по умолчанию: `$&#x7b;aspnet-request-form&#x7d;`.
* `cs-headers` -- Заголовок запроса. Если нужно взять только определенные заголовки, можно воспользоваться параметрами, подробнее см. https://github.com/NLog/NLog/wiki/AspNetRequest-Headers-Layout-Renderer[в документации NLog]. Значение по умолчанию: `$&#x7b;aspnet-request-headers&#x7d;`.
* `cs-host` -- Значение `Host` из заголовка запроса. Значение по умолчанию: `$&#x7b;aspnet-request-url:includeScheme=false:includeHost=true:includePath=false&#x7d;`.
* `cs-fullhostname` -- Полное имя хоста (с портом). Значение по умолчанию: `$&#x7b;aspnet-request-host&#x7d;`.
* `cs-isauthenticated` -- Состояние аутентификации (значения `0` или `1`). Значение по умолчанию: `$&#x7b;aspnet-user-isAuthenticated&#x7d;`.
* `cs-method` -- Метод (`get`/`post` и т.п.). Значение по умолчанию: `$&#x7b;aspnet-request-method&#x7d;`.
* `cs-mvc-action` -- Вызываемое действие. Значение по умолчанию: `$&#x7b;aspnet-mvc-action&#x7d;`.
* `cs-mvc-controller` -- Вызываемый контроллер. Значение по умолчанию: `$&#x7b;aspnet-mvc-controller&#x7d;`.
* `cs-posted-body` -- Значение по умолчанию `$&#x7b;aspnet-request-posted-body&#x7d;`.
+
.Значения:
** `1`, если:
*** Это запрос HTTP/1.x с ненулевым значением Content-Length или заголовком "Transfer-Encoding: chunked".
*** Это запрос HTTP/2, который не установил флаг END_STREAM на исходном фрейме заголовка.
** `0`, если:
*** Это запрос HTTP/1.x без заголовка Content-Length или "Transfer-Encoding: chunked", или Content-Length равен 0.
*** Это запрос HTTP/1.x с Connection: Upgrade (например, WebSockets). Для этих запросов не существует тела HTTP-запроса, и никакие данные не должны быть получены до тех пор, пока не будет выполнено обновление.
*** Это запрос HTTP/2, который устанавливает END_STREAM на начальном фрейме заголовка.
+
* `cs-tracking-consent` -- Согласие на отслеживание (значения `0` или `1`). Значение по умолчанию: `$&#x7b;aspnet-request-tracking-consent&#x7d;`.
+
--
.Возможные параметры:
** `property`.
+
.Допустимые значения:
*** `CanTrack` --  Указывает, было ли дано согласие, или если согласие не требуется (1 или 0);
*** `HasConsent` --  было ли дано согласие;
*** `IsConsentNeeded` --  требуется ли согласие для данного запроса.
--
+
Пример вызова в собственном формате: `$&#x7b;aspnet-request-tracking-consent:property=CanTrack&#x7d;`.
+
* `cs-uri-query` -- Значение по умолчанию: `$&#x7b;aspnet-request-url:includeScheme=false:includeHost=false:includePath=false:includeQueryString=true&#x7d;`. Запрос URI.
* `cs-uri-stem` -- Ресурс URI. Значение по умолчанию: `$&#x7b;aspnet-request-url:includeScheme=false:includeHost=false&#x7d;`.
* `cs-username` -- Имя пользователя. Значение по умолчанию: `$&#x7b;aspnet-user-identity&#x7d;`.
* `is-websocket` -- Является ли запрос запросом на установку WebSocket (`0` или `1`). Значение по умолчанию: `$&#x7b;aspnet-request-is-web-socket&#x7d;`.
* `s-basepath` -- Значение `ContentRootPath`. Значение по умолчанию: `$&#x7b;aspnet-appbasepath&#x7d;`.
* `s-computername` --Имя сервера. Значение по умолчанию: `$&#x7b;machinename&#x7d;`.
* `s-environment` -- Значение `ASPNETCORE_ENVIRONMENT`. Значение по умолчанию: `$&#x7b;aspnet-environment&#x7d;`.
* `s-ip` -- IP-адрес сервера. Значение по умолчанию: `$&#x7b;aspnet-request-local-ip&#x7d;`.
* `s-port` -- Порт. Значение по умолчанию: `$&#x7b;aspnet-request-local-port&#x7d;`.
* `s-sitename` -- Имя сайта. Значение по умолчанию: `$&#x7b;iis-site-name&#x7d;`.
* `s-webrootpath` -- `WebRootPath`. Значение по умолчанию: `$&#x7b;aspnet-webrootpath&#x7d;`.
* `sc(Content-Type)` -- Тип контента ответа. Значение по умолчанию: `$&#x7b;aspnet-response-contenttype&#x7d;`.
* `sc-bytes` -- Отправлено байт. Значение по умолчанию: `$&#x7b;aspnet-response-contentlength&#x7d;`.
* `sc-response-has-started` -- Были ли отправлены заголовки ответа, т.е. начался ли уже ответ или нет. Значения `0` или `1`. Значение по умолчанию: `$&#x7b;aspnet-response-has-started&#x7d;`.
* `sc-status` -- Код статуса ответа (`200`, `404` и т.д.). Значение по умолчанию: `$&#x7b;aspnet-response-statuscode&#x7d;`.
* `time-taken` -- Сколько времени заняла обработка запроса (в миллисекундах). Значение по умолчанию: `$&#x7b;aspnet-request-duration&#x7d;`.
====
