:conas: yes
:do-what: варианта настройки управления доступом и просмотра открытых сессий
:link: access.adoc#sessions[Управление сессиями]" и "xref:dev@mgmtconsole:user:msg-sessions.adoc[]
:cns-section: "Управление доступом"

= Управление доступом

[#partjson]
== Настройки в "windows-client-part.json"

include::ROOT:partial$excerpts.adoc[tags=winconfig]

Использовать протокол::
Настройки определяют протокол соединения {wincl}а, параметры подключения {wincl}а и РМА к серверу {dv} по умолчанию. Протокол подключения к серверу {dv} указывается в параметре `"Transport`":
+
* `0` -- веб-сервис (HTTP + SOAP).
* `10` -- WCF сервис (HTTP + SOAP).
* `11` -- WCF TCP сервис.
* `12` -- WCF именованный канал (named pipe).
+
.Особенности использования протоколов:
****
* Доступ по протоколу `WCF TCP сервис` возможен только во внутренней сети организации при использовании встроенной аутентификации. При явном запросе пароля клиентская часть автоматически переключается на работу по протоколу `Веб-сервис (HTTP+SOAP)`.
* Внешний доступ возможен только по `HTTP`.
* Протокол `WCF именованный канал (named pipe)` работает только в рамках одного компьютера. Связь с использованием этого транспорта по сети невозможна.
* При использовании протокола `HTTP+SOAP` максимальный размер файла, который может быть приложен к карточке, по умолчанию составляет 2 Гб. Данное ограничение может быть изменено в файле `web.config`, где необходимо в элементе `httpRuntime` поменять значение параметра `maxRequestLength`.
****

Адрес сервера {dv}::
В параметре `"ConnectAddress"` указывается адрес подключения к серверу {dv} для {wincl} и РМА в формате `\http://example.com:5000/StorageServer/StorageServerService.asmx`.

Адрес сайта при подключении через внешнюю сеть или по HTTP::
В параметре `"ServerUrl"` указывается адрес сайта при подключении через внешнюю сеть или по HTTP.

Запретить встроенную аутентификацию::
Если значение параметра `"DisableNTLM"` `1`, при запуске {wincl} и РМА будет запрашиваться имя и пароль пользователя.

[#cns]
== Настройки в программе {cns}

include::admin:partial$mancons.adoc[]

Управление сессиями::
Блок настроек содержит настройки управления пользовательскими сессиями:
Автоматически отключать сессии, не активные более <...> минут:::
В поле указывается допустимое время неактивности пользовательской сессии, по истечении которого сессия будет принудительно закрыта сервером.
+
Неактивной считается сессия, по которой не поступало команд поддержания сессии. Команды отправляются ядром клиента один раз в 60 минут. Функция автоматического закрытия сессий предназначена для отключения "зависших" клиентских подключений {wincl}а, СУБП и др., когда клиент завершил работу аварийно.
+
.Особенности автоматического отключения сессий
****
* Значение параметра должно быть больше `60 минут`.
* Не рекомендуется изменять значение параметра без необходимости.
* Значение по умолчанию: `300 минут`.
* Если значение параметра меньше или равно нулю, будет использоваться значение по умолчанию.
* При обновлении базы данных {dv} установленное значение будет заменено на значение по умолчанию.
****
+
Открытые сессии (использовано X лицензий из X):::
Текущее и максимально возможное количество подключений из лицензии {dv}.
+
[NOTE]
====
Учитываются все лицензии независимо от их типа, пользовательские подключения и подключения сервисов {dv} (например, подключения СУБП).
====
+
Информация о текущих подключениях:::
Учетная запись пользователя, название компьютера, время подключения и время последней активности пользователя.
Обновить::
Обновляет список открытых сессий.
Закрыть:::
Закрывает выбранную в списке сессию.
Закрыть все:::
Закрывает все сессии.
