= Управление доступом

include::ROOT:partial$excerpts.adoc[tags=winconfig]

Использовать протокол::
Настройки определяют протокол соединения {wincl}а, параметры подключения {wincl}а и РМА к серверу {dv} по умолчанию. Протокол подключения к серверу {dv} указывается в параметре `"Transport`":
+
* `0` -- веб-сервис (HTTP + SOAP).
* `10` -- WCF сервис (HTTP + SOAP).
* `11` -- WCF TCP сервис.
* `12` -- WCF именованный канал (named pipe).
+
.Особенности использования протоколов:
****
* Доступ по протоколу `WCF TCP сервис` возможен только во внутренней сети организации при использовании встроенной аутентификации. При явном запросе пароля клиентская часть автоматически переключается на работу по протоколу `Веб-сервис (HTTP+SOAP)`.
* Внешний доступ возможен только по `HTTP`.
* Протокол `WCF именованный канал (named pipe)` работает только в рамках одного компьютера. Связь с использованием этого транспорта по сети невозможна.
* При использовании протокола `HTTP+SOAP` максимальный размер файла, который может быть приложен к карточке, по умолчанию составляет 2 Гб. Данное ограничение может быть изменено в файле `web.config`, где необходимо в элементе `httpRuntime` поменять значение параметра `maxRequestLength`.
****

Адрес сервера {dv}::
В параметре `"ConnectAddress"` указывается адрес подключения к серверу {dv} для {wincl} и РМА в формате `\http://example.com:5000/StorageServer/StorageServerService.asmx`.

Адрес сайта при подключении через внешнюю сеть или по HTTP::
В параметре `"ServerUrl"` указывается адрес сайта при подключении через внешнюю сеть или по HTTP.

Запретить встроенную аутентификацию::
Если значение параметра `"DisableNTLM"` `1`, при запуске {wincl} и РМА будет запрашиваться имя и пароль пользователя.

Управление сессиями::
Настройка выполняется в {of-mc}, см. подробнее "xref:dev@mgmtconsole:servers:appserver-access.adoc#sessions[Управление сессиями]".

Автоматически отключать сессии, не активные более <...> минут::
Настройка выполняется в {of-mc}, см. подробнее "xref:dev@mgmtconsole:servers:appserver-access.adoc#sessions[Управление сессиями]".
