include::6.2@mgmtconsole:servers:db-redis-cache.adoc[tags=beginning]

=== Подключение Redis к {dv}

. Откройте _{cns}_.
. Перейдите в раздел настроек menu:Настройки сервера[Базы данных].
. Выберите настраиваемую базу данных, при работе с которой сервер будет кэшировать данные в Redis, и нажмите на кнопку *Настройки*.
+
****
Будет открыто окно *Свойства и управление базой данных*.
****
+
. Перейдите на вкладку xref:db-config.adoc#caching[Настройки кэширования].
. Выберите в списке _Провайдер_ значение *_Redis_*. Будет разблокировано поле _Строка подключения_.
. Введите в поле _Строка подключения_ адрес и порт для подключения к компьютеру с Redis в формате `адрес:порт`. В качестве адреса может использоваться IP или имя хоста, в качестве порта по умолчанию Redis использует порт `6379`.
+
WARNING: Сетевые политики должны разрешать подключения с серверов {dv} к Redis.
+
. Нажмите на кнопку *Тест*, чтобы проверить соединение с Redis. Результат проверки ("Успешно" или "Ошибка") отобразится в диалоговом окне.
. Сохраните изменения настроек базы данных.
. Если настраивается кластер серверов {dv}, подключите все сервера к одному кэш-серверу Redis.
