= Настройки кэширования и производительности

include::dv6@install-linux:ROOT:partial$excerpts.adoc[tags=winconfig]

Включить счетчики производительности::
Параметр `"PerfCounters"` включает запись данных в счетчики производительности из сервера {dv}. Эта же функция доступна в главном меню Windows menu:Пуск[Настройки > Панель управления > Администрирование > Производительность]. Откройте конфигурационный файл `windows-client-part.json` в любом текстовом редакторе (потребуются права суперпользователя/администратора), и создайте или отредактируйте параметр `PerfCounters`:
+
* `1` -- счетчики производительности активированы.
* `0` -- счетчики производительности деактивированы.

Подробнее про счётчики производительности см. в разделе "xref:performance.adoc[]".

Режим кэширования::
Общие для всех пользователей настройки клиентского кэширования, применяемые при работе в {wincl}е. Откройте конфигурационный файл `windows-client-part.json` в любом текстовом редакторе (потребуются права суперпользователя/администратора), и создайте или отредактируйте параметр `CacheMode`:
+
* Значение:
** `1` -- если требуется кэшировать карточки.
** `2` -- если требуется кэшировать файлы.
** `4` -- если требуется кэшировать справочники.
+
Установите в `CacheMode` сумму значений, чтобы кэшировались карточки, файлы, справочники. Например, для кэширования только справочников и файлов, результирующее значение будет равно `2`+`4` = `6`.
+
[NOTE]
====
Настройки клиентского кэша могут быть переопределены на клиенте. Инструкция приведена в документации по администрированию модуля _{wincl}_, в разделе "xref:dev@winclient:admin:client-cache.adoc#setup[Настройка кэширования]".
====

[#client-cache]
Очистить клиентский кэш:::
+
// tag::cl-cache[]
.Чтобы очистить клиентский кэш:
. Создайте или отредактируйте параметр `ClearCacheFrom` в конфигурационном файле `windows-client-part.json`. В параметре укажите дату и время в формате https://ru.wikipedia.org/wiki/ISO_8601[ISO 8601]. Клиентский кэш будет очищен после перезапуска службы Сервера {dv} в указанное время при подключении клиента к серверу {dv}.
+
Во время очистки удаляется содержимое папки `%temp%\DVCache\ИмяБазы\Идентификатор пользователя\`. Очищается кэш пользователя, от имени которого выполняется подключение.
+
Процедура очистки кэша может выполняться без ограничений, при необходимости.
+
WARNING: Запуск клиента может занять больше времени из-за выполнения очистки.
// end::cl-cache[]
