= Ограничить размер файлового кэша

Сервер {dv} кэширует файлы запрашиваемые клиентами
// в папку `C:\Windows\TEMP\Название-БД\FileCache`.

.Разрастание кэша ограничивается двумя параметрами:
* `FileCacheSize` -- устанавливает максимальный размер кэша от *общего размера диска*, на котором размещается кэш. Значение задаётся в процентах: от `0` до `100`. По умолчанию: `10%`.
* `FileCacheMaxFilesCount` -- устанавливает максимальное количество файлов в файловом кэше. По умолчанию: `1000 файлов`.

Очистка файлового кэша выполняется при запуске *{sss-new}* и при чтении файла, если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

.Администратор может изменить установленные ограничения:
. Откройте реестр ОС на сервере {dv}.
. Перейдите в раздел `menu:{dv}[Platform > Server]`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`. Если параметры отсутствуют, создайте их самостоятельно.
+
[source,json]
----
  "DocsVision": {
      "Platform": {
        "Server": {
          "FileCacheSize": 0, <.>
          "FileCacheMaxFilesCount" 0 <.>
        }
      }
  }
----
<.> Для `FileCacheSize` укажите значение от `0` до `100`.
<.> Для `FileCacheMaxFilesCount` укажите значение от `0`.
