= Ограничить размер файлового кэша

Сервер {dv} кэширует файлы запрашиваемые клиентами во временную папку `\Название-БД\FileCache`.

.Разрастание кэша ограничивается двумя параметрами:
* `FileCacheSize` -- устанавливает максимальный размер кэша от *общего размера диска*, на котором размещается кэш. Значение задаётся в процентах: от `0` до `100`. По умолчанию: `10%`.
* `FileCacheMaxFilesCount` -- устанавливает максимальное количество файлов в файловом кэше. По умолчанию: `1000 файлов`.

Очистка файлового кэша выполняется при запуске *{sss-new}* и при чтении файла, если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

.Администратор может изменить установленные ограничения:
. Откройте конфигурационный файл модуля, расположенном по адресу `/usr/lib/docsvision/platform/appsettings.json` на сервере {dv}.
. Перейдите в раздел `menu:Platform[Server]`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`.
+
Если параметр(ы) отсутствует, создайте:

[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "FileCacheSize": 0, <.>
        "FileCacheMaxFilesCount": 0 <.>
      }
    }
  }
}
----
<.> Для `FileCacheSize` укажите значение от `0` до `100`.
<.> Для `FileCacheMaxFilesCount` укажите значение от `0`.

[#rest-cache]
== Файловый кэш для менеджера объектов Rest

При попытке доступа к файлам менеджер объектов Rest кэширует информацию о них. Кэш не хранится на диске, а располагается в памяти. Кэш разделяется между всеми сессиями, включая сессии разных пользователей. Для существующих БД кэширование по умолчанию включено. Отключение или настройка кэширования выполняется при помощи параметров конфигурационного файла модуля, для которого требуется настроить кэширование, секция menu:DocsVision[Platform > ObjectManager]. Изменять настройки рекомендуется в нерабочее время:

* `DisabledCaching` -- параметр отключает кэширование. Значение по умолчанию: `0` -- включено, для отключения укажите `1`.
* `MaxFileDataEntrySize` -- регулирует максимальный размер кэшируемых файлов. Значение по умолчанию -- `65536` байт (64 Кб).
* `MaxFileDataCacheSize` -- задаёт общий размер кэша в памяти. Значение по умолчанию составляет `67108864` байт (64 Мб). При превышении размера кэша очищаются данные наименее часто используемых файлов согласно статистике обращений к файлу.

NOTE: Если настройки в конфигурационном файле отсутствует, создайте их самостоятельно в указанном разделе. Файловый кэш для ОМ Rest поддерживается в модуле {pl} версии {pl-cu5}.
