= Ограничить размер файлового кэша

Сервер {dv} кэширует файлы запрашиваемые клиентами во временную папку `\Название-БД\FileCache`.

.Разрастание кэша ограничивается двумя параметрами:
* `FileCacheSize` -- устанавливает максимальный размер кэша от *общего размера диска*, на котором размещается кэш. Значение задаётся в процентах: от `0` до `100`. По умолчанию: `10%`.
* `FileCacheMaxFilesCount` -- устанавливает максимальное количество файлов в файловом кэше. По умолчанию: `1000 файлов`.

Очистка файлового кэша выполняется при запуске *{sss-new}* и при чтении файла, если превышено значение `FileCacheSize` или `FileCacheMaxFilesCount`.

.Администратор может изменить установленные ограничения:
. Откройте конфигурационный файл модуля, расположенном по адресу `/usr/lib/docsvision/platform/appsettings.json` на сервере {dv}.
. Перейдите в раздел `menu:Platform[Server]`.
. Измените значение параметров `FileCacheSize` и/или `FileCacheMaxFilesCount`.
+
Если параметр(ы) отсутствует, создайте:

[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "FileCacheSize": 0, <.>
        "FileCacheMaxFilesCount": 0 <.>
      }
    }
  }
}
----
<.> Для `FileCacheSize` значения -- от `0` до `100`.
<.> Для `FileCacheMaxFilesCount` значения -- от `0`.
