= Уровень подготовки пользователя

Для эксплуатации модуля _{wf}_ определены две пользовательские роли: администратор {dv} и пользователь. На этапе внедрения системы {dv} в организации и настройки бизнес-процессов появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает модуль (серверную и клиентскую части), выполняет первоначальную настройку. Администратор {dv} должен обладать навыками настройки модуля "Платформа", а также ознакомиться с документацией по xref:admin:install.adoc[администрированию модуля] "модуль {wf}".

Пользователь работает с письмами, рассылаемыми почтовым сервером модуля. Основным пользовательским рабочим местом является xref:6.1@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере.

Инженер выполняет настройку бизнес-процессов с помощью предоставляемых функций и шлюзов, а также разработанных скриптов.

При необходимости разработки собственных бизнес-процессов и функций определяется дополнительная роль: разработчик {dv}. Разработчик создаёт собственные скрипты (сценарии) БП. Разработчик должен быть знаком с языками C# или Visual Basic .NET, ознакомиться с данной документацией для модуля {to}, а также документацией в разделе xref:programmer::index.adoc[Руководство разработчика {dv}].
