= Структура модуля

{mir} содержит в себе бизнес-логику: операции регистрации, отзыва и проверки статуса.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Расширение для Службы {ws} -- _{mir}_.
.. Серверное расширение {wc}а, сигнализирующее модулю о необходимости зарегистрировать МЧД.
// .. Журнал обмена с реестром МЧД -- карточка, которая соответствует каждой СКД. После установки {of-mir} добавляется следующая логика: при обращении к модулю из какой-либо карточки доверенности, в СКД появляется ссылка на журнал и в журнале сразу появляется запись. Например, о нажатии кнопки *Зарегистрировать МЧД* -- создается карточка журнала и в ней запись о том, что МЧД была отправлена на регистрацию.
.. Библиотеки API модуля.

[#inner-links]
== Сведения о связях между составными частями модуля

Модуль отслеживает сообщение о необходимости регистрации, проверки или отзыва МЧД в карточке сообщений. При получении запроса, сервис формирует соответствующее обращение в {kd}. После выполнения запроса в _{log}_ добавляется запись о запросе, и поля карточки xref:system:ROOT:terms.adoc#attorney[СКД] изменяются соответствующим образом.

Действия с доверенностью отслеживаются и могут быть просмотрены через сообщения {of-mc}.

[#outer-links]
== Сведения о связях с другими системами

_{mir}_ является промежуточным звеном в связи системы {dv} с оператором {kd}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций взаимодействия с {cr} через {kd}.

[#formats]
== Форматы доверенности

Модуль поддерживает работу с МЧД следующих форматов:

* Формат единой формы МЧД, версия 002, 003.
* Формат доверенности, подтверждающей полномочия представителя налогоплательщика, версии 5.01, 5.02 и 5.03.

// Система также позволяет хранить собственные разрабатываемые (нестандартные) форматы.

Указанные выше стандартные форматы доверенностей поддерживаются системой по-разному, операции _Регистрации_, _Проверки_ и _Отзыва_ доверенности могут быть поддержаны в разной степени:

.Формат единой формы МЧД, версия 002:
[cols=",,",options="header"]
|===

|Формат / Способ взаимодействия
|002 / 003 (ЕМЧД)
|5.01 / 5.02 / 5.03

|Регистрация
|+
|-


|Проверка
|+
|-


|Отзыв
|+
|-

|===
