= Конфигурация модуля "{wf}" из {of-mc}

[#minimum]
== Необходимые настройки конфигурационного файла

.Фрагмент конфигурационного файла {wf}:
[source,json]
----
{
  "Docsvision": {
    "ServiceId": "00000000-0000-0000-0000-000000000000", <.>
    "SettingsService": {
      "ConnectionString": "http://localhost:5200/api", <.>
      "ApiKey": "anything" <.>
    }
  },
  "AllowedHosts": "*",
  "Kestrel": { <.>
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      }
    }
  }
}
----
<.> `ServiceId` -- уникальный идентификатор данного экземпляра модуля, генерируется и записывается автоматически.
<.> `ConnectionString` -- полный адрес {of-sett-serv}.
<.> `ApiKey` -- API-ключ для подключения к {to-sett-serv}, можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {sett-serv} и {wf} были одинаковые.
<.> Опционально. Настройка доступа к Storage Server по HTTPS, см. подробнее xref:new-admin-console@platform:console:https-access.adoc[] в документации модуля {pl}.

[#console]
== Указание настроек из {of-mc}

. Заполните настройки модуля {wf} в разделе menu:Серверы[Имя сервера > {wf} > "xref:dev@mgmtconsole:servers:workflow-connection.adoc[Группа настроек "Подключение"]]:
+
* В первую очередь выберите _Сервер приложений_ из раскрывающегося списка.
* Укажите _Имя_ и _Пароль системного пользователя_ СУБП.
* Укажите _Почтовое соединение_, _Почта по умолчанию_, _API-ключ для подключения к серверу_.
* Заполните настройку _Доля процессов_, укажите число, определяющее относительную нагрузку на сервис Workflow от `0` до `1000`. Например, если указать доли `3` и `4` нагрузка на сервис {wfs-new} не обрабатывает БП делится как `43%` на `57%`
* При использовании xref:new-admin-console@engineer:ROOT:account-protection.adoc[шифрования паролей] укажите _Штамп сертификата шифрования паролей_.
+
. В разделе menu:Серверы[Имя сервера > {wf} > "xref:dev@mgmtconsole:servers:workflow-templates.adoc[Группа настроек "Шаблоны"]] выполните установку справочников и шаблонов для БД, назначенной по умолчанию. Выберите строки в таблице и нажмите кнопку *Переустановить*.
