:config: `/usr/lib/docsvision/workflow/appsettings.json`

= Конфигурация модуля "{wf}" из {of-mc}

. {blank}
+
[subs="specialchars,attributes,quotes"]
Если это не было выполнено ранее, убедитесь, что в конфигурационном файле модуля {wf} по адресу {config} указаны необходимиые минимальные настройки, описанные в разделе "xref:./install-other-server.adoc#register-services[Регистрация модулей системы]".
+
. Найдите в {of-mc} раздел menu:Серверы[Имя сервера > {wf} > "xref:dev@mgmtconsole:servers:workflow-connection.adoc[Группа настроек "Подключение"]].
+
. Укажите _Имя_ и _Пароль системного пользователя_ СУБП.
. Выберите _Сервер приложений_ из раскрывающегося списка.
. Нажмите кнопку *Применить* в правом верхнем углу окна Консоли, чтобы применить настройки модуля и перезапустите службу Workflow.
. Укажите _Почтовое соединение_, _Почта по умолчанию_, _API-ключ для подключения к серверу_.
. Заполните настройку _Доля процессов_, укажите число, определяющее относительную нагрузку на сервис Workflow от `0` до `1000`. Например, если указать доли `3` и `4` нагрузка на сервис Workflow, который обрабатывает БП, делится как `43%` на `57%`
. При использовании xref:new-admin-console@engineer:ROOT:account-protection.adoc[шифрования паролей] укажите _Штамп сертификата шифрования паролей_.
. Нажмите кнопку *Применить* в правом верхнем углу окна Консоли, чтобы применить настройки модуля и перезапустите службу Workflow.
. [Опционально] В разделе menu:Серверы[Имя сервера > {wf} > "xref:dev@mgmtconsole:servers:workflow-templates.adoc[Группа настроек "Шаблоны"]] выполните установку справочников и шаблонов для БД, назначенной по умолчанию. Выберите строки в таблице и нажмите кнопку *Переустановить*.
