:page-aliases: install-other-linux.adoc

// tag::no-alias[]
= Установка базовых модулей на Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:./install-server.adoc[установки] модуля {pl}.

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc]
== Установка {wc}а

. Установите пакеты модуля:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-webclient

{os2}::
+
 $ sudo dnf install docsvision-webclient
====
+
. Выполните конфигурацию модуля в файле настроек, подробное описание приведено в документации модуля _{wc}_, раздел "xref:./dvwebclient.adoc[Установка {wc}а]".
+
. Запустите службу {wc}а:
+
 $ sudo systemctl start dvwebclient

[#wc-ext]
== Установка расширения {wc}а для {of-mc}

Расширение {wc}а для {of-mc} необходимо для импорта решений {wc}а в версиях {of-mc} 6.2 и выше, получения списка локализаций и видов карточек, а также загрузки новых значений в базу данных.

:what-mod: {wc}
include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

. Установите серверные компоненты Расширения {wc}а для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-ext-webc-mc

{os2}::
+
 $ sudo dnf install docsvision-ext-webc-mc
====
+
. Запустите расширение:
+
 $ sudo systemctl start docsvision-ext-webc-mc

[#workflow]
== Установка СУБП

. Установите модуль _{wf}_ следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workflow

{os2}::
+
 $ sudo dnf install docsvision-workflow
====
+
. Выполните конфигурацию Службы {ws} в файле настроек, подробное описание приведено в документации модуля _{wf}_, раздел "xref:./dvworkflow.adoc[]".
+
. Запустите службу модуля:
+
 $ sudo systemctl start dvworkflow

[#wf-ext]
== Установка расширения модуля {wf} для {of-mc}

Расширение модуля {wf} для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки модуля {wf} из {of-mc}.

:what-mod: {wf}
include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

. Установите серверные компоненты расширения модуля {wf} для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-docsvision-ext-workflow-mc

{os2}::
+
 $ sudo dnf install docsvision-docsvision-ext-workflow-mc
====
+
. Запустите расширение:
+
  $ sudo systemctl start docsvision-ext-workflow-mc

include::dev@mgmtconsole:admin:install.adoc[tags=register-services]
// end::no-alias[]
