= Установка базовых модулей на Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:install-platform.adoc[установки] модуля {pl}.

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc]
== Установка {wc}а

. Установите пакеты модуля:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-webclient

{os2}::
+
 $ sudo dnf install docsvision-webclient
====
+
. Выполните конфигурацию модуля в файле настроек, подробное описание приведено в документации модуля _{wc}_, раздел "xref:dvwebclient.adoc[Установка {wc}а]".

См. подробнее "xref:dvwebclient.adoc[]".

[#sett-serv]
== Установка Сервиса настроек

. Установите сервис:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-settingsservice

{os2}::
+
 $ sudo dnf install docsvision-settingsservice
====
+
. Выполните конфигурацию сервиса настроек в файле настроек, подробное описание приведено в документации модуля _{mc}_, раздел "xref:dvconsole.adoc#sett-serv[Установка {of-mc}]".

См. подробнее "xref:dvconsole.adoc#settings-service[Установка {of-sett-serv}]".

[#ext-api]
== Установка Сервиса внешнего API {of-mc}

. Установите сервис внешнего API:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-externalapi

{os2}::
+
 $ sudo dnf install docsvision-externalapi
====
+
. Выполните конфигурацию сервиса внешнего API в файле настроек, подробное описание приведено в документации модуля _{mc}_, раздел "xref:dvconsole.adoc#external-api[Установка {of-mc}]".

См. подробнее "xref:dvconsole.adoc#external-api[Установка сервиса внешнего API]".

[#worker]
== Установка Службы {ws}

. Установите модуль Служба {ws} следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workerservice

{os2}::
+
 $ sudo dnf install docsvision-workerservice
====
+
. Выполните конфигурацию Службы {ws} в файле настроек, подробное описание приведено в документации модуля _Служба {ws}_, раздел "xref:dvworkerservice.adoc[]".

См. подробнее "xref:dvworkerservice.adoc[]".

[#manconsole]
== Установка {of-mc}

. Следующей командой установите {mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-managementconsole

{os2}::
+
 $ sudo dnf install docsvision-managementconsole
====
+
. Выполните конфигурацию модуля в файле настроек, подробное описание приведено в документации модуля _{mc}_, раздел "xref:dvconsole.adoc#console[Установка {of-mc}]".

См. подробнее "xref:dvconsole.adoc#console[Установка {of-mc}]".

[#workflow]
== Установка СУБП

. Установите модуль _{wf}_ следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workflow

{os2}::
+
 $ sudo dnf install docsvision-workflow
====
+
. Выполните конфигурацию Службы {ws} в файле настроек, подробное описание приведено в документации модуля _{wf}_, раздел "xref:dvworkflow.adoc[]".

См. подробнее "xref:dvworkflow.adoc[]".

[#start-services]
== Запуск системных служб

. Запустите системные службы для модулей {dv}:
+
 $ sudo systemctl restart dvappserver && sudo systemctl restart dvwebclient && sudo systemctl restart dvsettings && sudo systemctl restart dvexternalapi && sudo systemctl restart dvconsole && sudo systemctl restart dvworkerservice && sudo systemctl restart dvworkflow && sudo systemctl restart dvfileservice
