:page-aliases: install-other-linux.adoc

// tag::no-alias[]
= Установка базовых модулей и расширений на сервер под управлением Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:./install-server.adoc[установки] модуля {pl}.

ifndef::mc62[]
[#webc]
== Установка {wc}а

. Установите пакеты модуля:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-webclient

{os2}::
+
 $ sudo dnf install docsvision-webclient
====

[#workflow]
== Установка СУБП

. Установите модуль _{wf}_ следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workflow

{os2}::
+
 $ sudo dnf install docsvision-workflow
====
endif::mc62[]

[#extensions-linux]
== Установка расширений модулей для {of-mc} на сервер под управлением Linux

include::dev@mgmtconsole:admin:install.adoc[tags=extensions]

[WARNING]
====
При первичном обновлении расширения устанавливаются автоматически, при последующих обновлениях расширения необходимо обновлять отдельно, в соответствии с версиями модулей, к которым они относятся.
====

include::dev@mgmtconsole:admin:install.adoc[tags=extensions-linux]

include::dev@mgmtconsole:admin:install.adoc[tags=register-services]

[#start-services]
== Запуск системных служб

. Запустите системные службы для модулей {dv}:
+
 $ sudo systemctl start dvappserver && sudo systemctl start dvwebclient && sudo systemctl start dvsettings && sudo systemctl start dvconsole && sudo systemctl start dvworkerservice && sudo systemctl start dvworkflow && sudo systemctl start dvfileservice

// end::no-alias[]
