= Установка базовых модулей на Linux

Данный раздел описывает установку базовых модулей для ОС Linux. Все описанные ниже команды необходимо выполнять после завершения xref:install-platform.adoc[установки] модуля {pl}.

При установке модулей {dv} в ОС Linux разделение на серверную и клиентскую части отсутствует. Установка выполняется описанными ниже командами, другие базовые модули будут установлены автоматически.

[#webc]
== Установка {wc}а

. Установите пакеты модуля:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-webclient

{os2}::
+
 $ sudo dnf install docsvision-webclient
====
+
. Выполните конфигурацию модуля в файле настроек, подробное описание приведено в документации модуля _{wc}_, раздел "xref:dvwebclient.adoc[Установка {wc}а]".
+
. Запустите службу {wc}а:
+
 $ sudo systemctl start dvwebclient

[#sett-serv]
== Установка Сервиса настроек

. Установите сервис:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-settingsservice

{os2}::
+
 $ sudo dnf install docsvision-settingsservice
====
+
. Выполните конфигурацию сервиса настроек в файле настроек, подробное описание приведено в документации модуля _{mc}_, раздел "xref:dvconsole.adoc#sett-serv[Установка {of-mc}]".
+
. Запустите сервис:
+
 $ sudo systemctl start dvsettings

[#ext-api]
== Установка Сервиса внешнего API {of-mc}

Установка Сервиса внешнего API не требуется в версиях {of-mc} 6.2 и выше.

[#ws-ext]
== Установка расширения Службы {ws} для {of-mc}

. Расширение Службы {ws} для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-docsvision-ext-ws-mc

{os2}::
+
 $ sudo dnf install docsvision-docsvision-ext-ws-mc
====
+
. Запустите Расширение Службы {ws} для {of-mc}:
+
 $ sudo systemctl start docsvision-ext-ws-mc

[#pl-ext]
== Установка расширения сервера приложений для {of-mc}

Расширение сервера приложений для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки Сервера приложений из {of-mc}.

:what-mod: {pl}
include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

. Установите серверные компоненты расширения Сервера приложений для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-docsvision-ext-platform-mc

{os2}::
+
 $ sudo dnf install docsvision-docsvision-ext-platform-mc
====
+
. Запустите Расширение Службы {ws} для {of-mc}:
+
 $ sudo systemctl start docsvision-ext-platform-mc

[#wc-ext]
== Установка расширения {wc}а для {of-mc}

Расширение {wc}а для {of-mc} необходимо для импорта решений {wc}а в версиях {of-mc} 6.2 и выше, получения списка локализаций и видов карточек, а также загрузки новых значений в базу данных.

:what-mod: {wc}
include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

. Установите серверные компоненты Расширения {wc}а для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-ext-webc-mc

{os2}::
+
 $ sudo dnf install docsvision-ext-webc-mc
====
+
. Запустите Расширение Службы {ws} для {of-mc}:
+
 $ sudo systemctl start docsvision-ext-webc-mc

[#wf-ext]
== Установка расширения модуля {wf} для {of-mc}

Расширение модуля {wf} для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки модуля {wf} из {of-mc}.

:what-mod: {wf}
include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

. Установите серверные компоненты расширения модуля {wf} для {of-mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-docsvision-ext-workflow-mc

{os2}::
+
 $ sudo dnf install docsvision-docsvision-ext-workflow-mc
====
+
. Запустите Расширение Службы {ws} для {of-mc}:
+
  $ sudo systemctl start docsvision-ext-workflow-mc

[#manconsole]
== Установка {of-mc}

. Следующей командой установите {mc}:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-managementconsole

{os2}::
+
 $ sudo dnf install docsvision-managementconsole
====
+
. Выполните конфигурацию модуля в файле настроек, подробное описание приведено в документации модуля _{mc}_, раздел "xref:dvconsole.adoc#console[Установка {of-mc}]".
+
. Запустите службу:
+
 $ sudo systemctl start dvconsole
+
. Теперь вы можете открыть Консоль управления из браузера по адресу `\http://console.domain.com:5100`
+
NOTE: При авторизации укажите имя в формате `user@domain.com`, вариант `domain\user` не работает.

[#worker]
== Установка Службы {ws}

. Установите модуль Служба {ws} следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workerservice

{os2}::
+
 $ sudo dnf install docsvision-workerservice
====
+
. Выполните конфигурацию Службы {ws} в файле настроек, подробное описание приведено в документации модуля _Служба {ws}_, раздел "xref:dvworkerservice.adoc[]".
+
. Запустите службу модуля:
+
 $ sudo systemctl start dvworkerservice

[#workflow]
== Установка СУБП

. Установите модуль _{wf}_ следующей командой:
+
[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-workflow

{os2}::
+
 $ sudo dnf install docsvision-workflow
====
+
. Выполните конфигурацию Службы {ws} в файле настроек, подробное описание приведено в документации модуля _{wf}_, раздел "xref:dvworkflow.adoc[]".
+
. Запустите службу модуля:
+
 $ sudo systemctl start dvworkflow
