= Структура модуля {mc}

[subs="specialchars,attributes,quotes"]
_{mc}_ -- веб-приложение, в котором функции сервера реализует служба {wacs-new}, а клиента -- веб-браузер пользователя.

Подключение к Консоли управления может выполняться по протоколу HTTP или HTTPS. В рабочей среде рекомендуется использовать HTTPS, так как модуль предназначен для администрирования системы, взаимодействует с такими конфиденциальными данными, как параметры подключения и учетные данные. Компрометация доступа к {of-mc} может привести к необратимым последствиям.

{mc} получает сведения о конфигурациях сервисов системы из {of-sett-serv}. {sett-serv} -- отдельный сервис {dv}, предназначенный для хранения настроек компонентов системы.

.В Сервисе настроек хранятся:
* Собственные настройки {of-mc}.
* Настройки сервисов и функций {dv}, управляемых с помощью {of-mc}.
* Регистрационные данные компонентов {dv}.

Настройки компонентов, хранимых в Сервисе настроек, изменяются через {mc} и используются соответствующими компонентами {dv}.

Для защиты данных {mc} также поддерживает работу с внешними хранилищами секретов для размещения конфиденциальных данных, тогда {sett-serv} будет хранить только указатели на секреты.

Содержимое {of-sett-serv} размещается в отдельной БД для {of-sett-serv}.

Сформированная пользователем конфигурация для компонентов {dv} сохраняется в {sett-serv} с исполняемым процессом `XXX.Service.exe`. Системные службы компонентов {dv} при перезапуске запрашивают настройки из {of-sett-serv}. Для чтения настроек используется REST API.

Возможность настройки компонентов предоставляют _Расширения консоли управления для модулей системы_. Расширения добавляют связанные с модулями ресурсы локализации, обработчики, специализированные редакторы, необходимые для администрирования соответствующих компонентов. В список расширений входят:

* Расширение консоли управления для модулей {pl} и {fs} {pl-cu-mc}.
* Расширение консоли управления для {wc}а {wc-cu-mc}.
* Расширение консоли управления для модуля {wf} {wf-cu-mc}.
* Расширение консоли управления для Службы {ws} {worker-cu-mc}.

_Виджеты_ и _Информационные страницы_ {of-mc} получают статистические данные об обработке сообщений Службой {ws} из системы {dv}.

{mc} получает информацию о сообщениях с ошибками или блокировками карточек {dv} через карточки сообщений Службы {ws}. Полученная информация отображается в пользовательском интерфейсе и позволяет администратору контролировать нагрузку на Службу {ws}.

{mc} также позволяет контролировать количество онлайн и офлайн сессий, а также отслеживать общее количество использованных и доступных лицензий.