= Структура модуля {mc}

[subs="specialchars,attributes,quotes"]
_{mc}_ -- является веб-приложением, в котором функции сервера реализует служба {wacs-new}, а клиента -- веб-браузер пользователя.

Подключение к Консоли управления может выполняться по протоколу HTTP или HTTPS. В рабочей среде рекомендуется использовать HTTPS, так как модуль предназначен для администрирования системы, взаимодействует с такими конфиденциальными данными как параметры подключения и учетные данные. Компрометация доступа к {of-mc} может привести к потере системы.

{mc} получает сведения о конфигурациях сервисов системы из {of-sett-serv}. {sett-serv} -- отдельный сервис {dv}, предназначенный для хранения настроек компонентов системы.

.В "Сервисе настроек" хранятся:
* Собственные настройки "{of-mc}".
* Настройки сервисов и функций {dv}, управляемых с помощью "{of-mc}".

Для защиты данных {mc} также поддерживает работу с внешними хранилищами секретов. {mc} может использоваться для хранения значений секретов, тогда {sett-serv} будет хранить только указатели на секреты.

Содержимое _{of-sett-serv}_ размещается в подключенной к системе БД.

. Пользователи работают с Консолью настройки с помощью веб-браузера. Запросы обрабатываются веб-приложением. Используется протокол подключения `HTTP`.
. Сформированная пользователем конфигурация для Службы {ws} сохраняется в _{sett-serv}_ с исполняемым процессом `XXX.Sevice.exe`. Для записи настроек используется REST API.
+
Возможность настройки Службы {ws} предоставляет _Расширение для работы со Службой {ws}_.
+
. Служба {ws} при первом запуске запрашивает новые настройки из _{of-sett-serv}_. Для чтения настроек используется REST API.
. _Виджеты_ и _Информационные страницы_ получают статистические данные об обработке сообщений Службой {ws} из системы {dv}. Для получения данных используются карточки Сообщений Службы {ws}. Полученная информация отображается в пользовательском интерфейсе.
