= Структура модуля {mc}

_{mc}_ -- является веб-приложением, в котором функции сервера реализует служба *{wacs-new}*, а клиента -- веб-браузер пользователя.

{mc} включает два основных компонента: сервер {of-mc} и Сервис внешнего API.

Сервер {of-mc} предоставляет точку подключения пользователей (по протоколу `HTTP`) и обеспечивает работу графического интерфейса.

Сервис внешнего API обеспечивает взаимодействие {of-mc} с сервером {dv}, получение сообщений и списков сообщений.

. Пользователи работают с Консолью настройки с помощью веб-браузера. Запросы обрабатываются веб-приложением. Используется протокол подключения `HTTP`.
. Сформированная пользователем конфигурация для Службы {ws} сохраняется в xref:settings-service::index.adoc[{sett-serv}] с исполняемым процессом `XXX.Sevice.exe`. Для записи настроек используется REST API.
+
Возможность настройки Службы {ws} предоставляет _Расширение для работы со Службой {ws}_.
+
. Служба {ws} при первом запуске запрашивает новые настройки из _{of-sett-serv}_. Для чтения настроек используется REST API.
. _Виджеты_ и _Информационные страницы_ получают статистические данные об обработке сообщений Службой {ws} из системы {dv}. Для получения данных используются карточки Сообщений Службы {ws}. Полученная информация отображается в пользовательском интерфейсе.
