:pool: "DocsvisionSitePool"
:def: Default Web Site

= Изменить порт подключения {wc}а

По умолчанию {wc} работает по протоколу HTTP, использующему порт `5004`. Администратор может установить новый порт для доступа к {wc}.

Также администратору доступна возможность настроить подключение по протоколу HTTPS, см. "xref:dv6@engineer:ROOT:https-connection.adoc[]" в руководстве по настройке системы.

.Чтобы изменить порт доступа к {wc}у:
. Откройте конфигурационный файл {wc}а по адресу `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows при помощи любого текстового редактора.
. Укажите порт доступа к {wc}у в параметре menu:Kestrel[Endpoints > Http > Url].
+
[source,json]
----
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://*:5004" <.>
      }
    }
  }
}
----
<.> Укажите адрес и порт подключения к {wc}у.
+
Не забудьте открыть порт и создать правила, открывающие новые TCP порты для входящих и исходящих подключений.
+
****
.Чтобы запустить {wc} в ОС Linux на порту `443` (или любом ином, не превышающем `1024`), должно соблюдаться хотя бы одно из условий:
. Сервис должен запускаться с правами суперпользователя (ROOT).
. Должно запускаться ядро, позволяющее непривилегированным пользователям связывать порты:
+
[source]
----
net.ipv4.ip_unprivileged_port_start=1
----
+
. Должны быть изменены параметры запуска сервиса:
+
[source]
----
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE
----
****
+
. Сохраните изменения конфигурационного файла.
+
:wcs-new: *dvwebclient* для Linux и *{wcs-win}* для Windows
include::dv6@system:ROOT:partial$restart-wcs.adoc[]
+
. После изменения порта подключения распространите новые настройки на все клиентские машины.
