= Настройка запроса на перенос срока исполнения заданий

В {wc}е версии {wc-change-deadline-req} исполнитель задания может создать запрос на перенос срока исполнения после предварительной настройки.

Ниже настройка приведена на примере заданий menu:Задание УД[На исполнение] и menu:Задание УД[На ознакомление].

.Чтобы сотрудники могли работать с запросами на перенос срока исполнения:
. Откройте _Конструктор состояний_. Выберите _Библиотеку карточек_ "Базовые объекты" и _Вид карточки_ menu:Задание УД[На исполнение] и menu:Задание УД[На ознакомление] на панели конструктора.
. Сделайте доступной операцию редактирования _Запрос изменения срока_ и, при необходимости, _Изменение срока исполнения_ в требуемых состояниях.
. Откройте _Конструктор ролей_. Выберите _Библиотеку карточек_ "Базовые объекты" и _Вид карточки_ menu:Задание УД[На исполнение] и menu:Задание УД[На ознакомление] на панели конструктора.
. На вкладке _Роли_ добавьте роли, для которых должна быть доступна возможность запросить перенос сроков исполнения. Также настройте условия, при которых будут доступна операция.
. На вкладке _Матрица доступа_ выполните настройки для:
+
* Создания и отзыва запроса.
* Принятия и отклонения запроса.
+
. Добавьте на разметки заданий элемент управления "xref:layouts:ctrl/special/executionDateChangeRequestInfo.adoc[Запрос изменения срока исполнения]".
