= Автоматически закрывать неактивные сессии пользователей

{wc} автоматически переводит в офлайн-режим сессии (подключение к серверу {dv}) неактивных пользователей. При этом у пользователей появится предупреждение о переводе сессии в офлайн. Впоследствии неактивные сессии будут закрыты. Таймер закрытия сессии запускается одновременно с переходом в офлайн-режим.

[NOTE]
====
После перевода пользовательской сессии в офлайн-режим или её закрытия будет остановлено автоматическое обновление счетчиков непрочитанных карточек и содержимого папок.
====

// tag::webconfig[]
.Чтобы изменить стандартные настройки сессии пользователей:
. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Производительность"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-performance.adoc#user-sessions[Пользовательских сессий]" и настройте следующие параметры:
+
* Оффлайн режим после паузы, мин
* Закрытие сессии после паузы, мин
* Показывать сообщение о переходе в оффлайн
+
. Сохраните изменения.
// end::webconfig[]

WARNING: Неактивные сессии не закрываются, если параметр "xref:clear-cache-config.adoc[DisableClearSession]" установлен в значении `true`.
