= Особенности настройки кластера {wc}

С целью повышения отказоустойчивости и распределения нагрузки, администратор может объединить несколько экземпляров модуля {wc} в кластер.

[#conditions]
== Обязательные условия для работы кластера

* Каждый экземпляр {wc}а должен иметь уникальный адрес подключения.
* Балансировщик нагрузки должен передавать заголовок X-Forwarded-Proto.

[#preparation]
=== Подготовка узлов кластера

.Чтобы подготовить узлы кластера {wc}а к работе:
// . xref:install-server.adoc#windows[Установите] серверное расширение {wc} на машине с Windows.
. xref:install-server.adoc#linux[Установите и настройте] модуль {wc} на первом компьютере кластера Linux.
. xref:install-server.adoc#linux[Установите и настройте] Web-клиент на последующих узлах кластера Linux.
. Настройте балансировщик нагрузки.

[#create-cert]
=== Сгенерируйте отпечаток

// tag::webconfig[]
. Если {wc} использует HTTPS, создайте сертификат с помощью OpenSSL. Пример использования утилиты приведён в разделе администрирования модуля {mc}: "xref:engineer:ROOT:create-cert.adoc[]".
. Установите и настройте {wc} на втором компьютере кластера (далее -- *УЗЕЛ 2*).
+
WARNING: Экземпляр {wc}а, установленный на втором и последующих узлах кластера, должен быть настроен на работу с теми же сервером и базой данных {dv}, что и УЗЕЛ 1.
+
// tag::webconfig[]
. В конфигурационном файле `{webconfig}` на УЗЛЕ 1 укажите путь к полученному сертификату в элементе `"Https":` (`"Http":`, если используется незащищённое соединение). Фрагмент конфигурационного файла приведён ниже:
+
[source,json]
----
"Https": {
  "Url": "https://*:5005",
  "Certificate": {
    "Path": "/home/user/certificate.pfx", <.>
    "Password": "password" <.>
    }
  }
----
<.> Путь к сертификату
<.> Пароль от сертификата
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сгенерируйте сертификат на втором узле.
. Откройте конфигурационный файл `{webconfig}` на УЗЛЕ 2 и укажите путь к полученному сертификату.
. Повторите шаги инструкции для третьего и последующих узлов кластера {wc}а.
// end::webconfig[]

См. также *xref:dvweb-cluster.adoc[Настройка утилиты DVWebTool для работы в кластере]*.
