= Управление временем жизни пользовательских cookie

Управлять временем действия пользовательской сессии можно с помощью настроек в модуле {mc}:

// tag::webconfig[]
. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Сайт"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-site.adoc#pechenkies[Пользовательские cookie]" и настройте следующие параметры:
+
* Интервал автоматического обновления сессии, ч
* Период действия пользовательской сессии, ч
* Период действия пользовательской сессии на мобильных устройствах, ч
// end::webconfig[]

.Принцип действия настроек:
. Настройка `Интервал автоматического обновления сессии, ч` позволяет продлевать срок уже выданных cookie, если пользователь зашёл до того, как они истекли.
+
По умолчанию настройка отключена, то есть установлена в значение `0`. Можно задать количество часов.
+
Когда пользователь авторизуется в {wc}е, ему по умолчанию выдаются cookie на 5 дней. Если в настройке указано значение `24` часа, действие cookie будет продлено, когда пользователь откроет {wc}. Настройка сработает только если пользователь откроет {wc} в промежутке между указанным временем и сроком истечения сессии.
+
. Настройка `Период действия пользовательской сессии, ч` устанавливает период действия пользовательской сессии. Значение по умолчанию: `120` часов (5 дней).
. Настройка `Период действия пользовательской сессии на мобильных устройствах, ч` отдельно задаёт период действия пользовательской сессии на мобильных устройствах. Значение по умолчанию: `120` часов (5 дней).

Настройки можно комбинировать. Например, задать для `Период действия пользовательской сессии, ч` значение `240` часов, чтобы все пользователи получали cookie на 10 дней. Для настройки `Период действия пользовательской сессии на мобильных устройствах, ч` можно указать период в `720` часов (30 дней). А также установить значение `Интервал автоматического обновления сессии, ч` на `72` часа. Когда пользователь откроет {wc} по прошествии трёх дней с предыдущей авторизации, cookie автоматически будут продлены.
