:do-what: варианты настройки порядка кнопок:
:link: webclient-interface.adoc[Группа настроек "Интерфейс"]

= Порядок кнопок "ОК/Отмена" по умолчанию

include::partial$mancons.adoc[]

// tag::webconfig[]
Порядок кнопок *ОК*/*Сохранить* и *Отмена*, отображаемых в диалоговых окнах и разметках {wc}а, может быть настроен. Пользователь может настроить схему расположения в меню _Профиль_. Администратор может установить порядок расположения по умолчанию, который будет действовать до выбора нового значения пользователем.

. Откройте конфигурационный файл `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `DefaultButtonPosition`:
+
.Включение режима "Отмена/ОК"
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "DefaultButtonPosition": "Auto" <.>
        }
      }
    }
  }
}
----
<.> Возможные значения:
+
* `Auto` -- значение по умолчанию -- порядок отображения кнопок определяется типом ОС пользователя. +
Для ОС MacOS: *Отмена*/*OK*. +
Для ОС Windows, Linux, Android и др. -- *ОК*/*Отмена*
* `OkCancel` -- *ОК*/*Отмена*
* `CancelOk` -- *Отмена*/*ОК*
// end::webconfig[]
. Сохраните изменения конфигурационного файла.
+
include::partial$excerpts.adoc[tags=ifabsent]
