= Порядок кнопок "ОК/Отмена" по умолчанию

// tag::webconfig[]
Порядок кнопок *ОК*/*Сохранить* и *Отмена*, отображаемых в диалоговых окнах и разметках {wc}а, может быть настроен. Пользователь может настроить схему расположения в меню _Профиль_. Администратор может установить порядок расположения по умолчанию, который будет действовать до выбора нового значения пользователем.

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два варианта настройки порядка кнопок:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-interface.adoc[Группа настроек "Интерфейс"]"
****

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `DefaultButtonPosition`:
+
.Включение режима "Отмена/ОК"
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "DefaultButtonPosition": "Auto" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `Auto` -- значение по умолчанию -- порядок отображения кнопок определяется типом ОС пользователя. +
Для ОС MacOS: *Отмена*/*OK*. +
Для ОС Windows, Linux, Android и др. -- *ОК*/*Отмена*
* `OkCancel` -- *ОК*/*Отмена*
* `CancelOk` -- *Отмена*/*ОК*
// end::webconfig[]
. Сохраните изменения конфигурационного файла.
