:do-what: варианты настройки удаления карточек и папок:
:link: webclient-interface.adoc#other[Группа настроек "Интерфейс"]

= Изменить способ удаления карточек и папок

По умолчанию карточки из {wc}а удаляются в корзину, папки удаляются временно, но в корзину не попадают. Администратор может включить режим удаления без возможности восстановления.

[NOTE]
====
Восстановить удалённые карточки и папки можно только в {wincl}е.
====

include::partial$mancons.adoc[]

// tag::webconfig[]
. Откройте конфигурационный файл `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `DeletePermanently`:
+
.Удалённые карточки будут помещаться в корзину, папки будут удаляться временно
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "DeletePermanently": "false" <.>
        }
      }
    }
  }
}
----
<.> Возможные значения:
+
* `True` -- отключает использование корзины, папки и карточки удаляются безвозвратно.
* `False` -- удалённые карточки помещаются в корзину, папки удаляются временно (значение по умолчанию).
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
