= Изменить способ удаления карточек и папок

По умолчанию карточки из {wc}а удаляются в корзину, папки удаляются временно, но в корзину не попадают. Администратор может включить режим удаления без возможности восстановления.

[NOTE]
====
Восстановить удалённые карточки и папки можно только в {wincl}е.
====

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два варианта настройки удаления карточек и папок:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-interface.adoc#other[Группа настроек "Интерфейс"]"
****

// tag::webconfig[]
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `DeletePermanently`:
+
.Удалённые карточки будут помещаться в корзину, папки будут удаляться временно
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "DeletePermanently": "false" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `True` -- отключает использование корзины, папки и карточки удаляются безвозвратно.
* `False` -- удалённые карточки помещаются в корзину, папки удаляются временно (значение по умолчанию).
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
