= Изменить логотип для штампа ЭП

По умолчанию в печатной версии подписанного файла, в штампе ЭП размещается логотип "Щит". Администратор может изменить изображение.

include::partial$excerpts.adoc[tags=ifabsent]

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два варианта настройки логотипа штампа ЭП:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-signature.adoc#stamp[Штамп ЭП]"
****

// tag::webconfig[]
.Чтобы изменить логотип для штампа ЭП:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps} > "DefaultESImageGenerator"].
. Измените значение параметра `LogoImagePath`, указав путь к PNG файлу нового логотипа (относительно каталога `{wcd}/` или абсолютный).
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "DefaultESImageGenerator": {
          "LogoImagePath": "Content/logo.png"
        }
      }
    }
  }
----
// end::webconfig[]
+
Файл логотипа должен быть доступен процессу сервера {wc}а. Размер стандартного изображения: 127x131 пискелей. Изображение будет сжато в соответствии с фактическим размером штампа.
+
. Сохраните изменения конфигурационного файла.

[NOTE]
====
Предусмотрена возможность реализации собственной функции формирования штампа. Пример реализации см. в https://github.com/Docsvision/WebClient-Samples[репозитории "ДоксВижн" на GitHub].
====
