:do-what: варианта настройки логотипа штампа ЭП
:link: webclient-signature.adoc#stamp[Штамп ЭП]

= Изменить логотип для штампа ЭП

По умолчанию в печатной версии подписанного файла, в штампе ЭП размещается логотип "Щит". Администратор может изменить изображение.

include::partial$excerpts.adoc[tags=ifabsent]

include::partial$mancons.adoc[]

// tag::webconfig[]
.Чтобы изменить логотип для штампа ЭП из конфигурационного файла:
. Откройте конфигурационный файл `{webconfig-lin}`.
. Перейдите к секции {cnf-sgrps} > "DefaultESImageGenerator"].
. Измените значение параметра `LogoImagePath`, указав путь к PNG файлу нового логотипа (относительно каталога `{wcd-lin}/` или абсолютный).
+
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "DefaultESImageGenerator": {
          "LogoImagePath": "Content/logo.png"
        }
      }
    }
  }
}
----
// end::webconfig[]
+
Файл логотипа должен быть доступен процессу сервера {wc}а. Размер стандартного изображения: 127x131 пискелей. Изображение будет сжато в соответствии с фактическим размером штампа.
+
. Сохраните изменения конфигурационного файла.
+
include::partial$excerpts.adoc[tags=ifabsent]
+
Предусмотрена возможность реализации собственной функции формирования штампа. Пример реализации см. в https://github.com/Docsvision/WebClient-Samples[репозитории "ДоксВижн" на GitHub].
