= Кэширование обращений к справочникам и карточкам

При обращении к справочникам и карточкам {wc} может использовать два режима обновления объектов:

* `ShortCacheRefreshPeriod` -- короткий период обновления кэша.
* `LongCacheRefreshPeriod` -- длительный период обновления кэша.

Короткий период обновления позволяет повысить производительность при обращении к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя. Настроить поведение можно в {of-mc}.

// tag::webconfig[]
.Чтобы настроить период обновления, укажите значения в секундах:
. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Производительность"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-performance.adoc#caching[Кэширования]" и настройте следующие параметры:
+
* Короткий период обновления кэша
* Длительный период обновления кэша
// Для папок используется `ShortCacheRefreshPeriod`. `LongCacheRefreshPeriod` -- пока не используется.
// end::webconfig[]
