= Кэширование обращений к справочникам и карточкам

При обращении к справочникам и карточкам {wc} может использовать два режима обновления объектов:

* `ShortCacheRefreshPeriod` -- короткий период обновления кэша.
* `LongCacheRefreshPeriod` -- длительный период обновления кэша.

Короткий период обновления позволяет повысить производительность при обращении к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя.

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два варианта настройки кэширования обращений к справочникам и карточкам:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-performance.adoc#caching[Кэширование]"
****

// tag::webconfig[]
.Чтобы настроить период обновления, укажите значения в секундах:
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "System": {
          "ShortCacheRefreshPeriod": "600" <.>
          "LongCacheRefreshPeriod": "14400" <.>
        }
      }
    }
  }
----
<.> Короткий период обновления кэша и данных в разметке профиля пользователя.
<.> Длительный период обновления кэша и данных в разметке профиля пользователя.

Для папок используется `ShortCacheRefreshPeriod`. `LongCacheRefreshPeriod` -- пока не используется.
// end::webconfig[]
