= Функциональность "Общие справочники"

Данная функциональность включает особый режим работы со справочниками, данные которых используются только в режиме чтения.

Функциональность по умолчанию активна для {wc}а, начиная с версии 17.

Использование функциональности _Общие справочники_ призвано сократить потребление памяти процессом сервера {dv}.

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два варианта настройки функциональности "Общие справочники":

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-performance.adoc#dir-cache[Кэширование]"
****

[#change-mode]
== Изменить способ обновления справочников в режиме "только чтение"

{wc} использует справочники, данные которых только читаются и не изменяются, в режиме "только чтение". В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках {wc}.

Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновления ведёт к увеличению числа обращений с северу {dv}, а уменьшение -- к возможности получения устаревших данных.

// tag::webconfig[]
.Чтобы изменить способ обновления справочников:
. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Производительность"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-performance.adoc#dir-cache[Кэширования]" и настройте следующие параметры:
+
* Режим обновления справочников
* Интервал обновления справочников, сек
// end::webconfig[]
+
. Сохраните изменения.
