:do-what: варианта настройки кэширования обращений к справочникам и карточкам
:link: servers:webclient-performance.adoc#caching[Кэширование]

= Кэширование обращений к справочникам и карточкам

При обращении к справочникам и карточкам {wc} может использовать два режима обновления объектов:

* `ShortCacheRefreshPeriod` -- короткий период обновления кэша.
* `LongCacheRefreshPeriod` -- длительный период обновления кэша.

Короткий период обновления позволяет повысить производительность при обращении к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя.

include::partial$mancons.adoc[]

// tag::webconfig[]
.Чтобы настроить период обновления из конфигурационного файла, укажите значения в секундах:
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "System": {
          "ShortCacheRefreshPeriod": "600", <.>
          "LongCacheRefreshPeriod": "14400" <.>
        }
      }
    }
  }
----
<.> Короткий период обновления кэша и данных в разметке профиля пользователя.
<.> Длительный период обновления кэша и данных в разметке профиля пользователя.

.Настройка `ShortCacheRefreshPeriod` используется для:
* Карточки папок
* Справочника видов
* Конструктора справочников
* Справочника сотрудников
* Справочника контрагентов
* Справочника категорий

.Настройка `LongCacheRefreshPeriod` используется для:
* Всего остального, включая справочник разметок
// end::webconfig[]

include::partial$excerpts.adoc[tags=ifabsent]