= Отключить создание карточек определённого типа

В случае необходимости, администратор системы может отключить возможность создания из {wc}а карточек определённого типа. Когда функция отключена, соответствующий тип карточек будет скрыт из списка доступных для создания типов карточки вместе с подвидами:

* При нажатии кнопки *+ Создать* на панели управления.
* При создании карточки с добавлением ссылки из карточек _Документ_ и _Задание_.

// tag::webconfig[]
. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Интерфейс"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-interface.adoc#appearance[Внешний вид]" и отредактируйте параметр:
+
* Типы карточек, отображаемые в диалоге создания
// end::webconfig[]
+
. Сохраните изменения.

****
Чтобы отключить любую возможность создания карточки _Группа заданий_ из {wc}а, укажите значение *_15_* (= 1+2+4+8). Чтобы скрыть тип карточки _Документ_ из списка типов при создании новой карточки, укажите значение `1`.

WARNING: Параметр `DisableCreateFlags` не действует, когда меню создания карточки вызывается из настраиваемой разметки.
****
