= Подписание без скачивания файла

По умолчанию подписываемый файл не скачивается в браузер для последующего использования, вместо этого скачивается только хэш подписываемого файла. Поведение по умолчанию может быть изменено администратором системы при помощи изменения параметра `CalculateSignatureHashOnServer` в конфигурационном файле {wc}.

WARNING: Изменение поведения по умолчанию может увеличить время, необходимое для подписания, особенно при подписании файлов большого размера.

// tag::webconfig[]
.Чтобы изменить режим скачивания подписи:
. Откройте конфигурационный файл, расположенный по адресу `{webconfig-lin}`.
. Перейдите к разделу {cnf-sgrps-wc}].
. Измените значение параметра `CalculateSignatureHashOnServer` с `true` на `false`.
+
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "CalculateSignatureHashOnServer": true <.>
        }
      }
    }
  }
}
----
<.> `true` -- скачивается только хэш подписываемого файла (значение по умолчанию), `false` -- будет скачиваться полностью подписываемый файл (устаревшее поведение).
+
[NOTE]
====
* Если алгоритм подписания не поддерживается или не установлены xref:ROOT:requirements-signature.adoc[необходимые компоненты КриптоПро], действует стандартная логика подписания со скачиванием файла в браузер.
* В данный момент подписание без скачивания файла не действует с облачной подписью.
====
// end::webconfig[]
