:do-what: способы изменить режим скачивания подписи
:link: webclient-files.adoc#stamp[Группа настроек "Электронная подпись"]

= Подписание без скачивания файла

Активация настройки позволяет не скачивать подписываемый файл в браузер для последующего использования, вместо этого скачиваться будет только хэш подписываемого файла.

include::partial$mancons.adoc[]

Настройка по умолчанию активирована (установлена в значение `true`) для {wc} версии 6.1, {hash-rq}. Для работы настройки потребуется наличие библиотеки КриптоПро .NET с соответствующей лицензией на сервере {wc}а, см. подробнее "xref:ROOT:requirements-software.adoc[]". При отсутствии библиотеки работает прежнее поведение -- будет скачиваться файл.

Библиотека КриптоПро .NET ПО ускоряет формирование подписи, особенно при подписании файлов большого размера. При необходимости администратор может отключить оптимизацию при помощи параметра `CalculateSignatureHashOnServer` в конфигурационном файле {wc}а.

[NOTE]
====
* Если алгоритм подписания не поддерживается, действует стандартная логика подписания со скачиванием файла в браузер.
* В данный момент подписание без скачивания файла не действует с облачной подписью.
====

// tag::webconfig[]
.Чтобы отключить поведение по-умолчанию:
. Откройте конфигурационный файл, расположенный по адресу `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows.
. Перейдите к разделу {cnf-sgrps-wc}].
. Измените значение параметра `CalculateSignatureHashOnServer` с `true` на `false`.
+
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "CalculateSignatureHashOnServer": true <.>
        }
      }
    }
  }
}
----
<.> Измените значение:
* `false` -- будет скачиваться полностью подписываемый файл (устаревшее поведение, библиотека не требуется).
* `true` -- скачивается только хэш подписываемого файла (значение по умолчанию, требуется библиотека КриптоПро .NET).
// end::webconfig[]
