:do-what: способы изменить режим скачивания подписи
:link: webclient-files.adoc#stamp[Группа настроек "Электронная подпись"]

= Подписание без скачивания файла

По умолчанию подписываемый файл не скачивается в браузер для последующего использования, вместо этого скачивается только хэш подписываемого файла.

include::partial$mancons.adoc[]

Поведение по умолчанию требует наличия библотек КриптоПро .NET с соответствующей лицензией на сервере {wc}а, см. подробнее "xref:ROOT:requirements-software.adoc[]". ПО ускоряет формирование подписи, особенно при подписании файлов большого размера. При необходимости администратор может отключить оптимизацию при помощи параметра `CalculateSignatureHashOnServer` в конфигурационном файле {wc}а.

// tag::webconfig[]
.Чтобы изменить режим скачивания подписи:
. {blank}
+
include::dv6@engineer:ROOT:partial$excerpts.adoc[tags=dll]
+
. Откройте конфигурационный файл, расположенный по адресу `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows.
. Перейдите к разделу {cnf-sgrps-wc}].
. Измените значение параметра `CalculateSignatureHashOnServer` с `true` на `false`.
+
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "CalculateSignatureHashOnServer": true <.>
        }
      }
    }
  }
}
----
<.> `true` -- скачивается только хэш подписываемого файла (значение по умолчанию), `false` -- будет скачиваться полностью подписываемый файл (устаревшее поведение).
+
[NOTE]
====
* Если алгоритм подписания не поддерживается,
// или не установлены xref:ROOT:requirements-signature.adoc[необходимые компоненты КриптоПро] на сервере
действует стандартная логика подписания со скачиванием файла в браузер.

* В данный момент подписание без скачивания файла не действует с облачной подписью.
====
// end::webconfig[]
