:do-what: способы отключить кэширование разметок фильтров данных
:link: webclient-performance.adoc#caching[Кэширование]

= Отключить кэширование разметок фильтров данных

По умолчанию {wc} использует серверный кэш для хранения разметок фильтров данных в представлении. Кэш обновляется при перезапуске сервера {wc}, а также автоматически при изменении настроек представления.

Администратору нужно отключить кэширование разметок фильтров, если в {wc}е планируется использовать две или более разметки представлений. Если кэширование не отключено, пользователи могут получать разметки фильтра, не соответствующие условиям выбора разметок, указанным в программе {kvr}.

include::partial$mancons.adoc[]

// tag::webconfig[]
.Чтобы отключить кэширование разметок из конфигурационного файла:
. Откройте конфигурационный файл `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows.
. Перейдите к секции {cnf-sgrps-wc}].
. Измените значение параметра `GridFilterCache` в `false`:
+
--
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "GridFilterCache": "False" <.>
        }
      }
    }
  }
}
----
<.> Возможные значения:
+
* `False` -- кэширование разметок фильтров будет отключено.
* `True` -- значение по умолчанию, кэширование включено.
--
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
