:do-what: способа включить журнал событий навигации
:link: webclient-logging.adoc[Группа настроек "Журналирование"]

= Включить журнал событий навигации

Администратор может включить ведение журнала для записи информации о событиях и последующего анализа ошибок. В лог браузера записывается информация о специальных навигационных обработчиках, передаваемым им параметрах и результатах их работы.

include::partial$mancons.adoc[]

// tag::webconfig[]
.Чтобы включить протоколирование из конфигурационного файла:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps-wc}.
. Измените значение параметра `EnableRouterLogging` на *_True_*:
+
--
.Включение протоколирования событий навигации
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "EnableRouterLogging": "True" <.>
        }
      }
    }
  }
----
<.> Возможные значения:
+
* `True` -- протоколирование событий навигации включено.
* `False` -- значение по умолчанию, протоколирование событий навигации отключено.
--
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
