= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

include::partial$excerpts.adoc[tags=ifabsent]

// tag::webconfig[]
// Базовые настройки журналирования представлены в панели управления (xref:..control-panel-webc.adoc[Раздел "WebClient"]).
Расширенные настройки журналирования осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Измените параметры журналирования в параметрах `targets` и `rules`.
+
[source,json]
----
{
 "NLog": {
     "throwConfigExceptions": false,
     "extensions": [
         { "assembly": "NLog.Extensions.Logging" },
         { "assembly": "NLog.Web.AspNetCore" }
     ],
     "targets": {
         "async": true,
         "logFile": {
             "type": "File",
             "fileName": "${basedir}/../Logs/WebClient${event-properties:item=Tenant} PID ${processId} ${shortdate}.log", <.>
             "layout": "[${longdate}][${level}][${callsite}] ${message} ${onexception:${newline}${exception:maxInnerExceptionLevel=10:format=shortType,message,stacktrace:separator=*:innerExceptionSeparator=&#xD;&#xA;&#x9;}}"
         },
         "logConsole": {
             "type": "Console"
         }
     },
     "rules": [ <.>
         {
             "logger": "Microsoft.*",
             "maxLevel": "Info",
             "final": true
         },
         {
             "logger": "*",
             "minLevel": "Error",
             "writeTo": "logFile" <.>
         },
         {
             "logger": "*",
             "minLevel": "Trace",
             "writeTo": "logConsole" <.>
         }
     ]
 }
}
----
<.> Измените значение параметра `fileName`, чтобы настроить путь для сохранения журнала работы: +
В `fileName` можно использовать https://github.com/nlog/NLog/wiki/File-target[допустимые для NLog переменные], например: `\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
<.> Измените значение параметров `minLevel` и `maxLevel`, например, на `trace`, чтобы включить протоколирование всех типов событий. +
Допустимые уровни протоколирования приведены https://github.com/nlog/NLog/wiki/Configuration-file#log-levels[на странице NLog в GitHub]. +
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
<.> Настройки журнала {wc}а.
<.> Настройки журнала {pu}.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*). Передать уровень журналирования можно, например, при помощи GET-параметра `minLevel`:

 Log/SetLogLevel?minLevel=0

// Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а.
После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====

[#advanced-logging]
== Расширенное журналирование

{wc} поддерживает расширенное журналирование параметров производительности. Сюда входит точное логирование времени выполнения запросов {wc}а, время выполнения запросов к *{sss-new}* с привязкой к запросу {wc}а.

Для настройки доступно три фильтра журнала: По пользователю, По конкретному адресу, По времени запроса.

После включения диагностического логирования можно делать запросы. Если в параметре будет слеш (`\` или `/`), его необходимо переводить в URL код. Иными словами, заменять `example\usr01` на `example%5Cusr01`.

.Для отдельного запроса {wc}а можно посмотреть:
* Какие запросы к *{sss-new}* выполнялись.
* Время, потраченное на выполнение каждого из них.
* Время, проведённое запросами на стороне *{sss-new}* и на стороне {wc}а.
* Параметры запросов.

.Эта информация позволяет:
* Устанавливать причины аномально быстрого или медленного выполнения запроса {wc}а.
* Выявлять ошибки и неоптимальные места в работе {wc}а и Object Manager.
* Обнаруживать блокировки {wc}а и Object Manager.
* Выявлять проблемные запросы на сервере.

Чтобы включить диагностическое логирование, нужно в конфигурационном файле {wc}а для параметра `EnableDiagnosticsLogger` в разделе {cnf-sgrps} > "System"] указать значение `1`:

[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "System": {
          "EnableDiagnosticsLogger": "1" <.>
        }
      }
    }
  }
}
----
<.> Включить расширенное журналирование.

Настроить параметры журналирования можно в конфигурационном файле следующим образом:

[source,json]
----
{
"targets": {
    "async": true,
    "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/webclient/webclient.log",
        "layout": "[${longdate}][${level}][${callsite}] ${message} ${onexception:${newline}${exception:maxInnerExceptionLevel=10:format=shortType,message,stacktrace:separator=*:innerExceptionSeparator=&#xD;&#xA;&#x9;}}"
    },
    "logConsole": {
        "type": "Console"
    },
    "diagnosticsLogWebClient": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/webclient/DiagnosticsLogWebClient${event-properties:item=Tenant} PID ${processId} ${shortdate}.tsv" <.>
    },
    "diagnosticLogStorageServer": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/webclient/DiagnosticLogStorageServer${event-properties:item=Tenant} PID ${processId} ${shortdate}.tsv" <.>
    }
}
}
----
<.> Адрес хранения журнала {wc}а. В параметре важно добавить в имя файла `$\{processId}`, например, `WebCDiagnostics PID$\{processId}.log`, а также указать `layout="$\{message}"`.
<.> Адрес хранения журнала *{sss-new}*. В параметре важно добавить в имя файла `$\{processId}`, например, `WebCDiagnostics PID$\{processId}.log`, а также указать `layout="$\{message}"`.

Журнал ведётся в формате `.tsv` и в дальнейшем может быть проанализирован через приложение для работы с журналами, например Log Parser Studio. Расширенный журнал по умолчанию сохраняется в стандартный каталог журналов {wc}а, но при помощи параметров конфигурации NLog можно записать в иной каталог.

Чтобы включить ведение расширенного журнала с требуемым фильтром, нужно выполнить в браузере запрос. Примеры запросов приведены далее.

[#query-sample]
=== Примеры запросов

. Запрос включения журнала для всех пользователей:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogUser?user=*
+
Журналируются все запросы `example\usr01`:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogUser?user=example%5Cusr01
+
. Запрос включения журнала по адресу:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogAddress?address=Grid%2FGetGridDataEx
+
Журналируются все запросы, в имени которых содержится подстрока `Grid/GetGridDataEx`. При необходимости можно журналировать все запросы конкретного контроллера:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogAddress?address=Grid
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogAddress?address=*
+
. Запрос включения журнала по времени выполнения запросов:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogRequestTime?milliseconds=500
+
. Запрос установки таймера журналирования с указанием времени работы 10 минут:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/SetIntervalTimer?minutes=10
+
.Принцип работы запроса :
[%collapsible%open]
====
Вызов запроса `SetIntervalTimer` не включает журналирование. Для журналирования должен быть указан конкретный фильтр (`AddLogUser`, `AddLogAddress` или `AddLogRequestTime`), который будет вызван до или после запроса `SetIntervalTimer`. Запрос `SetIntervalTimer` может быть выполнен в любой момент до или после установки фильтров. При его выполнении таймер перезапускается. Т.е. если нужно продлить время журналирования, достаточно выполнить этот запрос ещё раз.

Указание таймера в параметре `SetIntervalTimer` не является обязательным, в таком случае журналирование всех запросов по умолчанию будет длиться 1 час. Даже после сброса с помощью `Reset` запроса. Пользовательское значение таймера сбрасывается на значение по умолчанию после перезапуска {wcs-new} (т.е. значение времени таймера хранится в кэше {wc}а).

Время работы таймера отсчитывается с момента последнего запроса к API журналирования.
====
+
. Фильтры можно комбинировать. Ниже приведён пример включения фильтра для пользователя `example\usr01`, адреса `Grid/GetGridDataEx`, времени выполнения запросов `50` мс:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogUser?user=example%5Cusr01
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogAddress?address=Grid%2FGetGridDataEx
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/AddLogRequestTime?milliseconds=50
+
. Чтобы отключить ведение расширенного журнала, нужно выполнить запрос в браузере:
+
[subs=attributes]
 http://адрес-сервера-{wc}а:ПОРТ/DiagnosticsLog/Reset
