= Ограничить максимальный размер файла для предпросмотра

В {wc}е по умолчанию действует ограничение предпросмотра файлов больше 100 Мб.

Администратор системы может изменить действующее ограничение.

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два способа ограничить рмаксимальный размер файла для предпросмотра:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-files.adoc[Группа настроек "Работа с файлами"]"
****

//tag::webconfig[]
.Чтобы изменить ограничение для максимального размера файла для предпросмотра:
. Откройте конифгурационный файл {wc}а: `{webconfig}`.
. В категории настроек {cnf-sgrps-wc}] измените параметр `MaxPreviewFileSize`.
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "MaxPreviewFileSize": "0" <.>
        }
      }
    }
  }
----
<.> Укажите значение в байтах. +
Увеличение значения повысит нагрузку на сервер и время открытия файла на предпросмотр.
//end::webconfig[]
+
. Сохраните изменения конфигурационного файла.