:mo: {wc}
:cu253-mo-req: {cu253-wc-req}, {cu253-pl-req} и других модулей, входящих в обновление

= Настройка {wc}а в сети без Active Directory

{wc} поддерживает подключение к серверу {dv} под системной учётной записью из каталога ALD Pro, xref:install-server.adoc[указанной] в параметрах `SystemUserAccount` и `SystemUserPassword` конфигурационного файла.

include::6.1@engineer:ROOT:partial$excerpts.adoc[tags=ldaps-conditions]

Настройка каталога ALD Pro описана в разделе "xref:6.1@engineer:ROOT:ldaps-without-ad.adoc[]". В конфигурационном файле {wc}а потребуется указать следующие параметры:

[source,json]
----
{
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
  "Docsvision": {
    "WebClient": {
      "Server": {
        "SessionManagerConnection": {
          "ConnectionAddress": "http://dvserver.domain.com:5000", <.>
          "BaseName": "alias" <.>
        }
      }
    }
  }
}
----
<.> Учётная запись из каталога ALD Pro для подключения к серверу {dv}.
<.> Пароль УЗ из каталога ALD Pro для подключения к серверу {dv}.
<.> Адрес сервера {dv}.
<.> Псевдоним БД, от имени которой будут запускаться программы {pu} и {kvr}.

Для работы укажите УЗ из каталога ALD Pro на машине с {kvr} и {pu}:

 setx DV_SystemUserAccount account@domain.com
 setx DV_SystemUserPassword password

Функциональность доступна в {wc} версии {cu253-wc-req} при условии установки версий модулей, входящих в накопительное обновление 25.3.
