= Настройки сканирования с помощью DVSupService

По умолчанию сканирование с помощью ЭУ "xref:layouts:ctrl/special/scanButton.adoc[]" работает только в ОС Windows с помощью программы DVWebtool, чтобы иметь возможность сканировать файлы в ОС Linux, необходимо выполнить дополнительные действия по настройке DVSupService для работы со сканерами с поддержкой SANE. Установка DVSupService описана в разделе "xref:user:prepare-add-components.adoc#dvSupService[Установка и запуск службы DVSupService]".

[#scan-provider]
== Выбор провайдера сканирования

. Откройте {mc} на странице menu:Серверы[Имя сервера > {wc} > Группа настроек "Инструменты"].
. Перейдите к настройкам "xref:dev@mgmtconsole:servers:webclient-tools.adoc#supservice[DVSupService]" и настройте параметр:

* Провайдер сканирования

Если подключено несколько провайдеров, рядом с именем сканера в интерфейсе сканирования карточки будет отображаться название провайдера, чтобы избежать дублирования пунктов.

[#sane]
== Настройка сканирования

На машине с Linux и подключенным сканером необходимо установить компоненты SANE, выполнив в командной строке:

[tabs]
====
Astra Linux::
+
 $ sudo apt install sane

РЕД ОС::
+
 $ sudo dnf install sane

====

Если планируется использовать только провайдер `Naps2Provider`, дополнительные компоненты устанавливать не требуется. Если планируется использовать провайдер `ScanImageProvider`, необходимо установить пакет `sane-utils` командой:

[tabs]
====
Astra Linux::
+
 $ sudo apt install sane sane-utils

РЕД ОС::
+
 $ sudo dnf install sane sane-utils
====
