:update: webclient

= Обновление {wc}а

include::ROOT:partial$excerpts.adoc[tags=what-changed]

[#conditions]
== Условия обновления

* Установка новой версии должна выполняться в нерабочее время.
* Перед установкой обновления ознакомьтесь с требованиями к xref:webclient:ROOT:requirements-dv.adoc[системе] и xref:webclient:ROOT:requirements-software.adoc[программному обеспечению].
* При обновлении версия {wc}а должна равняться версии серверного расширения.
* Для корректной работы данной версии модуля {wc} требуется определённая версия модуля {pl}, требования указаны в пункте "xref:ROOT:requirements-dv.adoc[]".

Режим обновления предназначен для установки новой версии {wc}а без удаления существующей версии.

При обновлении {wc}а происходит проверка параметра `<LoadLayouts></LoadLayouts>` в конфигурационном файле панели управления {wc}а (`WebClientAdminConsole.config`), расположенного по адресу `%LocalAppData%\Docsvision\WebClientAdminConsole.config`.

Если файл отсутствует или значение `<LoadLayouts>true</LoadLayouts>`, {wc} будет обновлён в стандартном режиме с импортом решений в базу данных.

Если значение `<LoadLayouts>false</LoadLayouts>`, при обновлении {wc}а решения не будут автоматически загружено в базу данных, администратор должен будет сделать это самостоятельно позднее.

[#update]
== Порядок обновления

include::6.1@platform:admin:partial$update.adoc[]
+
. Обновите БД и дождитесь завершения обновления.
+
В процессе обновления стандартные решения {wc}а в базе данных по умолчанию будут перезаписаны.
+
Формат Решений, загруженных в БД по умолчанию, будет обновлен до новой версии.
+
. Если {wc} функционирует в кластере, выполните инструкцию xref:dvweb-cluster.adoc[Настройка утилиты DVWebTool для работы в кластере].
+
NOTE: Также данную инструкцию нужно выполнить, если подключение к {wc}у осуществляется через промежуточное устройство и при этом сервер {wc}а недоступен пользователям по его фактическому адресу.
