= Предоставить доступ в {wc}

* Чтобы предоставить пользователю доступ к {wc}у, добавьте его в _Справочник сотрудников_.
* Чтобы закрыть пользователю доступ к {wc}у, удалите его из _Справочника сотрудников_.

Пользователи {wc}а должны быть добавлены в группу *{dv-users-serv}* в конфигурационном файле модуля {pl}. См. подробнее в документации модуля _{pl}_, раздел "xref:6.1@platform:admin:config-platform.adoc[]".

****
В {of-mc} поддерживается возможность добавить пользователей в группы без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[{of-mc}]"
****

[#configure]
== Настройка способов входа

.Чтобы предоставить пользователю возможность авторизоваться с помощью сторонних сервисов, администратор должен:
. Настроить внешний вид страницы входа xref:programmer:client/authorization.adoc[по инструкции]
. Выполнить необходимые настройки {dv} см. подробнее "xref:authorization-extensions.adoc[]".
. Выполнить настройку в карточке сотрудника xref:user:directories/staff/employee-fields.adoc#security[на вкладке "Безопасность"].
