:do-what: способы предоставить пользователю доступ к {wc}у
:link: appserver-access.adoc#groups[{of-mc}]

= Предоставить доступ в {wc}

* Чтобы предоставить пользователю доступ к {wc}у, добавьте его в _Справочник сотрудников_.
* Чтобы закрыть пользователю доступ к {wc}у, удалите его из _Справочника сотрудников_.

include::partial$mancons.adoc[]

Пользователи {wc}а должны быть добавлены в системную группу *{dv-users-serv}* xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[{of-mc}], xref:6.1@platform:admin:config-platform.adoc[конфигурационном файле] или xref:user:directories/staff/groups-employees.adoc[справочнике сотрудников].

[#configure]
== Настройка способов входа

.Чтобы предоставить пользователю возможность авторизоваться с помощью сторонних сервисов, администратор должен:
. Настроить внешний вид страницы входа xref:dv6@programmer:WebClient:client/authorization.adoc[по инструкции]
. Выполнить необходимые настройки {dv} см. подробнее "xref:authorization-extensions.adoc[]".
. Выполнить настройку в карточке сотрудника xref:user:directories/staff/employee-fields.adoc#security[на вкладке "Безопасность"].

[#captcha]
== Настройки капчи

{wc} поддерживает механизм под названием капча (Captcha), предназначенный для защиты от попыток автоматического перебора пароля пользователя при входе в систему.
// tag::webconfig[]
Администратор настраивает количество неудачных попыток ввода пароля, после которых срабатывает капча, а также время до сброса счётчика неудачных попыток.

Обратите внимание, капча срабатывает только если сервер {wc} работает по HTTPS, см. "xref:admin:connect-https.adoc[]".

[source,json]
----
  "Docsvision": {
    "WebClient": {
        "SettingGroups": {
          "WebClient": {
            "MaxFailedLoginAttempts": 3, <.>
            "FailedLoginAttemptsTTL":  300 <.>
          },
        }
    },
  }
----
<.> Количество неудачных попыток ввода пароля.
<.> Время в секундах, после которого счётчик неудачных попыток будет сброшен.

Неудачные попытки входа и срабатывания капчи попадают в журнал {wc}а. Попытки входа будут записаны в журнал при уровне журналирования как `Error` и серьёзнее, срабатывания капчи будут записаны в журнал при уровне `Warn` и серьёзнее.
// end::webconfig[]
