:do-what: способы предоставить пользователю доступ к {wc}у
:link: appserver-access.adoc#groups[{of-mc}]
:installation:
:link2: config-platform.adoc[]
:admin:

= Предоставить доступ в {wc}

* Чтобы предоставить доступ к {wc}у пользователю, добавьте его в _Справочник сотрудников_.
* Пользователи, xref:6.2@mgmtconsole:servers:appserver-access.adoc[добавленные в группу] *{dv-admins-dir}*, например через {mc}, могут войти в {wc}, даже если их учётная запись отсутствует в справочнике сотрудников, начиная, с {wc-first-login-req}.
* Пользователь не получит доступ к {wc}у, если отсутствует в _Справочнике сотрудников_ и не является администратором.

[#configure]
== Настройка способов входа

.Чтобы предоставить пользователю возможность авторизоваться с помощью сторонних сервисов, администратор должен:
. Настроить внешний вид страницы входа xref:dv6@programmer:WebClient:client/authorization.adoc[по инструкции]
. Выполнить необходимые настройки {dv} см. подробнее "xref:authorization-extensions.adoc[]".
. Выполнить настройку в карточке сотрудника xref:user:directories/staff/employee-fields.adoc#security[на вкладке "Безопасность"].

[#captcha]
== Настройки капчи

:do-what: варианта настройки капчи при входе
:link: webclient-security.adoc[]
include::partial$mancons.adoc[]

// tag::everything-to-include[]
{wc} поддерживает механизм под названием капча (Captcha), предназначенный для защиты от попыток автоматического перебора пароля пользователя при входе в систему.
// tag::webconfig[]
Администратор настраивает количество неудачных попыток ввода пароля, после которых срабатывает капча, а также время до сброса счётчика неудачных попыток.

Обратите внимание, капча срабатывает, только если сервер {wc} работает по HTTPS, см. "xref:dv6@engineer:ROOT:https-connection.adoc[]".
// end::everything-to-include[]

[source,json]
----
{
  "Docsvision": {
    "WebClient": {
        "SettingGroups": {
          "WebClient": {
            "MaxFailedLoginAttempts": 3, <.>
            "FailedLoginAttemptsTTL":  300 <.>
          }
        }
    }
  }
}
----
<.> Количество неудачных попыток ввода пароля.
<.> Время в секундах, после которого счётчик неудачных попыток будет сброшен.

// tag::everything-to-include[]
Неудачные попытки входа и срабатывания капчи попадают в журнал {wc}а. Попытки входа будут записаны в журнал при уровне журналирования как `Error` и серьёзнее, срабатывания капчи будут записаны в журнал при уровне `Warn` и серьёзнее.
// end::everything-to-include[]
// end::webconfig[]
