= Изменить время ожидания пользовательской сессии

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два способа изменить время ожидания пользовательской сессии:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`: "xref:dev@mgmtconsole:servers:webclient-connection.adoc[Группа настроек "Подключение к серверу приложений"]"
****

// tag::webconfig[]
Администратор может изменить максимальное время ожидания ответа (таймаут) от сервера {dv}. Время ожидания устанавливается в миллисекундах.

.Чтобы изменить таймаут пользовательской сессии:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps} > System].
. Измените значение параметра `ConnectionTimeout`.
+
[source,json]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "System": {
          "ConnectionTimeout": 3600000 <.>
        }
      }
    }
  }
----
<.> Время ожидания пользовательской сессии равное 1 часу. Значение задаётся в миллисекундах.
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
