:do-what: способа предоставить пользователю доступ к {wc}у
:link: appserver-access.adoc#groups[{of-mc}]

= Предоставить доступ в {wc}

* Чтобы предоставить пользователю доступ к {wc}у, добавьте его в _Справочник сотрудников_.
* Чтобы закрыть пользователю доступ к {wc}у, удалите его из _Справочника сотрудников_.

include::partial$mancons.adoc[]

Пользователи {wc}а должны быть добавлены в системную группу *{dv-users-serv}* xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[{of-mc}], xref:6.1@platform:admin:config-platform.adoc[конфигурационном файле] или xref:user:directories/staff/groups-employees.adoc[справочнике сотрудников].

[#configure]
== Настройка способов входа

.Чтобы предоставить пользователю возможность авторизоваться с помощью сторонних сервисов, администратор должен:
. Настроить внешний вид страницы входа xref:programmer:client/authorization.adoc[по инструкции]
. Выполнить необходимые настройки {dv} см. подробнее "xref:authorization-extensions.adoc[]".
. Выполнить настройку в карточке сотрудника xref:user:directories/staff/employee-fields.adoc#security[на вкладке "Безопасность"].
