= Изменить порт подключения к DVWebTool

include::partial$excerpts.adoc[tags=dvweb-win]

****
Начиная с модуля {wc} версии {wc-cu5}, поддерживается два способа изменения порта подключения к программе DVWebTool:

* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
* При помощи WebToolUtil без необходимости работы с форматом `.json`, см. подробнее в разделе "xref:webservices-install.adoc[Работа с программой WebToolUtil]"
****

// tag::webconfig[]
Веб-браузер пользователя подключается к программе _DVWebTool_ по адресу `\http://localhost:5413`. Администратор может изменить стандартный порт подключения.

.Чтобы изменить стандартный порт подключения:
. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции {cnf-sgrps} > System].
. Измените значение параметра *_WebServicesPort_*, указав новый номер порта подключения к программе _DVWebTool_.
+
[source]
----
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "System": {
          "WebServicesPort": 5413
        }
      }
    }
  }
----
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сохраните изменения конфигурационного файла.
. Перезапустите программу _DVWebTool_.
