:wt: dvsupservice
:do-what: способа настройки запуска программы DVWebTool:
:link: webclient-tools.adoc[Закрывать DVWebTool после выполнения действия]

= Настройки запуска инструментов

[#dvweb]
== Настройки запуска программы DVWebTool

Поведение по умолчанию: программа запускается при загрузке системы и не закрывается после выполнения действия. Данное поведение можно изменить.

include::partial$mancons.adoc[]

include::admin:webservices-install.adoc[tags=webtool]

// tag::webconfig[]
.D конфигурационном файле {wc}а поведение DVWebTool при запуске настраивается:
* `DvWebToolAppShutDown` -- закрывать DVWebTool после выполнения действия. Значение по умолчанию: `false` -- не закрывать.
* `DvWebToolStartUpLaunch` -- отвечает за автоматический запуск DVWebTool. Значение по умолчанию: `true` -- утилита запускается автоматически при загрузке системы.
// end::webconfig[]

Чтобы настройки вступили в действие после изменения, необходимо повторно собрать инсталлятор DVWebTool по инструкции "xref:admin:webservices-install.adoc[]".

.Программа WebToolUtil позволяет собрать DVWebTool со следующими параметрами:
* _Адрес сервера {wc}а_: укажите адрес сервера {wc}а.
* _Порт DVWebTool_: укажите порт DVWebTool. По умолчанию `5413`.
* `*Автозапуск*`: параметр имеет приоритет над параметром `DvWebToolStartUpLaunch` в конфигурационном файле {wc}а. Если в конфигурационном файле {wc}а параметр `true`, но утилита собрана со снятым флагом `*Автозапуск*`, автозапуск не сработает.

[#dvsup]
== Настройки запуска DVSupService

include::user:prepare-add-components.adoc[tags=dvsup]

Чтобы запустить службу DVSupService, выполните следующую команду:

[subs=attributes]
 $ sudo systemctl start {wt}

Настроить автоматический запуск и иное поведение можно при помощи системных средств, см. подробнее руководство по работе с программным пакетом `systemd` в ОС Linux.
