= Общие сведения

Комплект инструментов {rk} предназначен для применения в организациях, эксплуатирующих систему {dv}.

{rk} содержит набор системных утилит различного назначения, предназначенных для специалистов {dv}.

.{rk} включает следующие программы:
. _{cns}_ -- программа для администраторов {dv}.
+
."{cns}" предоставляет следующие функции:
* Просмотр списка БД и базы по умолчанию.
* Получение отчёта по безопасности.
* Настройка дискреционных прав на папки.
* Выбор представлений для папок.
* Настройка сервиса полнотекстового индексирования.
+
. _CardManager_ -- программа для создания и регистрации схем метаданных библиотек карточек.
+
."CardManager" предоставляет следующие функции:
* Создание схем метаданных библиотек карточек.
* Создание схем метаданных карточек.
* Загрузка разработанных схем метаданных в БД {dv}.
+
. _ChangeAccount_ -- программа для обновления данных учётных записей пользователей {dv}.
+
."ChangeAccount" предоставляет следующие функции:
* Обновление данных учётных записей и дескрипторов безопасности в БД {dv} (в _Справочнике сотрудников_ и в системных таблицах) после переименования учётных записей и/или изменения домена.
* Удаление неиспользуемых дескрипторов безопасности.
+
. _DVExplorer_ -- программа для работы с данными {dv} на низком уровне.
+
."DVExplorer" предоставляет следующие функции:
* Просмотр/изменение данных карточек {dv}.
* Формирование и выполнение поисковых запросов.
* Получение детальной информации о типах карточек, загруженных в БД {dv}.
* Управление блокировками и др.
+
. _LogViewer_ -- программа для просмотра журналов работы {dv}.
+
."LogViewer" предоставляет следующие функции:
* Просмотр журналов (системы, безопасности, приложения) из файлов и/или из базы данных.
* Сортировка и фильтрация данных.
+
. _SearchUtil_ -- программа для интерпретации поискового запроса {dv} из XML в SQL код.
. _TOPartnersLoad_ -- программа для загрузки данных в _Справочник контрагентов_ из файлов формата `.xls`.
. _TOStaffLoad_ -- программа для загрузки данных в _Справочник сотрудников_ из файлов формата `.xls`.
. _ViewUtil_ -- программа для интерпретации кода представления (папки) {dv} из XML в SQL код.
. _WindowsClient LogParser_ -- программа для конвертации журнала работы {wincl}а в файл `.xls`.
