= Ключевые изменения в версии

. Главным изменением в самой новой версии является настройка системы с помощью {of-mc} версии {mc-cu-mc}. Это означает, что установка _Службы {ws}_, _{of-sett-serv}_, _{of-mc}_ и расширений {of-mc} теперь обязательна.
. В Накопительном Обновлении (НО) 26.1footnote:[{pl} версии {pl-cu-mc} и выше, {wincl} версии {win-cu-mc} и выше, {wc} версии {wc-cu-mc} и выше, {wf} версии {wf-cu-mc} и выше, {mc} версии {mc-cu-mc} и выше, а также другие модули, входящие в НО 26.1] поддержана кросс-платформенная работа сервера {dv} -- под управлением ОС {ms} Windows и ОС семейства Linux.
+
Также в НО 26.1 {cns} поставляется с комплектом утилит {rk}, {kvr} становится частью комплекта утилит WebClientToolKit, конфигурация DVWebTool производится через WebToolBuilder.
+
. В версии НО 25.3footnote:[{pl} версии {cu253-pl-req} и выше, {wincl} версии {cu253-wincl-req} и выше, {wc} версии {cu253-wc-req} и выше, {wf} версии {cu253-wf-req} и выше, {mc} версии {cu253-mc-req} и выше, а также другие модули, входящие в НО 25.3]:
+
* Модули системы переведены на .NET 8.
* Поддержана работа сервера {dv} под управлением ALT Linux версий 10 и 11.
* Поддержана работа системы с использованием учётной записи из альтернативной службы доменных каталогов, например ALD Pro.
* Появилось новое обязательное ПО:
+
** ПО {asp-bundle} обязательно должно быть установлено на:
*** Всех серверах системы под управлением Linux.
*** Клиентских рабочих местах, использующих DvWebTool и DVSupService
*** Машине с {pu} и {kvr}.
* ПО {net-r} обязательно должно быть установлено на:
*** Машины с серверными компонентами {dv} под управлением Windows.
*** Рабочие места с {wincl}ом.
** Собственные решения для {wc}а рекомендуется перевести на .NET 8.
+
. По сравнению с версиями 5.5 и 5.4:
+
* Поддержана работа сервера {dv} под управлением ОС семейства Linux, список поддерживаемых см. в соответствующем разделе для версии.
+
. По сравнению с версией 5.4:
+
* Система обрела модульную структуру и теперь содержит модули следующих версий:
+
* _{mc}_ версии {mc-cu-mc}.
* _{pl}_ версии {pl-cu-mc}.
* _Служба {ws}_ версии {worker-cu-mc}.
* _{bo}_ версии {bo-cu-mc}.
* _{wf}_ версии {wf-cu-mc}.
* _{dm}_ версии {ud-cu-mc}.
* _{ad}_ версии {ad-cu-mc}.
* _{wc}_ версии {wc-cu-mc}.
* _{wincl}_ версии {win-cu-mc}.
+
* В новой версии появилась возможность использовать отдельные (сателлитные) базы данных для хранения архивных карточек, журналов и некоторых системных таблиц.
* В {dv} 6.1 содержимое файлов может быть вытеснено из основной БД {dv} в отдельную БД, на файловую систему или в иное хранилище.
* В качестве СУБД теперь может использоваться {pgsql}, подробнее см. "xref:platform:console:appendix/microsoft-postgre.adoc[]".
* В новой версии изменился способ хранения расширенных метаданных в БД:
* Поля сохраняются в основных таблицах секций. Раньше использовались extended-секции.
* Для секций создаются таблицы со стандартными секционными названиями -- без суффикса *_extended*.
+
Данное изменение не затрагивает способ хранения динамических метаданных.
* Реализован механизм обновления базовых модулей {dv} ({pl}, {bo} и др.), значительно ускоряющий процесс обновления БД. Если у модуля изменились только программные компоненты, но не изменилась библиотека карточек, при его обновлении библиотека карточек повторно загружаться не будет.
