.Для сервера под управлением {caps} шифрование настраивается следующим образом:
. Используйте существующий сертификат с поддержкой функции шифрования или создайте сертификат по инструкции, указанной в разделе "xref:dv6@engineer:ROOT:https-connection.adoc#cert-{lower}[Создание самоподписанного сертификата]".
+
WARNING: Пароль для сертификата указывать не требуется!
+
. Добавьте:
+
* Публичный и приватный ключ на клиентскую и серверную машины модуля {wf}
ifdef::linux[]
по пути `/root/.dotnet/corefx/cryptography/x509stores/my`.
endif::linux[]
ifdef::windows[]
в хранилище _Сертификаты -- Локальный компьютер_.
endif::windows[]
+
TIP: На клиентской машине приватный ключ требуется, т.к. xref:edi:admin:configure-directory.adoc[при загрузке операторов] необходимы пароли к УЗ.
+
* Приватный ключ на машину, где планируется настраивать/редактировать справочник ЮЗДО
ifdef::linux[]
по пути `/root/.dotnet/corefx/cryptography/x509stores/my`.
endif::linux[]
ifdef::windows[]
в хранилище _Сертификаты -- Локальный компьютер_.
endif::windows[]
для пользователя, который будет настраивать и редактировать справочник ЮЗДО.
+
[NOTE]
====
// tag::cert-loc[]
ifdef::linux[]
Если {mdl} запущен от имени пользователя иного, чем ROOT, например от имени учётной записи {dv}, сертификат требуется размещать по пути `/home/docsvision/.dotnet/corefx/cryptography/x509stores/my`.
endif::linux[]
ifdef::windows[]
В ОС Windows сертификат необходимо установить в хранилище "Личное" на уровне "Локальный компьютер".
Затем необходимо предоставить права на приватную часть сертификата для УЗ, от имени которой запускается {mdl} (по умолчанию Network Service) в программе "Сертификаты", через управление закрытыми ключами (вызывается нажатием правой кнопки на сертификате).
endif::windows[]
// end::cert-loc[]
====
+
. Убедитесь, что в настройках оператора Диадок появился xref:6.1@edi:diadoc:connection-settings.adoc#thumbprint[параметр для ввода отпечатка] _Thumbprint_.
. В свойствах menu:Контекстное меню[Свойства > Состав > Отпечаток] созданного сертификата скопируйте отпечаток (например: `3f65b0bc7ca3f7291c5473e1cfb411f62bc0dfbe`) и укажите его в настройках оператора. Повторно введите пароли (_Password_, _ApiKey_, _ProxyPassword_) в настройках оператора Диадок, чтобы они сохранились с учётом новой логики шифрования. +
Если этот шаг пропустить, документооборот с оператором будет невозможен.
. {blank}
+
[subs="specialchars,attributes,quotes"]
Перезапустите службу {wfs-new}.
+
. Перезагрузите xref:6.1@edi:admin:configure-directory.adoc[список операторов] и xref:6.1@edi:admin:configure-partners.adoc[котрагентов].
. Проверьте работу модуля ЭДО (достаточно убедиться, что работает получение и отправка документов, если всё работает стандартно, дешифровка работает).