// tag::encryption[]
[CAUTION]
====
Пароли могут быть зашифрованы. Если вы планируете шифровать пароли, сначала укажите параметр _Thumbrint_, затем указывайте пароли, подробнее см. "xref:new-admin-console@engineer:ROOT:encryption.adoc[]".

Если вы планируете включить шифрование для уже настроенного {of-em}, потребуется заново задать пароли в настройках операторов ЭДО.

Шифрование доступно в {em} версии {edi-cu-mc}.
====
// end::encryption[]

// tag::reset-passwords[]
CAUTION: Начиная с версии {edi-cu-mc} {of-em} изменён механизм шифрования, при обновлении на версию {edi-cu-mc}, заново укажите пароли в настройках оператора в Справочнике настроек операторов ЮЗДО и перезагрузите список xref:admin:configure-directory.adoc[операторов ЮЗДО] и xref:admin:configure-partners.adoc[контрагентов].
// end::reset-passwords[]

// tag::maynot[]
[NOTE]
====
Если событие ответной подписи придёт после события запроса аннулирования (с любой стороны), карточка сообщения останется в статусе ответной подписи (`ReplySignature` или `PartnerSigned`), поэтому ответ может не загрузиться.
====
// end::maynot[]

// tag::connector[]
. Установите _{em}_ и _Коннектор к Диадок_.
. При наличии укажите логин и пароль прокси в _Справочнике настроек операторов ЮЗДО_ для оператора Диадок.
. Укажите полученный у Диадок API key для клиента.
// end::connector[]

// tag::last-connector[]
. Если коннектор устанавливается последним, запустите {cns} и выполните настройку системы следуя инструкции, данной в документации модуля {pl} xref:6.1@platform:admin:config-master.adoc[здесь] и xref:6.1@platform:admin:post-config-server.adoc[здесь].
// end::last-connector[]
