// tag::reset-passwords[]
[CAUTION]
====
Начиная с версии {edi-cu-mc}, в Модуле интеграции с операторами ЭДО и коннекторах изменён механизм шифрования конфиденциальных настроек.

При обновлении или установке потребуется создать сертификат с приватной и публичной частью, указать параметр _Thumbprint_ в настройках коннектора, заново указать пароли в настройках оператора в Справочнике настроек операторов ЮЗДО и перезагрузить список xref:admin:configure-directory.adoc[операторов ЮЗДО] и xref:admin:configure-partners.adoc[контрагентов].

ifndef::cryption[]
Подробнее о шифровании см. в разделе "xref:admin:encryption.adoc[]".
endif::cryption[]
====
// end::reset-passwords[]

// tag::maynot[]
[NOTE]
====
Если событие ответной подписи придёт после события запроса аннулирования (с любой стороны), карточка сообщения останется в статусе ответной подписи (`ReplySignature` или `PartnerSigned`), поэтому ответ может не загрузиться.
====
// end::maynot[]

// tag::connector[]
. Установите _{em}_ и _Коннектор к Диадок_.
. При наличии укажите логин и пароль прокси в _Справочнике настроек операторов ЮЗДО_ для оператора Диадок.
. Укажите полученный у Диадок API key для клиента.
// end::connector[]

// tag::last-connector[]
. Если коннектор устанавливается последним, запустите {cns} и выполните настройку системы следуя инструкции, данной в документации модуля {pl}, раздел "xref:6.1@platform:admin:config-master.adoc[]".
// end::last-connector[]
