:cryption:
:mdl: {wc}

= Шифрование системных настроек

Конфиденциальные настройки модуля и коннекторов шифруются при помощи сертификата шифрования с публичной и приватной частями.

include::ROOT:partial$excerpts.adoc[tags=reset-passwords]

.Шифрование настраивается следующим образом:
// tag::letsencrypt[]
. Создайте сертификат по инструкции "xref:dv6@engineer:ROOT:https-connection.adoc#certificate[Создание самоподписанного сертификата]".
+
WARNING: Пароль для сертификата указывать не требуется!
+
. Добавьте сертификаты с публичным и приватным ключом на клиентскую и серверную машины модуля {wf} по пути `/root/.dotnet/corefx/cryptography/x509stores/my`. Приватный ключ требуется и на клиенте, потому что xref:edi:admin:configure-directory.adoc[при загрузке операторов] нужны пароли к УЗ. +
Приватная часть требуется только на машине, где планируется настраивать/редактировать справочник ЮЗДО и под пользователем, который будет это делать. Устанавливать сертификат на все рабочие места с {wincl}ом не требуется.
+
[NOTE]
====
// tag::cert-loc-l[]
Если {mdl} запущен от имени пользователя иного, чем ROOT, например от имени учётной записи {dv}, сертификат требуется размещать по пути `/home/docsvision/.dotnet/corefx/cryptography/x509stores/my`.
// end::cert-loc-l[]

В ОС Windows сертификат необходимо установить в хранилище "Личное" на уровне "Локальный компьютер".
// tag::cert-loc-w[]
Затем необходимо предоставить права УЗ Network Service в программе "Сертификаты", через управление закрытыми ключами (нажатием правой кнопкой на сертификате).
// end::cert-loc-w[]
====
+
. Убедитесь, что в настройках оператора Диадок появился xref:6.1@edi:diadoc:connection-settings.adoc#thumbprint[параметр для ввода отпечатка] _Thumbprint_.
. В свойствах menu:Контекстное меню[Свойства > Состав > Отпечаток] созданного сертификата скопируйте отпечаток (например: 3f65b0bc7ca3f7291c5473e1cfb411f62bc0dfbe) и укажите его в настройках оператора. Повторно введите пароли (_Password_, _ApiKey_, _ProxyPassword_) в настройках оператора Диадок, чтобы они сохранились с учётом новой логики шифрования. +
Если этот шаг пропустить, документооборот с оператором будет невозможен.
. {blank}
+
[subs="specialchars,attributes,quotes"]
Перезапустите службу {wfs-new}.
+
. Перезагрузите xref:6.1@edi:admin:configure-directory.adoc[список операторов] и xref:6.1@edi:admin:configure-partners.adoc[котрагентов].
. Проверьте работу модуля ЭДО (достаточно убедиться, что работает получение и отправка документов, если всё работает стандартно, дешифровка работает).
// end::letsencrypt[]