= Настройка функций обмена формализованными документами

Для работы с формализованными документами предназначены карточки подвидов _Документ/УПД_:

. Исходящий УПД.
.. Исходящий УКД.
... Исходящий УКД (736) в формате приказа ФНС 189.
... Исходящий УКД (736) в формате приказа ФНС 736.
.. Исходящее исправление УПД.
... Исходящее исправление УПД (820).
.. Исходящий УПД (820).
.. Исходящий УПД (970)footnote:[В данный момент формат поддерживается только для коннектора к Диадок.].
. Входящий УПД.
.. Входящий УПД (820).
.. Входящий УПД (970)footnote:[В данный момент формат поддерживается только для коннектора к Диадок.].
.. Формализованный акт.
... Формализованный акт (820).
... Формализованный акт (552).
.. Входящий УКД.
... Входящий УКД (736) в формате приказа ФНС 189.
... Входящий УКД (736) в формате приказа ФНС 736.

Указанные виды карточек предоставляются с настроенными разметками, автоматом состояний и ролевой моделью.

.Администратору необходимо:
. Добавить <<print-forms,печатные формы для печати УПД>>.
. Добавить виртуальные папки для работы с УПД.

[#print-forms]
== Настройка печатных форм для формализованных документов

. Откройте _Рабочее место администратора_ с явным указанием локали, например `\http://localhost:5000/?showpanels=32768&langname=ru`.
. Вызовите команду _Свойства_ из контекстного меню элемента menu:Карточки[{bo} > Документ].
+
Будет открыто окно со свойствами типа карточки _Документ_.
+
. Перейдите на страницу _Преобразования_ и создайте преобразования:
.. _UniInvoiceRu_ c параметрами:
+
* Название: `UniInvoiceRu`.
* Псевдоним: `UniInvoiceRu`.
* Тип преобразование: *_Пользовательское_*.
* Тип содержимого: *_XML_*.
* Данные преобразования (выберите файл): `C:\Program Files (x86)\Docsvision\Edi\Xslt\UniInvoice.ru.xslt`.
+
.. Выполните аналогичные настройки со следующими преобразованиями:
+
* `UniInvoiceActRu`
* `UniInvoiceCorrectionRu`
* `UniInvoiceCorrFieldsRu`
* `UniInvoiceFieldsRu`
* `UniInvoiceSFRu`
* `UniInvoiceTorgRu`
* `UniInvoice970Rufootnote:[В данный момент формат поддерживается только для коннектора к Диадок.]`
* `UniInvoiceAct970Rufootnote:[В данный момент формат поддерживается только для коннектора к Диадок.]`
* `UniInvoiceSF970Rufootnote:[В данный момент формат поддерживается только для коннектора к Диадок.]`
* `UniInvoiceTorg970Rufootnote:[В данный момент формат поддерживается только для коннектора к Диадок.]`

[#formalized-folders]
== Настройка папок для формализованных документов

Для удобства работы с исходящими формализованными документами можно добавить пользователям модуля виртуальные папки со следующими поисковыми запросами:

* _Журнал Все УПД_ -- возвращает все виды УПД во всех статусах.
* _Журнал Исправление УПД_ -- возвращает только исправления УПД во всех статусах.
* _Журнал Исходящий УПД_ -- возвращает только исходящие УПД во всех статусах.
* _Журнал Корректировочный УПД_ -- только корректировочные УПД во всех статусах.
* _Поиск УПД_ -- выполняет поиск УПД по различным полям.

В настройках данных папок рекомендуется установить представление по умолчанию -- _УПД (Все)_.

Поисковые запросы и представления для папок входящих формализованных документов, если требуется, могут быть разработаны самостоятельно.

[#formalized-ribbon]
== Настройка ленты карточек для нового вида формализованных документов

Администратор может настроить собственные виды карточек для работы с формализованными документами. При этом добавляемые виды должны быть дочерними видами видов _Входящий УПД_ или _Исходящий УПД_.

Ленты карточек видов _Входящий УПД_ и _Исходящий УПД_ содержат команды для вызова стандартных функций обработки формализованных документов. В собственных видах могут использоваться функции, унаследованные от родительских видов, или разработаны собственные, например, дополнительная функция проверки данных.

NOTE: Упрощённый код функций, вызываемых командами ленты карточек, можно получить по запросу в xref:system:ROOT:technical-support.adoc[техническую поддержку]. Полный код смотрите в скриптах карточек соответствующих родительских видов.

[#custom-kind]
=== Собственный вид, не унаследованный от Входящий УПД или Исходящий УПД

Если требуется создать вид, не наследующий состояния от _Входящий УПД_ или _Исходящий УПД_, необходимо самостоятельно добавить в его автомат состояний следующие состояния:

* `Получена подпись от контрагента` c идентификатором встроенного состояния (поле `BuildInState`) `FF1346D7-93F0-4CA3-93F8-5AE47BCD41DD`.
* `Получен отказ от контрагента` c идентификатором встроенного состояния `D136A114-7C59-4C6E-AB12-5348B4883AB9`.
* `Требуется уточнение` c идентификатором встроенного состояния `9F8A156B-68EE-4543-9527-BF47B613330E`.
* `Запрошено аннулирование` c идентификатором встроенного состояния `E3ED8CD1-8D9E-4332-B2D3-0EE5B9FE5A10`.
* `Аннулирование подтверждено` c идентификатором встроенного состояния `D5CC4959-5E45-4F31-B630-F2C3613EDCB7`.
* `В аннулировании отказано` c идентификатором встроенного состояния `ED9B6929-BD9C-496B-B8A7-D9597B1BA5CA`.

Также потребуется добавить в разметку элементы управления с типами и названиями, которые используются в видах _Входящий УПД_ или _Исходящий УПД_.

NOTE: Данная логика справедлива и для неформализованных документов.
