= Настроить работу {modl} по HTTPS

Настройка защищённого соединения для {modl} выполняется в конфигурационном файле `appsettings.json`:

.Фрагмент конфигурационного файла в Linux:
[source,json]
----
{
  "AllowedHosts": "*",
  "Kestrel": {
    "Endpoints": {
      "Https": {
        "Url": "https://*:{s-port}", <.>
        "Certificate": {
          "Path": "/folder/certificate.crt", <.>
          "KeyPath": "/folder/docsvision.key" <.>
        }
      }
    }
  }
}
----
<.> `Url` -- адрес и порт для доступа по HTTPS. При такой конфигурации сервис будет прослшуивать одновременно два порта: стандартный `{port}` для HTTP и `{s-port}` для HTTPS. Чтобы использовать стандартный порт `{port}` для подключения по HTTPS, измените параметры следующим образом: menu:Http[Url > "https://*:{port}"]. Обратите внимание, вместо `Https` в данной конфигурации указывается `Http`.
<.> `Path` -- папка, в которую установлен полученный или самоподписанный сертификат.
<.> `KeyPath` -- папка, в которой расположен ключ шифрования полученного или самоподписанного сертификата.

ifeval::["{modl}" == "Сервера приложений"]
Аналогичным образом выполняется настройка для {of-fs}, и сервиса полнотекстового индексирования.
endif::[]

[TIP]
====
См. подробнее "xref:dv6@engineer:ROOT:https-connection.adoc[]" в документации по настройке {dv}.
====