ifndef::installation[]
[TIP]
====
.Модуль "{pl}" поддерживает следующие {do-what}:
ifndef::with-config[]
ifndef::conas[]
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`, начиная с версии {pl-cu-mc}: {link}
endif::conas[]
ifdef::conas[]
* Из интерфейса {of-mc}, минуя {cns}, начиная с версии {pl-cu-mc}: "xref:dev@mgmtconsole:servers:appserver-{link}"
endif::conas[]
ifdef::conas[]
* При помощи настройки в программе {cns}, в версиях ниже указанной, см. раздел {cns-section}
endif::conas[]
ifndef::conas[]
* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
endif::conas[]
endif::with-config[]
ifeval::["{with-unique}" == "yes"]
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`, начиная с версии {pl-cu-mc}, см. раздел "<<mancons,Конфигурация Сервера приложений из {of-mc}>>" ниже
* При помощи настройки в конфигурационном файле модуля, см. подробнее в разделе "<<config-file,Настройка в конфигурационном файле>>" ниже
endif::[]
ifeval::["{with-config}" == "yes"]
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`, начиная с версии {pl-cu-mc}: {link}
* При помощи настройки в конфигурационном файле модуля, см. подробнее ниже
endif::[]
ifeval::["{with-console}" == "yes"]
* Из интерфейса {of-mc}, минуя {cns}, начиная с версии {pl-cu-mc}: см. раздел {link}
* При помощи программы {cns}, в версиях ниже указанной, см. раздел {cns-section}
endif::[]
ifeval::["{sec-gorups}" == "yes"]
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`, начиная с версии {pl-cu-mc}: {link}
* При помощи настройки в конфигурационном файле модуля, параметр "Groups"
endif::[]
ifeval::["{installn}" == "yes"]
* Из интерфейса {of-mc} без необходимости работы с форматом `.json`, начиная с версии {pl-cu-mc}, {link}
* При помощи настройки в конфигурационном файле модуля, параметр menu:{dv}[Platform > Server > Databases > alias]
endif::[]
====
endif::installation[]
// Если не понятно, то поясняю: первое условие ifndef с with-config -- если оно не определено, то работает всё до первого ifeval. Если with-unique, with-config и sec-gorups определены и в yes, то работают соответствующие условия, но только если ifconfig Не определён. Остальное довольно очевидно: если определён такой-то атрибут, то будет такое-то, если нет -- будет другое. Например, conas используется только для разделов консоли настройки.