= Активация лицензии

Для активации лицензии в системе {dv} реализована специальная утилита.

.Активировать систему можно следующими способами:
* При помощи утилиты активации, поставляемой отдельным пакетом установки.
+
После установки утилиту можно запустить из меню "Пуск"
// * Из программы "xref:platform:console:manage-licenses.adoc[{cns}]".

.Утилита активации предоставляет следующие возможности:
. Онлайн активация с параметром в виде ключа и адреса сервера.
. Офлайн активация:
.. Создание запроса на офлайн активацию.
.. Применение ответа на офлайн активацию.
.. Получение справки по активации.

[#commands]
== Активация при помощи утилиты активации для Windows

. Запустите утилиту из любой директории командой:
+
 ./activation
+
В окне запущенной командной строки будет выведена справка по использованию утилиты.
+
. Выполните активацию:
.. Для онлайн-активации введите серийный номер лицензионного ключа, выданный при покупке продукта, в параметр команды для онлайн активации:
+
 ./activation online <серийный-номер-продукта>
+
.. Для офлайн-активации создайте файл запроса офлайн активации:
+
 offline <серийный-номер-продукта> <папка-для-сохранения-запроса>
+
Файл будет сохранён в формате `.xml` с указанием даты создания: `request-activation_ГГММДД_ЧЧММСС.xml`. Отправьте полученный файл запроса в компанию "ДоксВижн" на адрес электронной почты _sales@{dv}.com_.
+
.. Выберите файл, полученный от компании "ДоксВижн" на запрос активации и выполните офлайн активацию:
+
 activate <путь-к-файлу-активации>
+
. Дополнительные параметры утилиты активации:
+
--
* `--version` -- показать информацию о версии.
* `-?, -h, --help` -- показать справку и информацию об использовании.
--
+
NOTE: Если ввести команду без нужных аргументов, в окне терминала будет выведена справка для использованной команды.
