= Конфигурация сервера приложений

[#mancons]
== Конфигурация сервера приложений в {of-mc}

Настройка сервера приложений выполняется при помощи {of-mc} и частично в конфигурационном файле `C:\Program Files\Docsvision\Platform\appsettings.json` для Windows.

. Откройте конфигурационный файл в любом текстовом редакторе (потребуются права администратора) и заполните следующие параметры:
+
.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "DocsVision": {
    "ServiceId": "00000000-0000-0000-0000-000000000000", <.>
    "SettingsService": {
      "ConnectionString": "http://localhost:5200/api", <.>
      "ApiKey": "anything" <.>
    },
  },
  "AllowedHosts": "*",
  "Kestrel": { <.>
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      }
    }
  }
}
----
<.> `ServiceId` -- уникальный идентификатор данного экземпляра модуля, генерируется и записывается автоматически.
<.> `ConnectionString` -- полный адрес {of-sett-serv}.
<.> `ApiKey` -- API-ключ для подключения к {to-sett-serv}, можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {sett-serv} и {pl} были одинаковые. Адрес и API-ключ требуется указать, если планируется переходить в {mc} из карточек {wc}а и {wincl}а.
<.> Опционально. Настройка доступа к Storage Server по HTTPS, см. подробнее "xref:new-admin-console@engineer:ROOT:https-connection.adoc[]".
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc[Общие настройки сервера приложений]" укажите в первую очередь параметры:
+
* Имя компьютера в текущем домене Active Directory -- используется при получении списка доступных членов домена при настройке дискреционной безопасности.
* Логин системной учётной записи.
+
include::new-admin-console@install-linux:ROOT:partial$excerpts.adoc[tags=system-accounts]
+
* Пароль системной учётной записи.
* Файл журнала и Уровень журналирования -- путь к файлу, в котором регистрируются выполняемые сервером операции.
* API-ключ для подключения к Workflow -- используется для подключения серверного расширения {wf}. API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
* Штамп сертификата шифрования паролей -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux::appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[Группы пользователей]" выполните настройку системных групп.
. При необходимости в {mc}, на странице menu:Серверы[Имя сервера > Сервер приложений > "xref:dev@mgmtconsole:servers:appserver-auth-extensions.adoc[Группа настроек "Расширенная аутентификация"]], настройте использование расширенной аутентификации.
. {blank}
+
include::dev@mgmtconsole:servers:partial$excerpts.adoc[tags=client-path]
+
. Нажмите кнопку *Применить* в правом верхнем углу окна Консоли, чтобы применить настройки сервера приложений.
include::new-admin-console@system:ROOT:partial$restart-sss.adoc[]
