= Конфигурация сервера приложений

[#mancons]
== Конфигурация сервера приложений в {of-mc}

Настройка сервера приложений выполняется при помощи {of-mc} и частично в конфигурационном файле `/usr/lib/docsvision/platform/appsettings.json`.

. Откройте конфигурационный файл в любом текстовом редакторе (потребуются права администратора) и заполните следующие параметры:
+
.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "DocsVision": {
    "ServiceId": "00000000-0000-0000-0000-000000000000", <.>
    "SettingsService": {
      "ConnectionString": "http://localhost:5200/api", <.>
      "ApiKey": "anything" <.>
    },
  },
  "AllowedHosts": "*",
  "Kestrel": { <.>
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      }
    }
  }
}
----
<.> `ServiceId` -- уникальный идентификатор данного экземпляра модуля, генерируется и записывается автоматически.
<.> `ConnectionString` -- полный адрес {of-sett-serv}.
<.> `ApiKey` -- API-ключ для подключения к {to-sett-serv}, можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {sett-serv} и {pl} были одинаковые. Адрес и API-ключ требуется указать, если планируется переходить в {mc} из карточек {wc}а и {wincl}а.
<.> Опционально. Настройка доступа к Storage Server по HTTPS, см. подробнее xref:platform:console:https-access.adoc[].
+
. Откройте {mc} на странице menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:db-settings.adoc[Группа настроек "Базы данных"]], чтобы выбрать БД по умолчанию.
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc#catalogs[Настройка доменных каталогов]" укажите параметры:
+
* Тип аутентификации в LDAP
* Логин -- имя учётной записи, под которой процесс обращается к ActiveDirectory
* Пароль -- пароль учётной записи пользователя для аутентификации LDAP
* Домен по умолчанию -- полное имя домена для входа по умолчанию в формате FQDN
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc[Общие настройки сервера приложений]" укажите в первую очередь параметры:
+
* Логин системной учётной записи.
+
include::new-admin-console@install-linux:ROOT:partial$excerpts.adoc[tags=system-accounts]
+
* Пароль системной учетной записи.
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-general.adoc[Общие настройки сервера приложений]" укажите в первую очередь параметры:
+
* API-ключ для подключения к Workflow -- используется для подключения серверного расширения {wf}. API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
+
* Штамп сертификата шифрования паролей -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по настройке системы, раздел "xref:new-admin-console@engineer:ROOT:account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[Группы пользователей]" выполните настройку сисемных групп.
. При необходимости в {mc}, на странице menu:Серверы[Имя сервера > Сервер приложений > "xref:dev@mgmtconsole:servers:appserver-auth-extensions.adoc[Группа настроек "Расширенная аутентификация"]], настройте использование расширенной аутентификации.
. В разделе menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:appserver-etc.adoc[Дополнительные настройки]] задайте необязательные параметры:
+
* `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;LogFile` -- указывает путь к файлу журнала сервера. Если параметр не указан, действует системная настройка по умолчанию.
* `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;TraceLevel&#95;&#95;LogLevel` -- настройка уровня журналирования.
+
. Настройка клиентской части {wincl} выполняется при помощи конфигурационного файла `windows-client-part.json`, см. подробнее xref:6.1@platform:console:config-client.adoc[]. Если использовать {wincl} не планируется, пункт можно пропустить.

[#config-file]
== Конфигурация модуля {pl} без {of-mc}

Конфигурационный файл располагается по пути
`C:/Program Files/Docsvision/platform/appsettings.json` и может быть изменён в любом текстовом редакторе.

.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "DefaultBaseName": "alias", <.>
        "LogFile": "/var/log/docsvision/dvappserver.log", <.>
        "WindowsSecurityServerName": "any.domain.com", <.>
        "Databases": {
          "alias": "CONNECTION-STRING"  <.>
        }
      }
    },
    "ServiceId": "00000000-0000-0000-0000-000000000000", <.>
    "SettingsService": {
      "ConnectionString": "ConnectAddress=http://settings.service.com:5200/api", <.>
      "ApiKey": "apikey-settingsservice" <.>
    },
    "Workflow": {
      "ApiKey": "api-key" <.>
    }
  },
  "Groups": {
    "DocsVision Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
  "Ldap": { <.>
    "AuthType": "Basic", <.>
    "Credential": {
      "UserName": "account@domain.com", <.>
      "Password": "password" <.>
    }
  },
  "Domains": [
    "DOMAIN.COM" <.>
  ],
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password", <.>
  "Logging": { <.>
    "LogLevel": {
      "Default": "Error"
    }
  }
}
----
<.> `DefaultBaseName` -- псевдоним базы данных. Должен совпадать с псевдонимом подключаемой базы в Консоли настройки. Можно заполнить заранее, или вернуться позже, после создания из Консоли управления.
<.> `LogFile` -- путь к файлу журнала сервера. Параметр необязательный, если он не указан, действует системная настройка по умолчанию.
<.> `WindowsSecurityServerName` -- необходимо указать имя любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности в {wincl}е, РМА и DVExplorer.
<.> `alias` -- псевдоним используемой БД, для которой задаётся строка подключения. `CONNECTION-STRING` -- строка подключения, подробное описание строки подключения см. <<connection-string,ниже>>.
<.> `ConnectionString` -- полный адрес {of-sett-serv}.
<.> `ServiceId` -- уникальный идентификатор данного экземпляра модуля, генерируется и записывается автоматически.
<.> `ApiKey` -- API-ключ для подключения к {to-sett-serv}, можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {sett-serv} и {pl} были одинаковые. Адрес и API-ключ требуется указать, если планируется переходить в {mc} из карточек {wc}а и {wincl}а.
<.> `ApiKey` -- используется для подключения серверного расширения {wf}. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
<.> `Groups` -- эквивалент системных групп. Указанные в группах пользователи будут обладать соответствующими правами. Обратите внимание, что в группах массив строк, а не строка.
<.> `Ldap` -- имя и пароль учётной записи, под которой процесс обращается к ActiveDirectory.
<.> `AuthType` -- тип аутентификации: `Basic` -- аутентификация через LDAP, `Oauth` -- аутентификация через ЕСИА или Azure.
<.> `UserName` -- логин пользователя модуля для аутентификации LDAP.
<.> `Password` -- пароль учётной записи пользователя для аутентификации LDAP в открытом или в зашифрованном виде, см. подробнее о шифровании в документации по настройке системы, раздел "xref:new-admin-console@engineer:ROOT:account-protection.adoc[]".
<.> `Domains` -- домен сервера {dv}.
<.> `DataProtectCertificateThumbprint` -- Отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по настройке системы, раздел "xref:new-admin-console@engineer:ROOT:account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно удалить.
<.> `SystemUserAccount` -- имя системной учётной записи {dv}.
+
include::new-admin-console@install-linux:ROOT:partial$excerpts.adoc[tags=system-accounts]
+
<.> `SystemUserPassword` -- пароль системной УЗ рекомендуется хранить в зашифрованном виде, см. подробнее в документации по настройке системы, раздел "xref:new-admin-console@engineer:ROOT:account-protection.adoc[]".
<.> `Logging` -- настройка упразднена, используйте параметр `LogFile` или настройте журналирование с помощью xref:6.1@platform:console:logs.adoc#file[NLog].

****
* После установки на сервере необходимо настроить группы безопасности. Группы безопасности настраиваются в секции `"Groups"` конфигурационного файла `appsettings.json`.
+
.Пользователь, выполняющий установку и настройку системы должен входить в группы *{dv-admins-serv}* и *{dv-sec-admins-serv}* -- администраторы системы и администраторы безопасности системы.
// * *{dv-web-admin-cns-admins-serv}*. Пользователи, входящие в эту группу, имеют право работать с xref:6.1@mgmtconsole:admin:install-server.adoc[Консолью управления {dv}].
+
* Также через конфигурационный файл выполняется настройка клиентской части, см. подробнее xref:6.1@platform:console:config-client.adoc[].
****

[#connection-string]
=== Строка подключения к БД

.{mssql}
****
`Initial Catalog=Имя-БД-{dv}; Data Source=Полное-имя-сервера-СУБД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****

.{pgsql}/{pgl}
****
`Server=Адрес-сервера-базы-данных; Port=SQL-порт; Database=Название-БД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****
