= Сведения об установке на Windows

Настоящее руководство является обобщенной инструкцией по установке системы {dv} 6 (системы) в ОС {ms} Windows.

.Руководство приводит следующую информацию:
- Требования базовых модулей системы к аппаратному и программному обеспечению.
- Рекомендации по первоначальной настройке системы.

Подробная инструкция по установке и настройке каждого модуля приведена в руководстве администратора соответствующего модуля.

.Инструкция актуальна для следующих версий модулей {dv}:
* {dv} {pl} версии {pl-cu-mc}.
* {dv} Служба {ws} версии {worker-cu-mc}.
* {dv} {bo} версии {bo-cu-mc}.
* {dv} {wf} версии {wf-cu-mc}.
* {dv} {dm} версии {ud-cu-mc}.
* {dv} {ad} версии {ad-cu-mc}.
* {dv} {wincl} версии {win-cu-mc}.

Система {dv} предназначена для автоматизации управления документами и бизнес-процессами компании. Все модули, за исключением модуля {pl}, являются зависимыми, т.е. для их работы требуются другие модули.

.Модули {dv}, как правило, состоят из двух частей:
* Серверной -- для установки на компьютер с сервером {dv}.
* Клиентской -- для установки на пользовательские компьютеры.

Для серверной и клиентской части предоставляются отдельные пакеты установки. Если модуль включает только одну часть (как правило, серверную), предоставляется один пакет установки.

.Назначение пакета установки отражено в его названии (бывают исключения):
* {dv} Platform **server**.msi -- *серверная* часть модуля.
* {dv} Platform **client**.msi -- *клиентская* часть модуля.
