= Установка клиентских компонентов модулей

Для работы с системой {dv} пользователи (клиенты) могут использовать {wincl}, установленный на компьютеры.

.{wincl} может быть установлен двумя способами:
* <<fromServer,С сервера {dv}>> -- требуемые компоненты будут загружены с сервера {dv} и установлены автоматически.
* <<fromMsi,Из пакета установки (вручную)>> -- администратор должен самостоятельно установить клиентские части модулей {pl} и {wincl}, остальные базовые модули будут установлены автоматически.

Клиентские компоненты модулей могут быть установлены для текущего пользователя или для всех пользователей компьютера.

.Область установки выбирается:
* С помощью настройки menu:{cns}[Настройки сервера > Настройка клиентской части > Область установки] -- если компоненты устанавливаются <<fromServer,с сервера>> {dv}.
* При установке клиентской части модуля {pl} -- если компоненты устанавливаются <<fromMsi,вручную>>.

[#fromServer]
== Установка {wincl}а с сервера {dv}

include::new-admin-console@winclient:admin:install.adoc[tags=auto]

[#fromMsi]
== Установка {wincl}а из установочного пакета

. Запустите мастер установки клиентской части модуля {pl}footnote:[После установки серверной части, клиентские дистрибутивы соответствующих версий доступны в каталоге `C:\Program files\Docsvision\Platform\Site\Setup` (по умолчанию) на машине с установленным модулем {pl}.], открыв `{dv} Platform client.msi`. Нажмите *Далее*.
. Примите условия лицензионного соглашения для продолжения установки и нажмите *Далее*.
+
include::dev@mgmtconsole:servers:partial$excerpts.adoc[tags=client-path]
+
. Будет открыто окно выбора каталога установки модуля {pl}. Если требуется, измените каталог установки. Нажмите *Далее*.
. Чтобы начать установку, нажмите *Установить*. Дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
. Установите клиентскую часть модуля {wincl}, из пакета установки `{dv} WindowsClient.msi`. Для продолжения нажмите *Далее*.
+
WARNING: Если клиентская часть модуля {pl} установлена для всех пользователей, для установки {wincl}а потребуются права администратора.
+
. Примите условия лицензионного соглашения, нажмите *Далее*.
. Выберите дополнительные компоненты для установки и нажмите *Далее*.
+
NOTE: Можно отключить установку компонента Интеграция с Google Chrome, если не требуется возможность открытия ссылок на карточки {dv} с помощью веб-браузера Google Chrome.
+
. Чтобы начать установку, нажмите *Установить*. Дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
+
****
На рабочем столе и в меню Пуск будут размещены ярлыки для запуска {wincl}а и РМА.
****
+
. Установите клиентские части оставшихся базовых модулей одним из двух способов:
* Запустите {wincl}. Когда {wincl} подключится к серверу {dv}, будут установлены клиентские части базовых модулей, которые уже установлены на сервере {dv}.
+
WARNING: Если в программе _{cns}_ выбрана область установки клиентских компонентов _Для всех пользователей_, {wincl} должен быть запущен с правами администратора.
+
* Аналогично установке клиентской части модуля {wincl} установите клиентские части модулей из пакетов установки:
** `{dv} BackOffice client.msi` -- {bo}.
** `{dv} Workflow client.msi` -- {wf}.,
** `{dv} DocumentManagement client.msi` -- {dm}.
** `{dv} ApprovalDesigner client.msi` -- {ad}.
** `{dv} TakeOffice client.msi` -- {to}.
** `{dv} Worker service client.msi` -- Служба {ws}.
+
[NOTE]
====
Чтобы избежать ошибок, всегда устанавливайте клиентскую часть модуля _{to}_ после модуля {wincl}.
====
