// См. также xref:dv6@upgrade:54-61:windows/install-client.adoc[в обновлении системы] и xref:6.1@winclient:admin:install.adoc[в установке винклиента].

= {what} клиентских компонентов модулей

.{what} клиентских компонентов происходит двумя способами:
* <<fromServer,С сервера {dv}>> -- требуемые компоненты будут получены с сервера {dv} и обновлены автоматически после запуска {wincl}а.
+
** Компоненты будут установлены с областью установки, указанной в конфигурационном файле {wincl}а (см. "xref:6.1@platform:console:config-client.adoc[]" в документации модуля {pl}).
+
* <<fromMsi,Из пакета установки (вручную)>> -- администратор должен самостоятельно обновить клиентские компоненты всех модулей системы.
+
** Компоненты будут установлены с областью установки клиентской части модуля {pl}.

[#fromServer]
== {what} клиентских компонентов с сервера {dv}

. Запустите мастер установки клиентских компонентов модуля {pl}footnote:[После установки серверных компонентов, клиентские дистрибутивы соответствующих версий доступны в каталоге menu:Каталог-установки-модуля-{pl}[wwwroot > Setup] на машине с установленным модулем {pl}.], открыв `{dv} Platform client.msi`. Нажмите *Далее*.
. Примите условия лицензионного соглашения для продолжения установки и нажмите *Далее*.
. Будет открыто окно выбора каталога установки модуля {pl}. Если требуется, измените каталог установки. Нажмите *Далее*.
. Чтобы начать установку, нажмите *Установить*. Дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
. Установите клиентские компоненты модуля {wincl}, из пакета установки `{dv} WindowsClient.msi`. Для продолжения нажмите *Далее*.
. Примите условия лицензионного соглашения, нажмите *Далее*.
. Выберите дополнительные компоненты для установки и нажмите *Далее*.
+
NOTE: Можно отключить установку компонента Интеграция с Google Chrome, если не требуется возможность открытия ссылок на карточки {dv} с помощью веб-браузера Google Chrome.
+
. Чтобы начать установку, нажмите *Установить*. Дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
ifdef::upgrade[]
+
. Перед запуском {wincl}а убедитесь, что было выполнено восстановление клиентских компонентов модуля {pl}.
+
Восстановите компоненты из инсталлятора, если этого не было выполнено ранее.
include::dv6@upgrade:61-mc62:linux/uninstall-current.adoc[tags=restore-1]
endif::upgrade[]
. Запустите {wincl}, инсталляторы клиентских компонентов для остальных модулей запустятся автоматически.

[#fromMsi]
== {what} клиентских компонентов из установочного пакета

. Последовательно запустите установочные пакеты перечисленных ниже модулей и нажмите *Далее*:
+
После {chego} серверных компонентов, клиентские дистрибутивы соответствующих версий доступны в каталоге menu:Каталог-модуля-{pl}[wwwroot > Setup] на машине с модулем {pl}.
+
** `{dv} Platform client.msi` -- {pl}.
** `{dv} WindowsClient.msi` -- {wincl}.
** `{dv} BackOffice client.msi` -- {bo}.
** `{dv} Workflow client.msi` -- {wf}.
** `{dv} DocumentManagement client.msi` -- {dm}.
** `{dv} ApprovalDesigner client.msi` -- {ad}.
** `{dv} TakeOffice client.msi` -- {to}.
** `{dv} Worker service client.msi` -- Служба {ws}.
+
[NOTE]
====
Чтобы избежать ошибок, всегда обновляйте клиентскую часть модуля _{to}_ после модуля {wincl}.
====
+
. Примите условия лицензионного соглашения для продолжения {chego} и нажмите *Далее*.
. Нажмите *Установить* и дождитесь завершения {chego}.
. Нажмите кнопку *Готово*, процесс {chego} будет завершён.
+
WARNING: Если клиентские компоненты устанавливались _Для всех пользователей_, {wincl} должен быть запущен с правами администратора.

include::6.1@winclient:admin:install.adoc[tags=wincl-ext]
