= Действия после {chego} сервера

[#webc]
== Настройка {wc}а

После обновления БД выполните настройку программ {pu} и {kvr}.

include::6.1@webclient:admin:install-server.adoc[tags=kvr-pu]

[#disable-cache]
== Отключите клиентское кэширование

Рекомендуется отключить кэширование карточек и файлов на компьютере с сервером {dv}, для избежания переполнения клиентского кэша из-за работы СУБП, следствием чего может стать замедление обработки БП. Настройка выполняется в секции "Site" конфигурационного файла {wincl}а по адресу `/usr/lib/docsvision/platform/config/windows-client-part.json`.

include::6.1@platform:console:section-server.adoc[tags=cl-cache]

[#install-ft]
== Установка сервиса полнотекстового индексирования

. Установите сервис полнотекстового индексирования.
. Все настройки сервиса полнотекстового индексирования хранятся в конфигурационном файле `appsettings.json`. Откройте конфигурационный файл в любом текстовом редакторе.
. Выполните необходимые настройки сервиса:
+
--
[source,json]
----
{
  "DocsVision": {
    "Platform": {
      "Server": {
        "LogFile": "/var/log/docsvision/fulltextservice.log", <.>
        "Databases": {
          "alias": "CONNECTION-STRING" <.>
        }
      }
    }
  },
  "DataProtectCertificateThumbprint": "thumbprint", <.>
  "SystemUserAccount": "account@domain.com", <.>
  "SystemUserPassword": "password" <.>
}
----
<.> Путь к файлу журнала полнотекстового поиска.
<.> Строка подключения к индексируемой БД.
<.> Отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по настройке системы, раздел "xref:dv6@engineer:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно удалить.
<.> Имя системной учётной записи {dv}.
+
include::dv6@install-linux:ROOT:partial$excerpts.adoc[tags=system-accounts]
+
<.> Пароль системной учётной записи рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по настройке системы, раздел "xref:dv6@engineer:ROOT:appendix/account-protection.adoc[]".
--
+
. Запустите сервис полнотекстового поиска.

[#group]
== Настройка группы пользователей на контроллере домена

Если серверная часть модуля была установлена на компьютер, являющийся контроллером домена, нужно вручную добавить в локальную группу безопасности _{dv-users-serv}_ пользователей, которые будут работать с системой {dv}.
