= Установка пакета утилит {rk} и {wc} Toolkit

Если планируется использовать {cns}, Полнотекстовый поиск, {kvr} и DVWebTool необходимо установить пакет утилит {rk} и {wc} Toolkit на клиентскую машину с {wincl}ом.

{cns} входит в инсталлятор `ResourceKit.msi`.

Пакет утилит {rk} содержит системные утилиты для специалистов системы, включая программу {cns}. "xref:new-admin-console@resource-kit:console:db-settings.adoc[Базы данных]" (в сокращённом виде), "xref:new-admin-console@resource-kit:console:section-transformations-generator.adoc[Генератор преобразований]", "xref:new-admin-console@resource-kit:console:security-report.adoc[Отчёт по безопасности]", "xref:new-admin-console@resource-kit:console:folder-rights.adoc[Права папок]", "xref:new-admin-console@resource-kit:console:folder-views.adoc[Представления папок]", "xref:new-admin-console@resource-kit:console:full-text-service.adoc[Сервис полнотекстового поиска]"

include::new-admin-console@resource-kit:admin:install.adoc[leveloffset=+1]

include::new-admin-console@resource-kit:console:full-text-service.adoc[leveloffset=+1]

CAUTION: Дальнейшая настройка полнотекстового поиска выходит за рамки текущего руководства, подробное руководство приведено в документации Консоли настройки в составе пакета утилит {rk}, см. "xref:new-admin-console@resource-kit:console:full-text-service.adoc[]" .

include::new-admin-console@webclient:admin:install-server.adoc[tags=kvr-pu]
