:page-aliases: ininstall-docsvision.adoc

= Удаление системы {dv}

// tag::deletion[]
. Удалите поочерёдно все серверные компоненты {dv} с серверов и пользовательских компьютеров стандартным образом через меню "Установка и удаление программ".
. Удалите все серверные компоненты {dv} стандартным образом.
+
Перед удалением сохраните настройки сервера (названия подключенных баз данных, учетные записи сервисов, имена почтовых профилей, настройки производительности сервиса Workflow, и другие), которые можно найти в Консоли настройки {dv}.
+
. При удалении модуля {pl} будет предложено удалить или сохранить настройки сервера {dv}, настройки нужно удалить.
+
Порядок удаления системы {dv} строго не регламентирован, за исключением двух условий:
+
* Модуль {pl} удаляйте в последнюю очередь.
* Серверная часть модулей должна быть удалена в первую очередь.
+
. Удалите стандартным образом компоненты {dv} на кластерах и отдельных серверах, например, для модулей "{wf}", "Служба {ws}" и "{mc}".
. Если был отдельно установлен сервис полнотекстового поиска, удалите его стандартным образом.
. Перезагрузите компьютеры.
// end::deletion[]
