[NOTE]
====
* Чтобы чтение реквизитов проходило корректно, поле _Организация подписанта_ всегда должно быть заполнено. У выбранной организации в справочнике сотрудников или контрагентов должен быть задан ИНН. Для организаций, ИП или физических лиц следует создавать отдельную запись в справочнике с указанием ИНН.
// tag::box[]
ifdef::panel[]
* Если в системе зарегистрированы одна организация и один ящик, панель выбора подразделения и ящика организации не открывается. При этом, если не было диалога подписи, то показывается диалог подтверждения с текстом
ifndef::notice[]
`Отправить документ контрагенту?`.
endif::[]
ifdef::notice[]
`Отправить приглашение контрагенту?`.
endif::[]
+
Если в справочнике настроек операторов ЮЗДО зарегистрировано несколько организаций, поле _Подразделение_ по умолчанию будет заполнено организацией текущего сотрудника.
endif::panel[]
// end::box[]
ifdef::webuser[]
* При подписании может появляться сообщение `ФИО подписанта в документе не совпадает с ФИО выбранного сертификата`, информационное сообщение можно проигнорировать.
Сообщение вызвано проверкой соответствия ФИО в поле _Подписант_ данным SN и G из поля "Субъект" сертификата, использованного при подписании.
endif::[]
====