= Обновление клиентских компонентов модулей

.Обновление {wincl}а может быть установлена двумя способами:
* <<fromServer,С сервера {dv}>> -- требуемые компоненты будут получены с сервера {dv} и обновлены автоматически.
* <<fromMsi,Из пакета установки (вручную)>> -- администратор должен самостоятельно обновить клиентские части модулей {pl} и {wincl}, обновленияы остальных базовых модулей будут установлены автоматически.

[#fromServer]
== Обновление {wincl}а с сервера {dv}

include::new-admin-console@winclient:admin:install.adoc[tags=auto]

[#fromMsi]
== Обновление {wincl}а из установочного пакета

После обновления серверной части, клиентские дистрибутивы соответствующих версий доступны в каталоге `C:\Program files\Docsvision\Platform\Site\Setup` (по умолчанию) на машине с модулем {pl}.

. Запустите мастер установки клиентской части модуля {pl}, открыв `{dv} Platform client.msi`. Нажмите *Далее*.
. Примите условия лицензионного соглашения для продолжения установки и нажмите *Далее*.
+
include::dev@mgmtconsole:servers:partial$excerpts.adoc[tags=client-path]
+
. Чтобы начать установку обновления, нажмите *Установить*. Дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
. Обновите клиентскую часть модуля {wincl}, из пакета установки `{dv} WindowsClient.msi`. Для продолжения нажмите *Далее*.
. Примите условия лицензионного соглашения, нажмите *Далее*.
. Выберите дополнительные компоненты для обновления и нажмите *Далее*.
+
NOTE: Можно отключить установку компонента Интеграция с Google Chrome, если не требуется возможность открытия ссылок на карточки {dv} с помощью веб-браузера Google Chrome.
+
. Чтобы начать установку обновления, нажмите *Установить*. Дождитесь завершения.
. Нажмите кнопку *Готово*, чтобы завершить установку.
+
****
На рабочем столе и в меню Пуск будут размещены ярлыки для запуска {wincl}а и РМА.
****
+
. Обновите клиентские части оставшихся базовых модулей одним из двух способов:
+
* Запустите {wincl}. Когда {wincl} подключится к серверу {dv}, будут обновлены клиентские части базовых модулей, доступных на сервере {dv}.
+
WARNING: Если клиентские компоненты устанавливались _Для всех пользователей_, {wincl} должен быть запущен с правами администратора.
+
* По аналогии с клиентскими компонентами модуля {wincl} установите обновления клиентских компонентов модулей из пакетов установки:
** `{dv} BackOffice client.msi` -- {bo}.
** `{dv} Workflow client.msi` -- {wf}.
** `{dv} DocumentManagement client.msi` -- {dm}.
** `{dv} ApprovalDesigner client.msi` -- {ad}.
** `{dv} TakeOffice client.msi` -- {to}.
+
[NOTE]
====
Чтобы избежать ошибок, всегда обновляйте клиентскую часть модуля _{to}_ после модуля {wincl}.
====
+
** `{dv} Worker service client.msi` -- Служба {ws}.

include::new-admin-console@winclient:admin:install.adoc[tags=wincl-ext]
