= Обновление клиентских компонентов модулей

.Обновление {wincl}а может быть установлено двумя способами:
* <<fromServer,С сервера {dv}>> -- требуемые компоненты будут получены с сервера {dv} и обновлены автоматически после запуска {wincl}а.
* <<fromMsi,Из пакета установки (вручную)>> -- администратор должен самостоятельно обновить клиентские части всех модулей системы.

[#fromServer]
== Обновление клиентских компонентов с сервера {dv}

. Перед запуском {wincl}а убедитесь, что было выполнено восстановление клиентских компонентов модуля {pl}.
include::61-mc62:linux/uninstall-current.adoc[tags=restore-1]
include::new-admin-console@winclient:admin:install.adoc[tags=auto]
. Запустите пакет установки расширения {wincl}а `{dv} WindowsClient extension.msi`.
+
Если расширение отсутствует или не обновлено, в {wincl}е будут доступны только Справочник сотрудников и Справочник контрагентов. Шаг можно пропустить, если не планируется использовать {wincl}.

[#fromMsi]
== Обновление клиентских компонентов из установочного пакета

После обновления серверной части, клиентские дистрибутивы соответствующих версий доступны в каталоге `C:\Program files\Docsvision\Platform\Site\Setup` (по умолчанию) на машине с модулем {pl}.

. Последовательно мастер установки клиентской части модулей, открыв поочерёдно установочные пакеты, перечисленных ниже, и нажмите *Далее*:
+
** `{dv} WindowsClient.msi` -- {wincl}.
** `{dv} Platform client.msi` -- {pl}.
** `{dv} BackOffice client.msi` -- {bo}.
** `{dv} Workflow client.msi` -- {wf}.
** `{dv} DocumentManagement client.msi` -- {dm}.
** `{dv} ApprovalDesigner client.msi` -- {ad}.
** `{dv} TakeOffice client.msi` -- {to}.
** `{dv} Worker service client.msi` -- Служба {ws}.
+
[NOTE]
====
Чтобы избежать ошибок, всегда обновляйте клиентскую часть модуля _{to}_ после модуля {wincl}.
====
+
. Примите условия лицензионного соглашения для продолжения установки и нажмите *Далее*.
. Чтобы начать установку обновления, нажмите *Установить* и дождитесь завершения установки.
. Нажмите кнопку *Готово*, чтобы завершить установку.
+
WARNING: Если клиентские компоненты устанавливались _Для всех пользователей_, {wincl} должен быть запущен с правами администратора.
