:chego: самоподписанного сертификата шифрования
:encrypt-sserv:
:mdl: {sett-serv}
:gide: на уровне "Локальный компьютер"

= Шифрование настроек в Сервисе настроек

В {sett-serv} сохраняются конфиденциальные данные системы {dv}, например, пароли, ключи, строки подключения и т.д. Так как эти данные являются чувствительными, их рекомендуется шифровать. Данный раздел описывает шаги, необходимые для шифрования настроек, хранимых в Сервисе.

NOTE: Настройка шифрования поддерживается в Сервисе настроек, начиная с версии {sett-serv-encr-req}.

Настройки шифрования указываются в конфигурационном файле {of-sett-serv}, в параметре `EncryptionCertificate`. Требуется использовать самоподписанный сертификат, поддерживающий шифрование/дешифрование данных. Далее приводится инструкция по созданию сертификата и конфигурации {of-sett-serv}.

CAUTION: В конфигурационном файле по умолчанию указан параметр `EncryptionCertificate`, однако шифрование осуществляться не будет, пока не указан один из подчинённых параметров: `Path` или
`Thumbprint`. При необходимости создайте параметры самостоятельно.

[tabs]
======

Указание пути к сертификату::
+
--
.Создание и установка {chego} в Linux:
include::dv6@engineer:ROOT:https-connection.adoc[tags=lin-gen]
--
+
--
.Создание и установка {chego} в Windows:
. В случае с указанием пути к сертификату создание и установка сертификата в Windows аналогична действиям, описанным в разделе "<<lin-cr-cert,Создание {chego} в Linux>>".
+
Готовый сертификат экспортируйте в формате `.pfx` без пароля.
--
+
--
.Указание пути к сертификату
. Укажите путь к сертификату в параметре `Path`:
+
.Фрагмент конфигурационного файла с указанием пути к сертификату:
[source,json]
----
{
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Path": "/folder/certificate.crt" <.>
  }
}
----
<.> `Path` -- Путь к файлу сертификата для шифрования чувствительных данных в Сервисе настроек.
+
. После редактирования конфигурационного файла сохраните изменения и перезапустите службу {sett-serv}.
--

Указание отпечатка сертификата::
+
--
.Создание и установка {chego} в Linux:
include::dv6@engineer:ROOT:https-connection.adoc[tags=lin-gen]
+
include::dv6@engineer:ROOT:appendix/account-protection.adoc[tags=self-signed]
+
include::dv6@engineer:ROOT:https-connection.adoc[tags=ca-certificates]
+
[NOTE]
=====
include::edi:admin:encryption.adoc[tags=cert-loc-l]
=====
--
+
--
.Создание и установка {chego} в Windows:
include::dv6@engineer:ROOT:https-connection.adoc[tags=win-gen]
+
[NOTE]
=====
include::edi:admin:encryption.adoc[tags=cert-loc-w]
=====
--
+
--
.Указание отпечатка сертификата:
. {blank}
+
[subs="specialchars,attributes,quotes"]
В конфигурационном файле по адресу {config-ss} укажите отпечаток сертификата. Использование отпечатка допустимо в случаях, когда путь к сертификату не указан, например если сертификат установлен в операционной системе.
+
.Фрагмент конфигурационного файла с указанием отпечатка сертификата:
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Thumbprint": "certificate-thumbprint"  <.>
  }
}
----
<.> `Thumbprint` -- альтернативный вариант с указанием отпечатка сертификата.
+
. После редактирования конфигурационного файла сохраните изменения и перезапустите службу {sett-serv}.
+
Поиск сертификата по отпечатку будет выполняться в хранилище "Мои сертификаты" от имени пользователя, под которым запускается {sett-serv} (по умолчанию -- системный пользователь {dv} в Linux и Network Service в Windows). На случай если первый поиск не даст результатов, для Windows предусмотрен также поиск сертификата в хранилище "Локальный компьютер".
--

======

[#private]
== Установка сертификата с приватной частью

Следующим шагом необходимо установить приватную часть сертификата в хранилище сертификатов на всех серверах, данные которых шифруются, также включая сервер {of-mc}.

Приватная часть сертификата предназначается для чтения (расшифровки) зашифрованных настроек.

. Разместите полученный сертификат в формате `.pfx` в личное хранилище пользователя, от имени которого запускаются службы модулей.
+
WARNING: Обязательно предоставьте права на чтение файла для сервиса, от имени которого запускается служба {of-sett-serv}!

[#oopsie]
== Особенности настройки шифрования

В данный момент смена сертификата на другой не поддерживается. Если в конфигурационном файле указать новый сертификат, значения останутся зашифрованными, новые настройки шифроваться не будут, а при попытке расшифровать настройки возникнет ошибка.

Чтобы повторно зашифровать или снять шифрование, потребуется заново указать зашифрованные настройки.

Если настройка `EncryptionCertificate` удалена, прочитать зашифрованные свойства будет невозможно до тех пор, пока удалённый сертификат не будет повторно указан в конфигурационном файле.
