:chego: самоподписанного сертификата шифрования
:encrypt-sserv:
:mdl: {sett-serv}

= Шифрование настроек в Сервисе настроек

В {sett-serv} сохраняются конфиденциальные данные системы {dv}, например, пароли, ключи, строки подключения и т.д. Так как эти данные являются чувствительными, их рекомендуется шифровать. Данный раздел описывает шаги, необходимые для шифрования настроек, хранимых в Сервисе.

NOTE: Настройка шифрования поддерживается в Сервисе настроек, начиная с версии {sett-serv-encr-req}.

Настройки шифрования указываются в конфигурационном файле {of-sett-serv}, в параметре `EncryptionCertificate`. Можно использовать, например, самоподписанный сертификат, поддерживающий шифрование/дешифрование данных. Далее приводится инструкция по созданию сертификата и конфигурации {of-sett-serv} на примере самоподписанного сертификата.

CAUTION: В конфигурационном файле по умолчанию указан параметр `EncryptionCertificate`, однако шифрование осуществляться не будет, пока не указан один из подчинённых параметров: `Path` или
`Thumbprint`. При необходимости создайте параметры самостоятельно.

include::dv6@engineer:ROOT:appendix/account-protection.adoc[tags=self-signed]

[#cipher]
== Шифрование настроек сертификатом

После выпуска сертификата необходимо указать в конфигурационном файле по адресу {config-ss} <<path,либо путь к сертификату>>, <<thumbprint,либо отпечаток>>. Использование отпечатка допустимо в случаях, когда путь к сертификату не указан, например если сертификат установлен в операционной системе.

[#path]
== Указание пути к сертификату

--
.Фрагмент конфигурационного файла с указанием пути к сертификату:
[source,json]
----
{
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Path": "/folder/certificate.crt" <.>
  }
}
----
<.> `EncryptionCertificate` -- По умолчанию параметр отсутствует в конфигурационном файле, его необходимо создать самостоятельно.
<.> `Path` -- Путь к файлу сертификата для шифрования чувствительных данных в Сервисе настроек.
--
+
. Сохраните изменения конфигурационного файла и перезапустите службу {sett-serv}.

[#thumbprint]
== Указание отпечатка сертификата

. Сгенерированный ранее самоподписанный сертификат необходимо скопировать в директорию `/usr/local/share/ca-certificates/`.
. Добавьте сертификат в доверенные, скопировав его в директорию `/usr/local/share/ca-certificates/`.
+
.Фрагмент конфигурационного файла с указанием отпечатка сертификата:
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Thumbprint": "certificate-thumbprint"  <.>
  }
}
----
<.> `EncryptionCertificate` -- По умолчанию параметр отсутствует в конфигурационном файле, его необходимо создать самостоятельно.
<.> `Thumbprint` -- альтернативный вариант с указанием отпечатка сертификата.

Поиск сертификата по отпечатку будет выполняться в хранилище "Мои сертификаты" от имени пользователя, под которым запускается {sett-serv} (по умолчанию -- системный пользователь {dv} в Linux и Network Service в Windows). На случай если первый поиск не даст результатов, для Windows предусмотрен также поиск сертификата в хранилище "Локальный компьютер".

include::edi:admin:encryption.adoc[tags=cert-loc]

[#private]
== Установка сертификата с приватной частью

Следующим шагом необходимо установить приватную часть сертификата в хранилище сертификатов на всех серверах, данные которых шифруются, также включая сервер {of-mc}.

Приватная часть сертификата предназначается для чтения (расшифровки) зашифрованных настроек.

. Разместите полученный сертификат в формате `.pfx` в каталог личное хранилище пользователя, от имени которого запускаются службы модулей.
+
WARNING: Обязательно предоставьте права на чтение файла для сервиса, от имени которого запускается служба {of-sett-serv}!

[#oopsie]
== Особенности настройки шифрования

В данный момент смена сертификата на другой не поддерживается. Если в конфигурационном файле указать новый сертификат, значения останутся зашифрованными, новые настройки шифроваться не будут, а при попытке расшифровать настройки возникнет ошибка.

Чтобы повторно зашифровать или снять шифрование, потребуется заново указать зашифрованные настройки.

Если настройка `EncryptionCertificate` удалена, прочитать зашифрованные свойства будет невозможно до тех пор, пока удалённый сертификат не будет повторно указан в конфигурационном файле.
