:chego: самоподписанного сертификата шифрования

= Шифрование настроек в Сервисе настроек

В {sett-serv} сохраняются конфиденциальные данные системы {dv}, например, пароли, ключи, строки подключения и т.д. Так как эти данные являются чувствительными, их рекомендуется шифровать. Данный раздел описывает шаги, необходимые для шифрования настроек, хранимых в Сервисе.

Настройки шифрования указываются в конфигурационном файле {of-sett-serv}footnote:[Настройка шифрования поддерживается в Сервисе настроек, начиная с версии {sett-serv-encr-req}.], в параметре `EncryptionCertificate`. Можно использовать, например, самоподписанный сертификат, поддерживающий шифрование/дешифрование данных. Далее приводится инструкция по созданию сертификата и конфигурации {of-sett-serv} на примере самоподписанного сертификата.

CAUTION: Если в конфигурационном файле не указан параметр `EncryptionCertificate`, шифрование осуществляться не будет.

include::engineer:ROOT:appendix/account-protection.adoc[tags=self-signed]

[#config]
== Конфигурация шифрования {of-sett-serv}

. {blank}
+
[subs="specialchars,attributes,quotes"]
После выпуска сертификата необходимо указать в конфигурационном файле по адресу {config-ss} либо путь, либо отпечаток. Использование отпечатка допустимо в случаях, когда путь к сертификату не указан, например если сертификат установлен в операционной системе.
+
--
.Фрагмент конфигурационного файла:
[tabs]
====

Путь::
+
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Path": "/folder/certificate.crt", <.>
  }
}
----
<.> `EncryptionCertificate` -- По умолчанию параметр отсутствует в конфигурационном файле, его необходимо создать самостоятельно.
<.> `Path` -- Путь к файлу сертификата для шифрования параметров в Сервисе настроек.

Отпечаток::
+
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Thumbprint": "certificate-thumbprint"  <.>
  }
}
----
<.> `EncryptionCertificate` -- По умолчанию параметр отсутствует в конфигурационном файле, его необходимо создать самостоятельно.
<.> `Thumbprint` -- альтернативный вариант с указанием отпечатка сертификата.
+
Поиск сертификата будет выполняться в хранилище "Мои сертификаты" от имени пользователя, под которым запускается {sett-serv} (по умолчанию -- системный пользователь {dv} в Linux и Network Service в Windows). На случай если первый поиск не даст результатов, для Windows предусмотрен также поиск сертификата в хранилище "Локальный компьютер".

====
--
+
. Cохраните изменения конфигурационного файла и перезапустите службу {sett-serv}.

[#private]
== Установка сертификата с приватной частью

Следующим шагом необходимо установить приватную часть сертификата в хранилище сертификатов на всех серверах, данные которых шифруются, также включая сервер {of-mc} и прочие серверы {of-sett-serv}.

Приватная часть сертификата предназначается для чтения (расшифровки) зашифрованных настроек.

. Разместите полученный сертификат в формате `.pfx` в каталог личное хранилище пользователя, от имени которого запускаются службы модулей.
+
WARNING: Обязательно предоставьте права на чтение файла для сервиса, от имени которого запускается служба {of-sett-serv}!

[#open-key]
== Установка сертификата с открытым ключом

Поместите сертификат в хранилище сертификатов текущего пользователя в ОС Windows и в каталог `~/.dotnet/corefx/cryptography/x509stores/my` в ОС Linux. После установки обновите список сертификатов.

NOTE: Сертификат нужно добавлять в домашнюю папку пользователя, от имени которого запускается сервис. Например, для пользователя `root` (от имени пользователя ROOT службы запускаются по умолчанию) полный путь будет: `/root/.dotnet/corefx/cryptography/x509stores/my`. +
Если папка отсутствует, создайте её самостоятельно.

[#oopsie]
== Особенности настройки шифрования

В данный момент смена сертификата на другой не поддерживается. Если в конфигурационном файле указать новый сертификат, значения останутся зашифрованными, новые настройки шифроваться не будут, а при попытке расшифровать настройки возникнет ошибка.

Чтобы повторно зашифровать или снять шифрование, потребуется заново указать зашифрованные настройки.

Если настройка `EncryptionCertificate` удалена, прочитать зашифрованные свойства будет невозможно до тех пор, пока удалённый сертификат не будет повторно указан в конфигурационном файле.
