:chego: самоподписанного сертификата шифрования
:encrypt-sserv:
:mdl: сервис, дешифрующий настройки,
:gide: "Личное" на уровне "Локальный компьютер"

= Шифрование настроек в Сервисе настроек

В {sett-serv} сохраняются конфиденциальные данные системы {dv}, например, пароли, ключи, строки подключения и т.д. Так как эти данные являются чувствительными, их рекомендуется шифровать. Данный раздел описывает шаги, необходимые для шифрования настроек, хранимых в Сервисе.

// tag::sett-serv-version[]
NOTE: Настройка шифрования поддерживается в Сервисе настроек, начиная с {sett-serv-encr-req}.
// end::sett-serv-version[]

Настройки шифрования указываются в конфигурационном файле {of-sett-serv}, в параметре `EncryptionCertificate`. Требуется использовать самоподписанный сертификат, поддерживающий шифрование/дешифрование данных. Далее приводится инструкция по созданию сертификата и конфигурации {of-sett-serv}.

CAUTION: В конфигурационном файле по умолчанию указан параметр `EncryptionCertificate`, однако шифрование осуществляться не будет, пока не указан один из подчинённых параметров: `Path` или
`Thumbprint`. При необходимости создайте параметры самостоятельно.

[#lin-gen]
== Создание самоподписанного сертификата в Linux

include::dv6@engineer:ROOT:https-connection.adoc[tags=lin-gen]

[#win-gen]
== Создание самоподписанного сертификата в Windows

include::dv6@engineer:ROOT:https-connection.adoc[tags=win-gen]

[#config]
== Указание сертификата в конфигурационном файле

. {blank}
+
[subs="specialchars,attributes,quotes"]
В конфигурационном файле по адресу {config-ss} укажите путь к сертификату c публичной частью в параметре `Path` или отпечаток сертификата в параметре `Thumbprint`. Использование отпечатка допустимо, когда сертификат установлен в операционной системе.
+
[tabs]
======

Указание пути к сертификату::
+
.Фрагмент конфигурационного файла с указанием пути к сертификату:
[source,json]
----
{
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Path": "/folder/certificate.crt" <.>
  }
}
----
<.> `Path` -- Путь к файлу сертификата для шифрования чувствительных данных в Сервисе настроек. Пользователь, от имени которого запускается {sett-serv}, должен обладать правами на чтение файла сертификата.

Указание отпечатка сертификата::
+
* Если путь к сертификату не указан, укажите отпечаток сертификата. Использование отпечатка допустимо в случаях, например если сертификат установлен в операционной системе.
+
.Фрагмент конфигурационного файла с указанием отпечатка сертификата:
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Thumbprint": "certificate-thumbprint"  <.>
  }
}
----
<.> `Thumbprint` -- альтернативный вариант с указанием отпечатка сертификата.
+
CAUTION: В ОС Linux поддерживается только сертификат в формате `.pfx`.

======
+
. После редактирования конфигурационного файла сохраните изменения и перезапустите службу {sett-serv}.
+
Поиск сертификата по отпечатку будет выполняться в хранилище "Мои сертификаты" от имени пользователя, под которым запускается {sett-serv} (по умолчанию -- системный пользователь {dv} в Linux и Network Service в Windows). Если первый поиск не даст результатов, для Windows предусмотрен также поиск сертификата в хранилище "Локальный компьютер".

[#private]
== Установка сертификата с приватной частью

Следующим шагом необходимо установить приватную часть сертификата в хранилище сертификатов на всех серверах, данные которых шифруются, также включая сервер {of-mc}.

Приватная часть сертификата предназначается для чтения (расшифровки) зашифрованных настроек.

include::dv6@engineer:ROOT:appendix/account-protection.adoc[tags=self-signed]
+
--
include::edi:admin:encryption.adoc[tags=cert-loc]
--
+
Пользователь, от имени которого запускается сервис, дешифрующий настройки, должен обладать правами на чтение и выполнение файлов в каталоге, а также правами на чтение сертификата.

[#oopsie]
== Особенности шифрования

Чтобы повторно зашифровать или снять шифрование, потребуется заново указать зашифрованные настройки, а именно: Настройки соединений {dv}, Настройки соединения с Почтовым сервером, Настройки Службы {ws}.

Если настройка `EncryptionCertificate` удалена, прочитать зашифрованные свойства будет невозможно до тех пор, пока удалённый сертификат не будет повторно указан в конфигурационном файле.

Если в соединении есть настройка, значение которой не удалось расшифровать, под ней будет выведено сообщение об ошибке. В случае возникновения ошибки чтения/расшифровки существующие:

* _Настройки соединений {dv}_ -- отображаются ранее созданные подключения. Добавленные раннее подключения могут быть изменены или удалены, могут быть добавлены новые подключения.
* _Настройки соединения с Почтовым сервером_ -- отображаются ранее созданные подключения. Добавленные раннее подключения могут быть изменены или удалены, могут быть добавлены новые подключения.
* _Настройки Службы {ws}_ -- отображаются ранее зарегистрированные экземпляры Службы {ws} и добавленные процессы. Могут быть добавлены новые процессы.

.Запуск и восстановление работы компонентов:
* Если при запуске компонента не удается расшифровать хотя бы одну необходимую ему настройку, служба компонента не запускается, а причина записывается в журнал.
* Настройки, которые не удалось расшифровать, можно заново указать через Консоль управления даже если служба настраиваемого компонента не запущена.
* После восстановления всех недоступных для чтения настроек необходимо перезапустить службу соответствующего компонента.