:chego: самоподписанного сертификата шифрования
:encrypt-sserv:
:mdl: сервис, дешифрующий настройки,
:gide: "Личное" на уровне "Локальный компьютер"

= Шифрование настроек в Сервисе настроек

В {sett-serv} сохраняются конфиденциальные данные системы {dv}, например, пароли, ключи, строки подключения и т.д. Так как эти данные являются чувствительными, их рекомендуется шифровать. Данный раздел описывает шаги, необходимые для шифрования настроек, хранимых в Сервисе.

// tag::sett-serv-version[]
NOTE: Настройка шифрования поддерживается в Сервисе настроек, начиная с версии {sett-serv-encr-req}.
// end::sett-serv-version[]

Настройки шифрования указываются в конфигурационном файле {of-sett-serv}, в параметре `EncryptionCertificate`. Требуется использовать самоподписанный сертификат, поддерживающий шифрование/дешифрование данных. Далее приводится инструкция по созданию сертификата и конфигурации {of-sett-serv}.

CAUTION: В конфигурационном файле по умолчанию указан параметр `EncryptionCertificate`, однако шифрование осуществляться не будет, пока не указан один из подчинённых параметров: `Path` или
`Thumbprint`. При необходимости создайте параметры самостоятельно.

== Создание самоподписанного сертификата в Linux

include::dv6@engineer:ROOT:https-connection.adoc[tags=lin-gen]

== Создание самоподписанного сертификата в Windows

.. Если планируется использовать файл сертификата как есть, процесс создания сертификата в Windows аналогичен описанному в разделе "<<lin-cr-cert,Создание {chego} в Linux>>".
+
. Готовый сертификат экспортируйте в формате `.pfx` без пароля.
+
.. Если сертификат устанавливается на уровне системы, процесс создания отличается.
+
include::dv6@engineer:ROOT:https-connection.adoc[tags=win-gen]

== Указание пути к сертификату

. {blank}
+
[subs="specialchars,attributes,quotes"]
В конфигурационном файле по адресу {config-ss} укажите путь к сертификату.
+
Если сертификат сгенерирован отдельным файлом, укажите путь к нему в параметре `Path`.
+
Если путь к сертификату не указан, укажите отпечаток сертификата. Использование отпечатка допустимо, когда сертификат установлен в операционной системе.
+
[tabs]
======

Указание пути к сертификату::
+
.Фрагмент конфигурационного файла с указанием пути к сертификату:
[source,json]
----
{
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Path": "/folder/certificate.crt" <.>
  }
}
----
<.> `Path` -- Путь к файлу сертификата для шифрования чувствительных данных в Сервисе настроек. Пользователь, от имени которого запускается {sett-serv}, должен обладать правами на чтение файла сертификата.

Указание отпечатка сертификата::
+
* Если путь к сертификату не указан, укажите отпечаток сертификата. Использование отпечатка допустимо в случаях, например если сертификат установлен в операционной системе.
+
.Фрагмент конфигурационного файла с указанием отпечатка сертификата:
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey",
  "StorageOptions": {
    "Providers": [
      {
      ...
      }
    ]
  },
  "EncryptionCertificate: {
    "Thumbprint": "certificate-thumbprint"  <.>
  }
}
----
<.> `Thumbprint` -- альтернативный вариант с указанием отпечатка сертификата.
+
CAUTION: В ОС Linux поддерживается только сертификат в формате `.pfx`.

======
+
. После редактирования конфигурационного файла сохраните изменения и перезапустите службу {sett-serv}.
+
Поиск сертификата по отпечатку будет выполняться в хранилище "Мои сертификаты" от имени пользователя, под которым запускается {sett-serv} (по умолчанию -- системный пользователь {dv} в Linux и Network Service в Windows). На случай если первый поиск не даст результатов, для Windows предусмотрен также поиск сертификата в хранилище "Локальный компьютер".
+
. После редактирования конфигурационного файла сохраните изменения и перезапустите службу {sett-serv}.

[#private]
== Установка сертификата с приватной частью

Следующим шагом необходимо установить приватную часть сертификата в хранилище сертификатов на всех серверах, данные которых шифруются, также включая сервер {of-mc}.

Приватная часть сертификата предназначается для чтения (расшифровки) зашифрованных настроек.

include::dv6@engineer:ROOT:appendix/account-protection.adoc[tags=self-signed]
+
Пользователь, от имени которого запускается сервис, дешифрующий настройки, должен обладать правами на чтение и выполнение файлов в каталоге, а также правами на чтение сертификата.
+
--
include::edi:admin:encryption.adoc[tags=cert-loc]
--

[#oopsie]
== Особенности настройки шифрования

В данный момент смена сертификата на другой не поддерживается. Если в конфигурационном файле указать новый сертификат, значения останутся зашифрованными, новые настройки шифроваться не будут, а при попытке расшифровать настройки возникнет ошибка.

Чтобы повторно зашифровать или снять шифрование, потребуется заново указать зашифрованные настройки.

Если настройка `EncryptionCertificate` удалена, прочитать зашифрованные свойства будет невозможно до тех пор, пока удалённый сертификат не будет повторно указан в конфигурационном файле.
