= Установка сервиса настроек

[#sett-serv]
== Установка {of-sett-serv}

.Чтобы установить {sett-serv}:
:of: {of-sett-serv}
:file: appsettings
:wt: settingsservice
include::6.1@platform:admin:partial$install.adoc[]
+
Основные настройки, которые нужно сделать:
+
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey", <.>
  "StorageOptions": {
    "Providers": [
      {
        "Alias": "SqlStorage",
        "Default": true,
        "StorageType": "DB-type", <.>
        "StorageOptions": "CONNECTION-STRING", <.>
        "ProviderType": "Hierarchy"
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Path": "/folder/certificate.crt", <.>
    "KeyPath": "/folder/docsvision.key" <.>
  }
}
----
<.> Ключ доступа к Сервису настроек -- "пароль", который также необходимо указать в конфигурационном файле Сервиса внешнего API и конфигурационном файле {of-mc}.
<.> Тип БД: `MsSql` или `PgSql`.
<.> Строка подключения к БД. См. подробнее "xref:mgmtconsole:admin:install.adoc#conn-string[Строка подключения к базе данных для хранения настроек]" в документации {of-mc}.
<.> Настройки, записываемые в {sett-serv}, рекомендуется защищать при помощи шифрования. Для этой цели используется самоподписанный серификат, поддерживающий шифрование/дешифрование данных. Создайте сертификат локально, например, по инструкции в разделе "xref:install-linux:ROOT:appendix/account-protection.adoc#cr-cert[Защита системной учётной записи]", и установите его в хранилище сертификатов на всех серверах, данные которых шифруются, сервере {of-mc} и серверах Сервиса настроек.
<.> Путь к сертификату для шифрования параметров, хранящихся в Сервисе настроек.
<.> Путь к ключу шифрования сертификата.
+
. Запустите службу сервиса:
+
[source,bash]
----
sudo systemctl start dvsettings
----

[#cluster]
== Настройка кластера {of-sett-serv}

Для обеспечения надежности рекомендуется использовать кластер {of-sett-serv} и регулярно производить резервное копирование базы данных Сервиса.

.Чтобы настроить кластер {of-sett-serv}, выполните следующие действия:
. Установите {sett-serv} на первом и последующих узлах кластера согласно инструкции <<sett-serv,выше>>.
. Убедитесь, что на всех узлах используется один и тот же API ключ доступа и одну и ту же БД для хранения настроек.
. Настройте балансировщик нагрузкиfootnote:[Описание настройк балансировщика выходит за рамки документации {dv}.] с режимом active-passive и укажите адрес балансировщика в конфигурационных файлах компонентов, зарегистрированных в текущем Сервисе настроек.
