= Установка сервиса настроек

[#sett-serv]
== Установка {of-sett-serv}

.Чтобы установить {sett-serv}:
:of: {of-sett-serv}
:file: appsettings
:wt: settingsservice
include::6.1@platform:admin:partial$install.adoc[]
+
Основные настройки, которые нужно сделать:
+
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey", <.>
  "StorageOptions": {
    "Providers": [
      {
        "Alias": "SqlStorage",
        "Default": true,
        "StorageType": "DB-type", <.>
        "StorageOptions": "CONNECTION-STRING", <.>
        "ProviderType": "Hierarchy"
      }
    ]
  }
}
----
<.> Ключ доступа к Сервису настроек -- "пароль", который также необходимо указать в конфигурационном файле Сервиса внешнего API и конфигурационном файле {of-mc}.
<.> Тип БД: `MsSql` или `PgSql`.
<.> Строка подключения к БД. См. подробнее "xref:mgmtconsole:admin:install.adoc#conn-string[Строка подключения к базе данных для хранения настроек]" в документации {of-mc}.
+
. Запустите службу сервиса:
+
[source,bash]
----
sudo systemctl start dvsettings
----

[#cluster]
== Настройка кластера {of-sett-serv}

Для обеспечения надежности рекомендуется использовать кластер {of-sett-serv} и регулярно производить резервное копирование базы данных Сервиса.

.Чтобы настроить кластер {of-sett-serv}, выполните следующие действия:
. Установите {sett-serv} на первом и последующих узлах кластера согласно инструкции <<sett-serv,выше>>.
. Убедитесь, что на всех узлах используется один и тот же API ключ доступа и идну и ту же БД для хранения настроек.
. Настройте балансировщик нагрузки с режимом active-passive и укажите адрес балансировщика в настройках сервисов модулей {mc}, {pl}, {wc}.
+
Проверить проксирование запросов можно при помощи команды `sudo tail -f /var/log/nginx/access.log`, новые записи будут выводиться по мере их появления.
+
Данные настройки выходят за рамки документации {dv}.
