// tag::linux[]
= Установка сервиса настроек

Установка {of-sett-serv} на отдельный от {of-mc} сервер не поддерживается.

[#sett-serv]
.Чтобы установить {sett-serv}:
:of: {of-sett-serv}
:file: appsettings
:wt: settingsservice
include::new-admin-console@platform:admin:partial$install.adoc[]
+
// tag::config[]
Основные настройки, которые нужно сделать:
+
[source,json]
----
{
  "ApiKey": "SettingsServiceApiKey", <.>
  "StorageOptions": {
    "Providers": [
      {
        "Alias": "SqlStorage",
        "Default": true,
        "StorageType": "DB-type", <.>
        "StorageOptions": "CONNECTION-STRING", <.>
        "ProviderType": "Hierarchy"
      }
    ]
  },
  "EncryptionCertificate: { <.>
    "Path": "/folder/certificate.crt", <.>
  }
}
----
<.> Ключ доступа к Сервису настроек -- "пароль", который также необходимо указать в конфигурационном файле модулей {mc}, {pl}, {wc}, {wf}, Служба {ws} и {fs}.
<.> Тип БД: `MsSql` или `PgSql`.
<.> Строка подключения к БД. См. подробнее "<<conn-string,Строка подключения к базе данных для хранения настроек>>" далее.
<.> Настройки, записываемые в {sett-serv}, рекомендуется защищать при помощи шифрования. Для этой цели используется самоподписанный серификат, поддерживающий шифрование/дешифрование данных. Создайте сертификат локально, например, по инструкции в разделе "xref:install-linux:ROOT:appendix/account-protection.adoc#cr-cert[Защита системной учётной записи]", и установите его в хранилище сертификатов "Доверенные корневые центры сертификации" на уровне "Локальный компьютер": на всех серверах, данные которых шифруются, сервере {of-mc} и серверах Сервиса настроек.
<.> Путь к публичной части сертификата для шифрования параметров в Сервисе настроек.
// end::config[]
// end::linux[]
+
. Запустите службу сервиса:
+
[source,bash]
----
sudo systemctl start dvsettings
----

// tag::linux[]

[#cluster]
== Настройка кластера {of-sett-serv}

Для обеспечения надежности рекомендуется использовать кластер {of-sett-serv} и регулярно производить резервное копирование базы данных Сервиса.

.Чтобы настроить кластер {of-sett-serv}, выполните следующие действия:
. Установите {sett-serv} на первом и последующих узлах кластера согласно инструкции <<sett-serv,выше>>.
. Убедитесь, что на всех узлах используется один и тот же API ключ доступа и одну и ту же БД для хранения настроек.
. Настройте балансировщик нагрузкиfootnote:[Описание настройк балансировщика выходит за рамки документации {dv}.] с режимом active-passive и укажите адрес балансировщика в конфигурационных файлах компонентов, зарегистрированных в текущем Сервисе настроек.
// end::linux[]

include::dev@mgmtconsole:admin:install.adoc[tags=string]

include::dev@mgmtconsole:admin:install.adoc[tags=cert]

[#deletion]
== Удаление {of-sett-serv}

Чтобы удалить {of-sett-serv}, выполните команду:

include::new-admin-console@platform:admin:partial$delete.adoc[]

Созданные группы и службы будут удалены, _{sett-serv}_ станет недоступен.
