[#azure]
== Регистрация расширения Azure

[source,json]
----
{
  "Docsvision": {
    "Platform": {
      "Server": {
        "Authentication": {
          "Extensions": {
            "AzureAD": {
              "Name": "AzureAD", <.>
              "TypeName": "DocsVision.Platform.Authentication.AzureAD.AzureADRootAuthenticationExtension, DocsVision.Platform.Authentication.AzureAD, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7148AFE997F90519", <.>
              "Settings": "<?xml version=\"1.0\" encoding=\"utf-16\"?><AzureADAuthenticationSettings xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><WellKnownConfigurationUrl>https://login.microsoftonline.com/common/.well-known/openid-configuration</WellKnownConfigurationUrl><ClientId>c6c5c5e8-c320-4221-bbdf-205f8ff9610e</ClientId><GroupMembershipCheckerSettings><GroupMappings><AzureADGroupMapping><GroupId>94e14c7f-dbe9-42f4-8895-ac95c3dc8910</GroupId><Role>User</Role></AzureADGroupMapping></GroupMappings></GroupMembershipCheckerSettings><Tenants><guid>94e14c7f-dbe9-42f4-8895-ac95c3dc8910</guid></Tenants><ApplicationId>c6c5c5e8-c320-4221-bbdf-205f8ff9610e</ApplicationId></AzureADAuthenticationSettings>", <.>
              "Id": "{D4A9BCC3-E897-47AE-BBA5-8F5085D231E7}" <.>
            }
          },
          "Tenants": { <.>
            "CurrentDB": {
              "Extensions": "{D4A9BCC3-E897-47AE-BBA5-8F5085D231E7}", <.>
              "Name": "CurrentDB" <.>
            }
          }
        }
      }
    }
  }
}
----
<.> `Name` -- задаёт отображаемое имя сервиса аутентификации в справочнике сотрудников.
<.> `TypeName` -- строка с именем типа, реализующего расширение.
<.> `Settings` -- строка настроек расширения, для AzureAD. Подробнее см. <<azure-settings,ниже>>.
<.> `ID` -- строка с идентификатором расширения в виде Guid.
<.> `Tenants` -- в параметре указываются расширения аутентификации для конкретных БД {dv}.
<.> `Extensions` -- строка, содержащая идентификаторы расширений аутентификации для конкретной БД в виде списка Guid через `;` (точка с запятой).
<.> `Name` -- строка, содержащая псевдоним БД, например: `CurrentDB`.

// tag::azure[]
[#azure-settings]
=== Строка настроек Azure

include::partial$excerpts.adoc[tags=pretty]

[source,xml]
----
<?xml version="1.0" encoding="utf-16"?>
<AzureADAuthenticationSettings
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <WellKnownConfigurationUrl>https://login.microsoftonline.com/common/.well-known/openid-configuration</WellKnownConfigurationUrl> <.>
  <ClientId>c6c5c5e8-c320-4221-bbdf-205f8ff9610e</ClientId> <.>
  <GroupMembershipCheckerSettings>
    <GroupMappings>
      <AzureADGroupMapping> <.>
        <GroupId>94e14c7f-dbe9-42f4-8895-ac95c3dc8910</GroupId> <.>
        <Role>User</Role> <.>
      </AzureADGroupMapping>
    </GroupMappings>
  </GroupMembershipCheckerSettings>
  <Tenants>
    <guid>94e14c7f-dbe9-42f4-8895-ac95c3dc8910</guid>
  </Tenants>
  <ApplicationId>c6c5c5e8-c320-4221-bbdf-205f8ff9610e</ApplicationId> <.>
</AzureADAuthenticationSettings>",
----
<.> `WellKnownConfigurationUrl` -- URL публичной конфигурации OpenID.
<.> `ClientId` -- идентификатор тенанта AzureAD в котором производится привязка пользователей.
<.> `AzureADGroupMapping` -- задает сопоставление групп Azure AD системным xref:backoffice:desdirs:staff/groups/system-groups.adoc[группам безопасности {dv}]. Допускается на одну группу Azure AD создавать несколько групп {dv}.
<.> `GroupId` -- идентификатор группы Azure AD.
<.> `Role` -- имя группы без префикса "{dv}".
<.> `ApplicationId` -- идентификатор приложения {dv}, зарегистрированного в тенанте AzureAD, для которого включено и настроено использование OpenID Connect.
// end::azure[]