:link: https://github.com/Docsvision/WebClient-Samples/tree/master/ServerExtensions/FormationDescriptionsLinks
:name: FormationDescriptionsLinks

= Расширение для формирования описаний ссылок

Данный раздел содержит описание примера расширения для формирования описаний ссылок.

include::../client/authorization.adoc[tags=link]

include::6.1@webclient:ROOT:partial$excerpts.adoc[tags=wc-node]
include::6.1@webclient:ROOT:partial$excerpts.adoc[tags=vscode]

== Сборка и установка

. Откройте `/Samples.sln`.
. Соберите проект `ServerExtensions > FormationDescriptionsLinks > FormationDescriptionsLinksServerExtension`.
+
[source,csharp]
----
public class FormationDescriptionsLinksWebClientExtension : WebClientExtension
    {
        public FormationDescriptionsLinksWebClientExtension(IServiceProvider serviceProvider) <.>
            : base()
        {
        }

        public override string ExtensionName <.>
        {
            get { return Assembly.GetAssembly(typeof(FormationDescriptionsLinksWebClientExtension)).GetName().Name; }
        }

        public override Version ExtensionVersion <.>
        {
            get { return new Version(FileVersionInfo.GetVersionInfo(Assembly.GetExecutingAssembly().Location).FileVersion); }
        }

        #region WebClientExtension Overrides

        public override void InitializeServiceCollection(IServiceCollection services) <.>
        {
            services.AddTransient<ICardsPresentationExtension, CustomCardsPresentation>();
        }

        #endregion
    }

----
<.> Создаёт новый экземпляр `FormationDescriptionsLinksWebClientExtension`.
+
.Параметры:
* `serviceProvider` -- Сервис-провайдер
+
<.> Получить название расширения.
<.> Получить версию расширения.
<.> Регистрация типов в IoC контейнере
+
.Параметры:
* `containerBuilder` -- конструктор контейнеров.
+
. Скопируйте каталог `SamplesOutput\Site\Extensions\FormationDescriptionsLinksServerExtension` в каталог `Путь к сайту Web-клиента\Extensions`.
. Перезапустите *{wcs-new}*.

== Проверка примера

. Запустите конструктор разметок.
. Откройте для редактирования любую карточку документа.
. Добавьте или откройте для редактирования уже существующий ЭУ "xref:layouts:ctrl/special/links.adoc[]".
. В свойстве "Наименование метода для описания" укажите название расширения данного проекта: `CustomCardsPresentation`.
. Сохраните разметку.
. Перезапустите *{wcs-new}*.
. Откройте карточку с этой разметкой.
. Добавьте ссылку на документ.
. Убедитесь, что рядом с названием ссылки добавился текст из расширения: `[is EXTENSION]`.

== Проект "FormationDescriptionsLinksServerExtension"

Проект-расширение для {wc}а. Содержит бизнес-логику для формирования описаний ссылок.
Демонстрирует расширение функциональности с помощью добавления новых объектов.

Создано расширение представления `CustomCardsPresentation`, реализующее `ICardsPresentationExtension`.
Расширение представления должно иметь уникальное наименование `ExtensionName` и возвращать представление ссылок `GetPresentation`.

