= Изменения в релизной версии

* Модуль переведён на .NET 8.0.
* Разработаны страницы, содержащие общие настройки сервера приложений, {wc} и {wf}.
* Поддержана возможность получения настроек конфигурации для сервера приложений, {wc} и {wf} из {of-sett-serv}, если адрес {of-sett-serv} указан в конфигурационном файле соответствующих модулей.
* Разработаны страницы дополнительных настроек сервера приложений, {wc} и {wf} для настроек, не вынесенных в пользовательский интерфейс.
* Разработаны и поддержаны компоненты редактирования, необходимые для настройки сервера приложений, {wc} и {wf} в {of-mc}.
* Разработаны расширения: Сервера приложений, {wc} и {wf} для {of-mc}, расширения поставляют разметки страниц настроек для {of-mc}, специализированные компоненты редактирования, а также другие связанные с модулями ресурсы.
* Разработаны страницы и компоненты редактирования для работы с БД, включая создание, подключение, обновление и другие.
* Некоторые конфигурации могут блокироваться на время применения настроек, для таких случаев разработана страница блокировок конфигураций.
* Обновлена стартовая страница настроек {of-mc}, страница настроек соединений, почтового сервера и службы фоновых операций.
* Исходный код {of-mc} был переработан для приведения к системе плагинов, определяющих интерфейс настроек модуля в Консоли и взаимодействие с сервисом настроек.
* Виджеты настройки Службы {ws} в {of-mc} переведены на схему работы через настраиваемые компоненты редактирования.
* В {of-mc} добавлено отображение настроек при отсутствии компонента редактирования. Если компонент редактирования настроек отсутствует, отображается нередактируемое поле и сообщение `Не удалось загрузить "Редактор". Убедитесь что установлено расширение компонента для Консоли управления`.
* Разработана страница, содержащая серверы, зарегистрированные в Сервисе настроек.
* Разработана страница "Серверы", на которой отображается список серверов, информация о выбранном сервере и список установленных на нём компонентов.
* Разработан API, позволяющий подключать существующие БД из {of-mc}.
* Поддержан вход в {mc} по протоколу LDAPS с использованием учётной записи из доменного каталога ALD Pro.
