= Документация для разработчиков

Данный раздел документации предназначен для разработчиков {dv}. Документация поделена на две основные части:

* "xref:development.adoc[Руководство по разработке на платформе {dv}]" -- работа с API системы и разработка компонентов для модулей {pl}, {bo}, {wf} и других на языке C#.
* "xref:WebClient:index.adoc[Руководство по разработке web-решений]" -- разработка решений и компонентов на базе модуля {wc} на ReactJS.

[#platform]
== Руководство по разработке платформы {dv}

Первоочередная задача этого руководства --  рассказать о возможностях использования и дать разработчику практические примеры работы с API {dv}. При необходимости примеры сопровождаются фрагментами API {dv} на языке C# для разработки в среде Visual Studio.

Для получения справочной информации по программному коду системы рекомендуется обращаться к описанию объектной модели {dv}: "xref:DocsVisionObjectModel:class-lib.adoc[]".

Документация касается общего устройства {dv} и приложений системы, а также даёт рекомендации по работе с прогрммным кодом системы. В соответствующих разделах приводятся примеры разработки скриптов и карточек, расширяющих стандартную функциональность системы и необходимые меры предосторожности при модификации стандартных компонентов.

При отсутствии необходимой функциональности в стандартной поставке системы разработчик может создать собственные карточки и решения, добавляющие или расширяющие стандартную бизнес-логику. Данное руководство описывает разработку скриптов в бизнес-процессах для реализации действий, недоступных по умолчанию.

Если функциональности стандартных утилит, конструкторов и справочников недостаточно,разработчик может интегрировать в {dv} сторонние утилиты, которые будут получать данные и передавать их в систему.

[#web]
== Руководство по разработке web-решений

Раздел "xref:WebClient:index.adoc[Руководство по разработке web-решений]" посвящён разработке на базе модуля {wc} и включает, но не ограничивается следующей информацией: создание клиентских скриптов, созданией расширений модуля и программы {kvr}, изменение и добавление новых элементов управления, дополнительных компонентов модуля, комментарии к исходному коду {wc}а и прочую информацию, необходимую для разработки в web-среде.

Руководство по разработке web-решений требует от разработчика опыта в разработке компонентов на ReactJS и общего знания системы {dv}.

[#edi]
== Руководство по разработке {of-em}

Раздел xref:Edi:index.adoc[] описывает возможности по разработке компонентов для _Справочника настроек операторов ЮЗДО_. Сюда входят как компоненты для создания, чтения и изменения карточек {dv}, так и компоненты коннекторов к операторам ЭДО, включая сервис сообщений, импор и работа с ЭП.

Вынесенная в компоненты функциональность модуля позволяет абстрагировать механизм отправки электронных документов от видов карточек и механизмов взаимодействия с операторами ЭДО.

[#m4dreg]
== Руководство по разработке {of-mir}

В разделе xref:M4dRegistry:index.adoc[] описывается API и обращение с программным кодом модуля. В разделе документации описывается API для выполнения действия с доверенностью, такие как регистрация, проверка статуса и отзыв, а также для обработки сообщений.

[#worker]
== Руководство по разработке модуля Служба {ws}

Документация разработчика модуля Служба {ws} содержит описание объектной модели модуля.
