= Расширение возможностей ЭУ "Записи справочников"

Элемент управления "Записи справочников" позволяет задать список дополнительных полей элементов и логику их получения с помощью программного расширения.

.Чтобы задать список дополнительных полей:
. Создайте серверное расширение {wc}а и добавьте в него класс, реализующий интерфейс `DocsVision.DirectoryItemsCollection.WebServerExtension.Extensibility.IDirectoryItemsCollectionAdditionalFieldsPlugin`.
+
.В интерфейсе `IDirectoryItemsCollectionAdditionalFieldsPlugin` реализуйте следующие методы:
.. `GetAdditionaFields` -- возвращает список дополнительных полей для типа элементов. Необходимо вернуть список полей с указанием:
+
* `Name` -- имя поля секции,
* `DisplayName` -- отображаемое название поля,
* `DisplayInSelectedValue` -- отображать ли значение поля в режиме просмотра значения ЭУ.
+
.. `GetAdditionaFieldsValues` -- возвращает список значений доп. полей для указанного типа элементов и элемента. Необходимо вернуть список полей с указанием:
+
* `FieldName` -- имя поля секции,
* `Value` -- строковое значение,
* `DisplayInSelectedValue` -- отображать ли значение поля в режиме просмотра значения ЭУ.
+
. В реализации в свойстве `Name` укажите уникальное имя плагина. Это же имя укажите в свойстве ЭУ "xref:6.1@webclient:layouts:ctrl/directories/directoryItemsCollection.adoc#plugin-name[Имя плагина для доп. полей]".
. Зарегистрируйте новый класс в `Extension.cs`:
+
 services.AddSingleton<IDirectoryItemsCollectionAdditionalFieldsPlugin, ProjectAdditionalFieldsPlugin>();
+
. Добавьте созданное серверное расширение на сервер {wc}а.