= Общие настройки сервера приложений

Адрес сайта документации::
В поле указывается адрес, по которому располагается документация системы. Поле поддерживает шаблоны расположения документации. Подробнее см. "xref:docs-location.adoc[]".

Восстановить по умолчанию::
Кнопка восстанавливает стандартные настройки сервера, сбрасывает значения всех полей на заводские.

Логин системной учётной записи::
Поле для ввода имени системной учётной записи {dv} в формате `user@domain.com`.

Пароль системной учетной записи::
Поле для ввода пароля системной учётной записи {dv}. Рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

Штамп сертификата шифрования паролей::
Отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.

Имя компьютера в текущем домене Active Directory::
Необходимо для указания имени любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности.

API-ключ для подключения к Workflow::
API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.

== Группа настроек "Журналирование"

Файл журнала::
Путь к файлу журнала, в котором регистрируются выполняемые сервером операции. По умолчанию используется: `/var/log/docsvision/platform/dvappserver.log`.
+
Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.
+
По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/appserver/dvappserver.log`. Путь к журналу и уровень журналирования можно настроить в {of-mc}, menu:Серверы[Имя сервера > Сервер приложений > Дополнительные настройки].Уровень журналирования -- кнопки выбора глубины фиксации процессов в журнале сервера приложений. По умолчанию используется: `Error`.
+
.Доступные варианты:
*** *Отключено*
*** *Ошибки*
*** *Предупреждения*
*** *Сообщения*
*** *Подробное* журналирование
+
[NOTE]
====
В системном журнале и журнале приложений может встречаться ошибка `Unexpected error: The file '/docsvision/StorageServer/Fetch.aspx' does not exist.`

Ошибка возникает из-за наличия модуля _Конструктор отчетов_, несовместимого с {dv} текущей версии. Обработка запросов от данного модуля будет отключена.
====

== Группа настроек "Модули"

Проверка версии БД::
Когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.

Проверять версию базы данных::
Когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.

Обновление БД::
Флаг включает режим установки модулей без загрузки данных в БД. По умолчанию флаг активирован.

Пропускать обновление БД при установке модулей::
Флаг отключает обновление БД при установке модулей. По умолчанию флаг неактивен.

== Группа настроек "Локализация полей"

Язык::
язык локализации по умолчанию. По умолчанию используется Русский. Чтобы изменить язык локализации по умолчанию, измените значение параметра на: Русский, English. Подробнее см. "xref:default-localization.adoc[]".

Режим локализации полей::
установка локализованных значений для полей клиентского приложения. Подробнее см. "xref:default-localization.adoc[]".
+
.Доступные варианты:
*** *Выкл*
*** *Чтение*
*** *Запись*
*** *Вкл*
*** *Особый* режим
