= Общие настройки сервера приложений

:module: {pl}
:parameter: HelpUrl
Адрес сайта документации::
В поле указываетсяfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
адрес, по которому располагается документация системы. Поле поддерживает шаблоны расположения документации. Подробнее см. "xref:docs-location.adoc[]".

Восстановить по умолчанию::
Кнопка восстанавливает стандартные настройки сервера, сбрасывает значения всех полей на заводские.

:module: {pl}
:parameter: SystemUserAccount
Логин системной учётной записи::
Поле для ввода имени системной учётной записиfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
{dv} в формате `user@domain.com`.

Пароль системной учетной записи::
Поле для ввода пароля системной учётной записи {dv}. Рекомендуется хранить в зашифрованном виде. Подробнее про шифрование см. в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

:module: {pl}
:parameter: DataProtectCertificateThumbprint
Штамп сертификата шифрования паролей::
Отпечатокfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.

:module: {pl}
:parameter: WindowsSecurityServerName
Имя компьютера в текущем домене Active Directory::
Необходимо для указанияfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
имени любого компьютера в текущем домене Active Directory. Используется при получении списка доступных членов домена при настройке дискреционной безопасности.

:module: {pl}
:parameter: ApiKey
API-ключ для подключения к Workflow::
API-ключfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.

:module: {pl}
:parameter: ComplexSignatureServiceAddress
Криптосервис::
Адресfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
криптосервиса в формате `ConnectAddress=адрес_сервиса`. Установка и настройка криптосервиса описана в руководстве по настройке системы, раздел "xref:new-admin-console@engineer::java-service.adoc[]".

[#logging]
== Группа настроек "Журналирование"

:module: {pl}
:parameter: fileName
Файл журнала::
Путь к файлуfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
журнала, в котором регистрируются выполняемые сервером операции. По умолчанию используется: `/var/log/docsvision/platform/dvappserver.log`.
+
Данный журнал содержит информацию о работе сервера {dv}. Журнал сервера является средством диагностики при возникновении нештатных ситуаций и предназначен для передачи в службу технической поддержки {dv}.
+
По умолчанию журнал сервиса сохраняется в папку `/var/log/docsvision/appserver/dvappserver.log`. Путь к журналу и уровень журналирования можно настроить в {of-mc}, menu:Серверы[Имя сервера > Сервер приложений > Дополнительные настройки].Уровень журналирования -- кнопки выбора глубины фиксации процессов в журнале сервера приложений. По умолчанию используется: `Error`.
+
.Доступные варианты:
*** *Отключено*
*** *Ошибки*
*** *Предупреждения*
*** *Сообщения*
*** *Подробное* журналирование
+
[NOTE]
====
В системном журнале и журнале приложений может встречаться ошибка `Unexpected error: The file '/docsvision/StorageServer/Fetch.aspx' does not exist.`

Ошибка возникает из-за наличия модуля _Конструктор отчетов_, несовместимого с {dv} текущей версии. Обработка запросов от данного модуля будет отключена.
====

[#modules]
== Группа настроек "Модули"

Проверка версии БД::
Когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.

Проверять версию базы данных::
Когда флаг установлен, сообщение о несоответствии версии базы данных и версии сервера {dv} вносится в журнал выполняемых сервером операций.

Обновление БД::
Флаг включает режим установки модулей без загрузки данных в БД. По умолчанию флаг активирован.

Пропускать обновление БД при установке модулей::
Флаг отключает обновление БД при установке модулей. По умолчанию флаг неактивен.

[#localization]
== Группа настроек "Локализация полей"

Язык::
язык локализации по умолчанию. По умолчанию используется Русский. Чтобы изменить язык локализации по умолчанию, измените значение параметра на: Русский, English. Подробнее см. "xref:default-localization.adoc[]".

:module: {pl}
:parameter: LocalizationMode
Режим локализации полей::
Установка локализованных значенийfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]
для полей клиентского приложения. Подробнее см. "xref:default-localization.adoc[]".
+
.Доступные варианты:
*** *Выкл*
*** *Чтение*
*** *Запись*
*** *Вкл*
*** *Особый* режим
