= Настройки базы данных

На странице настроек сервера приложений отображается блок со списком подключенных баз данных. Каждая БД отображается на новой строке таблицы:

include::partial$excerpts.adoc[tags=dbalias]
include::partial$excerpts.adoc[tags=dbname]
include::partial$excerpts.adoc[tags=servername]
include::partial$excerpts.adoc[tags=dbindex]
include::partial$excerpts.adoc[tags=dbversion]
include::partial$excerpts.adoc[tags=dbupdate]
include::partial$excerpts.adoc[tags=dbcreated]
include::partial$excerpts.adoc[tags=dbdefault]
include::partial$excerpts.adoc[tags=dboff]
include::partial$excerpts.adoc[tags=actionbuttons]

Нажатие на строку с именем БД переводит на страницу настроек БД. Страница содержит следующие разделы:

* <<properties,Общие свойства>>
* xref:db-maintenance.adoc[Обслуживание]
* xref:db-storage.adoc[Внешние хранилища]
* xref:db-archive.adoc[Архивирование]
* xref:db-cache.adoc[Кэширование]
* xref:db-log.adoc[Журналирование]
* xref:db-additional.adoc[Дополнительные настройки]

[#properties]
== Общие свойства базы данных

Свойства базы данных приведены только для чтения и не могут быть изменены.

include::partial$excerpts.adoc[tags=dbname-1]

include::partial$excerpts.adoc[tags=dbalias-1]

include::partial$excerpts.adoc[tags=servername]

include::partial$excerpts.adoc[tags=servertype]

Версия:::
Версия базы данных.

Дата обновления:::
Дата, когда было выполнено последнее обновление БД.

Используются расширенные метаданные:::
Возможность добавлять в карточку новые секции и поля с помощью Конструктора разметок, подробнее см. xref:db-metadata.adoc[].

// Использовать по умолчанию:::
// Флаг для выбора БД, к которой по умолчанию будут подключаться клиенты и сервисы {dv}.

[#ext-bd]
== Внешняя база данных

Используется сателлитная БД для хранения архивных карточек:::
Определяет, должна ли для хранения архивных карточек использоваться сателлитная БД.

Используется сателлитная БД для хранения журналов работы:::
Определяет, должна ли для хранения журналов использоваться сателлитная БД.

Используется сателлитная БД для хранения системных данных:::
Определяет, должна ли для хранения системных таблиц использоваться сателлитная БД.

См. подробнее "xref:db-satellite.adoc[]".

[#service-tables]
== Расположение таблиц

Определяет расположение служебных таблиц:

* С изменениями объектов.
* С внутренними курсорами.
* С файловыми курсорами.
* С иконками.
* Представлений.
* С данными поисковых запросов.

Подробнее см. "xref:db-service-tables.adoc[]".

[#pool-volume]
== Количество соединений с сервером БД

Настройка выполняется в СУБД. Сервер приложений {dv} при работе с сервером БД использует пул соединений фиксированного размера. Изменить размер пула по умолчанию можно с помощью специальной настройки. По умолчанию данная настройка отсутствует, а размер задан как `100 соединений`.

Чтобы изменить количество соединений, необходимо в группе настроек menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:appserver-etc.adoc[Дополнительные настройки]] создать параметр `Platform&#x5f;&#x5f;Server&#x5f;&#x5f;DbConnectionPoolSize`, в котором определить требуемый размер пула.

[WARNING]
====
Увеличение размера пула может привести к увеличению потребляемой памяти на серверах приложений и баз данных.
====

.Конфигурировать СУБД нужно, учитывая перечисленные ниже факты:
* Используя настройки *max_connections* в БД {pgsql} можно ограничить количество подключений к серверу БД. Настройка влияет на подключения к серверу БД, а не к БД. Если на сервере {pgsql} несколько БД, ограничение влияет на общее количество подключений к серверу: может быть открыто 60 соединений с одной БД, а с другой удастся открыть лишь 40, дальнейшие попытки открыть подключение выдадут ошибку.
* Настройка *DbConnectionPoolSize* определяет максимальный размер пула соединений с базой на клиентской стороне, а не с сервером. Если на одном сервере приложений подключили две БД {pgsql} c одного инстанса, то *{sss-new}* при определённых нагрузках может пытаться открыть по 100 соединений к каждой БД, то есть 200 подключений к одному инстансу {pgsql}.
* Если два сервера приложений обрабатывают одну БД {pgsql}, то каждый *{sss-new}* может пытаться открыть по 100 соединений к этой базе, то есть 200 подключений к одному инстансу {pgsql}.
* Также нужно помнить о подключениях от _pgagent_, каких-то дополнительных соединениях от _pgadmin_ (или другой среды администрирования), ServerConsole, сервиса полнотекстового индексирования, файлового сервиса.
