= Настройки базы данных

На странице настроек сервера приложений отображается блок со списком подключенных баз данных. Каждая БД отображается на новой строке таблицы. Нажатие на строку с именем БД переводит на страницу настроек БД. В зависимости от типа БД количество и вид настроек может отличаться. Если какие-то настройки не поддерживаются для данного типа БД, об этом будет сказано в описании настроек. Следующие группы настроек доступны для изменения:

* <<properties,Общие свойства>>
* xref:db-maintenance.adoc[Обслуживание]
* xref:db-storage.adoc[Внешние хранилища]
* xref:db-archive.adoc[Архивирование]
* xref:db-performance.adoc[Кэширование]
* xref:db-log.adoc[Журналирование]
* xref:db-additional.adoc[Дополнительные настройки]

[#properties]
== Общие свойства базы данных

Свойства базы данных приведены только для чтения и не могут быть изменены.

include::partial$excerpts.adoc[tags=dbname-1]

include::partial$excerpts.adoc[tags=dbalias-1]

include::partial$excerpts.adoc[tags=servername]

include::partial$excerpts.adoc[tags=servertype]

Версия:::
Версия базы данных.

Дата обновления:::
Дата, когда было выполнено последнее обновление БД.

Используются расширенные метаданные:::
Возможность добавлять в карточку новые секции и поля с помощью Конструктора разметок, подробнее см. в документации модуля {pl}, "xref:dev@platform:console:db-metadata.adoc[]".

// Использовать по умолчанию:::
// Флаг для выбора БД, к которой по умолчанию будут подключаться клиенты и сервисы {dv}.

[#ext-bd]
== Внешняя база данных

Используется сателлитная БД для хранения архивных карточек:::
Определяет, должна ли для хранения архивных карточек использоваться сателлитная БД.

Используется сателлитная БД для хранения журналов работы:::
Определяет, должна ли для хранения журналов использоваться сателлитная БД.

Используется сателлитная БД для хранения системных данных:::
Определяет, должна ли для хранения системных таблиц использоваться сателлитная БД.

См. подробнее "xref:db-satellite.adoc[]".

[#service-tables]
== Расположение таблиц

include::partial$excerpts.adoc[tags=sat-ms-only]

Определяет расположение служебных таблиц:

* С изменениями объектов.
* С внутренними курсорами.
* С файловыми курсорами.
* С иконками.
* Представлений.
* С данными поисковых запросов.

****
include::partial$excerpts.adoc[tags=readonly]
****

Подробнее см. "xref:db-service-tables.adoc[]".
