= Настройки базы данных

На странице настроек сервера приложений отображается блок со списком подключенных баз данных. Каждая БД отображается на новой строке таблицы:

include::partial$excerpts.adoc[tags=dbalias]
include::partial$excerpts.adoc[tags=dbname]
include::partial$excerpts.adoc[tags=servername]
include::partial$excerpts.adoc[tags=dbindex]
include::partial$excerpts.adoc[tags=dbversion]
include::partial$excerpts.adoc[tags=dbupdate]
include::partial$excerpts.adoc[tags=dbcreated]
include::partial$excerpts.adoc[tags=dbdefault]
include::partial$excerpts.adoc[tags=dboff]
include::partial$excerpts.adoc[tags=actionbuttons]

[#settings]
== Настройки БД

Нажатие на строку с именем БД переводит на страницу настроек БД. Страница содержит следующие разделы:

* <<properties,Общие свойства>>
* xref:db-maintenance.adoc[Обслуживание]
// * xref:.db-storage.adoc[Внешние хранилища]
* xref:db-archive.adoc[Архивирование]
* xref:db-cache.adoc[Кэширование]
* xref:db-log.adoc[Журналирование]
* xref:db-additional.adoc[Дополнительные настройки]

[#properties]
== Свойства базы данных

Общие свойства::

include::partial$excerpts.adoc[tags=name]

include::partial$excerpts.adoc[tags=servername]

include::partial$excerpts.adoc[tags=servertype]

Версия:::
Версия базы данных.

Дата последнего обновления:::
Дата, когда было выполнено последнее обновление БД.

Использовать по умолчанию:::
Флаг для выбора БД, к которой по умолчанию будут подключаться клиенты и сервисы {dv}.

[#options]
Опции::
Группа настроек позволяет задать место хранения таблиц `ChangeObjectDataBaseType`, `CursorDataBaseType`, `FileCursorDataBaseType`, `IconDataBaseType`, `KeysetDataBaseType`, `SearchDataBaseType`. Доступные варианты расположения:
+
// tag::adv-options[]
* *UseOwnDatabase* -- использовать БД {dv}.
* *UseOuterDatabase* -- использовать сателлитную БД, предназначенную для системных таблиц `Название-БД-Docsvision_Metadata`.
+
[NOTE]
====
Если сателлитная БД `Название-БД-Docsvision_Metadata` не используется, она будет создана. Если сателлитная БД не используется, параметр `UseOuterMetadata` должен иметь значение `*False*`.
====
+
* *UseTemporaryDatabase* -- использовать временную базу данных `tempdb`.
+
.Для служебной таблицы "ChangedObjectDataBaseType" также доступны варианты:
* *InMemoryTableOwnDatabase* -- таблица в памяти SQL-сервера.
* *InMemoryTableOwnDatabaseNotPersistData* -- таблица в памяти SQL-сервера без сохранения данных при перезапуске SQL Server.
// end::adv-options[]
+
Подробнее см. "xref:db-service-tables.adoc[]".

[#sql-timeout]
== Время ожидания выполнения команды SQL

В процессе настройки сервера {dv} операция, связанная с изменением данных в БД, может завершиться с ошибкой из-за превышения времени ожидания её выполнения.

Чтобы устранить ошибку, можно увеличить время ожидания. Значение времени ожидания для операций создания, обновления и добавления БД устанавливается непосредственно перед выполнением операции.

Для операций обновления БД в консольном режиме, преобразования динамических метаданных в расширенные и при сохранении настроек xref:db-log.adoc[журналирования], значение времени ожидания получается из параметра `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;SqlCommandTimeout`. Значение задаётся в секундах.

[#pool-volume]
== Размер пула соединений с сервером БД

Сервер приложений {dv} при работе с сервером БД использует пул соединений фиксированного размера. Изменить размер пула по умолчанию можно с помощью специальной настройки. По умолчанию данная настройка отсутствует, а размер задан как `100 соединений`.

Чтобы изменить количество соединений, необходимо в группе настроек menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:appserver-etc.adoc[Дополнительные настройки]] создать параметр `Platform&#x5f;&#x5f;Server&#x5f;&#x5f;DbConnectionPoolSize`, в котором определить требуемый размер пула.

[WARNING]
====
Увеличение размера пула может привести к увеличению потребляемой памяти на серверах приложений и баз данных.
====

.Конфигурировать СУБД нужно, учитывая перечисленные ниже факты:
* Используя настройки *max_connections* в БД {pgsql} можно ограничить количество подключений к серверу БД. Настройка влияет на подключения к серверу БД, а не к БД. Если на сервере {pgsql} несколько БД, ограничение влияет на общее количество подключений к серверу: может быть открыто 60 соединений с одной БД, а с другой удастся открыть лишь 40, дальнейшие попытки открыть подключение выдадут ошибку.
* Настройка *DbConnectionPoolSize* определяет максимальный размер пула соединений с базой на клиентской стороне, а не с сервером. Если на одном сервере приложений подключили две БД {pgsql} c одного инстанса, то *{sss-new}* при определённых нагрузках может пытаться открыть по 100 соединений к каждой БД, то есть 200 подключений к одному инстансу {pgsql}.
* Если два сервера приложений обрабатывают одну БД {pgsql}, то каждый *{sss-new}* может пытаться открыть по 100 соединений к этой базе, то есть 200 подключений к одному инстансу {pgsql}.
* Также нужно помнить о подключениях от _pgagent_, каких-то дополнительных соединениях от _pgadmin_ (или другой среды администрирования), ServerConsole, сервиса полнотекстового индексирования, файлового сервиса.

[#role-debug]
=== Включение отладки ролевой модели

Отладка ролевой модели представляет собой процесс тестирования настроек ролевой безопасности с последующим включением его в продуктовую среду.

.Чтобы включить режим отладки ролевой модели:
. Задайте значение параметра `TraceLevel`. Отладка работает при значениях `3` и `4`.
. Дополнительно обязательно нужно создавать настройку в БД при помощи скрипта:
+
.Для {mssql}:
[source,sql]
----
DECLARE @On bit =1
EXEC dvsys_setting_set N'RoleModelTrace', @On
----
+
.Для {pgsql}:
[source,pgsql]
----
select * from dvsys_setting_set('RoleModelTrace', true);
----
+
. Перезапустите *{sss-new}*.
. После завершения исследования удалите настройку `"TraceLevel"` в БД или отключите её, установив в значение `0` для {mssql} или `false` для {pgsql}.
+
[source,sql]
----
delete from dvsys_settings where [Name] = N'RoleModelTrace
----
+
[source,pgsql]
----
delete from dvsys_settings where "Name" = 'RoleModelTrace;
----
+
. Перезапустите *{sss-new}* ещё раз.
