= Настройки базы данных

На странице настроек сервера приложений отображается блок со списком подключенных баз данных. Каждая БД отображается на новой строке таблицы. Нажатие на строку с именем БД переводит на страницу настроек БД. В зависимости от типа БД количество и вид настроек может отличаться. Если какие-то настройки не поддерживаются для данного типа БД, об этом будет сказано в описании настроек. Следующие группы настроек доступны для изменения:

* <<properties,Общие свойства>>
* xref:db-maintenance.adoc[Обслуживание]
* xref:db-storage.adoc[Внешние хранилища]
* xref:db-archive.adoc[Архивирование]
* xref:db-performance.adoc[Производительность]
* xref:db-log.adoc[Журналирование]
* xref:db-load-distribution.adoc[Распределение нагрузки]

[#properties]
== Общие свойства базы данных

Свойства базы данных приведены только для чтения и не могут быть изменены.

include::partial$excerpts.adoc[tags=dbname-1]

include::partial$excerpts.adoc[tags=dbalias-1]

include::partial$excerpts.adoc[tags=servername]

include::partial$excerpts.adoc[tags=servertype]

Версия:::
Версия базы данных.

Дата обновления:::
Дата, когда было выполнено последнее обновление БД.

Используются расширенные метаданные:::
Возможность добавлять в карточку новые секции и поля с помощью Конструктора разметок, подробнее см. в документации модуля {pl}, "xref:6.1@platform:console:db-metadata.adoc[]".

// Использовать по умолчанию:::
// Флаг для выбора БД, к которой по умолчанию будут подключаться клиенты и сервисы {dv}.
