:what-service: {fss-new}
:name-service: {of-fs}
:this-action: настройки {of-fs}
:anchor: fs
:module: {of-fs}

= Страница "{fs}"

Настройки {of-fs} в {of-mc}.

NOTE: Все описанные настройки хранятся в Сервисе настроек и могут также дублироваться в конфигурационном файле модуля. Настройки в конфигурационных файлах имеют приоритет по сравнению с настройками в Сервисе настроек. Если настройка отсутствует в конфигурационном файле, но присутствует в Сервисе настроек, она будет получена из Сервиса настроек.

include::partial$excerpts.adoc[tags=restart-service]

include::partial$excerpts.adoc[tags=address]

include::partial$excerpts.adoc[tags=mc-extension]

При запуске службы {of-fs} в сервисе настроек регистрируются или обновляются следующие данные:

* Имя сервера
* Операционная система
* Версия ОС
* Данные об установленном компоненте {of-fs}:
** Системное название модуля
** Продуктовая версия модуля
** Номер сборки модуля

WARNING: Перед запуском службы убедитесь, что в конфигурационном файле модуля {fs} указаны параметры, необходимые для работы {of-sett-serv}: menu:ServiceId[], menu:SettingsService[ConnectionString] и menu:SettingsService[ApiKey].

Интерфейс страницы настроек {of-fs} представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования.
