= Блокировки конфигураций

Применение некоторых настроек требует длительного времени на выполнение. На время применения страница переходит в режим только для чтения, выполнение длительной операции будет продолжено в фоновом режиме. Кнопки *Применить* и *Отменить* становятся неактивными, настройки недоступны для изменения. Операции на других серверах и на других страницах конфигурации могут выполняться без ограничений, текущая страница настроек при этом может быть закрыта

После применения настроек и завершения фоновой операции страница будет обновлена, пользователь будет оповещён об этом при помощи всплывающего сообщения.

Если конфигурирование закончилось ошибкой, то режим страницы только для чтения снимается. Пользователь получает об этом оповещение с красным ободком. (успешное завершение с синим ободком)
Внизу страницы появляется всплывающее сообщение

Если снять readonly автоматически не получилось, и страница осталась заблокированной (например, было аварийное завершение работы сервера), необходимо предусмотреть вариант принудительного снятия блокировки.

Для просмотра заблокированных сервисов нужно разработать отдельную страницу.
Перейти на нее можно только по URL. Ссылок из основного интерфейса нет. Адрес страницы: http://localhost:5100/#/configurationLocks.

Это простейшая страница без разметки, оболочки и навигации. На ней в виде таблицы отображаются следующие данные:

Сервер / Server - имя машины, где расположен компонент;
Компонент / Component - название сервиса, по которому выполняется конфигурация;
Запущено / Started - дата и время начала операции применения изменений;
Пользователь / User - учетная запись пользователя, который запустил операцию.
Напротив строки с ошибкой или недоступным состоянием должна быть кнопка "Разблокировать" / "Unlock".

При клике на кнопку "Разблокировать" снимается признак readonly со страницы конфигурации. На разблокированной странице настроек можно продолжить работу в обычном режиме.

Пока запрос не закончился нужно добавлять крутяшку вместо текста и блокировать ее для дальнейшего нажатия.
Если запрос завершился с ошибкой, то строку из таблицы не убирать.
Если запрос завершился успешно, строка удаляется из таблицы.
Пока страница не загрузилась показывать крутяшку под заголовком.
Если заблокированных компонентов нет, показывать текст на странице под заголовком "Отсутствуют заблокированные конфигурации
