= Блокировки конфигураций

Применение некоторых настроек требует длительного времени на выполнение. На время применения страница переходит в режим только для чтения, выполнение длительной операции будет продолжено в фоновом режиме. Кнопки *Применить* и *Отменить* становятся неактивными, настройки недоступны для изменения. Операции на других серверах и на других страницах конфигурации могут выполняться без ограничений, текущая страница настроек при этом может быть закрыта.

Если заблокированных компонентов нет, на странице ниже заголовка будет отображаться сообщение `Отсутствуют заблокированные конфигурации`.

После применения настроек и завершения фоновой операции страница будет обновлена, пользователь будет оповещён об этом при помощи всплывающего сообщения. Если конфигурирование закончилось ошибкой, режим страницы только для чтения снимается, всплывающее сообщение будет окрашено красным.

Ознакомиться со списком заблокированных сервисов можно на отдельной странице. Страница доступна только по адресу `\http://имя-сервера-{dv}:порт/\#/configurationLocks`, например `\http://dvserver.company.com:5100/#/configurationLocks`. Страница блокировок не может быть открыта из меню {of-mc}.

.Страница представлена таблицей со следующими данными:
* Сервер -- имя машины, на которой расположен компонент.
* Компонент -- название сервиса, по которому выполняется конфигурация.
* Запущено -- дата и время начала операции применения изменений.
* Пользователь -- учетная запись пользователя, запустившего операцию.
* Напротив строки с ошибкой или недоступным состоянием располагается кнопка *Разблокировать*.

[WARNING]
====
Настоятельно не рекомендуется использовать разблокировку страниц без крайней необходимости. Принудительное снятие блокировки во время штатной работы системы может повлиять на её функциональность и привести к конфликтам.

Механизм разблокировки должен использоваться *только* для экстренных случаев, когда страница не выходит из режима чтения самостоятельно. На случай такого аварийного завершения процесса или сбоя сервера предусмотрена отдельная страница.
====

При нажатии кнопки *Разблокировать* снимается признак "только для чтения" со страницы конфигурации. После того как страница настроек разблокирована, строка таблицы с описанием блокировки будет удалена, работу можно продолжить в обычном режиме.

Запрос на разблокировку может завершиться с ошибкой, в таком случае строка из таблицы не будет удалена.
