= Блокировки конфигураций

include::partial$excerpts.adoc[tags=readonly]

Если конфигурирование закончилось ошибкой, режим страницы только для чтения снимается, всплывающее сообщение будет окрашено красным. При невозможности сохранения будет выведено сообщение `Не удалось сохранить изменение элемента по пути из-за ошибки`.

Ознакомиться со списком заблокированных сервисов можно на отдельной странице. Страница доступна только по адресу `\http://имя-сервера-{dv}:порт/\#/configurationLocks`, например `\http://dvserver.company.com:5100/#/configurationLocks`. Страница блокировок не может быть открыта из меню {of-mc}.

.Страница представлена таблицей со следующими данными:
* Сервер -- имя машины, на которой расположен компонент.
* Компонент -- название сервиса, по которому выполняется конфигурация.
* Запущено -- дата и время начала операции применения изменений.
* Пользователь -- учётная запись пользователя, запустившего операцию.
* Напротив строки с ошибкой или недоступным состоянием располагается кнопка *Разблокировать*.

Если заблокированных компонентов нет, на странице ниже заголовка будет отображаться сообщение `Отсутствуют заблокированные конфигурации`.

[WARNING]
====
Настоятельно не рекомендуется использовать разблокировку страниц без крайней необходимости. Принудительное снятие блокировки во время штатной работы системы может повлиять на её функциональность и привести к конфликтам.

Механизм разблокировки должен использоваться *только* для экстренных случаев, когда страница не выходит из режима чтения самостоятельно. На случай такого аварийного завершения процесса или сбоя сервера предусмотрена отдельная страница.
====

При нажатии кнопки *Разблокировать* снимается признак "только для чтения" со страницы конфигурации. После того как страница настроек разблокирована, строка таблицы с описанием блокировки будет удалена, работу можно продолжить в обычном режиме.

Запрос на разблокировку может завершиться с ошибкой, в таком случае строка из таблицы не будет удалена.
