= Группа настроек "Журналирование"

Настройки журналирования {wc}а частично перенесены в интерфейс консоли:

* Файл журнала
* Логирование в консоль
* Логирование в файл

Файл журнала::
Путь к файлу журнала, в котором регистрируются операции, выполняемые {wc}ом, указывается в формате `$&#123;gdc:baseLogFolder&#125;/docsvision/webclient/webclient.log`. По умолчанию это `/var/log//docsvision/webclient/webclient.log`.

Включить журнал событий навигации::
По умолчанию протоколирование событий навигации отключено. Администратор может включить ведение журнала для записи информации о событиях и последующего анализа ошибок при помощи данного флага. В лог браузера записывается информация о специальных навигационных обработчиках, передаваемым им параметрах и результатах их работы.

Логирование сообщений браузера::
Отправлять сообщения браузера в журнал операций {wc}а. По умолчанию отправка сообщения браузера в журнал операций отключена. Администратор может включить отправку при помощи данного флага.

[#rules]
== Уровни логирования

Логирование в консоль::
Глубина фиксации процессов {wc}а в терминале или командной строке.
+
* Все
* Отладка
* Информация
* Предупреждения (значение по умолчанию)
* Ошибки

Логирование в файл::
Глубина фиксации процессов {wc}а в файл журнала.
+
* Все
* Отладка
* Информация (значение по умолчанию)
* Предупреждения
* Ошибки

[#query-logging]
== Логирование запросов

Включить журналирование запросов::
Включение/отключение протоколирования событий сервера {wc}а. Значение по умолчанию: неопределено. В стандартной конфигурации остальные настройки группы отсутствуют.

Путь к журналу запросов::
Расположение папки с файлами журнала запросов.

Журналируемые поля::
По умолчанию указываются запросы, ответы, заголовки, дата/время (записывается в формате UTC) и имя сервера. Значения разделяются запятой. Со всеми допустимыми значениями можно ознакомиться в https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Middleware/HttpLogging/src/W3CLoggingFields.cs[документации Microsoft].

Размер файла журнала, байт::
Максимальный размер файла журнала, после которого будет создаваться новый. Значение в байтах, по умолчанию 10485760 байт (10 Мб). Цифра `0` означает отсутствие ограничения по размеру.

Количество файлов журнала::
Количество сохраняемых файлов журнала. Допустимые значения от `1` до `10000`, по умолчанию используется `4`.

Префикс имени файла журнала::
Префикс имени файла журнала. Запросы будут записаны в файл `/var/log/docsvision/webclient/webclient-w3c-&#x7b;YYYYMMDD.X&#x7d;.txt`.

[#config]
== Настройка в конфигурационном файле

Возможность настроить журналирование с помощью конфигурационного файла поддерживается в качестве обратной совместимости. Однако если настройки заданы в `appsetings.json` и в интерфейсе консоли, конфигурационный файл будет иметь приоритет. Чтобы значения, выполненные в интерфейсе корректно применялись, убрерите из конфигурационного файла следующие поля:

[source,json]
----
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/webclient/webclient.log",
        "layout": "[${longdate}][${level}][${callsite}] ${message} ${onexception:${newline}${exception:maxInnerExceptionLevel=10:format=shortType,message,stacktrace:separator=*:innerExceptionSeparator=&#xD;&#xA;&#x9;}}"
      },
    "rules": [
      {
        "logger": "*",
        "minLevel": "Error",
        "writeTo": "logFile"
      },
      {
        "logger": "*",
        "minLevel": "Trace",
        "writeTo": "logConsole"
      }
    ]
  }
----
