= Группа настроек "Журналирование"

Адрес журнала операций {wc}а::
Путь к файлу журнала {wc}а (сервиса _{wcs-new}_).

Включить журнал событий навигации::
По умолчанию протоколирование событий навигации отключено. Администратор может включить ведение журнала для записи информации о событиях и последующего анализа ошибок при помощи данного флага. В лог браузера записывается информация о специальных навигационных обработчиках, передаваемым им параметрах и результатах их работы.

Логирование сообщений браузера::
Отправлять сообщения браузера в журнал операций {wc}а. По умолчанию отправка сообщения браузера в журнал операций отключена. Администратор может включить отправку при помощи данного флага.

[#rules]
== Уровни логирования

Категория "Default"::
Глубина фиксации процессов в журнале {wc}а для категории "Default".
+
* Все (значение по умолчанию)
* Отладка
* Информация
* Предупреждения
* Ошибки

Категория "Microsoft"::
Глубина фиксации процессов в журнале {wc}а для категории "Microsoft".
+
* Все
* Отладка
* Информация
* Предупреждения (значение по умолчанию)
* Ошибки

Категория "Microsoft.Hosting.Lifetime"::
Глубина фиксации процессов в журнале {wc}а для категории "Microsoft.Hosting.Lifetime".
+
* Все
* Отладка
* Информация (значение по умолчанию)
* Предупреждения
* Ошибки

[#query-logging]
== Логирование запросов

Включить журналирование запросов::
Включение/отключение протоколирования событий сервера {wc}а. Значение по умолчанию: неопределено. В стандартной конфигурации остальные настройки группы отсутствуют.

Путь к журналу::
Расположение папки с файлами журнала.

Журналируемые поля::
По умолчанию указываются запросы, ответы, заголовки, дата/время (записывается в формате UTC) и имя сервера. Значения разделяются запятой. Со всеми допустимыми значениями можно ознакомиться в https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Middleware/HttpLogging/src/W3CLoggingFields.cs[документации Microsoft].

Размер файла журнала::
Максимальный размер файла журнала, после которого будет создаваться новый. Значение в байтах, по умолчанию 10485760 байт (10 Мб). Цифра `0` означает отсутствие ограничения по размеру.

Количество файлов журнала::
Количество сохраняемых файлов журнала. Допустимые значения от `1` до `10000`, по умолчанию используется `4`.

Префикс имени файла журнала::
Префикс имени файла журнала. Запросы будут записаны в файл `/var/log/docsvision/webclient/webclient-w3c-&#x7b;YYYYMMDD.X&#x7d;.txt`.
