= Группа настроек "Инструменты"

Группа настроек "Инструменты" содержит параметры _DVWebTool_ и _DVSupService_.

Порт подключения::
Общая настройка для DVWebTool и DVSupService, задаёт порт для подключения.

Время жизни токена доступа, сек::
Срок действия токена. По умолчанию время жизни составляет `300` секунд (5 минут).

Допустимая погрешность часов при проверке времени жизни, сек::
Допустимая погрешность часов при проверке времени жизни токена. Значение прибавляется к сроку действия токена. По умолчанию значение составляет `300` секунд (5 минут).

// [#supservice]
// == DVSupService
//
// Провайдер сканирования::
// Чтобы иметь возможность сканировать файлы в ОС Linux, необходимо выполнить дополнительные действия по настройке DVSupService для работы со сканерами с поддержкой SANE. Установка DVSupService описана в разделе "xref:dev@webclient:user:prepare-add-components.adoc#dvSupService[Установка и запуск службы DVSupService]". На выбор доступны два провайдера: *_Naps2Provider_*, *_ScanImageProvider_*.

[#extensions]
== Расширения

Размещение расширений::
Адрес каталога для расширений {wc}а.

// [#webtool]
// == DVWebTool
//
// Для корректной работы DVWebTool необходимо собрать инсталлятор через утилиту WebToolUtil и скопировать собранные файлы на сервер {wc}а. Подробнее см. в документации модуля {wc}, разделе "xref:GBL-3654@webclient:admin:webservices-install.adoc[]".
//
// Адрес установщика утилиты DVWebTool::
// Расположение инсталлятора DVWebTool.

Автозакрытие DVWebTool после выполнения действия::
Настройка регулирует поведение утилиты DVWebTool после выполнения действия. Поведение по умолчанию: не закрывать.
