= Группа настроек "Сайт"

[#pechenkies]
== Пользовательские cookie

:module: {wc}
:parameter: AuthCookieLifetime
Период действия пользовательской сессии, ч::
Настройкаfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
] устанавливает период действия пользовательской сессии. Значение по умолчанию: `120` часов (5 дней).

:module: {wc}
:parameter: MobileAuthCookieLifetime
Период действия пользовательской сессии на мобильных устройствах, ч::
Настройкаfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
] отдельно задаёт период действия пользовательской сессии на мобильных устройствах. Значение по умолчанию: `120` часов (5 дней).

Настройки можно комбинировать. Например, задать _Период действия пользовательской сессии_ в значение `240` часов, чтобы все пользователи получали cookie на 10 дней. Для _мобильных устройств_ можно указать период в `720` часов (30 дней). Когда пользователь откроет {wc} по прошествии трёх дней с предыдущей авторизации, cookie автоматически будут продлены.

:module: {wc}
:parameter: TabletRegExpString
[#devices]
== Устройства

Пользовательский интерфейс {wc}а адаптируется под тип клиентского устройства, который определяется по https://ru.wikipedia.org/wiki/User_Agent[User Agent], передаваемому веб-браузером клиента. Если User Agent не сопоставляется или некорректно сопоставляется с типом устройства, нужно изменить шаблон, по которому выполняется сопоставление. В значении настройкиfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
] через символ `|` нужно указать User Agent соответствующего устройства:

Новые мобильные устройства::
Шаблон определения мобильных устройств нового поколения.

Старые мобильные устройства::
Шаблон определения старых мобильных устройств.

Планшеты::
Шаблон определения планшетов.

NOTE: Адаптивные свойства разметок могут быть xref:webclient:layouts:layouts-adaptive.adoc[настроены] в программе {kvr}.
