= Группа настроек "Электронная подпись"

Группа настроек "Электронная подпись" содержит параметры, связанные с конфигурацией электронной подписи.

[#cloud-sign]
== Облачная подпись

[WARNING]
====
Запросы к облачному сервису электронной подписи отправляются через сервер {wc}а. Это означает, что {wc} должен иметь доступ к сервису ЭП для отправки запросов на проверку подписи и для авторизации.
====

Проверка подлинности подписи может осуществляться локально или через облачный сервис электронной подписи. Способ проверки подписи зависит от конфигурации {wc}а в {of-mc}. Проверка подлинности подписи будет проводиться локально, если не указаны настройки облачной подписи.

NOTE: Для работы с облачной подписью требуется дополнительная опция лицензии _{dv} Коннектор КриптоПро DSS_.

Адрес сервера::
Адрес сервиса облачной подписи.

Клиент ID::
Идентификатор клиента. Настраивается в сервисе облачной подписи КриптоПро.

Адрес сервиса штампа времени::
Адрес сервиса штампа времени для XLT1.

Тип подписи::
Формат используемой подписи в стандарте CAdES:
+
* `CAdES-BES` -- будет использоваться CAdES-BES.
* `CAdES-XLT1` -- будет использоваться CAdES-XLT1.
* `CAdES-T` -- будет использоваться CAdES-T.

URL для переадресации после авторизации::
Адрес, на который будет переадресован пользователь после авторизации в сервисе электронной подписи. Настраивается в сервисе электронной подписи.

Режим хранения токена::
Режим хранения токена авторизации.
+
.Возможные значения:
* `Отключено` -- авторизация будет запрашиваться каждый раз.
* `В кэше сессии` -- авторизация будет повторно запрошена по окончании сессии.
* `В памяти` -- авторизация будет запрошена при перезапуске *{wcs-new}*.
* `Зашифровано в профиле пользователя` -- авторизация будет запрошена по истечении срока действия токена.

Адрес сервиса обработки документов::
Имя сайта на сервере КриптоПро DSS. Настраивается при установке сервиса электронной подписи КриптоПро DSS. Параметр `DocumentStoreAppName`.

Сервис подписи::
Сервис подписи, обрабатывающий создание транзакций и получение результатов, подтвержденной операции. Параметр `SignServerAppName`.

Центр идентификации::
Сервис аутентификации, ответственный за аутентификацию пользователей для возможности обращений к сервису подписи и подтверждение транзакций. Параметр `STSAppName`

[#stamp]
== Штамп ЭП

Механизм формирования электронной подписи::
По умолчанию подписывемый файл не скачивается в браузер для последующего использования, вместо этого скачивается только хэш подписываемого файла. Поведение по умолчанию может быть изменено администратором системы при помощи флага `*Вычислять хэш подписываемых данных*`.

Логотип электронной подписи::
Укажите путь к PNG файлу нового логотипа (относительно каталога `{wc}а` или абсолютный).
Файл логотипа должен быть доступен процессу сервера {wc}а. Размер стандартного изображения: 127x131 пискелей. Изображение будет сжато в соответствии с фактическим размером штампа.
