= Группа настроек "Подключение"

Данный раздел документации {of-mc} описывает группу настроек подключения {wc}а к серверу приложений.

Подключение к серверу приложений настраивается в {of-mc} на странице menu:Серверы[Имя-сервера > Web-клиент > Подключение к серверу приложений]. Интерфейс страницы настроек {wc}а представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wcs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wcs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

:module: {wc}
:proga: {pu}", раздел "Базы данных
Конфигурация сервера приложений::
Полный или сокращенный адрес сервера приложений {dv}footnote:[
include::partial$excerpts.adoc[tags=analog-program]
], к которому подключается {wc} в формате `\https://dvserver.domain.com:port`.

База данных::
База данных для работы с {wc}омfootnote:[
include::partial$excerpts.adoc[tags=analog-program]
]
. Если поле не заполнено, используется база по умолчанию.
+
[NOTE]
====
После добавления новой БД необходимо её настроить. Потребуется проверить локализации, импортировать решения и настроить виды карточек по умолчанию.
====

:module: {wc}
:parameter: SystemUserAccount
Имя пользователя::
Имя системной учётной записи {dv}footnote:[
include::partial$excerpts.adoc[tags=analog-param]
] в формате `user@domain.com`.

Пароль::
Пароль системной учётной записи.

:module: {wc}
:parameter: ConnectionTimeout
Таймаут подключения, мс::
Максимальное время ожидания ответаfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
] от сервера {dv}.

include::appserver-access.adoc[tags=catalog]
* Домен по умолчанию -- полное имя домена для входа по умолчанию в формате FQDN.
