= Группа настроек "Производительность"

[#user-sessions]
== Пользовательские сессии

{wc} автоматически переводит в офлайн-режим сессии (подключение к серверу {dv}) неактивных пользователей. При этом у пользователей появится предупреждение о переводе сессии в офлайн. Впоследствии неактивные сессии будут закрыты. Таймер закрытия сессии запускается одновременно с переходом в офлайн-режим.

[NOTE]
====
После перевода пользовательской сессии в офлайн-режим или её закрытия будет остановлено автоматическое обновление счетчиков непрочитанных карточек и содержимого папок.
====

Оффлайн режим после паузы, мин::
Настройка задаёт время неактивности пользователя в минутах, через которое сессия будет переведена в офлайн-режим. Значение по умолчанию -- `10` минут.

Закрытие сессии после паузы, мин::
Настройка задаёт время неактивности пользователя в минутах, через которое сессия будет закрыта. Значение по умолчанию -- 300 минут.

Показывать сообщение о переходе в оффлайн::
Флаг `*Показывать сообщение о переходе в оффлайн*` отключает показ сообщения _"Подключение остановлено в связи с отсутствием активности"_.

[#caching]
== Кэширование

При обращении к справочникам и карточкам {wc} может использовать два режима обновления объектов.

NOTE: Настройки обновления справочников влияют также на обновление разметок. *На период разработки разметок* рекомендуется изменить значения параметров _Период обновления кэша_, а также _Режим обновления справочников_.

.Настройка _Короткий период обновления кэша_ используется для:
* Карточки папок
* Справочника видов
* Конструктора справочников
* Справочника сотрудников
* Справочника контрагентов
* Справочника категорий

.Настройка _Длительный период обновления кэша_ используется для:
* Всего остального, включая справочник разметок.

Короткий период обновления кэша::
Вместе с _Длительным периодом обновления кэша_ настройка позволяет повысить производительность при обращении к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя. Настроить поведение можно, изменив значение данного параметра.

Длительный период обновления кэша::
Вместе с _Коротким периодом обновления кэша_ настройка позволяет изменить параметры обращения к справочникам и карточкам. Параметры также влияют на обновление данных в разметке профиля пользователя. Настроить поведение можно, изменив значение данного параметра.

Минимальное время обновления кэша справочника представлений, мс::
{wc} кэширует настройки представлений в серверном кэше и обновляет его с периодичностью в `1000` мс (1 минута).
+
На сервере {wc}а, предназначенном для тестирования, период обновления может быть уменьшен, например, до одной секунды (для своевременного получения изменений разметок на клиенте).

Кэширование разметок фильтров данных::
По умолчанию {wc} использует серверный кэш для хранения разметок фильтров данных в представлении. Кэш обновляется при перезапуске сервера {wc}, а также автоматически при изменении настроек представления.
+
Администратор может отключить кэширование разметок фильтров сняв флаг `*Включить кэширование справочника представлений*`, если в {wc}е планируется использовать две или более разметки представлений. Если кэширование не отключено, пользователи могут получать разметки фильтра, не соответствующие условиям выбора разметок, указанным в программе {kvr}.

Кэширование поисковых запросов::
Администратор может отключить кэширование настроек у всех пользователей с помощью флага `*Отключить кэширование сохраненных поисковых запросов*`. При этом клиент будет каждый раз заново получать актуальные данные с сервера {wc}а. Отключение кэширования отрицательно повлияет на скорость работы модуля.

[#dir-cache]
== Кэш справочников

Режим обновления справочников::
Данная функциональность позволяет настроить особый режим работы со справочниками, данные которых используются только в режиме чтения. Использование функциональности _Общие справочники_ призвано сократить потребление памяти процессом сервера {dv}. Функциональность по умолчанию активна для {wc}а, начиная с версии 17.
+
В режиме "только чтение" {wc} использует справочники, данные которых только читаются и не изменяются. В данном режиме один справочник используется всеми сессиями и обновляется в соответствии со стратегией обновления, установленной в настройках {wc}.
+
Администратор может изменить режим обновления таких справочников в зависимости от требований к актуальности их данных. Увеличение частоты обновления ведёт к увеличению числа обращений к северу {dv}, а уменьшение -- к возможности получения устаревших данных.
+
.Обновление справочников в режиме "только чтение" регулируется следующими настройками:
* *_Через указанный интервал времени_* -- обновление выполняется с интервалом, указанным в параметре _Интервал обновления справочников, сек_.
* *_При следующем обращении_* -- если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено при следующем обращении.
* *_Сразу после изменения_* -- если в одной из сессий данные справочника в режиме только чтение были изменены, обновление будет выполнено сразу после изменения (значение по умолчанию).
+
NOTE: Настройки обновления справочников влияют также на обновление разметок. *На период разработки разметок* рекомендуется установить меньший период обновления, а также уменьшить значения параметров Короткий и Длительный _Период обновления кэша_.

Интервал обновления справочников, сек::
Настройка задаёт период обновления справочника в секундах, по умолчанию -- 600 секунд.
