= Группа настроек "Подключение"

Данный раздел документации {of-mc} описывает группу настроек подключения модуля {wf} к серверу приложений.

Подключение к серверу приложений настраивается в {of-mc} на странице menu:Серверы[Имя-сервера > Управление процессами > Подключение к серверу приложений]. Интерфейс страницы настроек модуля {wf} представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wfs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wfs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

Сервер приложений::
Список, позволяющий выбирать зарегистрированный сервер приложений, к которому подключается сервис "Управление процессами".

Почта по умолчанию::
В списке отображаются названия почтовых соединений из списка настроенных для Службы {ws}. Выбранное в списке соединение назначается почтовым соединением по умолчанию для данного экземпляра модуля {wf}. Если соединение по умолчанию выбрано, оно будет использоваться. Если в сервисе настроек почтовые соединения недоступны, вместо списка отображается текст: `Нет доступных почтовых соединений`.

[#handling]
Назначение сервиса для обработки баз данных::
Компонент редактирования для выбора БД, xref:workflow:admin:cluster.adoc[доли обрабатываемых процессов] и почтового соединения, с которыми будет работать данный сервер СУБП. Компонент также позволяет выбирать почтовое соединение.
+
Компонент представляет собой таблицу с колонками: _Сервер приложений_, _База данных_, _Доля процессов_, _Почтовое соединение_. Под таблицей располагается кнопка *Подключить*. При нажатии на кнопку открывается окно _Подключить сервис_. Данное окно позволяет указывать долю процесса и выбрать почтовое соединение.
+
--
.Следующие элементы доступны в окне "Подключить сервис":
* _База данных_ -- Обязательное поле. Список БД, которые обрабатываются выбранным сервером приложений. Чтобы выбрать БД, установите флаг слева от её названия.
* _Доля процессов_ -- Обязательное поле. Число, отражающее распределение нагрузки на выбранную БД
* _Почтовое соединение_ -- раскрывающийся список почтовых соединений, сохраненных в том же Сервисе настроек
* Кнопка *Подключить* -- кнопка применяет все выполненные в окне изменения. После сохранения в таблице появляется новая строка с настроенным подключением.
* Кнопка *Отменить* -- отменяет все изменения.
--
+
По нажатию на строку таблицы открывается то же окно _Подключить сервис_, в котором можно отредактировать настройки конкретного подключения. В каждой строке таблицы отображается кнопка удаления соединения. При удалении появляется сообщение: "Подтвердите удаление." / "Confirm removal.", кнопки: Ок/Отмена.

API-ключ для подключения к серверу::
Используется для аутентификации в API данного сервиса {wf} Сервера приложений. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые. Обязательная настройка.

Имя системного пользователя::
Имя системной учётной записи {dv}. Обязательная настройка.

Пароль системного пользователя::
Пароль Пароль системной УЗ для взаимодействия с Сервером приложений, рекомендуется хранить в зашифрованном виде, см. подробнее в документации по установке системы, раздел "xref:install-linux::appendix/account-protection.adoc[]". Обязательная настройка.

Штамп сертификата шифрования паролей::
Отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.

Лимит памяти, Мбайт::
Объем оперативной памяти, выделенной для сервиса Управления процессами. Минимальное значение `1024` Мб.
