= Группа настроек "Подключение к серверу приложений"

Данный раздел документации {of-mc} описывает группу настроек подключения модуля {wf} к серверу приложений.

Подключение к серверу приложений настраивается в {of-mc} на странице menu:Серверы[Имя-сервера > Управление процессами > Подключение к серверу приложений]. Интерфейс страницы настроек модуля {wf} представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования. Если компонент редактирования отсутствует, для настройки отображается поле ввода текста.

В шапке страницы расположены кнопки *Отменить* и *Применить*. При нажатии *Применить* отображается сообщение `Изменения на данной странице, вступят в силу после перезапуска службы *{wfs-new}*`. Все настройки сохраняются в Сервисе настроек после перезапуска службы *{wfs-new}*.

При нажатии *Отменить* отменяются все сделанные пользователем изменения.

[#handling]
Назначение сервиса для обработки баз данных::
Компонент редактирования для выбора сервера приложений и БД, с которыми будет работать данный сервер СУБП. Компонент также позволяет выбирать почтовое соединение.
+
Компонент представляет собой таблицу с колонками: _Сервер приложений_, _База данных_, _Доля процессов_, _Почтовое соединение_. Под таблицей располагается кнопка *Подключить*. При нажатии на кнопку открывается окно _Подключить сервис_. Данное окно позволяет указывать долю процесса и выбрать почтовое соединение.
+
--
.Следующие элементы доступны в окне "Подключить сервис":
* _Сервер приложений_ -- Обязательное поле. Раскрывающийся список серверов, зарегистрированных в том же Сервисе настроек
* _База данных_ -- Обязательное поле. Раскрывающийся список БД, которые обрабатываются выбранным сервером приложений
* _Доля процессов_ -- Обязательное поле. Число, отражающее распределение нагрузки на выбранную БД
* _Почтовое соединение_ -- раскрывающийся список почтовых соединений, сохраненных в том же Сервисе настроек
* Кнопка *Подключить* -- кнопка применяет все выполненные в окне изменения. После сохранения в таблице появляется новая строка с настроенным подключением.
* Кнопка *Отменить* -- отменяет все изменения.
--
+
По нажатию на строку таблицы открывается то же окно _Подключить сервис_, в котором можно отредактировать настройки конкретного подключения. В каждой строке таблицы отображается кнопка удаления соединения. При удалении появляется сообщение: "Подтвердите удаление." / "Confirm removal.", кнопки: Ок/Отмена.

API-ключ для подключения к серверу::
Используется для аутентификации в API {wf}. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.

Имя системного пользователя::
Имя системной учётной записи {dv}.

Пароль системного пользователя::
Пароль системной УЗ, рекомендуется хранить в зашифрованном виде, см. подробнее в документации по установке системы, раздел "xref:install-linux::appendix/account-protection.adoc[]".

Штамп сертификата шифрования паролей::
Отпечаток закрытого ключа шифрования SHA1. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.

Сертификат для шифрования и подписания в бизнес-процессах::
Сертификат, с помощью которого будут выполняться все действия по подписанию и шифрованию во всех бизнес-процессах.

Лимит памяти::
Объем оперативной памяти, выделенной для сервиса Управления процессами.
