= Группа настроек "Подключение"

Данный раздел документации {of-mc} описывает группу настроек подключения модуля {wf} к серверу приложений.

Подключение к серверу приложений настраивается в {of-mc} на странице menu:Серверы[Имя-сервера > Управление процессами > Подключение к серверу приложений]. Интерфейс страницы настроек модуля {wf} представлен в виде списка. Поля и компоненты настроек представлены универсальными компонентами редактирования.

// Сервер приложений::
// Список, позволяющий выбирать зарегистрированный сервер приложений, к которому подключается сервис "Управление процессами".

[#default-mail]
Почта по умолчанию::
В списке отображаются названия почтовых соединений из xref:user:connections-mail-server.adoc[сохранённых в Сервисе настроек]. Выбранное в списке соединение назначается почтовым соединением по умолчанию для данного экземпляра модуля {wf}. Если соединение по умолчанию выбрано, оно будет использоваться. Если в сервисе настроек почтовые соединения недоступны, вместо списка отображается текст: `Нет доступных почтовых соединений`.

// :module: {wf}
// :proga: {cns}", раздел "Управление процессами
[#handling]
// Назначение сервиса для обработки баз данных::
// Компонент редактирования для выбора БД, xref:workflow:admin:cluster.adoc[доли обрабатываемых процессов] и почтового соединения, с которыми будет работать данный сервер СУБП. Компонент также позволяет выбирать почтовое соединениеfootnote:[
// include::partial$excerpts.adoc[tags=analog-program]
// ].
// +
// Компонент представляет собой таблицу с колонками: _Сервер приложений_, _База данных_, _Доля процессов_, _Почтовое соединение_. Под таблицей располагается кнопка *Подключить*. При нажатии на кнопку открывается окно _Подключить сервис_. Данное окно позволяет указывать долю процесса и выбрать почтовое соединение.
// +
// --
// .Следующие элементы доступны в окне "Подключить сервис":
// * _База данных_ -- Обязательное поле. Список БД, которые обрабатываются выбранным сервером приложений. Чтобы выбрать БД, установите флаг слева от её названия.
// * _Доля процессов_ -- Обязательное поле. Число, отражающее распределение нагрузки на выбранную БД
// * _Почтовое соединение_ -- раскрывающийся список почтовых соединений, сохраненных в том же Сервисе настроек
// * Кнопка *Подключить* -- кнопка применяет все выполненные в окне изменения. После сохранения в таблице появляется новая строка с настроенным подключением.
// * Кнопка *Отмена* -- отменяет все изменения.
// --
// +
// По нажатию на строку таблицы открывается то же окно _Подключить сервис_, в котором можно отредактировать настройки конкретного подключения. В каждой строке таблицы отображается кнопка удаления соединения. При удалении появляется сообщение: "Подтвердите удаление." / "Confirm removal.", кнопки: Ок/Отмена.

:module: {wf}
:parameter: APIKEY
API-ключ для подключения к серверу::
Используется для аутентификации в API данного сервиса {wf} Сервера приложенийfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]. Можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые. Обязательная настройка.

:module: {wf}
:parameter: SystemUserAccount
Имя системного пользователя::
Имя системной учётной записи {dv}footnote:[
include::partial$excerpts.adoc[tags=analog-param]
]. Обязательная настройка.

Пароль системного пользователя::
Пароль системной УЗ для взаимодействия с Сервером приложений, рекомендуется хранить в зашифрованном виде, см. подробнее в документации по установке системы, раздел "xref:install-linux::appendix/account-protection.adoc[]". Обязательная настройка.

[#cert-stamp]
:module: {wf}
:parameter: DataProtectCertificateThumbprint
Штамп сертификата шифрования паролей::
Отпечаток закрытого ключа шифрования SHA1footnote:[
include::partial$excerpts.adoc[tags=analog-param]
]. Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.

:module: {wf}
:parameter: MemorySize
Лимит памяти, Мбайт::
Объем оперативной памяти, выделенной для сервиса Управления процессамиfootnote:[
include::partial$excerpts.adoc[tags=analog-param]
]. Минимальное значение `1024` Мб.
