= Группа настроек "Шаблоны"

Группа настроек _Шаблоны_ предназначена для просмотра установленных шаблонов и возможность их повторной установки.

****
include::partial$excerpts.adoc[tags=readonly]
****

Шаблоны бизнес-процессов::
Каждая строка содержит сведения о конкретном шаблоне. Выберите шаблоны, . Шаблоны устанавливаются для БД, которая назначена по умолчанию. В таблице отображаются как стандартные шаблоны, так и пользовательские.
+
.Группа представлена таблицей с двумя колонками:
* Флаг -- позволяет выбрать одну или нексколько строк с шаблонами, которые нужно переустановить.
* Имя шаблона -- наименование, заданное в файле шаблона.
+
.Следующие шаблоны автоматически устанавливаются при инсталляции системы:
** Процессы мониторинга активизированных карточек согласования
** Процессы мониторинга активизированных карточек заданий
** Системные настройки
** Функции WF
** Шлюзы WF
** Процесс актуализации состояния сотрудников
+
* Установлен -- если в БД есть карточка с идентификатором этого шаблона, для него в колонке указывается признак `Да`. Если идентификатор не загружен в БД, для него в колонке указывается `Нет`. Если файл шаблона отсутствует, но шаблон был загружен в БД, он не отображается в таблице.

Переустановить::
Если бизнес-процессы изменились, их можно переустановить.
+
Отметьте флагами не установленные по каким-либо причинам бизнес-процессы или бизнес-процессы, которые со времени установки были изменены, нажмите кнопку *Переустановить* и дождитесь окончания установки.

.Чтобы добавить пользовательские шаблоны бизнес-процессов, необходимо:
. Разместите файл шаблона в папке `/usr/lib/docsvision/Workflow/Templates/`.
. Добавьте сведения о шаблоне в файл `ProcessTemplates.xml`.
. Выберите шаболоны в списке и переустановите их.
