= Настройки по умолчанию и разметки {of-mc}

[#default-settings]
== Настройки по умолчанию

При использовании {of-mc} версии 6.1 и выше и модулей {dv} самых новых версий каждый сервис (модуль) {dv} при инсталляции записывает значения своих настроек по умолчанию и свои разметки в {sett-serv}.

Вместе с каждым сервисом поставляется файл, который содержит значения настроек, рекомендуемых по умолчанию -- файл `appsettings.default.json`. При установке файл размещается в той же папке, что и `appsettings.json`. При регистрации компонента значения по умолчанию считываются из `appsettings.default.json` и записаться в {sett-serv}. Чтение настроек из этого файла выполняется только один раз. При последующем запуске компонента чтение настроек по умолчанию не требуется, а сам файл не является постоянным источником конфигурации. Если одна и та же настройка задана и в `appsettings.json` и в `appsettings.default.json`, её значение считывается только из `appsettings.json` и не заменяется значением по умолчанию.

[#layouts-publishing]
== Публикация разметок

Схемы страницы настроек сервиса в {of-mc} поставляются сервисами {dv}, каждый сервис поставляет разметки для своей страницы настроек. При регистрации любого сервиса вместе с его данными публикуются также данные о его страницах конфигурации.

Каждая страница имеет свой номер версии. Нумерация версий сквозная, начинается с `1`. После внесения любых изменений на странице версия повышается на `1`. При установке новой версии сервиса публикуется новая версия разметки. Один сервис может содержать несколько страниц настроек: основные и дополнительные. Дополнительные страницы версионируются по аналогии с основной. Версии основной и дополнительной страниц могут отличаться. Если изменения конфигурации затрагивают только основную страницу, номер версии дополнительной страницы не повышается.

При переходе на страницу настроек компонента вычисляется его версия. Для этой версии компонента открывается страница конфигурации соответствующей версии. Разметки недоступны для редактирования, они входят в комплект установки и устанавливаются автоматически.
