= Основные группы безопасности

В {dv} системные группы безопасности могут быть определены на одном из двух независимых уровней:

. Уровень Сервера приложений (<<appserver-groups,текущая страница>>) -- настраивается в {of-mc}. Права, назначаемые участникам групп, действуют на все БД, подключенные к данному экземпляру Сервера приложений.
. Уровень базы данных (см. документацию модуля {bo} "xref:backoffice:desdirs:staff/groups/system-groups.adoc[]") -- настраивается в Справочнике сотрудников. Права, назначаемые участникам групп, действуют только на текущую БД.

Составы групп на разных уровнях не синхронизируются, добавление пользователя в группу на одном уровне не добавляет его в аналогичную группу на другом.

[#appserver-groups]
{dv-users-serv} ({dv-users-dir})::
Члены группы имеют права на работу с системой {dv}.
+
По умолчанию в группу включаются все пользователи, совершившие совершившие вход в систему. Входит в систему могут только зарегистрированные в справочнике сотрудников пользователи. Участники этой группы по умолчанию имеют уровень допуска `самый низкий`; при необходимости их уровень допуска может быть переопределен в _Справочнике сотрудников_.
+
Члены группы имеют права на работу с системой после того, как их учетная запись добавлена в _Справочник сотрудников_. Вхождение в группу не предоставляет права на вход в {wincl} или {wc}.

{dv-power-users-serv} ({dv-power-users-dir})::
Члены группы имеют права просмотра всех объектов системы {dv}, включая чтение системного журнала, исключая, возможность изменения прав доступа.
+
По умолчанию пользователи в эту группу не включаются.

{dv-admins-serv} ({dv-admins-dir})::
Члены группы -- администраторы {dv}, имеют право доступа к БД, ряду административных функций, а также возможность чтения и предоставления прав доступа (но не изменения назначенного уровня безопасности) ко всем объектам базы данных. Администраторы могут входить в {wincl} без регистрации в справочнике сотрудников.
+
Пользователь, входящий в эту группу может архивировать и разархивировать карточки, на которые у него есть права, находить в архиве любые карточки, отображать содержимое архива в представлении {wincl} и РМА;
+
Пользователи этой группы всегда имеют уровень допуска `высокий`, несмотря на то, какой уровень указан для конкретного пользователя в Справочнике сотрудников.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

{dv-sec-admins-serv} ({dv-sec-admins-dir})::
Члены группы обладают всеми правами *{dv-admins-serv}*, а кроме того могут изменять уровни безопасности, назначенные субъектам и объектам системы.
+
Пользователи, входящие в эту группу могут архивировать, разархивировать и находить в архиве любые карточки.
+
Пользователи этой группы всегда имеют уровень допуска `самый высокий`, несмотря на то, какой уровень указан для конкретного пользователя в Справочнике сотрудников.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

{dv-arch-ops-serv} ({dv-arch-ops-dir})::
Члены группы имеют право архивировать и разархивировать и находить в архиве только те карточки {dv}, на работу с которыми у них есть права (минимальные требования -- права на чтение и изменение).
+
Группа создаётся на сервере {dv} и используется для проверки прав при работе с архивом. По умолчанию пользователи в эту группу не включаются.
+
Участникам группы предоставляются права группы *{dv-users-serv}*.

{dv-web-admin-cns-admins-serv} ({dv-web-admin-cns-admins-dir})::
Участники группы имеют право просматривать карточки сообщений в {of-mc}, а также открывать их в {wc}е или {wincl}е. Права действуют в рамках текущего экземпляра Сервера приложений.
+
CAUTION: Группа не предоставляет административного доступа к интерфейсу {of-mc} для изменения настроек.

== Дополнительные группы безопасности

{dv-wf-creators-serv} ({dv-wf-creators-dir})::
Члены группы имеют право создавать и редактировать шаблоны и экземпляры БП модуля _{wf}_. Поскольку БП во время исполнения имеет доступ к защищенным объектам, состав этой группы не менее важен, чем состав группы *{dv-admins-serv}*.
+
Участникам группы предоставляются права группы *{dv-users-serv}*.
+
В группу автоматически включается пользователь, настроивший систему {dv}.

{dv-search-creators-serv} ({dv-search-creators-dir})::
Члены группы имеют право работать с окном расширенного поиска (вызывать окно поиска из приложения {wincl}, создавать и сохранять поисковые запросы), создавать и редактировать личные и общие запросы, удалять и импортировать общие запросы _Личного помощника_.
+
По умолчанию в эту группу включаются все пользователи, зарегистрированные в справочнике сотрудников.
+
Пользователям, включённым в группу *{dv-search-creators-serv}*, должны быть предоставлены права на чтение и изменение системной папки `Результаты поиска`.
+
Участникам группы предоставляются права группы *{dv-users-serv}*.