// tag::linux[]
// tag::windows[]
:chego: сертификата шифрования

= Защита системной учётной записи

Системная учётная запись -- учётная запись пользователя, от имени которого сервис ({wc}, СУБП и пр.) должен подключаться к серверу {dv} при выполнении служебных операций.

include::dv6@install-linux:ROOT:partial$excerpts.adoc[tags=system-accounts]

При необходимости можно защитить шифрованием пароли системной учётной записи и учётной записи для работы с LDAP. Имена учётных записей шифровать не требуется. В данном разделе приведено руководство по шифрованию.

Для шифрования паролей используется утилита _EncryptionTool_, которая может быть установлена на Linux или Windows.

NOTE: Для шифрования паролей потребуется использовать сертификаты RSA.

// end::windows[]

[#lin-install]
== Установка и запуск утилиты на Linux

В Linux утилита устанавливается следующей командой:

[tabs]
====
{os1}::
+
 $ sudo apt-get install docsvision-encryption

{os2}::
+
 $ sudo dnf install docsvision-encryption
====

После установки утилита располагается по пути: `/usr/lib/docsvision/tools/encryption`.

Запустить утилиту можно из командной строки следующим образом:

.Запуск из директории установки:
[source,bash]
----
./encryption [command] [options]
----

.Запуск из любой директории:
[source,bash]
----
/usr/lib/docsvision/tools/encryption/encryption [command] [options]
----

// tag::certificate[]
[#lin-cr-cert]
== Создание и установка {chego} в Linux

include::../https-connection.adoc[tags=lin-gen]
+
// tag::self-signed[]
. [[earlier]]Полученный сертификат в формате `.pfx` необходимо скопировать в каталог `~/.dotnet/corefx/cryptography/x509stores/my`. Если каталог отсутствует, создайте его самостоятельно.
// end::self-signed[]
Пользователь, выполняющий шифрование, должен обладать правами на чтение и выполнение файлов в каталоге, а также правами на чтение сертификата.
// end::certificate[]

[#win-install]
== Установка и запуск утилиты на Windows

В ОС Windows утилита будет установлена вместе с серверной частью модуля _{pl}_ и после установки располагается по пути `C:\Program Files\Docsvision\Platform\Tools`.

.Запуск из директории установки:
[source,shell]
----
encryption.exe [command] [options]
----

.Запуск из любой директории:
[source,shell]
----
"C:\Program Files\Docsvision\Platform\Tools\encryption.exe" [command] [options]
----

:encypt-sserv:
[#win-cr-cert]
== Создание и установка {chego} в Windows

Сертификат можно сгенерировать в Windows и экспортировать в формате `.pfx` без пароля, действия аналогичны описанным в разделе "<<lin-cr-cert,Создание {chego} в Linux>>".

В Windows полученный сертификат необходимо установить в хранилище сертификатов текущего пользователя.

// tag::windows[]

[#encrypt-windows]
== Особенности настройки шифрования в Windows

В ОС Windows недостаточно указывать штамп сертификата в параметре _Штамп сертификата шифрования паролей_ в настройках модулей {wf} и {pl}, потребуются дополнительные настройки.

. Установите программу PsExec на сервер под управлением Windows.
. Установите сертификат для шифрования паролей.
. Выполните следующую команду через PsExec:

 psexec -i -u "NT AUTHORITY\\NETWORK SERVICE" cmd

+
По умолчанию в ОС Windows все службы запускаются от имени УЗ "NETWORK SERVICE". Если служба запускается от какой-то другой, укажите её.
+
. Перейдите в оснастку сертификатов `certmgr.msc`.
. Добавьте сертификат в личное хранилище пользователя.
. Отпечаток сертификата укажите в параметре _Штамп сертификата шифрования паролей_ для модулей "xref:6.2@mgmtconsole:servers:workflow-connection.adoc#cert-stamp[{wf}]" и "xref:6.2@mgmtconsole:servers:appserver-general.adoc#cert-stamp[{pl}]".
. {blank}
+
[subs="specialchars,attributes,quotes"]
Примените настройки и перезапустите службы {wfs-new}, {sss-new}.

// end::windows[]

[#encrypt]
== Шифрование пароля учётной записи

.Чтобы зашифровать пароль, выполните следующие команды:
. Зашифруйте пароль при помощи полученного сертификата.
+
[source,bash]
----
./encryption encrypt [отпечаток сертификата]
----
+
Отпечаток сертификата можно получить, выполнив запрос
+
[source,bash]
----
openssl pkcs12 -in docsvision.pfx -nodes | openssl x509 -noout -fingerprint
----
+
. В окне терминала введите пароль учётной записи для шифрования.
+
В ответ будет выведен зашифрованный пароль.
+
. Сохраните имя и пароль УЗ в зашифрованном виде:
+
.. Сохраните данные системной УЗ:
+
.В виде переменных окружения на машине с Windows:
[%collapsible]
====
****
* `DV_SystemUserAccount` -- имя системной учётной записи.
* `DV_SystemUserPassword` -- пароль системной учётной записи.
* `DV_DataProtectCertificateThumbprint` -- отпечаток сертификата шифрования.
****
====
+
.В конфигурационном файле Сервера приложений (модуля {pl}) на сервере Linux:
[%collapsible]
====
****
Добавьте в конфигурационный файл программы `appsettings.json` три параметра на корневом уровне:

* `SystemUserAccount` -- имя системной учётной записи в формате `user@domain.com`.
* `SystemUserPassword` -- пароль системной учётной записи в зашифрованном виде.
* `DataProtectCertificateThumbprint` -- отпечаток сертификата шифрования.
****
====
+
.. Данные УЗ для работы с LDAP сохраните в конфигурационном файле Сервера приложений (модуля {pl}) и/или {wc}:
+
****
* Использовать одну УЗ в качестве системной и для работы с LDAP необязательно, можно указывать разные УЗ в конфигурационных файлах модулей {pl} и {wc}. Главное условие -- указать верный пароль УЗ в зашифрованном или открытом виде.
* Параметр `DataProtectCertificateThumbprint` в конфигурационном файле необходимо указать только один раз. Для шифрования пароля системной УЗ и УЗ LDAP используется один отпечаток сертификата.
****
+
[source,json]
----
{
  "Ldap": {
    "AuthType": "Basic",
    "Credential": {
      "UserName": "user@domain.com", <.>
      "Password": "value" <.>
    }
  },
  "DataProtectCertificateThumbprint": "thumbprint", <.>
}
----
<.> Имя УЗ LDAP.
<.> Пароль системной УЗ LDAP в зашифрованном виде.
<.> `DataProtectCertificateThumbprint` -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`. +
Если шифровать пароль не планируется, параметр можно не указывать.
+
.. Вместо редактирования `appsettings.json` {mc} позволяет изменить нужные параметры через пользовательский интерфейс, настройка переменных среды не потребуется:
+
* Укажите данные системной УЗ и штамп сертификата шифрования в разделе "xref:6.2@mgmtconsole:servers:appserver-general.adoc[]".
* Укажите данные УЗ для работы с LDAP для модуля {pl} и/или {wc} в соответствующих разделах xref:6.2@mgmtconsole:servers:appserver-access.adoc#catalogs[для модуля "{pl}"] и/или xref:6.2@mgmtconsole:servers:webclient-connection.adoc#catalogs[для модуля "{wc}"].
+
. <<earlier,Если этого не было сделано ранее>>, установите сертификат шифрования в хранилище сертификатов текущего пользователя в ОС Windows и в каталог `~/.dotnet/corefx/cryptography/x509stores/my` в ОС Linux.
+
NOTE: Сертификат нужно добавлять в домашнюю папку пользователя, от имени которого запускается сервис. Например, для пользователя `root` (от имени пользователя ROOT службы запускаются по умолчанию) полный путь будет: `/root/.dotnet/corefx/cryptography/x509stores/my`. +
Если папка отсутствует, создайте её самостоятельно.

// end::linux[]
