= Особенности переноса БД

ifeval::[{old-console} == yes]
include::6.1@platform:admin:partial$mancons.adoc[]
endif::[]

== Перенос БД {mssql} Server с понижением редакции

{mssql} Server в редакции Standart имеет ограничения, которые не позволяют перенести БД {dv} с {mssql} Server Enterprise на SQL Server Standart.

== {pgsql}. Перенос БД {dv} на другой сервер

После переноса БД {dv} на другой сервер {pgsql} необходимо подготовить БД к работе, обновив адрес СУБД в конфигурации БД. Данная операция выполняется при повторном подключении БД к программе _{cns}_ и может быть выполнена двумя способами.

ifeval::[{old-console} == yes ]
.Обновление БД с помощью Консоли настройки {dv}
endif::[]
ifndef::old-console[]
.Обновление БД с помощью {of-mc}
endif::[]
. Выполните скрипт в БД {dv}:
+
[source,pgsql]
----
update dvsys_libraries
set "SysVersion" = "SysVersion" - 1
where "ID" = '26dbf2c0-e72e-4e9e-ab99-816758387ae2'::uuid
----
+
****
Данный скрипт понизит внутреннюю версию БД, чтобы было возможно выполнить следующий шаг.
****
+
ifeval::[{old-console} == yes ]
. Обновите БД при помощи Мастера баз данных из программы _{cns}_.
endif::[]
ifndef::old-console[]
. Обновите БД при помощи "xref:6.2@mgmtconsole:servers:db-master.adoc[Мастера баз данных]" из {of-mc}.
endif::[]
