= Подключение провайдера к внешнему хранилищу к системе {dv}

. Сборки с классом провайдера и классом графического интерфейса настройки должны быть подписаны. Допускается реализация класса провайдера и класса графического интерфейса в одной сборке.
. Сборки должны быть размещены в директории `/usr/lib/docsvision/common` в Linux и `C:\Program Files\Docsvision\Common` в Windows на сервере {dv}.

[start=3]
.Чтобы добавить новый тип хранилища в {dv} (требуется опция лицензии _{dv} модуль интеграции с произвольными файловыми хранилищами_):
include::dev@mgmtconsole:servers:partial$excerpts.adoc[tags=openStorages]
. При добавлении нового типа хранилища выберите в списке _Тип_ пункт *_Собственное хранилище_*.
. Укажите в поле _Имя сборки_ имя сборки (без расширения) из директории `/usr/lib/docsvision/common` в Linux и `C:\Program Files\Docsvision\Common` в Windows на сервере {dv}, в поле _Имя класса провайдера_ значение будет подставлено автоматически, в список _Тип_ будет добавлен новый пункт, соответствующий названию хранилища, указанному в `DisplayNameAttribute` класса хранилища.
. Настройте хранилище, группу и правила помещения стандартным образом согласно разделам в документации {of-mc}:
+
* "xref:dev@mgmtconsole:servers:db-storage-setup.adoc[]"
* "xref:dev@mgmtconsole:servers:db-storage-setup-group.adoc[]"
* "xref:dev@mgmtconsole:servers:db-storage-setup-rule.adoc[]"
