= Установка и настройка {of-mc}

// tag::linux[]
{mc} является основным инструментом конфигурации системы, необходимым для первоначальной настройки всех модулей системы, также без {of-mc} не будет функционировать модуль "xref:new-admin-console@workerservice::index.adoc[Служба {ws}]", необходимый для создания групп заданий и отправки почтовых уведомлений.
// end::linux[]

include::dev@mgmtconsole:user:partial$excerpts.adoc[tags=ext-ver]

// tag::linux[]
[#console]
== Установка {of-mc}

[WARNING]
====
{mc} можно установить на отдельный от {dv} сервер. В таком случае, пользователь, от имени которого запускается {mc}, должен быть добавлен в конфигурационном файле в параметр `{dv-web-admin-cns-admins-serv}` на сервере с Консолью управления. Также должны быть выполнены соответствующие настройки в конфигурационном файле модуля, подробнее см. ниже.
====
// end::linux[]

--
// tag::linux[]
.Чтобы установить {mc}:
:of: {of-mc}
:file: appsettings
:wt: managementconsole
include::new-admin-console@platform:admin:partial$install.adoc[]
// tag::config[]
+
[source,json]
----
{
  "SettingsService": {
    "ConnectionString": "ConnectAddress=http://settings.domain.com:5200/api", <.>
    "ApiKey": "SettingsServiceApiKey" <.>
  },
  "System": {
    "ManagementConsoleAddress": "http://console.domain.com:5100" <.>
  },
  "Catalogs": [], <.>
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
}
----
<.> `ConnectionString` -- Адрес {of-sett-serv}.
<.> `ApiKey` -- Ключ доступа к Сервису настроек -- "пароль", который также должен быть указан в конфигурационном файле сервиса и конфигурационном файле {of-sett-serv}.
<.> `ManagementConsoleAddress` -- Адрес {of-mc}.
<.> `Catalogs` -- см. подробнее "<<domain,Настройка работы в домене>>".
<.> `Docsvision Management Console Administrators` -- Пользователи, которым разрешен вход в Консоль управления.
// end::linux[]
// end::config[]
+
. Запустите службу Консоли:
+
[source,bash]
----
sudo systemctl start dvconsole
----
+
include::new-admin-console@install-linux:ROOT:partial$restart-and-db.adoc[]
--

[#settings-service]
include::new-admin-console@settings-service:admin:install.adoc[tags=linux,leveloffset=+1]

[#external-api]
== Установка сервиса внешнего API

Установка Сервиса внешнего API не требуется в версиях {of-mc} 6.2 и выше.

// tag::register-services[]
[#register-services]
== Регистрация модулей системы

Для возможности настройки модулей системы через интерфейс {of-mc} необходимо, чтобы в конфигурационном файле настраиваемого модуля, {pl} (*{sss-new}*), {fs} (*{fss-new}*), {wc} (*{wcs-new}*), {wf} (*{wfs-new}*), были заданы следующие параметры:

--
* menu:DocsVision[ServiceId] -- уникальный идентификатор данного экземпляра модуля. Параметр задаётся автоматически при установке модуля.
* menu:DocsVision[SettingsService > ConnectionString] -- адрес подключения к хранилищу настроек. Параметр необходимо указать вручную.
* menu:DocsVision[SettingsService > ApiKey] -- ключ приложения для подключения к хранилищу настроек. Параметр необходимо указать вручную.
--
// end::register-services[]

[#ws-ext]
== Установка расширения Службы {ws} для {of-mc}

Расширение Службы {ws} для {of-mc} добавляет функциональность для работы со Службой {ws}: настройка службы в Консоли, просмотр сообщений. Расширение обязательно для установки в версии {of-mc} 6.2 и выше.

:of: Расширение Службы {ws} для {of-mc}
// :file: appsettings конфига нет?
:wt: ext-ws-mc
.Чтобы установить расширение Службы {ws} для {of-mc}:
. Выполните следующие команды, чтобы установить {of}:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]

[#webc-ext]
== Установка расширения {wc}а для {of-mc}

Расширение {wc}а для {of-mc} необходимо для импорта решений {wc}а, получения списка локализаций и видов карточек, а также загрузки новых значений в базу данных.

.Чтобы установить "Расширение {wc}а для {of-mc}":
:of: Расширения {wc}а для {of-mc}
:wt: ext-webc-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]

[#pl-ext]
== Установка расширения сервера приложений для {of-mc}

Расширение сервера приложений для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки Сервера приложений из {of-mc}.

.Чтобы установить "Расширение сервера приложений для {of-mc}":
:of: Расширения сервера приложений для {of-mc}
:wt: ext-platform-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]

[#wf-ext]
== Установка расширения модуля {wf} для {of-mc}

Расширение модуля {wf} для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки модуля {wf} из {of-mc}.

.Чтобы установить "Расширение модуля {wf} для {of-mc}":
:of: Расширения модуля {wf} для {of-mc}
:wt: ext-workflow-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]

[#fs-ext]
== Установка расширения {of-fs} для {of-mc}

Расширение {of-fs} для {of-mc} включает связанные с модулем ресурсы локализации, обработчики и (при наличии) специализированные редакторы для настройки {of-fs} из {of-mc}.

.Чтобы установить "Расширение {of-fs} для {of-mc}":
:of: Расширения {of-fs} для {of-mc}
:wt: ext-fileservice-mc
. Установите компоненты {of} следующей командой, предварительно обновив индекс пакетов:
include::new-admin-console@platform:admin:partial$install.adoc[tags=commands]

// tag::string[]
:of-what: {of-sett-serv}

[#conn-string]
== Строка подключения к базе данных для хранения настроек

Строка подключения содержит адрес подключения к базе данных для хранения настроек. Вид строки подключения зависит от выбранной базы данных.

NOTE: Для _{of-what}_ рекомендуется использовать отдельную базу данных.

//tag::mssql[]
Для {mssql} Server: `Data Source=Адрес-сервера-баз-данных;Initial Catalog=Название-БД-{of-what};Integrated Security=False;User ID=Имя-пользователя-БД;Password=Пароль-пользователя-БД;TrustServerCertificate=True`.

* `Data Source` -- адрес сервера SQL для подключения к БД. В качестве `Data Source` может быть указан экземпляр SQL-сервера, например так: `Data Source=DVDatabse\\Server1`.
* `Название-БД-{of-what}` -- псевдоним базы данных.
* `Integrated Security` -- задает логическое значение, определяющее способ проверки подлинности:
** `False` -- при подключении в строке должны быть указаны идентификатор пользователя и пароль.
** `True` -- при подключении будут использованы учетные данные текущей учетной записи Windows.
* `Имя-пользователя-БД` -- учётная запись пользователя для подключения к БД.
* `Пароль-пользователя-БД` -- пароль учётной записи для подключения к БД.
* `TrustServerCertificate=True` -- подробнее про настройку см. <<cert,особенности настройки сертификата>>.

NOTE: При использовании строки подключения к хранилищу с Windows-аутентификацией для {mssql} Server учетной записи службы _{of-what}_ необходимо предоставить права на создание новых БД, а также полные права на БД, которая будет создана при запуске _{of-what}_.

ifndef::sm-page[]
Если в строке подключения введены корректные данные, при запуске _{of-what}_ будет создана новая или обновлена существующая БД.
endif::sm-page[]
//end::mssql[]

//tag::pgsql[]
Для {pgsql}/{pgl}: `host=Адрес-сервера-баз данных;Port=SQL-порт;database=Название-БД-{of-what};Username=Имя-пользователя-БД;Password=Пароль-пользователя-БД`.

* `Адрес-сервера-баз данных` -- адрес сервера SQL для подключения к БД.
* `SQL-порт` -- порт SQL-сервера.
* `Название-БД-{of-what}` -- псевдоним базы данных.
* `Имя-пользователя-БД` -- учётная запись пользователя для подключения к БД.
* `Пароль-пользователя-БД` -- пароль учётной записи для подключения к БД.
//end::pgsql[]
// end::string[]

[#configuration]
== Настройка {of-mc}

Установка приносит настройки, которые не зависят от машины где развертывается {mc}.
После установки создаётся файл настроек {of-mc} `appsettings.json` По умолчанию в файле указываются настройки для BackOffice.
В `.json` файле настроек содержатся: имена типов реализаций подключаемых к Службе {ws}, настройки их сопоставления, роли обработки задач BackOffice, а также настройки самой Службы {ws} (включая очереди, фабрики и прочие).

После установки {mc} требуется выполнить первичную настройку Консоли и _Службы {ws}_. Если проигнорировать первичную настройку, дальнейшая работа с системой будет невозможна. См. подробнее в руководстве пользователя Консоли управления "xref:dev@mgmtconsole:user:initial-configuration.adoc[]".

// tag::cert[]
[#cert]
== Особенности настройки сертификата

Настройка актуальна только для {mssql} Server, для {pgsql} дополнительных настроек не требуется. По умолчанию провайдер считает соединение с БД защищённым.

Если соединение не защищено (т.е. не настроен сертификат на уровне БД, используется самозаверенный или недействительный сертификат), необходимо в строке соединения указывать `TrustServerCertificate = true`, это сообщит провайдеру, что серверу можно доверять.

При необходимости использовать
ifeval::["{sservice}" == "yes"]
xref:dev@mgmtconsole:admin:https-access.adoc[защищённое соединение],
endif::[]
ifndef::sservice[]
xref:./https-access.adoc[защищённое соединение],
endif::[]
настройте {mssql} сервер в соответствии с инструкцией в руководстве по настройке системы, см. подробнее "xref:new-admin-console@engineer:ROOT:create-cert.adoc[]" в руководстве по настройке системы.
// end::cert[]

// tag::linux[]

[#domain]
== Настройка работы {of-mc} в домене

WARNING: Без выполнения данных настроек аутентификация в {of-mc} будет недоступна!

// tag::config[]
. {mc} поддерживает работу в одном или нескольких доменах. Для этого в конфигурационном файле модуля необходимо выполнить настройку доменных каталогов -- параметр `"Catalogs"`.
. В конфигурационном файле настройка представлена следующим массивом: `"Catalogs": []`. Настройки вступают в работу, если в массиве присутствует хотя бы одно описание каталога.
+
[source,json]
----
{
 "Catalogs": [
  {
   "FullDomainName": "example1.com", <.>
    "NetBiosDomainName": "example1", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example1.com" ], <.>
      "AuthType": "Basic", <.>
      "Credential": { <.>
        "UserName": "user@example1.com",
        "Password": "Password"
      }
    }
 },
  {
    "FullDomainName": "example2.com", <.>
    "ChallengeTo": "example1.com" <.>
  }
  ]
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `ChallengeTo` -- настройка позволяет переадресовывать запросы от выбранного домена к каталогам указанного домена, см. <<challengeto,далее>>.
// end::config[]
// end::linux[]

.Раздел `Catalogs` может содержать массив настроек вида:
[source,json]
----
{
    "FullDomainName": "example.com", <.>
    "NetBiosDomainName": "EXAMPLE", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example.com" ], <.>
      "AuthType": "Basic", <.>
      "Port": 389, <.>
      "Credential": { <.>
        "UserName": "user@example.com",
        "Password": "Password"
      }
    }
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

include::new-admin-console@platform:admin:config-domains.adoc[tags=chalto]

[#deletion]
== Удаление {of-mc}

Чтобы удалить {mc},
// запустите инсталлятор в режиме удаления.
выполните команду:

:wt: managementconsole
include::new-admin-console@platform:admin:partial$delete.adoc[]

Созданные группы и службы будут удалены, _{sett-serv}_ станет недоступен.
