:of-what: {of-sett-serv}

= Установка и настройка {of-mc}

WARNING: В данной версии установка {mc} предусмотрена только в ОС Linux.

Без установки и первоначальной настройки {of-mc} не будет функционировать базовый модуль "xref:6.1@workerservice::index.adoc[Служба {ws}]", необходимый для создания групп заданий и отправки почтовых уведомлений.

Требуется установить {mc} и сервис настроек. Установка должна выполняться на одной машине, установка на разные серверы не поддерживается.

[#console]
== Установка {of-mc}

[WARNING]
====
{mc} можно установить на отдельный от {dv} сервер. В таком случае, пользователь, от имени которого запускается {mc}, должен быть добавлен в конфигурационном файле в параметр `{dv-web-admin-cns-admins-serv}` на сервере с Консолью управления. Также должны быть выполнены соответствующие настройки в конфигурационном файле модуля, подробнее см. ниже.
====

--
.Чтобы установить {mc}:
:of: {of-mc}
:file: appsettings
:wt: managementconsole
include::6.1@platform:admin:partial$install.adoc[]
+
[source,json]
----
{
  "SettingsService": {
    "ConnectionString": "ConnectAddress=http://settings.domain.com:5200/api", <.>
    "ApiKey": "SettingsServiceApiKey" <.>
  },
  "ExternalApiService": {
    "ConnectionString": "Address=http://externalapi.domain.com:5300/api", <.>
    "ApiKey": "ExternalApiServiceApiKey" <.>
  },
  "System": {
    "ManagementConsoleAddress": "http://console.domain.com:5100" <.>
  },
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
}
----
<.> Адрес {of-sett-serv}.
<.> Ключ доступа к Сервису настроек -- "пароль", который также должен быть указан в конфигурационном файле сервиса и конфигурационном файле {of-sett-serv}.
<.> Адрес Сервиса внешнего API.
<.> Ключ доступа к Сервису внешнего API -- "пароль", который также должен быть указан в конфигурационном файле сервиса.
<.> Адрес {of-mc}.
<.> Пользователи, которым разрешен вход в Консоль управления.
+
. Запустите службу Консоли:
+
[source,bash]
----
sudo systemctl start dvconsole
----
+
include::install-linux:ROOT:partial$restart-and-db.adoc[]
--

[#sett-serv]
include::settings-service:admin:install.adoc[leveloffset=+1]

[#external-api]
== Установка сервиса внешнего API

.Чтобы установить Сервис внешнего API:
:of: Сервиса внешнего API
:file: appsettings
:wt: externalapi
include::6.1@platform:admin:partial$install.adoc[]
+
[source,json]
----
{
  "ApiKey": "ExternalApiServiceApiKey", <.>
  "SettingsService": {
    "ConnectionString": "address", <.>
    "ApiKey": "SettingsServiceApiKey" <.>
  }
}
----
<.> Ключ доступа к Сервису внешнего API -- "пароль", который также должен быть указан в конфигурационном файле {of-mc}.
<.> Адрес сервиса настроек. Например, `ConnectAddress=http://settings.domain.com:5200/api`.
<.> Ключ доступа к Сервису настроек -- "пароль", который также нужно указать в конфигурационном файле Сервиса настроек и конфигурационном файле {of-mc}.
+
. Запустите службу сервиса:
+
[source,bash]
----
sudo systemctl start dvexternalapi
----
+
include::install-linux:ROOT:partial$restart-and-db.adoc[]

// tag::string[]
[#conn-string]
== Строка подключения к базе данных для хранения настроек

Строка подключения содержит адрес подключения к базе данных для хранения настроек. Вид строки подключения зависит от выбранной базы данных.

NOTE: Для _{of-what}_ рекомендуется использовать отдельную базу данных.

//tag::mssql[]
Для {mssql} Server: `Data Source=Адрес-сервера-баз-данных;Initial Catalog=Название-БД-{of-what};Integrated Security=False;User ID=Имя-пользователя-БД;Password=Пароль-пользователя-БД;TrustServerCertificate=True`.

* `Data Source` -- адрес сервера SQL для подключения к БД. В качестве `Data Source` может быть указан экземпляр SQL-сервера, например так: `Data Source=DVDatabse\\Server1`.
* `Название-БД-{of-what}` -- псевдоним базы данных.
* `Integrated Security` -- задает логическое значение, определяющее способ проверки подлинности:
** `False` -- при подключении в строке должны быть указаны идентификатор пользователя и пароль.
** `True` -- при подключении будут использованы учетные данные текущей учетной записи Windows.
* `Имя-пользователя-БД` -- учётная запись пользователя для подключения к БД.
* `Пароль-пользователя-БД` -- пароль учётной записи для подключения к БД.
* `TrustServerCertificate=True` -- подробнее про настройку см. <<cert,особенности настройки сертификата>>.

NOTE: При использовании строки подключения к хранилищу с Windows-аутентификацией для {mssql} Server учетной записи службы _{of-what}_ необходимо предоставить права на создание новых БД, а также полные права на БД, которая будет создана при запуске _{of-what}_.

ifndef::sm-page[]
Если в строке подключения введены корректные данные, при запуске _{of-what}_ будет создана новая или обновлена существующая БД.
endif::sm-page[]
//end::mssql[]

//tag::pgsql[]
Для {pgsql}: `host=Адрес-сервера-баз данных;Port=SQL-порт;database=Название-БД-{of-what};Username=Имя-пользователя-БД;Password=Пароль-пользователя-БД`.

* `Адрес-сервера-баз данных` -- адрес сервера SQL для подключения к БД.
* `SQL-порт` -- порт SQL-сервера.
* `Название-БД-{of-what}` -- псевдоним базы данных.
* `Имя-пользователя-БД` -- учётная запись пользователя для подключения к БД.
* `Пароль-пользователя-БД` -- пароль учётной записи для подключения к БД.
//end::pgsql[]
// end::string[]

[#configuration]
== Настройка {of-mc}

Установка приносит настройки, которые не зависят от машины где развертывается {mc}.
После установки создаётся файл настроек {of-mc} `appsettings.json` По умолчанию в файле указываются настройки для BackOffice.
В `.json` файле настроек содержатся: имена типов реализаций подключаемых к Службе {ws}, настройки их сопоставления, роли обработки задач BackOffice, а также настройки самой Службы {ws} (включая очереди, фабрики и прочие).

После установки {mc} требуется выполнить первичную настройку Консоли и _Службы {ws}_.

.Если проигнорировать первичную настройку:
* Не будут создаваться и отправляться группы заданий.
* Не будут отправляться почтовые уведомления исполнителям.

См. подробнее в руководстве пользователя Консоли управления "xref:6.1@mgmtconsole:user:initial-configuration.adoc[]".

// tag::cert[]
[#cert]
== Особенности настройки сертификата

Настройка актуальная только для {mssql}, для {pgsql} дополнительных настроек не требуется.
// end::cert[]

Поскольку _{mc}_ работает под управлением .NET 6, компонент `System.Data.SqlClient` был заменён на `Microsoft.Data.SqlClient` как более перспективный с точки зрения развития.

В этом компоненте значение `Encrypt` по умолчанию https://learn.microsoft.com/ru-ru/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver15#encrypt-default-value-set-to-true[изменилось].
// tag::cert[]
По умолчанию провайдер считает соединение с БД защищённым.

Если соединение не защищено (т.е. не настроен сертификат на уровне БД, используется самозаверенный или недействительный сертификат), необходимо в строке соединения указывать `TrustServerCertificate = true`, это сообщит провайдеру, что серверу можно доверять.

Если есть потребность защитить соединение, настройте {mssql} сервер в соответствии с xref:engineer:ROOT:create-cert.adoc[инструкцией].
// end::cert[]

[#domain]
== Настройка работы в домене

{mc} поддерживает работу в одном или нескольких доменах. Для этого в конфигурационном файле модуля необходимо выполнить настройку доменных каталогов -- параметр `"Catalogs"`.

В конфигурационном файле настройка представлена следующим массивом: `"Catalogs": []`. Настройки вступают в работу, если в массиве присутствует хотя бы одно описание каталога.

WARNING: Без выполнения данных настроек аутентификация в модуле будет недоступна!

[source,json]
----
 "Catalogs": [
  {
   "FullDomainName": "example1.com", <.>
    "NetBiosDomainName": "example1", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example1.com" ], <.>
      "AuthType": "Basic", <.>
      "Credential": { <.>
        "UserName": "user@example1.com",
        "Password": "Password"
      }
    }
 },
  {
    "FullDomainName": "example2.com", <.>
    "ChallengeTo": "example1.com" <.>
  }
]
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `ChallengeTo` -- настройка позволяет переадресовывать запросы от выбранного домена к каталогам указанного домена, см. <<challengeto,далее>>.

.Раздел `Catalogs` может содержать массив настроек вида:
[source,json]
----
 {
    "FullDomainName": "example.com", <.>
    "NetBiosDomainName": "EXAMPLE", <.>
    "LdapOptions": { <.>
      "LdapServerAddresses": [ "example.com" ], <.>
      "AuthType": "Basic", <.>
      "Port": 389, <.>
      "Credential": { <.>
        "UserName": "user@example.com",
        "Password": "Password"
      }
    }
}
----
<.> `FullDomainName` -- полное имя домена указывается в формате `user@example.com` учётной записи после `@`.
<.> `NetBiosDomainName` -- `NetBios`-имя домена указывается в формате `domain\\user` перед `\\`.
<.> `LdapOptions` -- настройки подключения к LDAP каталогу домена.
<.> `LdapServerAddresses` -- адреса серверов LDAP данного домена. Если адрес соответствует полному имени домену, параметр можно удалить.
<.> `AuthType` -- тип аутентификации в LDAP.
<.> `Port` -- порт подключения к LDAP каталогам, перечисленным в `LdapServerAddresses`.
<.> `Credential` -- логин и пароль пользователя для подключения к LDAP-каталогам текущего домена. Пароль для подключения можно зашифровать, см. подробнее в документации по установке системы, раздел "xref:install-linux:ROOT:appendix/account-protection.adoc[]".

include::6.1@platform:admin:config-domains.adoc[tags=chalto]

[#deletion]
== Удаление {of-mc}

Чтобы удалить {mc},
// запустите инсталлятор в режиме удаления.
выполните команду:

:wt: managementconsole
include::6.1@platform:admin:partial$delete.adoc[]

Созданные группы и службы будут удалены, _{sett-serv}_ станет недоступен.
