:mo: {mc}
:cu253-mo-req: {cu253-mc-req}

= Авторизация в Консоли управления по протоколу LDAPS без Active Directory

Данный раздел описывает работу {of-mc} с каталогом ALD Pro без привязки к конкретной службе каталогов Active Directory. Настройка работы Сервера приложений описана в руководстве по настрйоке системы, см. "xref:CU25.3@engineer:ROOT:ldaps-without-ad.adoc[]". Администратор самостоятельно может настроить получение данных по доменным учётным записям, включая системные УЗ из каталога ALD Pro.

include::CU25.3@engineer:ROOT:partial$excerpts.adoc[tags=domain-format]

// [#ldaps]
// == Коннектор к LDAPS
//
include::CU25.3@engineer:ROOT:partial$excerpts.adoc[tags=ldaps-conditions]
//
// [source,json]
// ----
// {
// "Authentication": {
//   "Connectors": [
//      {
//         "Name": "LDAP", <.>
//         "Type": "DocsVision.Auth.Extensions.GenericLDAPConnector, DocsVision.Auth.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7148afe997f90519", <.>
//         "Settings": "<?xml version=\"1.0\" encoding=\"utf-16\"?><LdapConnectorOptions><LdapServerAddresses><string>example.com</string></LdapServerAddresses><Port>389</Port><EnableLDAPS>true</EnableLDAPS><FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName><Credential><UserName>user@example.com</UserName><Password>Password</Password></Credential></LdapConnectorOptions>", <.>
//         "Id": "{D5002984-4C2A-4EFB-9B3B-83E142E4DB73}" <.>
//      }
//   ]
// }
// }
// ----
// <.> `Name` -- задаёт название коннектора.
// <.> `Type` -- строка с именем типа, реализующего коннектор, указывается так же, как в примере.
// <.> `Settings` -- строка настроек коннектора, для LDAPS. Подробнее см. <<ldaps-settings,ниже>>.
// <.> `ID` -- строка с идентификатором коннектора в виде Guid.
//
// include::CU25.3@engineer:ROOT:ldaps-without-ad.adoc[tags=ldaps-settings]

[#ald]
== Коннектор к ALD Pro

ALD Pro является альтернативной службой каталогов с групповыми политиками, предназначенной для управления устройствами в сети. ALD Pro работает по протоколу LDAPS.

include::CU25.3@engineer:ROOT:partial$excerpts.adoc[tags=ald-format]

[source,json]
----
{
  "Authentication": {
    "Connectors": [
      {
        "Name": "ALDPro", <.>
        "Type": "DocsVision.Auth.Extensions.ALDProConnector, DocsVision.Auth.Extensions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7148afe997f90519", <.>
        "Settings": "<?xml version=\"1.0\" encoding=\"utf-16\"?><LdapConnectorOptions><LdapServerAddresses><string>XXX.XXX.XXX.XXX</string></LdapServerAddresses><Port>389</Port><EnableLDAPS>true</EnableLDAPS><FullyQualifiedDnsHostName>false</FullyQualifiedDnsHostName><Credential><UserName>user@example.com</UserName><Password>Password</Password></Credential></LdapConnectorOptions>", <.>
        "Id": "{DCF3EDA3-2F84-4FD1-8E1D-A06B762AE822}" <.>
		  }
    ]
  }
}
----
<.> `Name` -- задаёт название коннектора.
<.> `Type` -- строка с именем типа, реализующего коннектор.
<.> `Settings` -- строка настроек коннектора к ALD Pro. Подробнее см. <<ald-settings,ниже>>.
<.> `ID` -- строка с идентификатором коннектора в виде Guid.

include::CU25.3@engineer:ROOT:ldaps-without-ad.adoc[tags=ald-settings]

.Особенности и рекомендации при работе с ALD Pro:
****
* ALD Pro не поддерживает пробелы и заглавные буквы в именах пользователей и групп, а также имеет прочие ограничения наименования. +
В связи с этим *только для данного коннектора* допускается использовать следующий аналог группы *{dv-web-admin-cns-admins-serv}*: *docsvision_management_console_administrators*
+
include::CU25.3@engineer:ROOT:ldaps-without-ad.adoc[tags=bla-bla]
