= Предоставление доступа к {of-mc}

При работе с Консолью управления выделяется роль _Администратор {of-mc}_. Администратору предоставляется полный доступ ко всем функциям модуля.

Предоставить пользователям доступ к Консоли или внесению изменений в конфигурацию _{of-sett-serv}_ можно вручную, изменив конфигурационный файл {of-mc}:

// tag::config[]
.Фрагмент конфигурационного файла модуля {pl}:
[source,json]
----
{
  "DocsVision": {
  "Groups": {
    "DocsVision Management Console Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
}
----
<.> Добавьте пользователей, которые должны иметь доступ к {of-mc}.
// end::config[]

[source,json]
----
{
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
}
----
<.> Добавьте пользователей, которые должны иметь доступ сообщениям карточек.

ifndef::windows[]
// tag::keytab[]
NOTE: При необходимости может быть настроена прозрачная аутентификация Kerberos, необходимые настройки см. в разделе "xref:dv6@engineer:ROOT:kerberos-authentication.adoc[]".
// end::keytab[]
endif::windows[]
