= Поиск по номенклатуре дел

include::6.1@webclient:user:page$directories/staff/search.adoc[tags=activateSearch]

.Поиск осуществляется:
* В режиме отображения "Делопроизводитель" поиск осуществляется по всем разделам и делам справочника в выбранном году. Если был выбран другой год, то поиск запустится снова, но уже для другого года. В раскрывающемся списке слева от поисковой строки можно выбрать поиск только по делам или только по разделам.
* В режиме отображения "Архивариус" поиск осуществляется по всем фондам, описям и делам справочника.

Поиск осуществляется по полям "Объектов номенклатуры": MainInfo\Name, MainInfo\Title, MainInfo\Index, MainInfo\Number.

В результатах поиска отображаются все найденные результаты, а также указывается общее количество найденных результатов. Цветом выделяются совпадения с поисковым запросом.

Нажатие на результат поиска переводит в иерархическую структуру справочника. Структура справочника сворачивается до выбранного элемента и фокус смещается на найденный элемент.
