= Сведения о составных частях модуля

Модуль {wc} состоит из следующих частей:

[horizontal]
Сервер приложений {wc}::
Включает следующие элементы:
+
* Компоненты, обеспечивающие работу веб-приложения.
// * Программа _{pu}_ -- приложение для рабочего стола, которое предназначено для настройки {wc}а администратором.

{dv} {wc} Toolkit::
* Программа _{kvr}_ -- приложение для рабочего стола, которое предназначено для настройки разметок (интерфейса пользователя) {wc}а.
* _DVWebTool_ и _DvSupService_ -- обеспечивают возможность взаимодействия {wc}а с программным и аппаратным обеспечением компьютера пользователя в ОС Windows и Linux соответственно. Сборка и настройка _DVWebTool_ делегирована утилите xref:admin:webservices-install.adoc[WebToolBuilder].

Серверное расширение {wc}::
Серверное расширение устанавливается на компьютеры с _сервером {dv}_ и включает следующие компоненты:
+
* Схему метаданных справочника _Расширенный конструктор разметок_ (для хранения данных программы {kvr}).
* Хранимые процедуры для БД.
