= Изменение состояния карточки

.Пример кода, переводящего карточку группы заданий в завершённое состояние:
[source,csharp]
----
ObjectContext context = this.LocalContext; <.>
            
BaseCard taskGroupCard = GetParentCard(); <.>

if (taskGroupCard != null)
{
    if (this.LocalContext.LockObject(taskGroupCard, false)) <.>
    {
        ObjectModel.Services.IStateService stateService = context.GetService<ObjectModel.Services.IStateService>(); <.>

        StatesStateMachineBranch branch = stateService.FindBranchByBuiltIn(TaskGroup.PerformanceToCompletedByCompleteBranch, taskGroupCard.SystemInfo.State); <.>
        if (branch = null)
            return false;

        taskGroupCard.SystemInfo.State = branch.EndState; <.>

        this.LocalContext.SaveObject<BaseCard>(taskGroupCard); <.>

        this.LocalContext.UnlockObject(taskGroupCard); <.>
    }
}
----
<.> Получаем контекст.
<.> Получаем карточку.
<.> Блокируем карточку.
<.> Получаем сервис состояний.
<.> Получаем ветку перехода по встроенной ветке перехода.
<.> Получаем конечное состояние веки и присваиваем его полю состояния в карточке.
<.> Сохраняем карточку группового задания.
<.> Разблокируем карточку.

[#code]
== Добавление собственного кода при создании задания по группе заданий

При создании задания по группе заданий можно добавлять собственный код стандартным способом, по аналогии с другими случаями:

. На уровне логики карточки группы заданий. Унаследовать `TaskGroupEventHandlerService`, в нём дореализовать нужную функциональность, определив свои версии нужных методов. Заменить в справочнике видов (в секции `Services` у нужного вида ГЗ) штатную регистрацию сервиса `TaskGroupEventHandlerService` на собственную.
. На уровне логики карточки задания. Реализовать `ITaskEventHandlerService` или `IEventHandlerService` (можно унаследовать базовый класс `EventHandlerService`). Реализовать метод-обработчик смены состояния задания, в котором при запуске задания выполнять нужную логику. Добавить в справочнике видов (в секции `Services` у нужного вида задания) регистрацию этого нового сервиса обработчика. Другой вариант -- унаследовать `TaskEventHandlerService` и переопределять его логику, но тогда нужно заменять регистрацию стандартного сервиса в справочнике видов, а не добавлять параллельно (иначе одна и та же базовая логика будет отрабатывать 2 раза).
