= Назначение и функции модуля

Служба {ws} предназначена для выполнения задач, поступивших от других компонентов {dv} в фоновом режиме. Модули и компоненты могут делегировать Службе {ws} обработку данных или выполнение иных длительных задач, для которых не требуется немедленное получение результата и возможно выполнение вне {of-ws} модуля.

.В модуле Служба {ws} реализованы следующие функции:
* Выполнение задач различных типов:
** Сервисные задачи.
** Периодические задачи.
** Задачи по расписанию.
** Задачи по получению сообщения в очереди.
* Создание дополнений, расширяющих функции модуля.
* Изоляция выполнения задач определённого типа в выделенном физическом процессе.
* Создание кластера Службы {ws} для параллельной обработки задач.
// * Отправка почтового уведомления о завершении задания автору.
// * Отправка почтового уведомления о завершении группы заданий автору.
// * Отправка почтового уведомления об отклонении задания автору.
// * Отправка почтового уведомления о начале приёмки задания.
// * Отправка почтовых уведомлений.

Служба {ws} выполняет задачи таких компонентов, как:

* Новый конструктор согласований
* Задания и Группы заданий
+
Логика работы заданий и групп заданий, а также модуля {ad} использует Службу {ws}. Бизнес-процессы модуля {wf} отвечают только "старые", уже настроенные маршруты. Новые маршруты усовершенствованного согласования работают исключительно через Службу {ws}.
+
* Почтовый клиент
* Менеджер решений
* Сервис по перештамповке ЭЦП
* Модуль интеграции с реестром МЧД
