= Требования к учётной записи Службы {ws}

_Служба {ws}_ является базовым модулем системы {dv}. Для учётной записи, от имени которой запускается Служба {ws}, требуются такие же права, как и для учётной записи модуля _{wf}_. Подробно требования перечислены ниже.

. Членство в группе *{dv-sys-wf-dir}*. Доменная учётная запись, указанная в {of-mc} для подключения Службы {ws} (См. документацию модуля {mc}, раздел "xref:6.2@mgmtconsole:user:connections-docsvision.adoc[]"), должна состоять в группе *{dv-sys-wf-dir}* в справочнике сотрудников на сервере {dv}.
+
WARNING: Используйте учётную запись, которая будет указана в _{of-mc}_ для подключения Службы {ws} к серверу.
+
. Права на карточку сообщений очереди почтовых уведомлений. Пользователь, от имени которого запускается Служба {ws}, должен обладать правами на чтение, изменение и удаление карточки с идентификатором `0C052E58-3C25-4F29-8CE1-FF9CC2D1F31B`.
+
По умолчанию необходимые права выдаются автоматически при создании карточки сообщений. Если УЗ была изменена, соответствующие права на карточку необходимо выдать вручную.
