= Конфигурация модуля {pl}

Настройка модуля выполняется при помощи {of-mc} и частично в конфигурационном файле `/usr/lib/docsvision/platform/appsettings.json`.

. Откройте конфигурационный файл в любом текстовом редакторе, например `nano` (потребуются права суперпользователя) и заполните следующие параметры:
+
.Фрагмент конфигурационного файла `appsettings.json`:
[source,json]
----
{
  "DocsVision": {
    "ServiceId": "00000000-0000-0000-0000-000000000000", <.>
    "SettingsService": {
      "ConnectionString": "http://localhost:5200/api", <.>
      "ApiKey": "anything" <.>
    },
  },
  "AllowedHosts": "*",
  "Kestrel": { <.>
    "Endpoints": {
      "Http": {
        "Url": "http://*:5000"
      }
    }
  }
}
----
<.> `ServiceId` -- уникальный идентификатор данного экземпляра модуля, генерируется и записывается автоматически.
<.> `ConnectionString` -- полный адрес {of-sett-serv}.
<.> `ApiKey` -- API-ключ для подключения к {to-sett-serv}, можно оставить значение по умолчанию или изменить, главное условие, чтобы значения в конфигурации модулей {sett-serv} и {pl} были одинаковые. Адрес и API-ключ требуется указать, если планируется переходить в {mc} из карточек {wc}а и {wincl}а.
<.> Опционально. Настройка доступа к Storage Server по HTTPS, см. подробнее xref:platform:console:https-access.adoc[].
+
. Откройте {mc} на странице menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:db-settings.adoc[Группа настроек "Базы данных"]], чтобы выбрать БД по умолчанию.
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc#catalogs[Настройка доменных каталогов]" укажите параметры:
+
* Тип аутентификации в LDAP
* Логин -- имя учётной записи, под которой процесс обращается к ActiveDirectory
* Пароль -- пароль учётной записи пользователя для аутентификации LDAP
* Домен по умолчанию -- полное имя домена для входа по умолчанию в формате FQDN
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-general.adoc[Общие настройки сервера приложений]" укажите параметры:
+
* API-ключ для подключения к Workflow -- используется для подключения серверного расширения {wf}. API-ключ для подключения серверного расширения {wf}. Главное условие, чтобы значения в конфигурации модулей {pl} и {wf} были одинаковые.
* Логин системной учётной записи.
+
include::ROOT:partial$excerpts.adoc[tags=system-accounts]
+
* Пароль системной учетной записи.
+
* Штамп сертификата шифрования паролей -- отпечаток закрытого ключа шифрования SHA1. +
Указывается без двоеточия, например, `D8602179888DC8402B393F11DCA16A3376DDF879`, см. подробнее в документации по установке системы, раздел "xref:install-linux::appendix/account-protection.adoc[]". +
Если шифровать пароль системной учётной записи не планируется, параметр можно не указывать.
+
. В разделе "xref:dev@mgmtconsole:servers:appserver-access.adoc#groups[Группы пользователей]" выполните настройку сисемных групп.
. При необходимости в {mc}, на странице menu:Серверы[Имя сервера > Сервер приложений > "xref:dev@mgmtconsole:servers:appserver-auth-extensions.adoc[Группа настроек "Расширенная аутентификация"]], настройте использование расширенной аутентификации.
. В разделе menu:Серверы[Имя сервера > Сервер приложений > xref:dev@mgmtconsole:servers:appserver-etc.adoc[Дополнительные настройки]] задайте необязательные параметры:
+
* `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;LogFile` -- указывает путь к файлу журнала сервера. Если параметр не указан, действует системная настройка по умолчанию.
* `{dv}&#95;&#95;Platform&#95;&#95;Server&#95;&#95;TraceLevel&#95;&#95;LogLevel` -- настройка уровня журналирования.
. Настройка клиентской части {wincl} выполняется при помощи конфигурационного файла `windows-client-part.json`, см. подробнее xref:dev@mgmtconsole:servers:config-client.adoc[]. Если использовать {wincl} не планируется, пункт можно пропустить.

[#connection-string]
== Строка подключения к БД

.{mssql}
****
`Initial Catalog=Имя-БД-{dv}; Data Source=Полное-имя-сервера-СУБД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****

.{pgsql}
****
`Server=Адрес-сервера-базы-данных; Port=SQL-порт; Database=Название-БД; User ID=Имя-пользователя; Password=Пароль-пользователя;`
****
