// Ранее было так:
// :asp: ASP.NET 4.6
// :platform:
// :installguide:
//
// include::partial$preconfigure-server.adoc[]
// partial до сих пор существует
:os1: Astra Linux

= Предварительная настройка сервера Linux

// tag::preconfig[]
// . Подключите официальный репозиторий {dv} в качестве источника пакетов. Для этого необходимо отредактировать `/etc/apt/sources.list` при помощи текстового редактора, например, _nano_:
// +
// [source,bash]
// ----
// sudo nano /etc/apt/sources.list
// ----
// +
. В {os1} установите ПО, необходимое для подключения репозитория {dv} следующими командами:
+
[source]
----
sudo apt-get update
sudo apt-get install ca-certificates curl
----
+
В {os2} создайте файл для указания адреса репозитория:
+
[source]
----
sudo nano /etc/yum.repos.d/docsvision.repo
----
+
// tag::repo[]
. Подключите официальный репозиторий {dv} в качестве источника:
+
[tabs]
=====
{os1}::
+
[source]
----
sudo curl -fsSLo /etc/apt/trusted.gpg.d/docsvision.asc https://packages.docsvision.com/linux/docsvision.asc
echo "deb https://packages.docsvision.com/linux/6.1/$(. /etc/os-release && echo $ID $VERSION_CODENAME) main" | sudo tee /etc/apt/sources.list.d/docsvision.list > /dev/null
echo "deb https://packages.docsvision.com/linux/6.2/$(. /etc/os-release && echo $ID $VERSION_CODENAME) main" | sudo tee -a /etc/apt/sources.list.d/docsvision.list > /dev/null
sudo apt-get update
----

{os2}::
+
[source]
----
[docsvision]
name=Docsvision for RED OS $releasever
baseurl=https://packages.docsvision.com/linux/6.1/redos/8.0/$basearch/main
enabled=1
gpgcheck=1
gpgkey=https://packages.docsvision.com/linux/6.1/redos/docsvision.asc

[docsvision62]
name=Docsvision for RED OS $releasever
baseurl=https://packages.docsvision.com/linux/6.2/redos/8.0/$basearch/main
enabled=1
gpgcheck=1
gpgkey=https://packages.docsvision.com/linux/6.2/redos/docsvision.asc
----

{os3}::
+
[source]
----
curl -fsSL https://packages.docsvision.com/linux/docsvision.asc | sudo gpg --no-default-keyring --keyring /usr/lib/alt-gpgkeys/pubring.gpg --import
printf 'simple-key "docsvision" {\n\tFingerprint "DFAC99D298A0EC4E98B57238BCF7D31F16E999D6";\n\tName "DocsVision <help@docsvision.com>";\n}\n' | sudo tee /etc/apt/vendors.list.d/docsvision.list > /dev/null
echo "rpm [docsvision] https://packages.docsvision.com/linux/6.1/altlinux $(. /etc/os-release && echo p$VERSION | cut -d . -f 1)/branch/noarch main" | sudo tee /etc/apt/sources.list.d/docsvision.list > /dev/null
echo "rpm [docsvision] https://packages.docsvision.com/linux/6.2/altlinux $(. /etc/os-release && echo p$VERSION | cut -d . -f 1)/branch/noarch main" | sudo tee -a /etc/apt/sources.list.d/docsvision.list > /dev/null
sudo apt-get update
----
+
[WARNING]
====
При обновлении пакета `alt-gpgkeys` ключ подписи репозитория будет удалён. В этом случае его нужно добавить повторно, либо поставить этот пакет на https://www.altlinux.org/Hold[Hold].
====

=====
// end::repo[]
+
. Подключите репозиторий дополнительного ПО ({asp-bundle}) предпочтительным способом. Для {os2} перейдите сразу к <<kerb,пункту 4>>.
+
* Используйте расширенный репозиторий {os1} (предпочтительный способ для {os1} 1.8 и выше).
// , раскомментировав следующую строку в файле `/etc/apt/sources.list`
// +
// [source]
// ----
// deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free
// ----
+
* Получите необходимое ПО из репозитория {ms} (способ для {os1}, см. "xref:upgrade:cu253:update.adoc#astranet[Руководство по обновлению]").
// +
// [lowerroman]
// .. Подключите репозиторий следующими командами:
// +
// [source,bash]
// ----
// sudo apt-get install packages-microsoft-prod
// sudo apt-get update
// ----
// +
// .. Поднимите приоритет пакетов из репозитория {ms}, для этого создайте файл `/etc/apt/preferences.d/microsoft.pref` и добавьте в него следующие строки:
// +
// [source]
// ----
// Package: dotnet* aspnet* netstandard*
// Pin: origin packages.microsoft.com
// Pin-Priority: 910
// ----
+
. [[kerb]]Чтобы иметь возможность использования сквозной аутентификации в {wc}е, {wincl}е, РМА и {of-mc} в Linux необходимо выполнить специальные настройки Kerberos и используемого браузера.
// end::preconfig[]
