:os1: Astra Linux

= Удаление модуля

Компоненты модуля удаляются стандартными средствами ОС.
При удалении будет предложено удалить или сохранить настройки сервера {dv}; если планируется полное удаление, настройки можно также удалить, в противном случае -- сохранить.

WARNING: Компоненты модуля {pl} следует удалять только после удаления других модулей {dv}. Если не все другие модули были удалены предварительно, система не позволит продолжить удаление.

// .Удалите модуль {pl} в следующем порядке:
// . _{pl}_. Сервер.
// . _{pl}_. Клиент.

[#windows]
== Удаление на Windows

* Чтобы удалить модуль в ОС Windows, воспользуйтесь стандартными средствами системы (Установка и удаление программ).

[#linux]
== Удаление на Linux

* Чтобы удалить модуль {pl} в ОС Linux, выполните команду:
+
--
:wt: platform
include::6.1@platform:admin:partial$delete.adoc[]
--
+
** Чтобы удалить раширение модуля {pl} для {of-mc} в ОС Linux, выполните:
+
--
:wt: ext-platform-mc
include::6.1@platform:admin:partial$delete.adoc[]
--
+
* Чтобы удалить модуль {fs} в ОС Linux, выполните команду:
+
--
:wt: fileservice
include::6.1@platform:admin:partial$delete.adoc[]
--
+
** Чтобы удалить раширение модуля {fs} для {of-mc} в ОС Linux, выполните:
+
--
:wt: ext-fileservice-mc
include::6.1@platform:admin:partial$delete.adoc[]
--
