:platform:
:service:
:restart: dvappserver
:update: platform
:installer: {dv} Platform server.msi

= Обновление модуля

include::webclient:ROOT:partial$excerpts.adoc[tags=what-changed]

[#conditions]
== Условия обновления

* Установка новой версии должна выполняться в нерабочее время.
* Перед установкой создайте резервную копию БД {dv}.
* Если в БД {pgsql} используется pgAgent, остановите планировщик.
* База данных {dv} должна быть переведена на работу с расширенными метаданными.
* При обновлении разных серверов компоненты модуля должны быть одной версии.

.Обратите внимание!
****

Данное обновление включает изменение способа хранения расширенных метаданных в БД, после обновления может потребоваться изменение собственных хранимых процедур. Подробности в пункте xref:update-scripts.adoc[Обновление кода скриптов, работающих с БД {dv}].

'''

При обновлении версия клиентского дистрибутива должна быть равной версии серверного дистрибутива.
****

Перед установкой убедитесь в наличии {net-r}, подробнее см. "xref:ROOT:requirements-software.adoc[]".

include::partial$update.adoc[]

[#client]
== Обновление клиентских компонентов

include::new-admin-console@platform:admin:partial$client.adoc[]
`{dv} Platform client.msi`.
+
[NOTE]
====
Если клиентская часть модуля {pl} установлена с областью установки _для текущего пользователя_, *самостоятельно удалите ВСЕ клиентские компоненты старой версии* до установки новой, в ином случае в ОС будут параллельно существовать старая и новая версии.
====
+
. При необходимости после установки модуля {pl} установите клиентские компоненты других модулей.
+
Клиентские компоненты других модулей будут установлены с областью установки _для всех пользователей_.
