= Запуск Консоли управления

WARNING: {mc} не поддерживает работу в браузере Microsoft Internet Explorer.

== Требования для запуска {of-mc}

.Предварительные требования для запуска {mc}:
. {mc} должна быть xref:admin:install.adoc[установлена].
. Нужно знать сетевой адрес {of-mc}.
. Пользователь должен быть указан в параметре `{dv-web-admin-cns-admins-serv}` в конфигурационном файле {of-mc}, см. подробнее "xref:admin:config.adoc[]".
// на компьютере с установленным модулем {mc}.
. Для работы с Консолью управления должен использоваться совместимый веб-браузер, см. пункт xref:ROOT:requirements.adoc[Необходимые ресурсы].

== Запуск {of-mc}

.Чтобы запустить {mc}:
// tag::start[]
. Откройте веб-браузер по адресу `\http://Адрес-{of-mc}:5100`.
+
Для работы с Консолью управления пользователь должен быть указан в параметре `{dv-web-admin-cns-admins-serv}` в конфигурационном файле {of-mc}.
// end::start[]
При переходе по адресу пользователь может быть:
+
* Авторизован автоматически и переадресован на указанную страницу.
* Если сессия была закрыта, можно авторизоваться под именем текущего пользователя с помощью кнопки *Войти как текущий пользователь*.
* Войти под именем другого пользователя можно, указав учётные данные на странице аутентификации. После авторизации пользователь будет переадресован на предыдущую страницу.
+
. Если пользователь состоит в группе _{dv-web-admin-cns-admins-serv}_ в конфигурационном файле {of-mc}, он будет перенаправлен по указанному адресу. В противном случае появится сообщение об ошибке `Работа с модулем "{mc}" разрешена только пользователям группы "{dv-web-admin-cns-admins-serv}"`.
+
include::6.1@winclient:user:partial$excerpts.adoc[tags=ald-no-win]
+
. Сообщения о входе-выходе пользователя записываются в журнал консоли. Сообщения будут видны, если включить уровень журналирования `Information`.
