:serv: {wacs-new}

= Журналирование {of-mc}

.Для {mc} поддерживается два типа журналов:
* <<user-log,Журналы работы приложения>> -- сюда относится журнал {of-mc} и {of-sett-serv}, предназначенные для отслеживания состояния служб, диагностики проблем и анализа причин сбоев. Журнал сохраняется в виде файла и хранится в файловой системе сервера {dv}.
* xref:admin-log.adoc[Журнал действий администратора] -- содержит события взаимодействия с самой консолью.

[#user-log]
== Журнал работы приложения

Технические журналы Консоли управления и {of-sett-serv} можно посмотреть в каталоге `/var/log/docsvision` для Linux и `C:\ProgramData\Docsvision` для Windows.

Чтобы изменить путь хранения файла журнала по умолчанию, нужно в конфигурационном файле модуля `appsettings.json` изменить параметр menu:NLog[targets > logFile > fileName] с указанием нужного пути:

.Путь к файлу журнала:
[source,json]
----
{
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/managementconsole/${shortdate}_ManagementConsole.log"
      }
    }
  }
}
----
