:serv: {wacs-new}

= Журналирование {of-mc}

// Журнал {of-mc} хранится по адресу: `C:\ProgramData\Docsvision\ManagementConsole\Logs\ГГГГ_ММ_ДД_ManagementConsole_UserEvents.log`. Каждый день создаётся новый журнал.

[#user-log]
== Журнал работы пользователей Консоли

Журналы консоли управления и сервиса настроек можно посмотреть в каталоге `/var/log/docsvision` для Linux и `C:\ProgramData\Docsvision` для Windows.

// include::install-linux:ROOT:appendix/commands.adoc[tags=log]

// по адресу: `C:\ProgramData\Docsvision\SettingsService\Logs`.

Чтобы изменить путь хранения файла журнала по умолчанию, нужно в конфигурационном файле модуля `appsettings.json` изменить параметр menu:NLog[targets > logFile > fileName] с указанием нужного пути:

.Путь к файлу журнала:
[source,json]
----
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/managementconsole/${shortdate}_ManagementConsole.log",
      }
    },
----

[#admin-log]
== Журнал действий администратора

В журнале действий администратора фиксируются действия, выполняемые в {of-mc}. Записи в журнале создаются после подтверждения действия, при начале операции или ее завершении.

.Для всех действий фиксируется:
* Идентификатор события
* Дата/время
* Тип события
* Уровень журналирования
* Инициатор действия
* Результат (успех/ошибка)
* Текст ошибки при наличии
* Идентификатор сервиса

.В журнал попадают следующие события / Дополнительная информация по ним:
. Вход в {mc} и выход из системы / Логин пользователя.
. Факт регистрации, удаления компонентов / Тип компонента.
. Изменение любых параметров в конфигурации компонентов / Путь параметра в Сервисе настроек, тип редактора, значения до и после изменения. Для чувствительных зашифрованных данных фиксируется только факт изменения.
. Выполнение операций с базами данных / Параметры запроса (имя базы и тд).
+
* Настройка локализаций, решений и видов карточек по умолчанию для {wc}а.
* Настройки доли процесса, переустановка шаблонов для модуля {wf}.
* Управление персональными лицензиями, автоматическое отключение сессий для Сервера приложений.
* Настройка свойств БД.
+
. Изменения на странице расширенных настроек / Путь параметра, значения до и после изменения. Значения чувствительных зашифрованных настроек не фиксируются.
. Копирование настроек с сервера на сервер (импорт настроек компонента) / идентификатор целевого сервиса, сервер откуда скопировано. Содержимое настроек не логируется.
. Управление Службой {ws} и соединениями / Название сервиса и процесса.
. Работа с очередями и сообщениями / Идентификатор сообщения и идентификатор карточки сообщений.

Не фиксируются действия, которые не приводят к изменениям конфигурации: навигация по страницам и группам, промежуточные изменения до нажатия кнопки *Применить*, ошибки проверки значения полей.

.Уровень журналирования событий консоли определяестя следующим образом:
* `Error` (1) -- ошибки при выполнении операции или применении конфигурации. Например, ошибка подключения к БД.
* `Warning` (2) -- предупреждения о неудачных действиях пользователя, не являющихся ошибкой. Например, если пользователь ввёл неверный логин или пароль.
* `Information` (3) -- информационные события об изменениях, сообщения о начале\завершении обработки сообщения, успешные действия. Например, успешное изменение настройки.

Для журналирования действий администратора используется отдельная система, не связанная с основными механизмами журналирования. Журнал сохраняется в БД {of-sett-serv}. Такое решение позволяет отделить действия пользователя от технических журналов.
