:serv: {wacs-new}

= Просмотр журнала действий администратора

В {of-mc} ведётся журнал действий администратора.

.В журнал попадают следующие действия:
* Входы в {mc}.
* Изменение настроек соединений и Службы {ws}.
* Принудительная перезагрузка Службы {ws}.
* Нажатие кнопки *Повторить обработку*. При нажатии кнопки фиксируется идентификатор сообщения.

// Журнал {of-mc} хранится по адресу: `C:\ProgramData\Docsvision\ManagementConsole\Logs\ГГГГ_ММ_ДД_ManagementConsole_UserEvents.log`. Каждый день создаётся новый журнал.

Журналы консоли управления и сервиса настроек можно посмотреть в каталоге `/var/log/docsvision` для Linux и `C:\ProgramData\Docsvision` для Windows.

// include::install-linux:ROOT:appendix/commands.adoc[tags=log]

// по адресу: `C:\ProgramData\Docsvision\SettingsService\Logs`.

Чтобы изменить путь хранения файла журнала по умолчанию, нужно в конфигурационном файле модуля `appsettings.json` изменить параметр menu:NLog[targets > logFile > fileName] с указанием нужного пути:

.Путь к файлу журнала:
[source,json]
----
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/managementconsole/${shortdate}_ManagementConsole.log",
      }
    },
----