:serv: {wacs-new}

= Журналирование {of-mc}

.Для {mc} поддерживается два типа журналов:
* <<user-log,Журналы работы приложения>> -- сюда относится журнал {of-mc} и {of-sett-serv}, предназначеные для отслеживания состояния служб, диагностики проблем и анализа причин сбоев. Журнал сохраняется в виде файла и хранится в файловой системе сервера {dv}.
* <<admin-log,Журнал операций пользователя>> -- сохраняется в БД {of-sett-serv} и содержит события взаимодействия с самой консолью.

[#user-log]
== Журнал работы приложения

Журналы консоли управления и сервиса настроек можно посмотреть в каталоге `/var/log/docsvision` для Linux и `C:\ProgramData\Docsvision` для Windows.

:module-service: {of-mc}
include::6.1@webclient:admin:partial$excerpts.adoc[tags=no-rights]

Чтобы изменить путь хранения файла журнала по умолчанию, нужно в конфигурационном файле модуля `appsettings.json` изменить параметр menu:NLog[targets > logFile > fileName] с указанием нужного пути:

.Путь к файлу журнала:
[source,json]
----
{
  "NLog": {
    "targets": {
      "logFile": {
        "type": "File",
        "fileName": "${gdc:baseLogFolder}/docsvision/managementconsole/${shortdate}_ManagementConsole.log"
      }
    }
  }
}
----

[#admin-log]
== Журнал операций пользователя

В журнале операций пользователя фиксируются действия, выполняемые в {of-mc}. Записи в журнале создаются после подтверждения действия, при начале операции или ее завершении.

[NOTE]
====
Для журналирования операций пользователя используется отдельная система, не связанная с основными механизмами журналирования. Журнал сохраняется в таблицах *dvsettings_ApplicationLog* и *dvsettings_SystemLog* БД {of-sett-serv} автоматически и без участия администратора. Такое решение позволяет отделить действия пользователя от технических журналов.
====

События могут быть сгруппированы или разделены в зависимости от идентификатора сервиса ({wf}, {fs} и т.д.) и идентификатора операции (когда одно действие вызывает несколько изменений. Например, изменение нескольких параметров на странице настроек с последующим нажатием кнопки *Применить*.

.Для всех действий фиксируется:
* Идентификатор события
* Дата/время
* Тип события
* Уровень журналирования
* Инициатор действия
* Результат (успех/ошибка)
* Текст ошибки при наличии
* Идентификатор сервиса

.В журнал попадают следующие события / Дополнительная информация по ним:
. Вход в {mc} и выход из системы / Логин пользователя.
. Факт регистрации, удаления компонентов / Тип компонента.
. Изменение любых параметров в конфигурации компонентов / Путь параметра в Сервисе настроек, тип редактора, значения до и после изменения. Для чувствительных зашифрованных данных фиксируется только факт изменения.
. Выполнение операций с базами данных / Параметры запроса (имя базы и тд).
+
* Настройка локализаций, решений и видов карточек по умолчанию для {wc}а.
* Настройки долей процессов, переустановка шаблонов для модуля {wf}.
* Управление персональными лицензиями, автоматическое отключение сессий для Сервера приложений.
* Настройка свойств БД.
+
. Изменения на странице расширенных настроек / Путь параметра, значения до и после изменения. Значения чувствительных зашифрованных настроек не фиксируются.
. Копирование настроек с сервера на сервер (импорт настроек компонента) / идентификатор целевого сервиса, сервер откуда скопировано. Содержимое настроек не логируется.
. Управление Службой {ws} и соединениями / Название сервиса и процесса.
. Работа с очередями и сообщениями / Идентификатор сообщения и идентификатор карточки сообщений.

Не фиксируются действия, которые не приводят к изменениям конфигурации: навигация по страницам и группам, промежуточные изменения до нажатия кнопки *Применить*, ошибки проверки значения полей.

.Уровень журналирования событий консоли определяется следующим образом:
* `Error` (1) -- ошибки при выполнении операции или применении конфигурации. Например, ошибка подключения к БД.
* `Warning` (2) -- предупреждения о неудачных действиях пользователя, не являющихся ошибкой. Например, если пользователь ввёл неверный логин или пароль.
* `Information` (3) -- информационные события об изменениях, сообщения о начале\завершении обработки сообщения, успешные действия. Например, успешное изменение настройки.
