// tag::config[]
ifdef::is-service[]
. На сервере {dv} при обновлении сервисов будет предложено перезаписать текущий конфигурационный файл `appsettings.json`. При обновлении системы с предыдущих версий можно принять решение оставить существующий конфигурационный файл или выполнить все настройки в {of-mc}. Доступные варианты:
+
.Доступные варианты:
[%collapsible]
====
* Перезаписать текущий конфигурационный файл `appsettings.json`.
** Текущий файл будет перезаписан стандартным, все выполненные настройки будут сохранены в файле `appsettings.json.dpkg-old`. Существующие настройки, включая псевдонимы и строки подключения к БД, потребуется перенести в новый файл `appsettings.json`.
+
Начиная с НО 26.1, основным инструментом настройки системы является {mc}. Принимая решение заменить конфигурационый файл модулей {pl} (*{sss-new}*), {fs} (*{fss-new}*), {wc} (*{wcs-new}*), {wf} (*{wfs-new}*), учитывайте, что все существующие настройки будут заменены базовым набором параметров:
+
menu:ServiceId[]::
Уникальный идентификатор данного экземпляра модуля. Параметр задаётся автоматически при установке модуля.
menu:SettingsService[ConnectionString]::
Адрес подключения к хранилищу настроек. Параметр необходимо указать вручную.
menu:SettingsService[ApiKey]::
Ключ приложения для подключения к хранилищу настроек. Параметр необходимо указать вручную.
+
* Сохранить текущий `appsettings.json`.
** Все выполненные настройки останутся без изменений, стандартный файл конфигурации будет сохранён как `appsettings.json.dpkg-dist`.
* Показать различия между версиями.
** В окне командной строки будут отображены отличия между старой и новой версией. Знаком `+` обозначаются добавленные строки, знаком `-` обозначаются удалённые строки.
* Запустить оболочку командной строки для проверки ситуации.
** Возвращает в окно командной строки, дальнейшие действия зависят от администратора.
====
endif::[]
// end::config[]
