= Необходимые ресурсы

[#server]
== Требования серверной части модуля

include::dv6@install-linux:ROOT:requirements-software.adoc[tags=oslist]

[#client]
== Требования клиентской части модуля

.Операционная система:
* ОС Windows для работы в {wincl}е или любая ОС, перечисленная в требованиях к установке системы, см. "xref:install-linux:ROOT:requirements-software.adoc[]" для работы в {wc}е.

[#hard]
== Необходимое техническое обеспечение

Специальные требования к аппаратному обеспечению клиентского и серверного компьютера не предъявляются.

[#dv]
== Требования к системе {dv}

Для корректной работы данной версии модуля _{ad}_ требуется установить *серверные*
// и *клиентскую*
части следующих модулей:

.Модули {dv}:
. Модуль {pl} {pl-req} и выше.
. Модуль {bo} {bo-req} и выше.
. Приложение {dm} {dm-req} и выше.
. Модуль {wf} {wf-req} и выше.
. Приложение {to} {to-req} и выше.
. Модуль {wincl} {win-req} и выше.
. Модуль Служба {ws} {ws-req} и выше.
+
Требуется для полноценной работы функций модуля, включая усовершенствованное согласование.
+
Если _Служба {ws}_ устанавливается отдельно от сервера {dv}, потребуется указать адрес сервера {dv} и соответствующие настройки в конфигурационном файле Службы.
include::admin:update-module.adoc[tags=warning]

[#license]
== Лицензия

Для работы с модулем _{ad}_ лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Approval Designer_.

Если лицензия отсутствует, создание расширенных согласований будет недоступно. При попытке создать новые карточки _Этап согласования_ и _Маршрут согласования_ будет выдано сообщение об ошибке: `Лицензия не позволяет работать с конструктором согласований`. Однако возможность отправлять задания с использованием настроенных ранее маршрутов и этапов остаётся доступной даже без лицензии.
