= Уровень подготовки пользователя

Для эксплуатации модуля _{ad}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает серверную часть модуля, выявляет неполадки в работе бизнес-процессов согласования. Администратор {dv} должен обладать навыками настройки модуля _{pl}_, формирования сертификатов ЭП, использования криптопровайдера "КриптоПро"; а также ознакомиться с xref:6.1@backoffice:admin:install.adoc[документацией по администрированию] модуля {bo}.

Пользователь {dv} отправляет документы на согласование и участвует в их согласовании. Основным пользовательским рабочим местом является xref:6.1@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере. Пользователям необходимо ознакомиться с xref:6.1@documentmgmt:user:preparation.adoc[документацией по работе с модулем {dm}].

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}. Инженер {dv} настраивает шаблоны, этапы и маршруты согласования, выполняет конфигурацию Службы {ws}.

При необходимости разработки собственных скриптов, маршрутов и сценариев согласования и функций БП разработчик {dv} занимается их разработкой. Програмист должен иметь опыт разработки на любом из языков платформы .NET: C# или Visual Basic .NET, а также ознакомиться с xref:programmer::index.adoc[Руководством разработчика {dv}].
