= Уровень подготовки пользователя

Для эксплуатации приложения {dm} определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации и настройки решений появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает Приложение, выполняет первоначальную настройку, выявляет неполадки в работе бизнес-процессов Приложения в процессе эксплуатации, заполняет и актуализируют справочники {dv}. Администратор {dv} должен обладать навыками настройки модуля {pl}, а также ознакомиться с xref:admin:install.adoc[документацией] по администрированию Приложения _{dm}_.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, согласованием, также может заполнять и актуализировать справочники {dv} и т.п. Конечные пользователи должны ознакомиться с xref:user:preparation.adoc[разделом документации] для пользователей. Основным пользовательским рабочим местом является xref:6.1@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере.

Инженер {dv} настраивает работу с карточками Приложения при помощи предоставляемых _конструкторов_ и _справочников_ {dv}, настраивает бизнес-процессы. Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}.

Разработчик {dv} разрабатывает скрипты карточек, иметь опыт разработки на языке C# или Visual Basic .NET. Разработчик должен ознакомиться с с данной документацией для Приложения _{dm}_, а также документацией в разделе xref:programmer::index.adoc[Руководство разработчика {dv}].
