= Объекты номенклатуры

Идентификатор: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`

Псевдоним: `ObjectsNomenclatures`

Название: _Объекты номенклатуры_

== Секции карточки

=== Основная информация

Идентификатор: `3486E1F4-AACC-4C68-9093-FEA1E14A6549`
Псевдоним: `MainInfo`
Тип секции: `struct`
Название: _Основная информация_

.Поля секции Основная информация
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`InitialNomenclature`
a|_Номенклатура в которой было инициировано дело_
a|`refid`
a|
a|* Идентификатор типа: `9EEE908F-BFCC-48C5-BA52-F5EACC083DA7`
* Идентификатор секции: `E64256AC-43F7-41AB-AE28-70BEC28B6C38`


a|`Index`
a|_Индекс_
a|`unistring`
a|
a|

a|`Title`
a|_Заголовок_
a|`unistring`
a|1024
a|

a|`Comments`
a|_Комментарии_
a|`string`
a|1024
a|

a|`Created`
a|_Дата и время создания_
a|`datetime`
a|
a|

a|`LastModified`
a|_Дата и время последней модификации_
a|`datetime`
a|
a|

a|`IsPassing`
a|_Переходящее_
a|`bool`
a|
a|

a|`StorageTerm`
a|_Срок хранения_
a|`refid`
a|
a|* Идентификатор типа: `B995501A-FABF-4B7F-858B-C1A03E650658`
* Идентификатор секции: `05F1DBEA-EFF9-4D87-ACB4-FC8E649B782E`


a|`StorageBeginDate`
a|_Дата начала хранения_
a|`datetime`
a|
a|

a|`StorageEndDate`
a|_Дата окончания хранения_
a|`datetime`
a|
a|

a|`AllowToAddToClosed`
a|_Разрешить списание в закрытое дело_
a|`bool`
a|
a|

a|`Closed`
a|_Дата закрытия дела_
a|`datetime`
a|
a|

a|`Article`
a|_Статья_
a|`string`
a|512
a|

a|`Personnel`
a|_По личному составу_
a|`bool`
a|
a|

a|`Carrier`
a|_Вид носителя_
a|`enum`
a|
a|.Значения
* Бумажный = 0
* Электронный = 1


a|`Order`
a|_Порядковый номер_
a|`int`
a|
a|

a|`DefaultDocumentKind`
a|_Вид документа из которого по умолчанию будет происходить списание в данное дело_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`DefaultDocumentType`
a|_Тип документа по которому искать соответствующее дело_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`Barcode`
a|_Штрихкод_
a|`string`
a|255
a|

a|`LocationName`
a|_Название места_
a|`string`
a|512
a|

a|`Borrower`
a|_Заемщик_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Borrowed`
a|_Заимствовано_
a|`datetime`
a|
a|

a|`DueDate`
a|_Заимствовано до_
a|`datetime`
a|
a|

a|`BoxCode`
a|_Код коробки_
a|`string`
a|512
a|

a|`ExtLocationName`
a|_Внешнее название места_
a|`string`
a|512
a|

a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


a|`CreatedByTrigger`
a|_CreatedByTrigger_
a|`bool`
a|
a|

a|`Type`
a|_Тип дела_
a|`enum`
a|
a|.Значения
* Электронное = 0
* Бумажное = 1
* Смешанное = 2


a|`Unit`
a|_Подразделение_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `7473F07F-11ED-4762-9F1E-7FF10808DDD1`


a|`Box`
a|_Короб_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`
* Идентификатор секции: `3486E1F4-AACC-4C68-9093-FEA1E14A6549`


a|`Responsible`
a|_Ответственный за принятие в архив_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`AutoConversation`
a|_Автоматическая конвертация в формат долгосрочного хранения_
a|`bool`
a|
a|

a|`StoragePlace`
a|_Место хранения_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`DisableVolumeGeneration`
a|_Отключить формирование томов_
a|`bool`
a|
a|

a|`SheetsCount`
a|_Кол-во листов в деле_
a|`int`
a|
a|

a|`Notes`
a|_Примечания_
a|`string`
a|1024
a|

a|`InventoryNumber`
a|_Опись №_
a|`unistring`
a|
a|

a|`Fund`
a|_Фонд_
a|`string`
a|512
a|

a|`EPKProtocolNumber`
a|_Протокол ЭПК №_
a|`unistring`
a|
a|

a|`ActualAnnihilationDate`
a|_Фактическая дата уничтожения_
a|`datetime`
a|
a|

a|`AnnihilationRequest`
a|_Заявка на уничтожение_
a|`refcardid`
a|
a|

a|`StorageTimes`
a|_Сроки хранения_
a|`refid`
a|
a|* Идентификатор типа: `4538149D-1FC7-4D41-A104-890342C6B4F8`
* Идентификатор секции: `1B1A44FB-1FB1-4876-83AA-95AD38907E24`


a|`OperativeArchiveRetentionPeriod`
a|_Срок хранения в оперативном архиве_
a|`datetime`
a|
a|

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Issued`
a|_Выдан_
a|`bool`
a|
a|

a|`Missing`
a|_Утерян_
a|`bool`
a|
a|

a|`SelectedForDesctruction`
a|_Выделен к уничтожению_
a|`bool`
a|
a|

a|`Exterminated`
a|_Уничтожен_
a|`bool`
a|
a|

a|`CaseID`
a|_Дело_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


a|`ParentPartition`
a|_Ссылка на родительский раздел_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


a|`Name`
a|_Наименование_
a|`unistring`
a|1024
a|

a|`UnitIndex`
a|_Индекс подразделения_
a|`unistring`
a|
a|

a|`Primary`
a|_Первичный_
a|`bool`
a|
a|

a|`IndexNumber`
a|_Индекс (номер)_
a|`refid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`
* Идентификатор секции: `D2D10BE9-0B5A-478D-A079-7CFE28B5A711`


a|`CasesNumber`
a|_Количество дел_
a|`int`
a|
a|

a|`RefundRequest`
a|_Заявка на возврат_
a|`refcardid`
a|
a|

a|`StorageDateCasesStart`
a|_Дата дел хранения с_
a|`datetime`
a|
a|

a|`StorageDateCasesEnd`
a|_Дата дел хранения по_
a|`datetime`
a|
a|

a|`Number`
a|_Номер_
a|`int`
a|
a|

a|`ParentCase`
a|_Ссылка на родительское дело_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


a|`InitialYearNomenclature`
a|_Номенклатура в которой был создан раздел_
a|`refid`
a|
a|* Идентификатор типа: `9EEE908F-BFCC-48C5-BA52-F5EACC083DA7`
* Идентификатор секции: `EB2B5EF5-41A4-4A6D-8ADC-DB654C64C7CE`


a|`SheetsCountInApplication`
a|_Кол-во листов в приложении_
a|`int`
a|
a|

a|`ZipFileID`
a|_Файл ZIP-архива_
a|`refcardid`
a|
a|* Идентификатор типа: `6E39AD2B-E930-4D20-AAFA-C2ECF812C2B3`
* Идентификатор секции: `2FDE03C2-FF87-4E42-A8C2-7CED181977FB`
Поля ссылки: 
FileName > FileCurrentVersion

a|`Author`
a|_Автор_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Electronic`
a|_Электронный_
a|`bool`
a|
a|

a|`ParentFund`
a|_Родительский фонд_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


a|`ParentInventory`
a|_Родительская опись_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


a|`StorageRoom`
a|_Помещение хранения_
a|`unistring`
a|1024
a|

a|`StorageCloset`
a|_Шкаф хранения_
a|`unistring`
a|1024
a|

a|`StorageShelf`
a|_Полка хранения_
a|`unistring`
a|1024
a|

a|`DisplayString`
a|_Строка отображения_
a|`unistring`
a|1024
a|

a|`MessagesId`
a|_Карточка сообщений_
a|`refcardid`
a|
a|* Идентификатор типа: `23A98E72-8C75-4B99-A3E6-3DA5853B3CA9`


a|`CountCopiedChild`
a|_Количество копируемых объектов_
a|`int`
a|
a|

|===

=== Системные свойства

Идентификатор: `4853EC61-C28D-4DBC-9B18-52663C25014B`
Псевдоним: `System`
Тип секции: `struct`
Название: _Системные свойства_

.Поля секции Системные свойства
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`State`
a|_Состояние_
a|`refid`
a|
a|* Идентификатор типа: `443F55F0-C8AB-4DD3-BCBD-5328C7C9D385`
* Идентификатор секции: `521B4477-DD10-4F57-A453-09C70ADB7799`


a|`Kind`
a|_Вид_
a|`refid`
a|
a|* Идентификатор типа: `8F704E7D-A123-4917-94B4-F3B851F193B2`
* Идентификатор секции: `C7BA000C-6203-4D7F-8C6B-5CB6F1E6F851`


|===

=== Тома

Идентификатор: `C6A1AC59-CD92-4ECB-97D8-0C9535AA0525`
Псевдоним: `Volumes`
Тип секции: `coll`
Название: _Тома_

.Поля секции Тома
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Order`
a|_Порядковый номер_
a|`int`
a|
a|

a|`Name`
a|_Наименование_
a|`string`
a|512
a|

a|`SheetsCount`
a|_Количество листов_
a|`int`
a|
a|

a|`Comment`
a|_Примечание_
a|`string`
a|
a|

a|`Closed`
a|_Дата закрытия_
a|`datetime`
a|
a|

a|`Deleted`
a|_Дата уничтожения_
a|`datetime`
a|
a|

a|`Lost`
a|_Дата утраты_
a|`datetime`
a|
a|

|===

=== Документы дела

Идентификатор: `551B0E90-E3FD-4136-9D42-27A63B65FC24`
Псевдоним: `CaseDocuments`
Тип секции: `coll`
Название: _Документы дела_

.Поля секции Документы дела
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`RefDocument`
a|_Документ, списанный в Дело_
a|`refcardid`
a|
a|

a|`IsCopy`
a|_Копия_
a|`bool`
a|
a|

a|`Digest`
a|_Дайджест документа_
a|`string`
a|512
a|

a|`Number`
a|_Номер_
a|`text`
a|
a|

a|`Attached`
a|_Дата списания_
a|`datetime`
a|
a|

a|`Registered`
a|_Дата регистрации_
a|`datetime`
a|
a|

a|`SheetsCount`
a|_Количесвто листов_
a|`int`
a|
a|

a|`StartPage`
a|_Начальная страница_
a|`int`
a|
a|

a|`EndPage`
a|_Конечная страница_
a|`int`
a|
a|

a|`Order`
a|_Order_
a|`int`
a|
a|

a|`ArchiveDocument`
a|_Нормативный документ_
a|`refid`
a|
a|* Идентификатор типа: `9EEE908F-BFCC-48C5-BA52-F5EACC083DA7`
* Идентификатор секции: `CBCBF1F1-E03C-43A6-9957-6147B0CDB59B`


|===

=== Хранение

Идентификатор: `AD479A74-49B3-4ECE-A573-1C73ECAE08AA`
Псевдоним: `Storage`
Тип секции: `coll`
Название: _Хранение_

.Поля секции Хранение
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Order`
a|_Порядковый номер срока хранения_
a|`int`
a|
a|

a|`StorageTerm`
a|_Срок хранения дела_
a|`refid`
a|
a|* Идентификатор типа: `B995501A-FABF-4B7F-858B-C1A03E650658`
* Идентификатор секции: `05F1DBEA-EFF9-4D87-ACB4-FC8E649B782E`


|===

=== Номенклатуры

Идентификатор: `3EC5F33E-442A-4FC2-9388-1B4474C135E5`
Псевдоним: `Nomenclatures`
Тип секции: `coll`
Название: _Номенклатуры_

.Поля секции Номенклатуры
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`UnitNomenclature`
a|_Объект справочника номенклатуры_
a|`refid`
a|
a|* Идентификатор типа: `9EEE908F-BFCC-48C5-BA52-F5EACC083DA7`
* Идентификатор секции: `E64256AC-43F7-41AB-AE28-70BEC28B6C38`


|===

=== История

Идентификатор: `B92E18D5-A167-4331-A3C9-9A1E0BC6B0B1`
Псевдоним: `History`
Тип секции: `coll`
Название: _История_

.Поля секции История
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`StateName`
a|_Состояние_
a|`string`
a|
a|

a|`RegulatoryRef`
a|_Основание_
a|`refid`
a|
a|* Идентификатор типа: `9EEE908F-BFCC-48C5-BA52-F5EACC083DA7`
* Идентификатор секции: `CBCBF1F1-E03C-43A6-9957-6147B0CDB59B`


a|`Employee`
a|_Сотрудник_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Date`
a|_Дата действия_
a|`datetime`
a|
a|

|===

=== Ответственные за дело

Идентификатор: `B63FB814-A641-4E3A-8A28-1E3374E3323A`
Псевдоним: `Responsibles`
Тип секции: `coll`
Название: _Ответственные за дело_

.Поля секции Ответственные за дело
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Responsible`
a|_Ответственный_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


|===

=== Журнал передач

Идентификатор: `F2E63035-CCAE-4BFD-9195-86A7976AA940`
Псевдоним: `TransferLog`
Тип секции: `coll`
Название: _Журнал передач_

.Поля секции Журнал передач
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Lender`
a|_Кому выдано_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`ReturnDatePlan`
a|_Дата возврата (план)_
a|`datetime`
a|
a|

a|`ReturnDateFact`
a|_Дата возврата (факт)_
a|`datetime`
a|
a|

a|`Acceptance`
a|_Принял_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`Comments`
a|_Комментарии_
a|`string`
a|1024
a|

a|`Mortgagee`
a|_Выдал_
a|`refid`
a|
a|* Идентификатор типа: `6710B92A-E148-4363-8A6F-1AA0EB18936C`
* Идентификатор секции: `DBC8AE9D-C1D2-4D5E-978B-339D22B32482`


a|`IssuedDate`
a|_Дата выдачи_
a|`datetime`
a|
a|

a|`IssuedStorageUnit`
a|_Выдано ед. хранения_
a|`refcardid`
a|
a|

|===

=== Номера

Идентификатор: `D2D10BE9-0B5A-478D-A079-7CFE28B5A711`
Псевдоним: `Numbers`
Тип секции: `coll`
Название: _Номера_

.Поля секции Номера
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`NumericPart`
a|_Числовая часть_
a|`refid`
a|
a|* Идентификатор типа: `959FF5E2-7E47-4F6F-9CF6-E1E477CD01CF`
* Идентификатор секции: `D47F2C38-6553-4864-BAFF-0BC4D3A85290`


a|`Number`
a|_Номер_
a|`string`
a|
a|

|===

=== Разделы дела

Идентификатор: `8B3BFAD8-3A9E-4A14-B377-9590FB5A6DA0`
Псевдоним: `PartitionsCase`
Тип секции: `coll`
Название: _Разделы дела_

.Поля секции Разделы дела
|===
|Псевдоним |Название |Тип поля |Размер |Дополнительная информация 

a|`Partition`
a|_Раздел_
a|`refcardid`
a|
a|* Идентификатор типа: `CD81A0E2-187E-417C-A21B-AEFDDE17C362`


|===

