:update:
:os1: Astra Linux

= Установка обновлений

WARNING: Накопительное обновление 25.3 переводит все модули {dv} на .NET 8. Обновление отдельных модулей невозможно, обновлять необходимо всю систему целиком. На серверах системы потребуется обновление дополнительного ПО {asp-bundle}.

[#astranet]
== Обновление .NET

Для {os1} версии 1.7 потребуется подключить репозиторий Microsoft (см. ниже), в остальных случаях обновление происходит автоматически при обновлении {dv}, но может также выполняться вручную предпочтительным способом.

.Только для {os1}1.7:
. Подключите репозиторий Microsoft:
+
[source,bash]
----
curl -O https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
----
+
. Откройте файл `microsoft.pref` при помощи любого текстового редактора, например nano:

 $ sudo nano /etc/apt/preferences.d/microsoft.pref

. Добавьте в файл следующие строки:
+
----
Package: dotnet* aspnet* netstandard*
Pin: origin packages.microsoft.com
Pin-Priority: 1000
----
+
. Замените ранее установленную версию .NET из расширенного репозитория {os1} на официальную версию из репозитория Microsoft следующей командой:
+
 $ sudo apt-get install --only-upgrade "dotnet*" "aspnet*" "netstandard*"
+
. (Опционально) Пакеты .NET обновятся автоматически при обновлении {dv}, при необходимости их можно установить вручную:
+
 $ sudo apt-get install aspnetcore-runtime-8.0

[#modules]
== Обновление модулей

. После ознакомления с условиями, описанными в разделе "xref:index.adoc[]" и установки {asp-bundle} на сервера {dv}  обновление выполняется стандартным образом:
+
include::partial$update.adoc[]
+
. Запустите программу _{cns}_ и обновите существующую БД стандартным образом. При необходимости воспользуйтесь инструкцией, приведённой в документации модуля _{pl}_, раздел "xref:6.1@platform:console:db-update.adoc[]".
+
NOTE: Установка флагов в диалогах выбора обновляемых библиотек карточек и настроек модулей может оказаться недоступной, если изменений в библиотеке карточек между обновлениями не было.

[#client]
== Обновление клиентских компонентов

. Обновите до {asp-bundle}:
+
* Клиентские рабочие места, использующие DvWebTool и DVSupService
* Переведите собственные решения {wc}а на .NET 8.
+
. Обновите до {net-r}:
+
** Рабочие места с {wincl}ом.
+
. Клиентские компоненты модулей на компьютерах пользователей обновятся автоматически после запуска {wincl}а. Также новые версии можно установить вручную из предоставляемых пакетов установки. Новые версии модулей устанавливаются с областью установки модуля {pl}.
