:update: модуль-{dv}

= Установка обновлений

WARNING: Накопительное обновление 25.3 затрагивает все модули системы! Обновление отдельных модулей невозможно, обновлять необходимо всю систему целиком.

[#astranet]
== Обновление .NET

Накопительное обновление 25.3 переводит все модули {dv} на .NET 8. На серверах системы потребуется обновление дополнительного ПО {asp-bundle}. Для Astra Linux версии 1.7 потребуется подключить репозиторий Microsoft (см. ниже), в остальных случаях обновление происходит автоматически при обновлении {dv}, но может также выполняться вручную предпочтительным способом.

.Чтобы подключить репозиторий Microsoft в Astra Linux 1.7:
. Откройте файл `microsoft.pref` при помощи любого текстового редактора, например nano:

 $ sudo nano /etc/apt/preferences.d/microsoft.pref

. Добавьте в файл следующие строки:
+
----
Package: dotnet* aspnet* netstandard*
Pin: origin packages.microsoft.com
Pin-Priority: 1000
----
+
. Подключите репозиторий Microsoft:
+
[source,bash]
----
curl -O https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
----
+
. Замените ранее установленную версию .NET 8 Runtime:
+
 $ sudo apt-get install --only-upgrade "dotnet*" "aspnet*" "netstandard*"

[#modules]
== Обновление модулей

. После ознакомления с условиями, описанными в разделе "xref:index.adoc[]" и установки {asp-bundle} на сервера {dv} обновление выполняется стандартным образом: сперва серверные компоненты модулей обновляются на сервере Linux.
+
include::partial$update.adoc[]
+
. На машине Windows стандартным образом обновите серверные части модулей {dv}, входящих в обновление.
. Обновите БД стандартным образом, _краткая_ инструкция приведена ниже.

[#dbupdate]
== Обновление БД

. Запустите программу _{cns}_ и перейдите в раздел _Базы данных_.
. Обновите существующую БД стандартным образом. При необходимости воспользуйтесь инструкцией, приведённой в документации модуля _{pl}_, раздел "xref:6.1@platform:console:db-update.adoc[]".
+
NOTE: Установка флагов в диалогах выбора обновляемых библиотек карточек и настроек модулей может оказаться недоступной, если изменений в библиотеке карточек между обновлениями не было.
+
. Дойдите до выбора обновляемых библиотек карточек. Выберите библиотеки и нажмите *Далее*.
. Перезапустите *{sss-new}* и все сервисы {dv} на Linux ещё раз.
. Выберите модули {dv}, настройки которых должны быть загружены в БД и нажмите *Завершить*.

[#client]
== Обновление клиентских компонентов

Клиентские компоненты модулей на компьютерах пользователей будут обновлены автоматически после запуска {wincl}а. Также новые версии можно установить вручную из предоставляемых пакетов установки. Новые версии модулей будут установлены с областью установки модуля {pl}.
